### ISSUE TITLE
'unexpected token export' w/ cosmos@next + TS — bug

### ISSUE THREAD

**Issue by haf** [react-cosmos/react-cosmos#1000]
### What's wrong?

When trying to get started I get this error:

```

ERROR in ./app/expenses/components/Category/index.fixture.tsx 3:16
Module parse failed: Unexpected token (3:16)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
| import Category from '.';
| import ReduxStub from "../../../../tests/ReduxStub";
> export default (<ReduxStub>
|     <Category />
|   </ReduxStub>);
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 7:56-150
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js
 @ multi ./node_modules/react-cosmos/dist/domRenderer/reactDevtoolsHook.js ./node_modules/@skidding/webpack-hot-middleware/client.js?reload=true&overlay=false ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js
```

This seems to be because the added ts-loader is [incorrectly configured](https://stackoverflow.com/a/43244048/63621) — or perhaps [the include path](https://github.com/TypeStrong/ts-loader/issues/742#issuecomment-373315663) of the loader.

### Steps to reproduce

1.  Create a tsx file in `./app/.../here`, and a redux stub provider outside of the `./app` in `./tests`
2.  Reference the stubbed redux provider from the `component.fixture.tsx`
3.  See the above error

### Screenshots

<img width="710" alt="Screenshot 2019-07-17 at 21 54 01" src="https://user-images.githubusercontent.com/193115/61407162-678c5680-a8dd-11e9-8196-638176f57f38.png">

<img width="521" alt="Screenshot 2019-07-17 at 21 54 27" src="https://user-images.githubusercontent.com/193115/61407197-796df980-a8dd-11e9-827b-956b834c5d8e.png">

**Comment by skidding** [comment]
@haf Please keep the conversation in a single issue until we figure out the underlying problem(s). I understand this is frustrating but you're polluting this project and you're not being respectful of my time. 

You really think "Create a tsx file in ./app/.../here, and a redux stub provider outside of the ./app in ./tests" is enough for me to understand what's going on? Create a public repo that reproduces your issue and I'll help you solve it. Otherwise this won't go anywhere.

**Comment by haf** [comment]
I created the example repo we talked about: https://github.com/haf/hello-next-cosmos — got to this point

<img width="828" alt="Screenshot 2019-07-17 at 22 30 44" src="https://user-images.githubusercontent.com/193115/61409438-880adf80-a8e2-11e9-9d65-17ec6cec162d.png">

**Comment by skidding** [comment]
First of all, you need to import React to use JSX

<img width="593" alt="image" src="https://user-images.githubusercontent.com/250750/61412767-6285d200-a8f2-11e9-88cf-ca0428be9bb7.png">
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/250750/61412821-86e1ae80-a8f2-11e9-9836-b99bd79a11f3.png">

**Comment by gk4m** [comment]
@haf Because `cosmos.config` should be in **JSON** format and also React should be imported in `fixture` file.
https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md#config

**Comment by skidding** [comment]
I see you're trying to use `ProvidePlugin` to avoid this. The problem was the cosmos config you were using was invalid.

Put this in `webpack.override.js` in project root and it will work:

```js
var webpack = require('webpack');
module.exports = (config, { env }) => {
  return {
    ...config,
    plugins: [
      ...(config.plugins || []),
      new webpack.ProvidePlugin({
        'React': 'react'
      })
    ]
  }
};
```

**Comment by skidding** [comment]
Regarding my previous message:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/250750/61412986-02436000-a8f3-11e9-9529-7b1ce21826c8.png">

**Comment by skidding** [comment]
Also, Cosmos seems to work with both `noEmit` set to `true` and `false`. It doesn't affect it in any way so maybe the issues was not with Cosmos to begin with?

**Comment by haf** [comment]
@skidding You're right; it's probably something else. NextJS 9 was just released with a bundled typescript config, and my main project just upgraded and so has lingering babel configs that probably are conflicting.

Now we have a sample of nextjs + cosmos! Yey! Feel free to take it.

**Comment by skidding** [comment]
Cool. The sample is more about not requiring React imported in JSX files, but I see your point. The docs for Cosmos Next are still in the works but maybe we'll find a way to incorporate this nugget of information somewhere in the future.

I agree to leave #995 open because I might add a "Did you install html-webpack-plugin" message in the UI. You can see the "make sure your build is generating an index.html page" message already, but maybe it requires to much webpack knowledge to figure out.

What about your other issues?

**Comment by haf** [comment]
The main issue is the "unexpected token"; it happens probably due to the next.config.js file containing:

```

const withStylus = require('@zeit/next-stylus')
const withCSS = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const withImages = require('next-images')
const withFonts = require('next-fonts')
const withTM = require('next-transpile-modules');
```

I have to do more debugging to find what bit causes the error: I've unified presets and versions between my sample and my app and that didn't help. I've unified tsconfig, and that didn't help. So this is left. #999 would help

**Comment by skidding** [comment]
@haf A minimal repo with Cosmos and Next that reproduces your issue would allow me to help you with this. I'd happily look over it.

**Comment by haf** [comment]
I could give you temporary access to my site's codebase, if you want. It's quite easy to repro with `yarn && yarn run cosmos`?

**Comment by skidding** [comment]
Sure. Maybe you want to join Slack to communicate easier? https://join-react-cosmos.now.sh

I'll make time to investigate later today.

**Comment by skidding** [comment]
@haf Upgrade react cosmos and try again please

```
yarn add --dev react-cosmos@next
```

![image](https://user-images.githubusercontent.com/250750/61486183-8822e200-a9ab-11e9-848d-b5748e2280a1.png)

**Comment by haf** [comment]
@skidding ❤️

**Comment by skidding** [comment]
This was the culprit https://github.com/react-cosmos/react-cosmos/commit/4b785f33b0e5c9a242cc1bfdc00de59a523757c6

**Comment by bjunix** [comment]
Just for reference: I ran into a similar issue with `react-cosmos 5.0.3` using typescript and a barebones `create-react-app`, before finding the [custom webpack config](https://github.com/react-cosmos/react-cosmos/tree/master/docs#custom-webpack-config) section in the documentation.

**Comment by skidding** [comment]
@bjunix Thanks for letting us know!

I added a [Troubleshooting section for Create React App](https://github.com/react-cosmos/react-cosmos/tree/master/docs#using-create-react-app) to help users find this information quicker.
