### ISSUE TITLE
React Cosmos Next: Webpack build fails with cryptic errors

### ISSUE THREAD

**Issue by samrith-s** [react-cosmos/react-cosmos#1009]
### What's wrong?

This is my current folder structure:
```
__fixtures__
  |- span.js
  |- paragraph.js
```

This is `span.js` fixture. The other fixture is exactly the same:
```jsx
import React from 'react';
import { Span } from 'enkel-ui'; // this is linked in package.json

export default <Span disabled>Hey this is a span!</Span>
```

### Steps to reproduce
I have a script in `package.json` called `cosmos`. I just run `yarn cosmos`.

### User info

- Server terminal output
```bash
[Cosmos] See you at http://localhost:5000
[Cosmos] Using default webpack config
[Cosmos] Building webpack...
webpack built 197c2ef897fe764d04eb in 1998ms
✖ ｢wdm｣: Hash: 197c2ef897fe764d04eb
Version: webpack 4.29.6
Time: 1998ms
Built at: 07/28/2019 6:59:27 PM
      Asset      Size  Chunks  Chunk Names
    main.js  2.21 MiB    main  main
main.js.map  2.49 MiB    main  main
Entrypoint main = main.js main.js.map
[0] multi ./node_modules/react-cosmos/dist/domRenderer/reactDevtoolsHook.js ./node_modules/@skidding/webpack-hot-middleware/client.js?reload=true&overlay=false ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js 52 bytes {main} [built]
[./__fixtures__/span.js] 1.54 KiB {main} [built] [failed] [1 error]
[./node_modules/@skidding/webpack-hot-middleware/client-overlay.js] 2.17 KiB {main} [built]
[./node_modules/@skidding/webpack-hot-middleware/client.js?reload=true&overlay=false] 7.68 KiB {main} [built]
[./node_modules/@skidding/webpack-hot-middleware/node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/@skidding/webpack-hot-middleware/process-update.js] 4.44 KiB {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/react-cosmos/dist/domRenderer/index.js] 1.33 KiB {main} [built]
[./node_modules/react-cosmos/dist/domRenderer/reactDevtoolsHook.js] 884 bytes {main} [built]
[./node_modules/react-cosmos/dist/plugins/webpack/client/errorOverlay/index.js] 292 bytes {main} [built]
[./node_modules/react-cosmos/dist/plugins/webpack/client/hmrErrorHandler.js] 317 bytes {main} [built]
[./node_modules/react-cosmos/dist/plugins/webpack/client/index.js] 770 bytes {main} [built]
[./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js] 278 bytes {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
    + 131 hidden modules

ERROR in ./__fixtures__/span.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
ReferenceError: [BABEL] /Users/samrith/Work/enkel/example/__fixtures__/span.js: Unknown option: base.root. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options.
    at Logger.error (/Users/samrith/Work/enkel/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/samrith/Work/enkel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
    at OptionManager.init (/Users/samrith/Work/enkel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/samrith/Work/enkel/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/samrith/Work/enkel/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/samrith/Work/enkel/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/samrith/Work/enkel/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/samrith/Work/enkel/node_modules/babel-loader/lib/index.js:173:20)
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 7:26-91
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js
 @ multi ./node_modules/react-cosmos/dist/domRenderer/reactDevtoolsHook.js ./node_modules/@skidding/webpack-hot-middleware/client.js?reload=true&overlay=false ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js
Child HtmlWebpackCompiler:
                          Asset     Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  558 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {HtmlWebpackPlugin_0} [built]
```
- Cosmos version: `5.0.0-alpha.21`
- If bug occurred on upgrade: Working Cosmos version

You can check out the repo with the error here: https://github.com/samrith-s/enkel

**Comment by samrith-s** [comment]
Okay, I fixed the error, which was because of incorrect `.babelrc` file.

Now, the new error is:
```bash
Module build failed (from ../node_modules/babel-loader/lib/index.js):

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

**Comment by samrith-s** [comment]
The above error is because `babel-loader` used within Cosmos, is an older version which uses Babel 6. If I manually install `babel-loader`, it atleast builds. But then it throws this error:
![image](https://user-images.githubusercontent.com/9032162/62010649-c23f7100-b16d-11e9-94a9-02663aacc704.png)

**Comment by skidding** [comment]
- Does anything load at http://localhost:5000?
- How does your standard dev environment work? Eg. Do you use CRA or a standard toolkit
- If you can provide a minimal public repo I will happily debug

**Comment by samrith-s** [comment]
Hey @skidding The repo link is already in the issue. Posting it again! https://github.com/samrith-s/enkel

As for the other questions:
- No, nothing loads at http://localhost:5000, as soon as Webpack is done building, is crashes with the `FSEvents` error. This oddly, also causes my Chrome to crash if I don't terminate the process quickly.
- I use CRA as my dev environment. 

In the Enkel repo, you can `cd examples` and run `yarn cosmos`. I've already followed all the steps mentioned in Cosmos README to integrate with CRA.

**Comment by skidding** [comment]
> Hey @skidding, thanks a ton! The repo link is already in the issue. Posting it again! https://github.com/samrith-s/enkel

Damn, I get so used to not getting a repo with issues that I automatically assumed you hadn't posted one. Sorry! 😅

> I've already followed all the steps mentioned in Cosmos README to integrate with CRA.

Actually, your cosmos config isn't even picked up by Cosmos, because it's of a previous format.  If you look into the [Cosmos Next](https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md) docs you'll see the new config is JSON, and some options have changed. I hope to move the Next docs to the main Readme soon enough.

The good part is the defaults work for your config. Except the fact that you needed to install `babel-loader`.

But there's still the issue of the FSEvents. I think it has do to with some low level fs watch module the entire ecosystem uses. I found this error or CRA and react-native issues, but they're likely to stem from a lower level cause I'm not able to understand at the moment.

But I found something that works! By default Cosmos watches for files in all your project. It does ignore files from node_modules but they probabil still get picked up and can overwhelm the running process. There's an option to narrow the watch file path in Cosmos, which can be `src` in most cases.

I fixed the issue on my machine by creating this `cosmos.config.json` in the _example_ directory:

```json
{
  "watchDirs": ["src"]
}
```

And you can remove the old config. But if you need to use any of the options there make sure to find their equivalents in [the new config format](http://json.schemastore.org/cosmos-config).

---

Let me know if it works for you as well. If it does I would appreciate an entry for this in the [Troubleshooting section](https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md#troubleshooting). I'd recommend setting `watchDirs` to `src` (or similar based on their file structure) if a user encounters this error.

Thanks!

**Comment by samrith-s** [comment]
>Damn, I get so used to not getting a repo with issues that I automatically assumed you hadn't posted one. Sorry! 😅

I can understand, no problem at all! 😁 

Ah okay, got it. I will try it out.

The one problem I noted with the NEXT docs is that they are kinda scattered. So when I initially encountered the error, I had to flip between `NEXT.md` and the main `README.md` and figure out the steps.

Also, if I install `babel-loader` manually, CRA's pre-flight check fails. That's no good. 😞 

I shall update this issue if I further encounter anything.

**Comment by skidding** [comment]
OH, how did I miss this. You need to put fixtures in `src` if you want to use [CRA's own webpack config](https://github.com/facebook/create-react-app/blob/404af90d9a4d3e2cc38ccb905ad8275480f5aeb7/packages/react-scripts/config/webpack.config.js#L381). And you do, because you want code in Cosmos to be bundled the same as in the CRA dev environment.

Put fixtures in `src` and you can update your Cosmos config to this:

```json
{
    "watchDirs": ["src"],
    "webpack": {
        "configPath": "react-scripts/config/webpack.config"
    }
}
```

Then you can uninstall `babel-loader` and remove `.babelrc` (unless you need it somewhere else).

---

This information about `src` compilation in CRA is actually in the root README, but we should add it to Cosmos Next Troubleshooting as well.

**Comment by samrith-s** [comment]
OH yes! I missed it too, even though I read through all of it!

Dang it. Thanks, it works now! I LOVE the new UI! 😁

**Comment by samrith-s** [comment]
Also, once the library is done, I shall send out the URL to you! You can check it out. I'm planning on using it as the doc page of my library! 😄

**Comment by skidding** [comment]
Awesome!

> I'd be happy to do a PR on this, if it suits the roadmap, and if you can point me the way!

Definitely an interesting suggestion. Right now I'm working hard to close in on v5 and move past this big milestone. I'll keep it in mind when I lay down the next roadmap.

---

Would it be too much to ask to update NEXT.md with the two gotchas?

- `"watchDirs": ["src"]` for FSEvents error
- To put fixtures in `src` when using CRA

**Comment by samrith-s** [comment]
> Would it be too much to ask to update NEXT.md with the two gotchas?
Not at all, I will quickly create a PR and tag you on it! :)

And, perfect! I can also pick up some issues over this week which might need help!

**Comment by skidding** [comment]
PS. If your feature request never makes it in the official bundle, I can show you how to do it with a plugin, after the public release of the plugin API later this year.

**Comment by samrith-s** [comment]
Thanks, that'd be awesome pretty cool as well. I'll then create a plugin which does it for people who are interested in doing the same.

**Comment by samrith-s** [comment]
@skidding Please do check out the PR https://github.com/react-cosmos/react-cosmos/pull/1010

**Comment by skidding** [comment]
Thanks!
