### ISSUE TITLE
Empty watchDirs speeds up hmr

### ISSUE THREAD

**Issue by abstracthat** [react-cosmos/react-cosmos#1012]
### What's wrong?

Our repo has a large number of files (it's a huge Rails app). HMR was very slow in our app (10+ seconds). By setting `{"watchDirs": ["./front-end/components"]}` I was able to speed HMR up to 2-3 seconds.

Curiously, if the component and fixture file are in the root of the repo the rebuild is 200-300ms! I tried every combination I could think of and the only way to keep the HMR rebuild in that 200-300ms range and still keep components in our `./front-end/components` directory is to set `{"watchDirs": []}` which despite what you might think still watches fixtures and the component files just fine.

So Cosmos is working well for me now, but there must be something funny going on with the `watchDirs` code, as it seems like it should not work when set to an empty array.

### Steps to reproduce

Apologies but I wasn't able to create a minimal reproducible case. Happy to test an possible fixes in our repo though.

### User info
This is the console output when using `{"watchDirs": ["./front-end/components"]}`.

- Server console output
```
[Cosmos] webpack build invalidated by front-end/components/button.js
webpack building...
webpack built 1ddb07fbb83afc8914fe in 2127ms
```

- Browser console output
```
[HMR] bundle rebuilding
client.js?reload=true&overlay=false:250 [HMR] bundle rebuilt in 2012ms
process-update.js:54 [HMR] Checking for updates on the server...
process-update.js:128 [HMR] Updated modules:
process-update.js:130 [HMR]  - ./front-end/components/button.js
process-update.js:130 [HMR]  - ./front-end/components/__fixtures__/button.fixture.js
process-update.js:130 [HMR]  - ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js
process-update.js:135 [HMR] App is up to date.
```

- Cosmos version: `5.0.0-alpha.22`

And the browser console output when using `{"watchDirs": []}`
```
[HMR] bundle rebuilding
client.js?reload=true&overlay=false:250 [HMR] bundle rebuilt in 247ms
process-update.js:54 [HMR] Checking for updates on the server...
process-update.js:128 [HMR] Updated modules:
process-update.js:130 [HMR]  - ./front-end/components/button.js
process-update.js:130 [HMR]  - ./front-end/components/__fixtures__/button.fixture.js
process-update.js:130 [HMR]  - ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js
process-update.js:135 [HMR] App is up to date.
```

**Comment by abstracthat** [comment]
As a follow-up, I now see the problem with `watchDirs: []`. When I add a new fixture it is not picked up. That's unfortunate. But the HMR rebuild time is an order of magnitude faster so I'm not sure what to do. Any ideas?

**Comment by skidding** [comment]
@abstracthat That is correct, `watchDirs` is used for detecting _new_ fixtures. The ones already bundled hot reload without additional watching.

Cosmos merely registers each dir as a webpack loader dependency. Meaning that the build will invalidate when anything in those dirs changes. But webpack does the _watching_. Here's the code:

https://github.com/react-cosmos/react-cosmos/blob/84878cd8122d38028ddf3cc6027b7e244e6c2eb2/packages/react-cosmos/src/plugins/webpack/webpackConfig/userDepsLoader.ts#L23-L26

And here's the webpack documentation: https://webpack.js.org/api/loaders/#thisaddcontextdependency

I'm afraid this is as far as my webpack knowledge goes. Let me know if you have any ideas on how to improve performance.

If you want to experiment you can open `node_modules/react-cosmos/dist/plugins/webpack/webpackConfig/userDepsLoader.js` in your project and change things around. It's TS-compiled code but should be readable enough.

Good luck!

**Comment by skidding** [comment]
Closed due to inactivity. Report back if this is still an issue.
