### ISSUE TITLE
Webpack error (cont'd?)

### ISSUE THREAD

**Issue by acting326** [react-cosmos/react-cosmos#1013]
Referencing this closed issue from a year ago:
https://github.com/react-cosmos/react-cosmos/issues/743

Wanted to open up a new issue (in case closed issues aren't surfaced) with the same message re-iterated:

@mitsuishihidemi @skidding, was there ever any resolution on this? I just lined things up and got the custom webpack config properly extended but am still getting the error in the playground but with no actual error in the terminal and the same browser 404 for _loader.html.

Let me know if you need any more context!

react-cosmos: 4.8.1
webpack: 4.29.6
babel-loader: 7.1.2

```
// cosmos.config.js

const baseConfig = require("./webpack.config.js").baseConfig;
module.exports = {
  webpack: () => {
    return baseConfig({});
  },
  watchDirs: ["src/components"]
};
```

**Comment by skidding** [comment]
Hi @acting326,

Are you just getting started or already have many fixture created? If the former, I recommend installing `react-cosmos@next` and reading these docs: https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md

The config is slightly different, and is a JSON file. But let me know which version you'll use and we'll take it from there. I'm currently putting all my energy into the new version, so hopefully you can use that.

**Comment by acting326** [comment]
Heya, @skidding! Appreciate the quick response. Haven't gotten that far yet so I can definitely check out vnext. The quirk about the webpack setup I'm working with is that the `webpack.config.js`'s module export looks like this:

```
// webpack.config.js
module.exports = {
  baseConfig,
  COMMITHASH,
  bucket: AWS_BUCKET
};
```

How might I integrate the `baseConfig` as the input in `webpack.override.js` rather than defaulting to "what's one loaded from `webpack.configPath`", since our setup exports config out in a different manner?

**Comment by skidding** [comment]
Hey. So use `webpack.overridePath` would be more difficult because you're overriding all the changes Cosmos added to the base webpack config. It is possible, but I propose an easier alternative.

Use `webpack.configPath` and point to a new file, say `webpack.config.cosmos.js`, which would look like this:

```js
module.exports = require('./webpack.config').baseConfig;
```

Does it work?

**Comment by acting326** [comment]
Hmm I'm getting the following error in my terminal: 

```
TypeError: Cannot read property 'module' of undefined
    at getDevWebpackConfig (/Users/alexcting/Desktop/Appcues/react.appcues.com/node_modules/react-cosmos/dist/plugins/webpack/webpackConfig/devServer.js:29:49)
    at webpackDevServer (/Users/alexcting/Desktop/Appcues/react.appcues.com/node_modules/react-cosmos/dist/plugins/webpack/devServer.js:35:64)
    at startDevServer (/Users/alexcting/Desktop/Appcues/react.appcues.com/node_modules/react-cosmos/dist/shared/devServer/index.js:39:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
Following that down a little, I'm seeing that `userWebpack` is `undefined` in `getDevWebpackConfig` in devServer.js, which seems weird since it looks like `webpackDevServer` should have returned out without `userWebpack` here:

![Screen Shot 2019-07-31 at 5 50 31 PM](https://user-images.githubusercontent.com/14987737/62250948-5272f580-b3bc-11e9-9533-e69729f669fe.png)

🤔

**Comment by skidding** [comment]
[This is the line that's failing](https://github.com/react-cosmos/react-cosmos/blob/beb07ecceda1aef012bdae188cc16dd7b9dc45d2/packages/react-cosmos/src/plugins/webpack/webpackConfig/devServer.ts#L25). It seems like your webpack config is missing the `module` key.

In your `webpack.config.cosmos.js`, or however you called it, `console.log` the config you're exporting (ie. baseConfig). It might not be a valid webpack config. What does it contain?

**Comment by acting326** [comment]
Yes, @skidding ! It had commented something out while debugging, but found it, thanks!

Now it is building, but I am seeing what I think is the same issue I ran into using `react-cosmos` in the playground. 

See here:

<img width="596" alt="Screen Shot 2019-08-01 at 9 35 06 AM" src="https://user-images.githubusercontent.com/14987737/62297887-f9e53c00-b43f-11e9-8635-7456ae365eff.png">

Here is my webpack config...do you see any issues here in how my setup might interact with `react-cosmos@next`:

```
// webpack.config.js
const path = require("path");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const GitRevisionPlugin = require("git-revision-webpack-plugin");
const TerserPlugin = require("terser-webpack-plugin");

const { NODE_ENV, AWS_BUCKET, APPCUES_ENV } = process.env || {};

const gitRevisionPlugin = new GitRevisionPlugin();
const COMMITHASH = gitRevisionPlugin.commithash();

// borrowed from the SDK for use in the DefinePlugin above
function wrapStrings(obj) {
  const newobj = {};
  Object.keys(obj).forEach(key => {
    const val = obj[key];
    newobj[key] = typeof val === "string" ? JSON.stringify(val) : val;
  });
  return newobj;
}

function isProduction(environment) {
  return !!environment && environment === "production";
}

const baseConfig = opscuesConfig => {
  return {
    devtool: "source-map",
    mode: isProduction(NODE_ENV) ? "production" : "development",
    entry: {
      main: path.resolve(__dirname, "src/main")
    },
    output: {
      library: "Reactcues",
      path: path.join(
        __dirname,
        AWS_BUCKET ? `dist/${AWS_BUCKET}/${COMMITHASH}` : `dist/${COMMITHASH}`
      ),
      filename: "[name].[hash].js",
      publicPath: `/${COMMITHASH}`
    },
    optimization: {
      minimizer: [new TerserPlugin({ sourceMap: true })],
      runtimeChunk: "single",
      splitChunks: {
        chunks: "all",
        maxInitialRequests: 5,
        minSize: 100,
        cacheGroups: {
          vendor: {
            test: /[\\/]node_modules[\\/]/,
            name(module) {
              const packageName = module.context.match(
                /[\\/]node_modules[\\/](.*?)([\\/]|$)/
              )[1];
              return `npm.${packageName.replace("@", "")}`;
            }
          }
        }
      }
    },
    plugins: [
      new HtmlWebpackPlugin(
        Object.assign({}, opscuesConfig, {
          template: "./index.html",
          filename: `../index.${COMMITHASH}.html`,
          environment: isProduction(NODE_ENV) ? "production.min" : "development"
        })
      ),
      new webpack.DefinePlugin(wrapStrings(opscuesConfig)),
      new webpack.DefinePlugin({
        "process.env": {
          NODE_ENV: JSON.stringify(NODE_ENV)
        },
        APPCUES_ENV: JSON.stringify(APPCUES_ENV)
      }),
      new webpack.DefinePlugin({
        COMMITHASH: JSON.stringify(COMMITHASH)
      }),
      new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
      new CopyWebpackPlugin(["_redirects", "appcues-favicon.png"]),
      new webpack.HashedModuleIdsPlugin(),
      new webpack.DefinePlugin({
        "process.traceDeprecation": true
      })
    ],
    module: {
      rules: [
        {
          test: /\.js$/,
          loader: "babel-loader",
          exclude: /node_modules\/(?!normalize-url)/,
          include: __dirname
        },
        {
          test: /\.s?css$/,
          use: ["style-loader", "css-loader", "postcss-loader", "sass-loader"]
        },
        {
          test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          loader: "url-loader?limit=10000&mimetype=application/font-woff"
        },
        {
          test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          loader: "file-loader",
          options: {
            publicPath: isProduction(NODE_ENV) ? `/${COMMITHASH}` : "/"
          }
        },
        {
          test: /\.(png|jpg|gif)$/,
          loader: "url-loader",
          options: {
            limit: 8192,
            fallback: "file-loader"
          }
        }
      ]
    },
    externals: {
      "react-dom": "ReactDOM",
      react: "React",
      "firebase/app": "firebase",
      "firebase/auth": "firebase.auth",
      "firebase/database": "firebase.database",
      quill: "Quill",
      moment: "moment",
      "sockjs-client/dist/sockjs": "SockJS",
      immutable: "Immutable",
      "react-virtualized": "ReactVirtualized",
      authClient: "apc_auth",
      ramda: "R"
    },
    resolve: {
      alias: {
        tests: path.resolve(__dirname, "tests"),
        jest: path.resolve(__dirname, "jest")
      },
      modules: [
        path.resolve(__dirname, "src"),
        path.resolve(__dirname, "node_modules")
      ]
    },
    node: { fs: "empty" }
  };
};

module.exports = {
  baseConfig,
  COMMITHASH,
  bucket: AWS_BUCKET
};

```

**Comment by skidding** [comment]
> Now it is building, but I am seeing what I think is the same issue I ran into using react-cosmos in the playground.

Not sure it's building, though. The Cosmos UI is prebuilt and works independently from your build. It's likely that your build is still failing. **Any errors in the terminal?**

> Here is my webpack config...do you see any issues here in how my setup might interact with

Well, a bit hard to guess like this but I'd say the issue is that `baseConfig` is not really a standard webpack config. Yes, it can be a function, but [the first argument should be the environment](https://webpack.js.org/configuration/configuration-types/#exporting-a-function). I don't know what `opscuesConfig` is.

It would really help if I had a repo to try for myself.

**Comment by skidding** [comment]
@acting326 Any update?

**Comment by acting326** [comment]
Sorry for the radio silence. Shelved the work for a bit. I'm going to try again this weekend and update and re-open if needed. Closing for now 🙇
