### ISSUE TITLE
Where is demo link?

### ISSUE THREAD

**Issue by ganapativs** [react-cosmos/react-cosmos#1014]
Is there a demo link? If it's there, it's not discoverable because I couldn't find it.

Can it be added somewhere to the top of the README?

**Comment by skidding** [comment]
Thanks @ganapativs. The [new README](https://github.com/react-cosmos/react-cosmos/blob/master/README.md) now has a link to a live demo. And in the future I would like to create a "marketing" website that explains functionality (without having to install Cosmos to understand).
