### ISSUE TITLE
Toasts position

### ISSUE THREAD

**Issue by avin** [react-cosmos/react-cosmos#1017]
Hey! Thanks for such a comfortable tool for react developers!

Can you make abbility to configure default position for popup toasts? For example to show it at bottom-right or bottom-left etc. Thank you!

**Comment by skidding** [comment]
Hi @avin,

I’m curious, where would you move it and why?

**Comment by avin** [comment]
Just don't want it overlaps elements. For example:
![image](https://user-images.githubusercontent.com/36100/62455346-cdeaf300-b77e-11e9-88a5-ea70e4699013.png)

**Comment by skidding** [comment]
I've had this issue as well. I'm thinking of moving it to bottom-right. And if anyone else complains then we can think of making it configurable. Good defaults first. What do you think?

**Comment by skidding** [comment]
@avin Please check `react-cosmos@5.0.0-alpha.23` 🕺

**Comment by avin** [comment]
works fine, thank you
