### ISSUE TITLE
HOCs option in fixtures.

### ISSUE THREAD

**Issue by Izhaki** [react-cosmos/react-cosmos#1023]
### What's up?

Most of the components I write ship with various HOCs, so the final behaviour is composed.

For instance:

```js
export default compose(
  interactive,
  withWaitOnce({ promise: waitForFont('Source Code Pro') }),
  withBoxResolver,
  withLayout(connectionLayout())
)(Graph);
```

Note also that some HOCs are parameterised, meaning that every fixture might involve slightly different composition. Further, I often end up having these compositions in subfolders since there is a fair share of related code.

Effectively, nearly every fixture involves a different (resultant) component. Although they are all 'fixtures' for the same base component (eg, `Graph` above).

The folder and name of a fixture in Cosmos are determined by the component name and folder. This was done with the (fair) assumption that fixtures demonstrate different `props` for the same component. But this assumption does not hold in the case above.

`name`, `displayName`, `namespace` do not help here - it seems that if the provided component reference is different, you always end up with a different folder/component.

### Mkay, tell me more...

All of could be resolved if we had an `hocs` property for the fixture, so the example above would look like so:

```js
export default [
  {
    component: Graph,
    hocs: compose(
      interactive,
      withWaitOnce({ promise: waitForFont('Source Code Pro') }),
      withBoxResolver,
      withLayout(connectionLayout())
    ),
    props,
  },
];
```

Cosmos would still derive at the folder/component based on the `component` property (as it does now), but before rendering it will simply call: `hocs(component)`

**Comment by skidding** [comment]
Hi @Izhaki,

This thread should help: https://github.com/react-cosmos/react-cosmos/issues/568.

Also, have you given [Cosmos Next](https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md) a try? I believe it solves this problem altogether.

**Comment by Izhaki** [comment]
Right then!

I've started migrating fixtures from Cosmos to Next.js, because I just wanted my fixtures to be react components, only to now find out that Cosmos Next does exactly that.

This is such a better approach!

In my case it's a no-brainer: I've got to migrate to Cosmos Next. I just hope it's stable enough.

**Comment by skidding** [comment]
@Izhaki That's good news. A significant number of Cosmos users, including myself, have been testing Cosmos Next for almost a year so yeah it's pretty stable. I plan to go from alpha to beta this month and freeze features, after which I'll redesign the documentation and help users migrate.
