### ISSUE TITLE
How do I tell it to look for fixtures files in ./src directory?

### ISSUE THREAD

**Issue by chovy** [react-cosmos/react-cosmos#1097]

**Comment by skidding** [comment]
You can set [rootDir](https://github.com/react-cosmos/react-cosmos/blob/5a4a0df870771432b36dcf9ed69968c934c1263b/packages/react-cosmos/config.schema.json#L10-L14) to `"src"`. Just note that all paths in the Cosmos config are relative to `rootDir`.

But most of the type just setting [watchDirs](https://github.com/react-cosmos/react-cosmos/blob/5a4a0df870771432b36dcf9ed69968c934c1263b/packages/react-cosmos/config.schema.json#L39-L44) to `["src"]` is enough.

Any update on #1096?

**Comment by chovy** [comment]
where what? what file does this go in??

**Comment by skidding** [comment]
> where what? what file does this go in??

https://github.com/react-cosmos/react-cosmos#config

**Comment by chovy** [comment]
```
module.exports = {
  rootDir: './src',
  fileMatch: [
    '**/*.fixture.js'
  ]
};
```

Put this in `./cosmos.config.json` doesn't seem to have any impact.

**Comment by skidding** [comment]
Cosmos config is JSON. Your config sounds like a Cosmos Classic (4.x) config. Please use https://github.com/react-cosmos/react-cosmos-classic if you can't upgrade webpack.
