### ISSUE TITLE
import style from './Button.scss' doesn't work

### ISSUE THREAD

**Issue by chovy** [react-cosmos/react-cosmos#1098]
```
ERROR in ./src/app/components/Button/Button.scss
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| button {|   border: 1px solid black;
|   background-color: gray;
 @ ./src/app/components/Button/index.js 3:0-34
 @ ./src/app/components/Button/Button.fixture.js
 @ ./node_modules/react-cosmos/dist/client/user-modules.js
 @ ./node_modules/react-cosmos/dist/client/mount.js
 @ ./node_modules/react-cosmos/dist/client/loader-entry.js
 @ multi ./node_modules/react-cosmos/dist/client/react-devtools-hook.js (webpack)-hot-middleware/client.js?reload=true&overlay=false ./node_modules/react-cosmos/dist/client/loader-entry.js
Child html-webpack-plugin for "_loader.html":
           Asset    Size  Chunks  Chunk Names
    _loader.html  568 kB       0
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs 376 bytes {0} [built]
       [1] ./node_modules/lodash/lodash.js 541 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
```

**Comment by skidding** [comment]
Please read the README docs. You'll see that React Cosmos doesn't install any build dependencies for you. Most likely you need to install scss-loader and maybe other css-related loaders.

> How you compile your code is 100% your business. React Cosmos jumps through hoops to compile your code using your existing build pipeline, but it doesn't have opinions nor does it install dependencies your setup might require.

> Unless you use a framework like Create React App or Next.js, you need to install build dependencies yourself. This include stuff like Babel, TypeScript, webpack loaders, html-webpack-plugin, etc.

> React Cosmos compiles your code using the build dependencies already installed in your project.

**Comment by chovy** [comment]
ok so i got that working. but it says I have no fixtures, even though the build is finding them.

**Comment by skidding** [comment]
You're using React Cosmos 5 fixtures with React Cosmos 4. I'll say it one more time: If you want to use RC 4 use https://github.com/react-cosmos/react-cosmos-classic instead. The documentation you see here will only mislead you as a lot of things changed in RC 5.
