### ISSUE TITLE
Webpack config returning a Promise

### ISSUE THREAD

**Issue by hlehmann** [react-cosmos/react-cosmos#1114]
### What's wrong?

My webpack config is a function returning a promise like in the official docs:
https://webpack.js.org/configuration/configuration-types/#exporting-a-promise

Bug I get the message 
```
WARNING in configuration
The 'mode' option has not been set, Webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
```

I tested with an sync config and it works well.

Could it be possible to accept Webpack config as a potential promise.

### Steps to reproduce

```typescript
// working webpack.config.js
module.exports = function(env, argv) {
    return {mode: "development"};
};

// not working webpack.config.js
module.exports = async function(env, argv) {
    return {mode: "development"};
};
```

### User info

- Cosmos version 5.0.0
- Webpack version 4.39.0

**Comment by skidding** [comment]
@hlehmann Thanks for reporting this issue. Luckily it will be fixed soon by #1113

**Comment by skidding** [comment]
Please check out `react-cosmos@5.0.1`.

**Comment by hlehmann** [comment]
Thx it works well !
