### ISSUE TITLE
Toast does not disapear

### ISSUE THREAD

**Issue by avin** [react-cosmos/react-cosmos#1139]
### What's wrong?

Current toaster does not disapear and stay constantly at the corner.
![image](https://user-images.githubusercontent.com/36100/72241963-4214a700-35f9-11ea-8908-468ae5801bcb.png)

### User info

Cosmos-version: 5.0.4

**Comment by skidding** [comment]
Hi @avin,

That is on purpose. The message is letting you know that the renderer iframe changed its location in a way that no longer reflects the selected fixture.

The assumption is that once you got in that state you're using React Cosmos as merely another browser window, and you probably want to return to one of your fixtures.

Is your experience different?

**Comment by avin** [comment]
So it is ok that it does not disapear in time? If so, then you can close the issue.

![vv](https://user-images.githubusercontent.com/36100/72246801-9b360800-3604-11ea-908a-646a15f23e18.gif)

**Comment by skidding** [comment]
Hmm, well I don't think it should occur on a regular basis. It seems like some of your fixtures triggers it as soon as they are selected.

Can you please inspect the preview iframe (the part where your components render) and tell me what's the value of `window.location.href` inside the iframe, after the "Renderer iframe location changed" warning appears?

**Comment by skidding** [comment]
Here is an example of what I mean

![image](https://user-images.githubusercontent.com/250750/72248870-d8989680-3600-11ea-80cd-016951807978.png)

**Comment by avin** [comment]
![cc](https://user-images.githubusercontent.com/36100/72249501-91170800-360a-11ea-8d4c-8bf0456d03e7.gif)

**Comment by skidding** [comment]
Almost there. But the `src` never changes in the Elements tab.

To get the current location you have to click on the `iframe` in the Elements tab, and then open the console and type `$0.contentWindow.location.href`.

Let me know what that returns.

**Comment by avin** [comment]
$0.contentWindow.location.href
"http://localhost:5000/_renderer.html#/"

**Comment by skidding** [comment]
I see. So you app adds `#/` to window location automatically?

Regardless, I think the "Renderer iframe location changed" warning shouldn't appear when the location only changes its hash fragment.

I'll mark this as a bug and try to push a patch asap. Sorry for the inconvenience!

**Comment by avin** [comment]
@skidding  Thank you for fast response, love to use your app :)

**Comment by skidding** [comment]
@avin Please try `5.0.5` and let me know if the issue persists.

**Comment by avin** [comment]
works fine now, thank you very much! 👍
