### ISSUE TITLE
Webpack with NormalModuleReplacementPlugin

### ISSUE THREAD

**Issue by avin** [react-cosmos/react-cosmos#1148]
Hey, @skidding! Do you know, is it possible to use NormalModuleReplacementPlugin with react-cosmos

https://webpack.js.org/plugins/normal-module-replacement-plugin

I use it to make environment dependent imports (like described in "Advanced Example" of webpack doc), and want that react-cosmos uses same strategy to import components from fixtures.

I think now there is no such opportunity, but it would be cool if it appeared in the future. Thanks!

**Comment by skidding** [comment]
Hi @avin,

You should be able to use any webpack plugin with React Cosmos.

> and want that react-cosmos uses same strategy to import components from fixtures

Can you show me an example of this?

**Comment by avin** [comment]
I'll make a demo project tonight

**Comment by avin** [comment]
i'm so sorry!! i've messed something, IT WORKS ABSOLUTTLY PERFECT from the box!

**Comment by skidding** [comment]
Beautiful!
