### ISSUE TITLE
Unable to set/append entry on webpack config override

### ISSUE THREAD

**Issue by andyrichardson** [react-cosmos/react-cosmos#1173]
### What's wrong?

I'm looking to add some tweaks to the cosmos playground welcome page. I can't do this because the `entry` override gets removed instead of merged.

### Steps to reproduce

1. Create an cosmos.overrides.js
2. Set an entry value (array, object, string)
3. Run a cosmos build

### Suggestions

It would be great if the full cosmos webpack config was provided to the override function rather than a partial one. [Here](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos/src/plugins/webpack/webpackConfig/export.ts#L24) is where the entry property is overriding the user-specified overrides.

**Comment by skidding** [comment]
> I'm looking to add some tweaks to the cosmos playground welcome page.

The playground is precompiled and doesn't get built when you run Cosmos on your machine, so you can't really alter it in any straightforward way. But let me know what are you trying to achieve.

> Here is where the entry property is overriding the user-specified overrides

Cosmos overrides the entry because it contains the mechanism that decides which fixture to load by communicating with the playground (via postMessage or WebSockets). Being able to change this will easily break Cosmos.

If you're only looking to append an entry, you can do that with the [globalImports](https://github.com/react-cosmos/react-cosmos/blob/c931ec39faea92c9bff87e4998b65fa5365e8e17/packages/react-cosmos/config.schema.json#L92-L96) config.

**Comment by andyrichardson** [comment]
> The playground is precompiled and doesn't get built when you run Cosmos on your machine

My understanding was that the webpack config is for building both the shell (cosmos playground) and the renderer - sounds like it's only for the renderer?

The reason we need this feature is because we're looking to use [Netlify's Open Source Plan Policy](https://www.netlify.com/legal/open-source-policy/) which requires us to add a badge to our deployment's home page (cc https://github.com/FormidableLabs/urql-devtools/pull/129).

I have tried global overrides and even a script inside decorators but these scripts only execute inside of the iframe (which is hidden by the welcome page).

**Comment by skidding** [comment]
> My understanding was that the webpack config is for building both the shell (cosmos playground) and the renderer - sounds like it's only for the renderer?

Correct, it's just for the renderer. The purpose for this was to make the playground more resilient (and faster). It only needs a web server to start, while the renderer is compiling using your own pipeline.

> I have tried global overrides and even a script inside our root decorator but these scripts only execute inside of the iframe (which is hidden by the welcome page).

Indeed, that's expected.

> The reason we need this feature is because we're looking to use Netlify's Open Source Plan Policy...

Hmm, I can't think of a clean solution right now. There is an underlying plugin system behind the playground, but it's WIP and realistically I don't expect the API to come out soon.

The best I can think of is to fork `react-cosmos-playground2` and bake in your welcome screen manually. If you go down this route I can help with pointers to the source code.

**Comment by andyrichardson** [comment]
No worries, that makes sense! Thanks for the suggestion :+1:

**Comment by skidding** [comment]
> Don't worry I have low standards

😂

> Thanks for the suggestion I'll see what I can do as a workaround

My pleasure. Good luck!
