### ISSUE TITLE
Setting html wrapping the component

### ISSUE THREAD

**Issue by jkavalec** [react-cosmos/react-cosmos#1187]
I need to be able to set a custom html wrapper - default one just tightly wraps around component with a margin, which prevents me testing container components that expand to the width and height of the screen.

Is there any way how to set this up?

**Comment by skidding** [comment]
> default one just tightly wraps around component with a margin

This is just the default behavior of the `body` element. React Cosmos doesn't add any wrapper by default.

You can approach this in many ways:

1. Add some global CSS (using [the `globalImports` config](https://github.com/react-cosmos/react-cosmos/blob/fb2e0deb5f4f1fde48940ea9370d36d7f142bdfa/packages/react-cosmos/config.schema.json#L92-L97)) and make the `body` element stretch to full window size.
2. Add a [fixture decorator](https://github.com/react-cosmos/react-cosmos/tree/master/docs#decorators) in the root of your source code (which thus applies to all fixtures) that wraps fixtures in a `<div>` with position absolute that stretches to full window.
3. [Use an existing webpack config](https://github.com/react-cosmos/react-cosmos/blob/master/docs/README.md#custom-webpack-config) (maybe you already do), and configure [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) to use a custom HTML template where you define the root wrapper as you please.

Choose the option you are most comfortable with and let me know if you need more help.

**Comment by jkavalec** [comment]
Thank you very much!

First two options work well, didn't try third, I am using CRA and don't want to change any WP related stuff.

**Comment by skidding** [comment]
Sounds great. Can we close this issue?
