### ISSUE TITLE
Unable to reproduce intentional states where objects contain undefined

### ISSUE THREAD

**Issue by andyrichardson** [react-cosmos/react-cosmos#1198]
## About

Hi there 👋 I'm having an issue where prop values are being changed by cosmos causing some fixtures to render incorrectly.

## Reproduction
Consider the following component 

```jsx
const MyComponent = ({ target }) => (
  <div>
    {Object.entries(target).map(([key, value]) => 
      <p>{`key: "${key}", value: JSON.stringify(value) || "undefined"`}</p>
    )}
  </div>
)
```

Here's a few example outputs in the browser given props:

#### Example 1
Props
```js
{
  target: { name: "John" }
}
```

Result
```html
<div>
  <p>key: "name", value: "john"</p>
</div>
```

#### Example 2
Props
```js
{
  target: { name: "John", other: undefined }
}
```

Result
```html
<div>
  <p>key: "name", value: "john"</p>
  <p>key: "other", value: undefined</p>
</div>
```

Here are the same examples being rendered in cosmos

#### Example 1
Props
```js
{
  target: { name: "John" }
}
```

Result
```html
<div>
  <p>key: "name", value: "john"</p>
</div>
```

#### Example 2
Props
```js
{
  target: { name: "John", other: undefined }
}
```

Result
```html
<div>
  <p>key: "name", value: "john"</p>
</div>
```

As you can see, the second example is not working because cosmos removes undefined properties from objects which have a prop value.

### Additional info

This looks to be caused by [this line of code](https://github.com/react-cosmos/react-cosmos/blob/a787a32807d21d628f08b8e79d32b0ef1eda5fff/packages/react-cosmos-shared2/src/fixtureState/createValues.ts#L38). 

I think removing undefined component props is a great shout for removing noise (and as far as I can tell, won't cause any functional changes to a component) but doing this for component properties is causing functional differences.

It would be awesome if prop transforms only applied to the top-level component props object 🙏

**Comment by skidding** [comment]
Hi @andyrichardson,

You're right, that file is probably the culprit. That code is related to the props panel and, if I recall correctly, the omission of undefined props was made in order to support a use case where you could delete a prop in the prop panel (temporarily), which we don't even support visually :).

I'll look more into it and maybe remove it that code, especially if it's dead code.

But for now I think you can work around this by changing your fixture from an "element fixture" into a component fixture".

```diff
-export default <MyComponent myProp={undefined} />;
+export default () => <MyComponent myProp={undefined} />;
```

Cosmos can't interfere with your props in the latter case. Let me know if this fixes the issue in the interim ✌️.

**Comment by skidding** [comment]
@andyrichardson this should be fixed in `5.3.0-alpha.5`. Please let me know when you get the chance to try it out.

**Comment by andyrichardson** [comment]
@skidding I didn't get around to trying your workaround - I'll give the Alpha a shot by Monday morning at the latest!

Thanks for looking into this 🙌

**Comment by andyrichardson** [comment]
Just tried `5.3.0-alpha.5` and undefined values inside objects property values are now working as expected - ([snapshot](https://github.com/FormidableLabs/urql-devtools/blob/a409d33de0927bdc07749b373280808a9f54d7e3/src/panel/__image_snapshots__/Arguments%20-%20basic-snap.png) and [reproduction](https://github.com/FormidableLabs/urql-devtools/pull/182/files)). 

Thanks a lot for sorting this! 🚀

**Comment by skidding** [comment]
Great!

Closing this, then, because `5.3.0` is good to go – I'm only waiting to find some time for some marketing stuff before releasing it. If I don't forget I'll ping you once this change gets into the stable channel 😄.
