### ISSUE TITLE
Configure Cosmos with react-app-rewired

### ISSUE THREAD

**Issue by reflash** [react-cosmos/react-cosmos#1209]
### What's wrong?

Hi!
I've been trying to configure React Cosmos to work in my project, but I'm using react-app-rewired to start/build the code.
I've followed some documentation on that, but it seems to be outdated (e.g. it requires to override webpack in config.js, but it seems Cosmos requires json file as a config now)

### User info
- cosmos: 5.3.0
- react-app-rewired: 2.1.6

**Comment by skidding** [comment]
> I've followed some documentation on that, but it seems to be outdated

What documentation are you referring to?

**Comment by reflash** [comment]
> > I've followed some documentation on that, but it seems to be outdated
> 
> What documentation are you referring to?
> 
> This is how you override the webpack config in React Cosmos 5: https://github.com/react-cosmos/react-cosmos/tree/733e4992f276413a562b430cf406a5dfb0225229/docs#webpack-config-override

Seems I've been using some old version of docs, so I figured out how to configure it with webpack config override, thanks!

**Comment by skidding** [comment]
Awesome.

@reflash Can you share what your webpack config override looks like? I want to add a section about react-app-rewired in the new docs for other people in your situation.

**Comment by reflash** [comment]
So I've used this method, but modified it a bit https://github.com/timarney/react-app-rewired#5-provide-rewired-webpack-config-for-3rd-party-tools

note: I'm using lessLoader to override ant-design theme
```
// config-overrides.js
const { addLessLoader, override } = require('customize-cra')

module.exports = override(
  addLessLoader({
    lessOptions: {
      javascriptEnabled: true,
      modifyVars: { '@primary-color': '#005FEA'},
    }
  })
)

// webpack.config.js
const { paths } = require('react-app-rewired');
// require normalized overrides
const overrides = require('react-app-rewired/config-overrides');
const config = require(paths.scriptVersion + '/config/webpack.config.js');

const env = process.env.NODE_ENV
const webpack = overrides.webpack(config(env), env)
module.exports = webpack;
```

**Comment by skidding** [comment]
Thanks for sharing!

Did you set the `webpack.configPath` to `react-scripts/config/webpack.config` in the Cosmos config? As mentioned [here](https://github.com/react-cosmos/react-cosmos/tree/733e4992f276413a562b430cf406a5dfb0225229/docs#using-create-react-app).

If you do I think you don't need the `webpack.config.js` file at all, as Cosmos will already reuse CRA's webpack config.

**Comment by reflash** [comment]
> Thanks for sharing!
> 
> Did you set the `webpack.configPath` to `react-scripts/config/webpack.config` in the Cosmos config? As mentioned [here](https://github.com/react-cosmos/react-cosmos/tree/733e4992f276413a562b430cf406a5dfb0225229/docs#using-create-react-app).
> 
> If you do I think you don't need the `webpack.config.js` file at all, as Cosmos will already reuse CRA's webpack config.

I'm not using `webpack.configPath` to set it. I think rewired applies overrides to the config at `react-scripts/config/webpack.config` and then returns it to react-cosmos. 
If I set it to use `react-scripts/config/webpack.config` directly - it works either, but doesn't apply my less-loader changes as they're not part of default CRA's config.

**Comment by skidding** [comment]
Makes sense. Thanks for the follow up!
