### ISSUE TITLE
Build Error with fresh install of Create React App - babel_loader - Unexpected token

### ISSUE THREAD

**Issue by ericwhitefield** [react-cosmos/react-cosmos#1210]
### What's wrong?

Cosmos does not work with a new install of Create React App

ERROR in ./src/hello.fixture.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/eric/Documents/sourcecode/freshapp/src/hello.fixture.js: Unexpected token (4:15)

  2 | import { Hello } from "./Hello";
  3 | 
> 4 | export default <Hello greeting="Aloha" name="Alexa" />;
    |                ^

### Steps to reproduce

- Install a new CRA
- $ yarn add --dev react-cosmos
- put cosmos scripts in package.json
- create Hello.js and Hello.fixture.js per example, in src directory
- $ yarn cosmos

The problem only occurs if there is a fixture. 

The token error is on the < token. Probably because of babel_loader error JSX in not compiled.

**Comment by skidding** [comment]
Did you configure Cosmos to use the CRA webpack config as described [here](https://github.com/react-cosmos/react-cosmos/tree/733e4992f276413a562b430cf406a5dfb0225229/docs#using-create-react-app)?

![image](https://user-images.githubusercontent.com/250750/83273753-8b931680-a1d5-11ea-98b3-50db46b62d4d.png)

**Comment by ericwhitefield** [comment]
Thx @skidding it was an incorrect format somewhere in my cosmos.config.json
