### ISSUE TITLE
Cosmos with Drag and Drop

### ISSUE THREAD

**Issue by tezcatlipoca** [react-cosmos/react-cosmos#1212]
Hi, and thank you for fantastic work, I've been enjoying and using cosmos with most of my react projects since the early versions. 

My apologies for what is probably a very basic question, but since 4.7 or so I have not been able to figure out how to get it to play nicely with drag-and-drop (react-dnd), and this is becoming a real hindrance.  To be sure I'm missing something fundamental but... Help? 

To get started, here is a naive-case fixture. It will load, but it doesn't work because one is only supposed to invoke `<DragDropContextProvider>` once, and  it will inevitably crash with 'Cannot have two HTML5 backends at the same time.'

PS I am aware that [you've answered this once before,](https://github.com/react-cosmos/react-cosmos/issues/694) but proxies are... deprecated? Difficult to set up? Something else? I'm just a bit lost here. Thank you!

```HTML
import React from 'react';
import Inspector from 'components/Inspector';
import props from './Inspector.props.json';
import { DragDropContextProvider } from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';

export default () => {
    return (
      <DragDropContextProvider backend={HTML5Backend} context="cosmos">
        <Inspector {...props}/>
      </DragDropContextProvider>
    );
};
```
<img width="1249" alt="Screen Shot 2020-06-05 at 5 46 10 PM" src="https://user-images.githubusercontent.com/1745781/83896457-81809300-a754-11ea-8f21-e956fcb34a7d.png">

**Comment by skidding** [comment]
Hi @tezcatlipoca,

Indeed proxies are deprecated, but the new decorators are way easier. So if the React DnD API hasn't changed since I posted that proxy in 2018, this is how a decorator would look like for React Cosmos v5:

```jsx
// cosmos.decorator.jsx

import React from 'react';
import HTML5Backend from 'react-dnd-html5-backend';
import { DragDropContext } from 'react-dnd';

// Create plain wrapper with dnd context
const DDContext = DragDropContext(HTML5Backend)(props => props.children);

export default ({ children }) => <DDContext>{children}</DDContext>;
```

Not sure what Inspector is, though. If this doesn't work, please create a minimal repo with Cosmos and React DnD, and I will help you get it working.

**Comment by tezcatlipoca** [comment]
Thanks so much for your quick response. Indeed the decorator is way easier, and gave me a good "a-ha..." I see how this is supposed to work now. It's still not quite working, but I will play with it a bit and see if I can troubleshoot and will post a repo as requested if I have trouble.

FYI "Inspector" is my component, the one the fixture is for. It's more or less [this](https://github.com/react-cosmos/react-cosmos/blob/master/example/__fixtures__/Values%20Playground.tsx) I just happen to be storing my test props in a JSON and I have baseurl set so my local components resolve without relative paths. Without the drag and drop code, it looks like this:

```js
// __fixtures__/Inspector.js

import React from 'react';
import Inspector from 'components/Inspector';
import props from './Inspector.props.json';

export default () => <Inspector {...props} />;
```

Right now I'm getting a webpack error with the `cosmos.decorator.jsx` setup as above, but I will dig a bit and see if I can troubleshoot this and will either follow up with a complete repo if I get stuck or an update if I sort it. Thank you again!

<img width="1204" alt="Screen Shot 2020-06-05 at 6 53 50 PM" src="https://user-images.githubusercontent.com/1745781/83903875-315afe00-a75f-11ea-80e3-266a6f129626.png">

**Comment by tezcatlipoca** [comment]
Easy fix (dumb mistake): I had the `cosmos.decorator.jsx` file  at the project root rather than inside the `__fixture__` directory ([rereading this](https://github.com/react-cosmos/react-cosmos/tree/master/docs#custom-webpack-config) helped).

Many thanks, all is well now!

**Comment by skidding** [comment]
Any `tsx` file probably needs to be in the `src` directory for Babel to compile it – at least this is how Create React App works. Happy to hear it works. Please close the issue if this is resolved.
