### ISSUE TITLE
Can I use https with own certs for Cosmos server?

### ISSUE THREAD

**Issue by avin** [react-cosmos/react-cosmos#1218]
Not found this feature in manual. I can switch port but seems there is no option to enable https for server. Or I missed something?

**Comment by skidding** [comment]
https is not currently supported. The Cosmos server uses Express and I think it's straightforward to provide private key and cert files. Would you be interesting in contributing to add https support?

**Comment by avin** [comment]
Ok, I'll try :)

**Comment by avin** [comment]
here it is https://github.com/react-cosmos/react-cosmos/pull/1219

**Comment by skidding** [comment]
Just left two comments on your PR, thanks!
