### ISSUE TITLE
Unable to install react-cosmos, unable to find all dependencies

### ISSUE THREAD

**Issue by yannick1691** [react-cosmos/react-cosmos#1245]
### What's wrong?
Unable to install react-cosmos because it's unable to find all needed dependencies.

### Steps to reproduce
1. Use either `npm i --D react-cosmos` or `yarn add --dev react-cosmos`
2. Install will fail because it's unable to find `https://registry.yarnpkg.com/@skidding/webpack-hot-middleware/-/webpack-hot-middleware-2.25.0.tgz:`

### Expected behavior
Installs the package succesfully.

### Screenshots
<img width="981" alt="Screenshot 2020-08-06 at 12 58 00" src="https://user-images.githubusercontent.com/19853448/89524218-772a5600-d7e4-11ea-8542-2c100195238a.png">

<img width="823" alt="Screenshot 2020-08-06 at 12 58 19" src="https://user-images.githubusercontent.com/19853448/89524237-81e4eb00-d7e4-11ea-95ec-80a1aa477a8d.png">

### User info
- Cosmos version: latest
- Node version: V12.18.3

<details><summary>Console output installing with npm (click to open)</summary>
<p>

```shell
➜  npm i --D react-cosmos
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@skidding%2fwebpack-hot-middleware - Not found
npm ERR! 404 
npm ERR! 404  '@skidding/webpack-hot-middleware@^2.25.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-cosmos'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

</p>
</details>

<details><summary>Console output installing with yarn (click to open)</summary>
<p>

```shell
➜  yarn add --dev react-cosmos
yarn add v1.19.1
warning package.json: No license field
warning create-react-app-example@0.1.0: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@skidding/webpack-hot-middleware/-/webpack-hot-middleware-2.25.0.tgz: Request failed \"404 Not Found\"".
```
</p>
</details>

### Additional context
I'm probably missing something, somewhere but I would have no clue what. (Using the example projects also throws this error)

**Comment by skidding** [comment]
Hi @yannick1691,

Thanks for reporting this, but unfortunately NPM was down for 3 hours today, affecting all developers across the globe.
![image](https://user-images.githubusercontent.com/250750/89540079-427ac680-d805-11ea-8f41-2caec97c961a.png)

Please try again and let me know if this persists now that NPM is back online, and close this issue if not. Thank you!

**Comment by yannick1691** [comment]
That explains it, works now 🙏
