### ISSUE TITLE
Using with `<StrictMode>` throws errors

### ISSUE THREAD

**Issue by brianespinosa** [react-cosmos/react-cosmos#1249]
### What's wrong?

Wrap either a decorator or a fixture with `React.StrictMode` and errors are present from Cosmos components.

### Steps to reproduce

1.  Create a decorator with `<StrictMode>` or a fixture with a component wrapped in `<StrictMode>`
2.  Run `npx react-cosmos`
3.  Errors from Strict Mode will show from Cosmos components

### User info

- These errors are from running with npx... I suspect that is irrelevant

**Comment by skidding** [comment]
I think I fixed this in 910a0b016ae596f3a982af1140d39895b6467f32

Please try out `react-cosmos@5.5.0-alpha.11` and let me know if it fixes the issue on your end.

**Comment by brianespinosa** [comment]
I haven't had a chance to test this yet since we use Cosmos with npx. But I have a blocking task to get done this week that this relates to so I will definitely have word before the week is out.

**Comment by skidding** [comment]
> I haven't had a chance to test this yet since we use Cosmos with npx. But I have a blocking task to get done this week that this relates to so I will definitely have word before the week is out.

Does npx not support package versions? I would think you can run `npx react-cosmos@5.5.0-alpha.11 [command]` (where command is cosmos or cosmos-export).

**Comment by brianespinosa** [comment]
@skidding confirmed that this is now working in `5.5.0-alpha.11`

**Comment by skidding** [comment]
This is included in the latest 5.5 release.
