### ISSUE TITLE
Strange behavior, not reloading

### ISSUE THREAD

**Issue by dgreensp** [react-cosmos/react-cosmos#1261]
### What's wrong?

Let me start by saying I am a big React Cosmos fan.  At the moment, hot reload and Command-R reload are both being really flaky for me.  This is with React Cosmos 5.4.0.  My project uses create-react-app.

HMR fires correctly maybe once after page load, but usually I get an error like this and no update occurs:

![image](https://user-images.githubusercontent.com/155814/91736686-ecc6df00-eb62-11ea-918c-98df487b655b.png)

Worse, when I press Command-R to reload (in Chrome on Mac), the page doesn't reload, the browser just waits forever, unless I open localhost:5000 in a fresh tab.

In the terminal, everything looks fine.  It reports that webpack is quickly rebuilding when I change a file.

I tried adding `"hotReload": false` to the Cosmos config, but then when I start Cosmos, the webpack build just hangs and never finishes.

Is there any way to get a verbose debug log?

### Steps to reproduce

This probably isn't something reproducible, unfortunately, but I'm hoping someone can shed some light.

### User info

Config:

```
{
  "watchDirs": ["src"],
  "webpack": {
    "configPath": "react-scripts/config/webpack.config"
  }
}
```

Version 5.4.0

Terminal (looks good):

```
yarn run v1.15.2
$ cosmos
[Cosmos] See you at http://localhost:5000
[Cosmos] Using webpack config found at node_modules/react-scripts/config/webpack.config.js
[Cosmos] Building webpack...
webpack built 2fc8b611686f94a1fa6d in 5213ms
[Cosmos] webpack build invalidated by src/layout/TopNav.tsx
webpack building...
webpack built 4e6866b2a93b1f6abc3f in 206ms
[Cosmos] webpack build invalidated by src/layout/TopNav.tsx
webpack building...
webpack built 0cdd536fcadcf6df6545 in 188ms
[Cosmos] webpack build invalidated by src/layout/TopNav.tsx
webpack building...
webpack built ca62ae30a4782a45ee6c in 173ms
```

**Comment by dgreensp** [comment]
Well, the issue went away, and I'm not sure why.  I was seeing it on my iPhone a lot yesterday, and on my laptop.  I'll reopen if I run into it again.

**Comment by skidding** [comment]
Glad the issue went away. Enjoy React Cosmos! 🙌
