### ISSUE TITLE
"cosmosCapture" error: Utility that converted an array of fixture specs to the list of components now fails... 

### ISSUE THREAD

**Issue by EdmundsEcho** [react-cosmos/react-cosmos#1265]
I have a utility that used to work (much older version of cosmos).  In my attempt to get it back up and running, I ran into the following.

This code:
```jsx
const mergeFixtures = curry((defaultFixture, fixtures) => {
  return fixtures.map(mergeDeepRight(defaultFixture)).reduce((acc, spec) => {
    acc[spec.name] = <spec.Component {...spec.props} />;
    return acc;
  }, {});
});

// Note the goal is to automate the following:
/*
export default {
  primary: (
    <TextField
      key={`${stateId}|format`}
      stateId={`${stateId}|format`}
      name='format'
      disabled={getValue('enabled')}
      value={getValue('format')}
      saveChange
    />
  ),
}; */

```

...compiles, but generates a runtime error when I try to select the component in the menu of components:

```
TypeError: can't access property "cosmosCapture", classType is undefined
```

The call stack includes: 
```
findRelevantElementPaths/<
node_modules/react-cosmos-shared2/dist/FixtureLoader/FixtureCapture/shared/findRelevantElementPaths.js:23

findRelevantElementPaths
node_modules/react-cosmos-shared2/dist/FixtureLoader/FixtureCapture/shared/findRelevantElementPaths.js:14

usePropsCapture
node_modules/react-cosmos-shared2/dist/FixtureLoader/FixtureCapture/props/index.js:37
```

The cosmos code source that references the `cosmosCapture` classname, seems to indicate the purpose is to restrict what props are considered ok... I gathered that the code might be rejected because of how I'm automatically generating the components from an array of objects.

Might anyone have any ideas for how to get this up and running?

\- E

**Comment by EdmundsEcho** [comment]
... It turned out to be a simple matter of making sure the spec prop for the `Component` be properly specified.  Thank you for this useful dev-tool!

**Comment by skidding** [comment]
Nothing better than an issue solved by the time I read it 😅

Glad you figured it out. Good luck!
