### ISSUE TITLE
You may need an appropriate loader to handle this file type: Cosmo 5.5

### ISSUE THREAD

**Issue by cj** [react-cosmos/react-cosmos#1267]
I just did a fresh install with next.js and cosmo 5.5, created an example button component and was greeted with:

```
ERROR in ./components/Button/Button.fixture.tsx 4:15
Module parse failed: Unexpected token (4:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Button } from '.'
|
> export default <Button />
|
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 7:42-135
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js
 @ multi ./node_modules/react-cosmos/dist/plugins/webpack/client/reactDevtoolsHook.js ./node_modules/@skidding/webpack-hot-middleware/client.js?reload=true&overlay=false ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js
```

Please let me know if you need anything further or for me to create a repo, cheers!

**Comment by skidding** [comment]
Hi @cj,

Did you follow [these steps](https://github.com/react-cosmos/react-cosmos/tree/master/docs#nextjs)?

**Comment by skidding** [comment]
If you ever get back to this please let us know if you [the Next.js instructions](https://github.com/react-cosmos/react-cosmos/tree/master/docs#nextjs) solved your issue. Specifically, if you installed `babel-loader` as a dev dependency.
