### ISSUE TITLE
Webpack error with brand new Expo project

### ISSUE THREAD

**Issue by tomparkp** [react-cosmos/react-cosmos#1274]
### What's wrong?

Based on the docs I was given the impression Cosmos can be used across React Native and web in an Expo project but using Cosmos in an Expo project yields webpack errors.

### Steps to reproduce

1.  Clone `https://github.com/tomparkp/react-cosmos-expo-bug`
2.  `yarn install` and `yarn cosmos`
3.  See webpack error.

```
ERROR in ./test.fixture.js 4:15
Module parse failed: Unexpected token (4:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import React from "react";
| 
> export default <Text>Hello World</Text>;
| 
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 7:22-76
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js
 @ multi ./node_modules/react-cosmos/dist/plugins/webpack/client/reactDevtoolsHook.js ./node_modules/@skidding/webpack-hot-middleware/client.js?reload=true&overlay=false ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js
```

**Comment by skidding** [comment]
Hi @tomparkp,

Did you check out the [Cosmos docs on React Native](https://github.com/react-cosmos/react-cosmos/tree/master/docs#react-native)?

The command you need to run is `cosmos-native`. This will get you past that error, and you'll also see the other steps required to get up and running with Cosmos in your React Native project. Please let me know if have other issues.

**Comment by tomparkp** [comment]
`cosmos-native` runs Cosmos in the native environment only (iOS/Android devices or simulators) per [this tweet](https://twitter.com/ReactCosmos/status/1189128577498910720) I thought it was possible to mirror across web and native at the same time?

**Comment by tomparkp** [comment]
Per the docs
> Run cosmos --external-userdeps instead of cosmos-native and Cosmos will mirror your fixtures on both DOM and Native renderers.

`cosmos --external-userdeps` yields the same error as above.

**Comment by skidding** [comment]
Oh, yes, I missed the _web_ part. In this case the [Compilation docs](https://github.com/react-cosmos/react-cosmos/tree/e92f1ecbce529af4b4706172b7e5aae15823ff1e/docs#compilation) is the relevant section.

To start with, run `yarn add --dev babel-loader html-webpack-plugin` and you'll get the "Hello World" going.

**Comment by tomparkp** [comment]
That works for the example project but when attempting to apply it to my own project it broke on images and on some React Native dependencies. I ended up creating my own webpack config based on: https://webpack.js.org/plugins/html-webpack-plugin/

However, in the RNW docs they recommend against doing this and using Expo since it now comes with RNW support out of the box. The Expo web config is pretty complex, I attempted to have cosmos use it by pointing to it in node_modules but no-go.

If Expo is the recommended way to use RNW it would be nice if Cosmos could leverage it out-of-the-box.

**Comment by skidding** [comment]
> I attempted to have cosmos use it by pointing to it in node_modules but no-go.

Can you expand more on this? Cosmos tries hard to run on existing webpack configs, so if the Expo webpack config is accessible I'd be interested in making sure it can be used by Cosmos.

**Comment by tomparkp** [comment]
Expo as of recent releases has built in RNW support via https://www.npmjs.com/package/@expo/webpack-config. If you add that package to an expo project it will add the base config to the expo node module with the option to customize/override via `expo customize:web`.

**Comment by skidding** [comment]
This is far from an out-of-the-box solution, but I played around with the Expo webpack config and managed to make it play nicely with Cosmos with some tweaks.

Can you try this `webpack.config.js`?

```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync({
    mode: 'development',
    projectRoot: __dirname
  }, argv);

  // Modify html-webpack-plugin
  config.plugins[0].options.filename = '_renderer.html';

  // Remove ManifestPlugin because it requires specific entrypoints that are
  // replaced by Cosmos
  config.plugins = config.plugins.filter(p =>
    !p.constructor || p.constructor.name !== 'ManifestPlugin'
  );

  return config;
};
```

**Comment by tomparkp** [comment]
Sorry to have this issue hanging open, we migrated away from Expo to bare React Native so I haven't had a chance to test this out, I'll have to make a new test project to see if this works.

**Comment by tomparkp** [comment]
@skidding That config does appear to work, thanks! Any thoughts on bringing expo-web compatibility out of the box given its the [recommended tooling](https://necolas.github.io/react-native-web/docs/installation/) for React Native Web?

**Comment by skidding** [comment]
> @skidding That config does appear to work, thanks! Any thoughts on bringing expo-web compatibility out of the box given its the [recommended tooling](https://necolas.github.io/react-native-web/docs/installation/) for React Native Web?

Out of the box compatibility is very desirable. It would be great if someone offered to maintain all these specific integrations because it's hard for me to keep up. At least once in the past I've made Cosmos compatible with CRA, Next, Expo, etc., but all these frameworks are moving targets and even a patch version can break compatibility with 3rd party tools like Cosmos because they are considered end user tools and they refactor their internals on a regular basis.

**Comment by tomparkp** [comment]
@skidding Ironically the configuration already appears to be broken again so you have a good point. I guess I'll close the issue as this isn't really solvable without introducing something like plugins e.g. `cosmos/expo` `cosmos/next` etc

**Comment by davidisaaclee** [comment]
I'd also like to use Cosmos in a web + iOS Expo project, although it makes sense that it would be a lot for one person to maintain all these different configurations.

In case it helps someone else out, I did the following to get mirroring working on Expo SDK 44 :

1. Run `expo customize:web` to generate a `webpack.config.js`. _(If this is exiting without making a config file, make sure you read the instructions - I was tripped up by the UI here.)_
2. The patch above is close to working, but needed two updates: (1) The `env` passed to `createExpoWebpackConfigAsync` doesn't accept a string anymore - it expects an object of [this shape](https://github.com/expo/expo-cli/tree/de947a91dfc3aa5c4b92330c3c03ec6649e0129f/packages/webpack-config#environment); and (2) the HtmlWebpackPlugin requires a `projectRoot` in its options (not sure what is different about running via Cosmos that omits this).

Putting that all together, I modified the `webpack.config.js` to look like this:

```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  if (typeof env === 'string') {
    env = {
      mode: env,
      projectRoot: __dirname,
      platform: 'web',
    };
  }
  const config = await createExpoWebpackConfigAsync(env, argv);
  
  // Modify html-webpack-plugin
  const htmlPlugin = config.plugins.find(p => p.constructor && p.constructor.name === 'HtmlWebpackPlugin');
  if (htmlPlugin) {
    htmlPlugin.options.projectRoot = __dirname;
    htmlPlugin.options.filename = '_renderer.html';
  }

  // Remove ManifestPlugin because it requires specific entrypoints that are
  // replaced by Cosmos
  config.plugins = config.plugins.filter(p =>
    !p.constructor || p.constructor.name !== 'ManifestPlugin'
  );


  return config;
};
```

As stated above, this will probably break when Expo updates. I'm using a managed Expo project; here are the relevant(?) dependency versions that I'm working with:

- @expo/webpack-config: 0.16.15
- expo: 44.0.3
- _are other dependencies relevant? happy to add more_

I have only used this briefly in iOS/web development so far; I haven't tried exporting.

**Comment by magom001** [comment]
Hi! Can someone actually explain how to launch cosmos on a simulator with this setup? I tried to run 
`cosmos --external-userdeps && expo start` but the simulator simply shows "No fixture selected"

**Comment by skidding** [comment]
> Hi! Can someone actually explain how to launch cosmos on a simulator with this setup? I tried to run
> `cosmos --external-userdeps && expo start` but the simulator simply shows "No fixture selected"

Did you open the Cosmos UI on http://localhost:5000 (or your configured port) to select the fixture?

**Comment by magom001** [comment]
ok, it was my mistake twice:
1. I had a mismatching RN version
2. My test fixture was hidden behind the "camera" on the simulator so I was staring at a blank screen (🤦‍♂️)
