### ISSUE TITLE
clean-webpack-plugin breaks react-cosmos

### ISSUE THREAD

**Issue by birtles** [react-cosmos/react-cosmos#1279]
### What's wrong?

`devServer.ts` forces the webpack output path to `/`:

https://github.com/react-cosmos/react-cosmos/blob/52ef3d16cbad56f7a1637e94adfd791cde8899fa/packages/react-cosmos/src/plugins/webpack/webpackConfig/devServer.ts#L69-L71

`clean-webpack-plugin` passes this output path to `delSync`:

https://github.com/johnagan/clean-webpack-plugin/blob/021d2b68efd18fbd99e02c169d9e32300f15b4f4/src/clean-webpack-plugin.ts#L310-L317

But that can result in errors when it tries to read paths it doesn't have access to. Under WSL I get the following error when running `yarn cosmos`:

```log
✖ ｢wdm｣: Error: EACCES: permission denied, scandir '/c/$Recycle.Bin/S-1-5-18'
    at Object.readdirSync (fs.js:854:3)
```

As a result react-cosmos just sits there waiting for the renderer without any apparent error in the browser.

### Steps to reproduce

1. Find any project using `clean-webpack-plugin`
2. Add `react-cosmos`
3. Run `yarn cosmos`

### Workaround

I worked around this by adding the following `webpack.override.js` to my setup:

```js
module.exports = (webpackConfig) => {
  // Drop clean-webpack-plugin because react-cosmos sets the compiler
  // output path to '/' and that will cause it to error when it does
  // del.sync with `cwd` set to `compiler.options.output.path` as it tries
  // to read from directories it doesn't have permission to read from.
  //
  // We shouldn't need clean-webpack-plugin for cosmos builds anyway.
  const plugins = webpackConfig.plugins.filter(
    (plugin) =>
      plugin.constructor && plugin.constructor.name !== 'CleanWebpackPlugin'
  );
  return { ...webpackConfig, plugins };
};
```

**Comment by skidding** [comment]
Hi @birtles,

Thanks for reporting this and especially for posting the solution.

We can fix this with a minor version because Cosmos 5 doesn't support webpack versions older than 4 anyway. What would be a better output path in development, the project root?

**Comment by birtles** [comment]
Thanks!

> What would be a better output path in development, the project root?

I suppose so. I'm really not familiar enough with webpack to know.

Alternatively you could use [`fs.mkdtemp`](https://nodejs.org/api/fs.html#fs_fs_mkdtemp_prefix_options_callback) (or `fs.mkdtempSync`) to create a temporary directory I guess? That would avoid the issue of plugins like `clean-webpack-plugin` trying to scan the entire filesystem.

**Comment by skidding** [comment]
Another thing we could do is automatically omit `CleanWebpackPlugin` in Cosmos since it's meant for production builds. 

**Better yet**, it seems like the way to go is to set `output.path` to `undefined` in development. Create React App [has been doing it since Nov 2018](https://github.com/facebook/create-react-app/blob/c1714042b60ff48cb08407bec236c0a92d26773b/packages/react-scripts/config/webpack.config.js#L157-L158) so it's definitely webpack 4 compatible. We don't need to hang on to that "weird ~~required~~ requirement for old webpack versions" anymore.

@birtles Would you like to tackle this one?

**Comment by birtles** [comment]
> @birtles Would you like to tackle this one?

Sure. I've opened #1280 for this.
