### ISSUE TITLE
Server crashed when user webpack config is es-module

### ISSUE THREAD

**Issue by Akiyamka** [react-cosmos/react-cosmos#1287]
### What's wrong?
Webpack 5.18.0 project.
Install 
```
[Cosmos] Using default cosmos config
[Cosmos] See you at http://localhost:5000
[Cosmos] Using default webpack config
[Cosmos] Server crashed...

  (╯°□°)╯︵ ┻━┻
  
webpack.config.ts:1
import path from 'path';
SyntaxError: Cannot use import statement outside a module

```
### Steps to reproduce
1. Create new project with with next webpack [config](https://gist.github.com/Akiyamka/e6cca2ccaa0f3f8384a989d4743acdf3)
Few stupid simple react components <App /> <HelloWorld /> and <Button />, check it work as expected.
2.
```
npm i --D react-cosmos
```
3. add 
```
    "cosmos": "cosmos",
    "cosmos:export": "cosmos-export"
 ```
 to package.json scripts
4.
```
npm run cosmos
```

### User info

- Server terminal output: 
```
npm run cosmos 

> landing@0.0.1 cosmos /Git/landing
> cosmos

[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] See you at http://localhost:5000
[Cosmos] Using webpack config found at webpack.config.ts
[Cosmos] Server crashed...

  (╯°□°)╯︵ ┻━┻

/Git/landing/webpack.config.ts:1
import path from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:991:16)
    at Module._compile (internal/modules/cjs/loader.js:1039:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireModule (/Git/landing/node_modules/react-cosmos/dist/shared/fs.js:19:10)
    at _callee2$ (/Git/landing/node_modules/react-cosmos/dist/plugins/webpack/webpackConfig/shared.js:110:84)
    at tryCatch (/Git/landing/node_modules/regenerator-runtime/runtime.js:63:40)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! landing@0.0.1 cosmos: `cosmos`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the landing@0.0.1 cosmos script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-01-28T11_52_11_153Z-debug.log

```

- Browser console output: null
- Cosmos version: 5.5.3
- Cosmos config: ["No config is required to star" ](https://github.com/react-cosmos/react-cosmos/tree/master/docs#config)
-  webpack version: 5.18
-  webpack [config](https://gist.github.com/Akiyamka/e6cca2ccaa0f3f8384a989d4743acdf3)

**Comment by skidding** [comment]
Yes, Cosmos doesn't support ES modules for webpack configs at the moment.

This is where Cosmos imports the user's webpack config:

https://github.com/react-cosmos/react-cosmos/blob/d88061a943457b967daf84a503e73283182f1521/packages/react-cosmos/src/plugins/webpack/webpackConfig/shared.ts#L62-L70

All published Cosmos code is compiled to CommonJS modules to support older Node versions. Do you know how to import an ES module from CommonJS code that's running on a version of Node that supports ES modules natively?

**Comment by Akiyamka** [comment]
Yes, with this [package](https://www.npmjs.com/package/esm), you can import the es code in a CommonJS module, even if the node does not support the ES modules native.
But I don't know if it will work with ts files, I need to investigate.

**Comment by Akiyamka** [comment]
I found a workaround:
- npm i ts-node -D
- near with current `webpack.config.ts` create new file `webpack.config.js` with next content:
```
require('ts-node').register({
  files: true,
  transpileOnly: true,
  project: './tsconfig.json',
});
module.exports = require('./webpack.config.ts');
```;
Now react-cosmos work without problems

**Comment by skidding** [comment]
> I found a workaround:
> 
> * `npm i ts-node -D`
> * near with current `webpack.config.ts` create new file `webpack.config.js` with next content:
> 
> ```js
> require('ts-node').register({
>   files: true,
>   transpileOnly: true,
>   project: './tsconfig.json',
> });
> module.exports = require('./webpack.config.ts');
> ```
> 
> Now react-cosmos work without problems (tested on `5.6.0-alpha.2`)

Nice!

Did you have to rename/move your old webpack config file?

**Comment by Akiyamka** [comment]
> Did you have to rename/move your old webpack config file?
Good question. When I have both - ...config.ts and ...config.js files webpack read only js version of config.
So it transpiled for webpack the same way as for cosmos.
But, for development mode I want to check types error so my dev script point directly to ts version of config:
```
"start:dev": "webpack-cli serve --env development --open --hot --config webpack.config.ts"
```
This possible because webpack 5 transpile config.ts under the hood

**Comment by skidding** [comment]
> > Did you have to rename/move your old webpack config file?
> 
> Good question. No, I have not touched the original configuration at all.
> 
> When I have both - ...config.ts and ...config.js - webpack read only js version of config.
> So it transpiled for webpack the same way as for cosmos.
> But, for development mode I want to check types, so my dev script point directly to ts version of config:
> 
> ```
> "start:dev": "webpack-cli serve --env development --open --hot --config webpack.config.ts"
> ```
> 
> This possible because webpack 5 compile ...config.ts under the hood.

Very cool. I'll close this issue then.

If anyone else has this problem we can add [troubleshooting](https://github.com/react-cosmos/react-cosmos/tree/master/docs#troubleshooting) bullet point for working with TS webpack configs. 

Moreover, Cosmos could potentially detect if ts-node is installed in the presence of webpack.config.ts, and do everything under the hood automatically. But I think it's a bit early for that as I don't how many people use TS webpack configs. And  we can also use your solution if needed. Thanks for reporting it!

**Comment by Akiyamka** [comment]
@skidding, I found that Webpack 5 have different config-as-function interface for js and ts configs:
For webpack-config`.ts` it's:
```ts
(env: { development: boolean, production: boolean }) => Webpack.Config
```
for webpack-config`.js` it's:
```ts
(env: 'development' | 'production') => Webpack.Config
```
Unfortunately, I did not find any mention of this feature in the [documentation](https://webpack.js.org/configuration/configuration-languages/#typescript).

To take this difference into account, I slightly change config compilation script.
```js
require('ts-node').register({
  files: true,
  transpileOnly: true,
  project: './tsconfig.json',
});

const webpackConfig = require('./webpack.config.ts').default;

module.exports = (env) => typeof webpackConfig === 'function'
  ? webpackConfig({
    development: env === 'development',
    production: env !== 'development'
  })
  : webpackConfig;
```

**Comment by skidding** [comment]
@Akiyamka Thanks for the heads up!
