### ISSUE TITLE
How to create a proxy to mock the API?

### ISSUE THREAD

**Issue by emirdeliz** [react-cosmos/react-cosmos#1293]
**How to create a proxy to mock the API?** 

I checked the documentation and didn't understand how to configure the proxy. 

My API has the following URL: `/api/departments/<dynamic value>/goals`

Is it possible to do that?

**Comment by skidding** [comment]
Hi @emirdeliz,

It appears that the `httpProxy` isn't explained in the docs. Sorry. [Here is the JSON schema](https://github.com/react-cosmos/react-cosmos/blob/84c8444fd5a5d2add0ca9f5fcd29dee892d49383/packages/react-cosmos/config.schema.json#L92-L131) for it.

[Here is another person asking about this](https://github.com/react-cosmos/react-cosmos/issues/1268). We need to document it 😬.

**Comment by emirdeliz** [comment]
Thanks!
