### ISSUE TITLE
Style order messed up after cosmos-export

### ISSUE THREAD

**Issue by Akiyamka** [react-cosmos/react-cosmos#1295]
### What's wrong?
Command cosmos-export produce style bundle with wrong order of styles.
Styles imported in cosmos decorator inserted in a middle of bundle 0_0.

**Just `cosmos` and `npm run build` or `dev` create main.css with right order.**

### Steps to reproduce

1.  Put in `cosmos.decorator.js` next strings
```js
import 'Common/styles/variables.css';
export default ({ children }) => children;
```

2. Create simple fixature with css-modules
3. `npm run cosmos`
4. Open main.css file (from network tab of page) and see right order 
5. Stop cosmos and run `npm run cosmos:export`
6. `npx serve ./cosmos-export`
7. Open main.css and see that variables somewhere in a middle

### Screenshots

From cosmos server
![изображение](https://user-images.githubusercontent.com/6587585/108881178-17768980-7614-11eb-94c0-7faafdddb2b1.png)

From cosmos-export + serve
![изображение](https://user-images.githubusercontent.com/6587585/108881403-5278bd00-7614-11eb-894c-828ba5ceebe2.png)

### User info

- Server terminal output
```bash
 npm run cosmos:export

> hot-activation-landing@0.0.1 cosmos:export /home/adubinin/Git/hot-activations-landing
> cosmos-export

[Cosmos] Using webpack config found at webpack.config.js
[Cosmos] Export complete!
Export path: /home/.../cosmos-export

```
- Browser console output - no errors
- Cosmos version - "react-cosmos": "5.6.0-alpha.2"
- If bug occurred on upgrade: I don't know
- Cosmos config: no config
- If applicable: webpack version 5.18.0
- If applicable: webpack config 
Part about styles
```
 {
      test: /\.module\.p?css$/,
      use: [
        MiniCssExtractPlugin.loader,
        {
          loader: 'css-loader',
          options: {
            sourceMap: true,
            modules: {
              localIdentName: '[name]_[local]__[hash:base64:5]',
            },
            importLoaders: 2,
          },
        },
        {
          loader: 'postcss-loader',
        },
      ].filter(f => f),
    },
    {
      test: /\.p?css$/,
      use: [
        MiniCssExtractPlugin.loader,
        {
          loader: 'css-loader',
          options: {
            sourceMap: true,
            modules: false,
            importLoaders: 2,
          },
        },
        {
          loader: 'postcss-loader',
        },
      ].filter(f => f),
      exclude: /\.module\./,
    },
```

### Additional context
Once the main.css?some_hash file just got stuck on one of the versions. No matter what I did, react-cosmos got out the old version from somewhere even after I completely killed its process and started it again. At same time in the generated file using react-cosmos this problem was not observed. During the investigation, the bug disappeared as mysteriously as it appeared and stopped playing even after a complete rollback of all changes to start point. Magic...

Look at screen-shots - different files have same hash - maybe that cause some problem?

**Comment by Akiyamka** [comment]
Total disabling react-fast-refresh not help.
Styles still messed after cosmos-export, add old style still stuck with cosmos.

An interesting point - I completely removed some of the styles from the project so that there was no mention of them, but react-cosmos still add this style in `main.css?different_hashes` event after restart. I wonder, how it possible? React-cosmos have some cache?

**Comment by skidding** [comment]
Have you tried putting `Common/styles/variables.css` as `globalImports` directly in the Cosmos config?

**Comment by Akiyamka** [comment]
@skidding, thanks for the hint! `globalImports` works great when i drop alias from path.
Does this mean cosmos decorator will get required after than fixtures during build?

**Comment by skidding** [comment]
> Does this mean cosmos decorator will get required after than fixtures during build?

Indeed, [decorators are imported right after fixtures](https://github.com/react-cosmos/react-cosmos/blob/45e9c63f301f17509e29dd1cfc6d8b9555a1882a/packages/react-cosmos/src/shared/userDeps/userDepsTemplate.ts#L37-L43). But I think it shouldn't make a difference. In the future I would like to support lazy fixture import (and probably decorator too), because it would increase the startup time when you have thousands of fixtures but you only care about a few in a given session. So the import order can differ more in that scenario.

If you want something to be always imported then `globalImports` is the way to go.
