### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by IgnusG** [react-cosmos/react-cosmos#1314]
### What's wrong?

I'm trying out cosmos with snowpack (love the idea of combining these two ❤️). 
I set up everything and the UI seems to connect to the renderer but then when selecting a component I get:

```
_playground.js:2 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at s (_playground.js:2)
    at postRendererRequest (_playground.js:2)
    at _playground.js:2
    at Array.forEach (<anonymous>)
    at _playground.js:2
    at Array.forEach (<anonymous>)
    at emit (_playground.js:2)
    at u (_playground.js:2)
    at i (_playground.js:2)
    at _playground.js:2
```

### Steps to reproduce

1.  Configure react-cosmos with snowpack (& typescript)
2.  Open cosmos and select component

### Screenshots

![image](https://user-images.githubusercontent.com/6438760/111503850-6ca34800-8747-11eb-8ce3-584b9c1f0831.png)

### User info

- Cosmos version: `5.6.0`

<details>
<summary><code>config/cosmos.config.json</code></summary>
<pre>
{
  "$schema": "http://json.schemastore.org/cosmos-config",
  "rootDir": "../",
  "staticPath": "public",
  "userDepsFilePath": "src/pages/cosmos/cosmos.userdeps.js",
  "experimentalRendererUrl": "http://localhost:8080/cosmos"
}
</pre>
</details>

<details>
<summary><code>snowpack.config.js</code></summary>
<pre>
/** @type {import("snowpack").SnowpackUserConfig } */
module.exports = {
  mount: {
    "src": "/dist",
    "public": {
      url: "/",
      static: false,
    },
  },
  routes: [
    { src: '/cosmos', dest: '/cosmos.html' },
  ],
  alias: {
    "@app": "./src"
  },
  plugins: [
    "@snowpack/plugin-react-refresh",
    "@snowpack/plugin-typescript",
    "@snowpack/plugin-optimize",
    ["@snowpack/plugin-postcss", { config: "./config/postcss.config.js" }],
  ],
  packageOptions: {
    "source": "local",
  },
  devOptions: {
    /* ... */
  },
  buildOptions: {
    /* ... */
  },
};
</pre>
</details>

<details>
<summary><code>public/cosmos.html</code></summary>
<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en&quot;&gt;
  &lt;head&gt;
    &lt;meta charset=&quot;utf-8&quot; /&gt;
    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
    &lt;meta name=&quot;description&quot; content=&quot;Starter Snowpack App&quot; /&gt;
    &lt;link rel=&quot;stylesheet&quot; href=&quot;/index.css&quot; /&gt;
    &lt;title&gt;Cosmos&lt;/title&gt;
  &lt;/head&gt;
  &lt;body&gt;
      &lt;div id=&quot;root&quot;&gt;&lt;/div&gt;
  &lt;/body&gt;
  &lt;script type=&quot;module&quot; src=&quot;/dist/pages/cosmos/cosmos.js&quot;&gt;&lt;/script&gt;
&lt;/html&gt;
</pre>
</details>

<details>
<summary><code>src/pages/cosmos/cosmos.tsx</code></summary>
<pre>
import { mountDomRenderer } from 'react-cosmos/dom';
// @ts-expect-error
import { decorators, fixtures, rendererConfig } from './cosmos.userdeps';
mountDomRenderer({ rendererConfig, decorators, fixtures });
if (import.meta.hot) import.meta.hot.accept();
</pre>
</details>

<details>
<summary><code>src/components/button/button.fixture.tsx</code></summary>
<pre>
import React from &quot;react&quot;;
import { Button } from &quot;@app/components/button/button&quot;;
export default &lt;Button&gt;Click me&lt;/Button&gt;;
</pre>
</details>

<details>
<summary><code>src/components/button/button.tsx</code></summary>
<pre>
import React from &quot;react&quot;;
export interface ButtonProps extends JSX.ElementChildrenAttribute {}
export function Button(props: ButtonProps) {
  const { children } = props;
  return &lt;button&gt;{ children }&lt;/button&gt;;
}
</pre>
</details>

Running `yarn snowpack dev` and `yarn cosmos --config ./config/cosmos.config.json`

**Comment by IgnusG** [comment]
Oh, I just realized it's the same with the official demo page.
It does not appear to work with Edge or the plugins I have installed.

I've tried Google Chrome Canary and it works there.

**Comment by IgnusG** [comment]
It's the Popup Blocker Extension 
https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche that breaks this. 

After disabling it the live demo and the local server both work fine.

> Sorry for the noise. Thanks for this awesome tool! ❤️

**Comment by skidding** [comment]
@IgnusG Thanks for the follow-up!
