### ISSUE TITLE
Expectations on performance

### ISSUE THREAD

**Issue by messman** [react-cosmos/react-cosmos#1315]
Question: Is it a goal of React Cosmos to have good startup performance?

By that question, I mean: Say I'm a developer who needs to start and stop React Cosmos often (perhaps due to machine constraints; perhaps out of personal preference due to work patterns). Should I expect that the React Cosmos project is trying to make `npm run cosmos` fast and optimized? I'm not talking about hot module reloading in this issue - just the 'startup'.

I don't mean to imply that React Cosmos does not currently have good performance. Performance is relative, and I'm not trying to open an issue just to say that React Cosmos is slow to start for my projects. However, I don't know whether or not it's _supposed_ to be fast / whether the developers (or developer) intend for it to be fast. From what I can tell, [the React Cosmos website](https://reactcosmos.org/) makes general claims about the time savings of hot-module-reloading and a UI component sandbox in general, but does not specifically claim that React Cosmos itself is trying to be fast. In reading the goals of React Cosmos in the documentation and contributing guidelines, I also see no specific mention of speed as a goal. I don't see many configuration options that would help in optimizing React Cosmos for speed.

Some tools similar to React Cosmos have stated that it is a goal of their products to be as fast as possible. For example, [Storybook 6.1](https://storybook.js.org/blog/storybook-6-1/) focused almost entirely on improving startup performance since startup can be known to take significantly longer than the build of the actual target application / library.

As a developer currently test-driving React Cosmos as a replacement for Storybook, knowing the answer to the question in this issue is somewhat important to my ongoing adoption of React Cosmos: startup performance affects my development experience. I understand that React Cosmos may not be interested in drawing direct comparisons to other similar tools.

More information on my specific experience:
Project / Repo: [messman/react-common](https://github.com/messman/react-common), a React utility component library
Time for React Cosmos (5.6.0) to finish startup: `~43s`
Time for build to complete (Webpack 5): `~8s`
Of course, these times are for my machine only and are an apples-to-oranges comparison. They build/bundle different assets. Hopefully, though, the numbers make clear why I am interested to know if React Cosmos is trying to be quick. Storybook 5 came in at around the same overall time, and Storybook 6 cut that time in half (though it was fully configured).

I'm a big fan of React Cosmos overall - great job. If performance is _not_ a goal of React Cosmos, I think that's fine. Making it a goal and stating so on the website, however, may help with marketing React Cosmos to developers.
Cheers!

**Comment by skidding** [comment]
Hi @messman,

Thanks for you interest. Cosmos definitely cares about performance. Not that we've done any crazy optimizations, but this is because we never had to. The main thing that Cosmos does that helps with performance is that it doesn't built anything Cosmos-related on the user's machine. The UI is prebuilt and published to npm.

You can tell that Cosmos is ready when you see

```bash
[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] See you at http://localhost:5000
[Cosmos] Using webpack config found at cosmos.webpack.config.js
[Cosmos] Building webpack...
```

which is about 1s or less. You can also open Cosmos and see that the UI is loaded and says `Waiting for renderer...` (ie. which basically means the user build).

Note: I just noticed for the first time in your project that sometimes Firefox doesn't open `localhost:5000` until the renderer is ready, which shouldn't be the case. You should be able to open the Cosmos UI instantaneously and see the loading message until the renderer is ready. Your project is the first time I see this, and the only explanation I can think of is that the (single threaded) Node process is so busy with the webpack build that it can't be bothered to serve a basic Express route. If this is the case I'd be curious why I haven't seen it in other codebases and how to fix it, because really Cosmos is ready immediately.

Now, your webpack compiles in 35-40s on my machine.

> Time for React Cosmos (5.6.0) to finish startup: ~43s
> Time for build to complete (Webpack 5): ~8s

Not sure where this time discrepancy comes from. I believe you're comparing `npm run cosmos` with `npm run build`. Not sure what `ts-webpack-builder` does, but in any case it doesn't seem to be analogous to how Cosmos uses webpack because one is saving the file on disk and the other is starting a dev server in watch mode.

You don't have to worry about the webpack version used because Cosmos doesn't come with webpack included, it just uses what you have installed already. I believe if you had a regular webpack dev server start your app, with the same webpack config, you'd see a very similar figure. 40s is indeed high for small app, but you may be compiling node modules. I didn't really spend time investigating your webpack setup.

Side note: When your app leverages code splitting, Cosmos can indeed take longer to build than a regular dev server. Cosmos imports all your fixtures (and potentially all your code) at once, so the Cosmos webpack build gets huge in a large app with many fixtures (think thousands). I'm actually experimenting with a solution for this (in Lazy fixture importing #1313), where you can opt out to make fixture importing lazy, and only import a fixture once you click on it in the Cosmos UI, effectively doing code splitting per fixture. This is still experimental as it might cause issues down the road, but it could also prove to be a game changer, so keep an eye on it if you're interested.

**Comment by messman** [comment]
I appreciate the swift and thorough response!

> Cosmos definitely cares about performance. Not that we've done any crazy optimizations, but this is because we never had to. The main thing that Cosmos does that helps with performance is that it doesn't build anything Cosmos-related on the user's machine. The UI is prebuilt and published to npm.

This statement above answers my question - thank you. That alone is enough to close this issue. Including that explanation in the documentation somewhere may be useful to others.

___

Also, I appreciated hearing your thoughts about my specific situation. I'm as puzzled as you are as to why `npm run cosmos` seems to take so long. I took a few hours this morning to investigate further, and I am still unsure. I tried a few things:

1. I attempted to delete my `*.fixture.tsx` files one by one, starting React Cosmos after each delete, to see how the startup time changed. Interestingly, each fixture was responsible for about 2 seconds increase in the startup time of React Cosmos. If I removed _all_ fixtures, the startup time was equivalent to my library's build time (`npm run build`) at around 8 seconds. I have about 15 fixture files, and if each one adds between 1.5 and 2.5 seconds to the launch of React Cosmos, then 43s makes more sense. Why, though, would each fixture add two seconds?
2. I attempted the same test as above but replaced the content of each of the 15 fixture files with a no-op (`export default () => { return null; }`). Multiple runs of `npm run cosmos` averaged about 30 seconds. This suggests that there is a cost, somehow, to even just creating a `*.fixture.tsx` file in my setup. If I then delete all the fixture files, `npm run cosmos` returns to the expected 8 seconds.
3. I added the Webpack [ProgressPlugin](https://webpack.js.org/plugins/progress-plugin/) to my webpack config to hopefully learn more about where the increase in time occurs. The plugin reports on the build in the console as it progresses. Routinely, the progress plugin would stutter and freeze when the webpack builder was focused on files in `core-js` or `react-cosmos-shared2`. I imagine there is code in `react-cosmos-shared2` that needs to be run in order to prepare fixtures, but it seems as if webpack is actually building parts of React Cosmos itself. It's likely I'm misinterpreting what I saw, because that doesn't seem right.

I also went into the React Cosmos source to log the final webpack configuration before build and after React Cosmos tweaks it. I've included that below, with absolute paths on my machine changed for privacy.

```js

{
  mode: 'development',
  target: 'web',
  resolve: {
    extensions: [ '.ts', '.tsx', '.js', '.json' ],
    alias: {
      '@': '[...]/react-common-git/src',
      react: '[...]/react-common-git/node_modules/react',
      'react-dom': '[...]/react-common-git/node_modules/react-dom'
    }
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [
                [
                  '@babel/preset-env',
                  { debug: false, targets: '> 2%, not ie <= 11' }
                ],
                '@babel/preset-react'
              ],
              cacheDirectory: false,
              cacheCompression: false
            }
          },
          {
            loader: 'ts-loader',
            options: {
              getCustomTransformers: [Function: getCustomTransformers],
              onlyCompileBundledFiles: true
            }
          }
        ]
      },
      {
        loader: '[...]/react-common-git/node_modules/react-cosmos/dist/plugins/webpack/webpackConfig/userDepsLoader.js',
        include: '[...]/react-common-git/node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js'
      }
    ]
  },
  entry: [
    '[...]/react-common-git/node_modules/react-cosmos/dist/plugins/webpack/client/reactDevtoolsHook.js',
    '[...]/react-common-git/node_modules/@skidding/webpack-hot-middleware/client.js?reload=true&overlay=false',
    '[...]/react-common-git/node_modules/react-cosmos/dist/plugins/webpack/client/index.js'
  ],
  output: {
    filename: '[name].js',
    publicPath: '/',
    devtoolModuleFilenameTemplate: [Function: devtoolModuleFilenameTemplate]
  },
  plugins: [
    DefinePlugin {
      definitions: {
        __DEV__: 'true',
        'process.env': { NODE_ENV: '"development"', PUBLIC_URL: '""' }
      }
    },
    NoEmitOnErrorsPlugin {},
    HotModuleReplacementPlugin { options: {} },
    HtmlWebpackPlugin {
      userOptions: { title: 'React Cosmos', filename: '_renderer.html' },
      version: 5
    }
  ]
}

```

> Not sure where this time discrepancy comes from. I believe you're comparing npm run cosmos with npm run build. Not sure what ts-webpack-builder does, but in any case it doesn't seem to be analogous to how Cosmos uses webpack because one is saving the file on disk and the other is starting a dev server in watch mode.

`@messman/ts-webpack-builder` is a package I created to abstract away the webpack build of a library project. It includes webpack 5, `ts-loader`, `babel-loader`, etc as dependencies and comes with a default webpack configuration that I override in `@messman/react-common` so as to not get bogged down in copying webpack configs everywhere. I use `ts-webpack-builder` to get the webpack configuration that appears above. It includes all the same loaders from `npm run build`.

So in this way, Cosmos and `ts-webpack-builder` should be very similar in that both need to do at least the same work through the non-fixture files (regular source code) in `src`. This is why it makes sense to me that `npm run cosmos` takes _at least_ 8 seconds, since it certainly can't be faster than `npm run build`. 

Thanks again for the response. You technically answered my question, so I will close this issue. The startup time for React Cosmos in this specific case seems unexpected to us both, which might merit a new issue if I can learn more about why it's happening. I'll have to keep digging to figure out what is going on... maybe lazy fixtures will be the fix. I'll be on the lookout.

**Comment by skidding** [comment]
> but it seems as if webpack is actually building parts of React Cosmos itself. It's likely I'm misinterpreting what I saw, because that doesn't seem right.

Indeed, that doesn't sound right. Cosmos is precompiled specifically so that users don't need to worry about compiling library modules. But by looking at the webpack config it seems you're already excluding `node_modules`.

The only thing that stands out at the moment is that you use both `babel-loader` and `ts-loader` to compile your source. While this may be just fine, it's more common to rely on one or the other. Unless you've already been down this road, I suggest replacing `ts-loader` with the `@babel/preset-typescript` plugin and see if it speeds up compilation.

> maybe lazy fixtures will be the fix

They would help for sure, but it would sweep the issue under the rug so to speak. At this size you shouldn't need lazy fixtures to get good performance.

An interesting thing you could try, to make sure your `build` command imports the same amount of modules as Cosmos, is to run `cosmos --external-userdeps`. This will generate a file called `cosmos.userdeps.js` in your project. You can import this file in your index source module and see if the build command is still faster or gets closer to the webpack build time in Cosmos.

Another thing that you could try is https://github.com/stephencookdev/speed-measure-webpack-plugin. I would be satisfying to get to the bottom of this :).

**Comment by messman** [comment]
🎉  Problem solved. 

Your previous message was helpful in getting me to think more about TypeScript as the potential cause.

> The only thing that stands out at the moment is that you use both `babel-loader` and `ts-loader` to compile your source. While this may be just fine, it's more common to rely on one or the other. Unless you've already been down this road, I suggest replacing `ts-loader` with the `@babel/preset-typescript` plugin and see if it speeds up compilation.

I was vaguely aware of `@babel/preset-typescript`, and my understanding was that while it is capable of transpiling TypeScript to JavaScript it cannot perform the type-checking that the TypeScript compiler can. Upon researching, this has been confirmed by [TypeScript documentation on the use of babel](https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html), the [@babel/preset-typescript documentation](https://babeljs.io/docs/en/babel-preset-typescript) (via the [inner plugin documentation](https://babeljs.io/docs/en/babel-plugin-transform-typescript)) and [this blog post](https://evanlouie.github.io/posts/typescript-babel-preset-typescript-ts-loader). I prefer to always have type-checking even in React Cosmos/Storybook, and `ts-loader` also generates the type definitions that I export with the library.

I did start to dive more deeply into `ts-loader` as a cause for this issue. Here are a few things I tried:

1. I removed `babel-loader` to see what effect it had. There was no significant difference.
2. I added [Speed Measure Webpack Plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin) as you suggested. I had forgot it existed. It wasn't all that clear because of the ambiguity of "modules with no loaders":

An example of `npm run cosmos`
```
 SMP  ⏱  
General output time took 38.71 secs

 SMP  ⏱  Loaders
modules with no loaders took 38.12 secs
  module count = 284
babel-loader, and 
ts-loader took 37.18 secs
  module count = 42
react-cosmos took 0.104 secs
  module count = 1
html-webpack-plugin took 0.04 secs
  module count = 1
```

An example of `npm run build`
```
 SMP  ⏱  
General output time took 8.67 secs

 SMP  ⏱  Plugins
CleanWebpackPlugin took 0.067 secs

 SMP  ⏱  Loaders
babel-loader, and 
ts-loader took 8.24 secs
  module count = 24
modules with no loaders took 0 secs
  module count = 2
```

It did point to `babel-loader` and `ts-loader`, though. 

3. I tested to see how build time would change when using the `transpileOnly` option of `ts-loader`, which works just like `@babel/preset-typescript` - no type checking. Startup time was reduced to 5 seconds. This meant that `ts-loader`/`tsc` was getting caught up somewhere - either compiling files it should be, or type-checking files it shouldn't be.
4. I messed around with options for both the `tsc` compiler and `ts-loader`. I realized that I could change some TypeScript settings for React Cosmos with no adverse effects. After trying different combinations, I was able to get the startup time for React Cosmos down to **< 8 seconds** while still keeping type-checking.

So, turns out it was a webpack/`ts-loader`/TypeScript issue and not related to React Cosmos at all. Great news to me, and I'm sure it is good news to you as well. The below section summarizes what settings I recommend for anyone using `ts-loader` with React Cosmos in the future.

___

Summary of the problem and fix:

Problem: I have a project that uses webpack (5), `ts-loader`, and `babel-loader` to bundle a React component library with type definitions. My webpack build came in at around 8 seconds. The React Cosmos build, using the same loaders, came in at around 40 seconds.

Fix: I needed to change some of the `tsc` compiler options and `ts-loader` options that are not needed when using React Cosmos.

Here is the `tsconfig.json` I use for the build of the library to compile, type-check, and generate declaration files:

```json
{
    "compilerOptions": {
        "module": "esnext",
        "moduleResolution": "node",
        "lib": [
            "DOM",
            "ES2019"
        ],
        "target": "ES2017",
        "sourceMap": true,
        "declaration": true,
        "declarationMap": true,
        "incremental": true,
        "allowJs": false,
        "checkJs": false,
        "alwaysStrict": true,
        "strict": true,
        "noImplicitReturns": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noFallthroughCasesInSwitch": true,
        "noEmitOnError": true,
        "preserveConstEnums": true,
        "jsx": "react",
        "outDir": "./dist",
        "baseUrl": ".",
        "paths": {
            "@/*": [
                "src/*"
            ]
        },
    },
    "compileOnSave": false,
    "exclude": [
        "node_modules"
    ],
    "include": [
        "src/**/*"
    ]
}
```

In order to override some of those settings just for React Cosmos, I needed to specify them differently in the webpack config. See the webpack config below, particularly the `ts-loader` options:

```js
{
    mode: 'development',
    target: 'web',
    
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.json'],
        alias: {
            '@': path.resolve(__dirname, './src')
        }
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            // You can avoid a .babelrc and a .browserlistrc by just specifying it all here.
                            presets: [['@babel/preset-env', { debug: false, targets: '> 2%, not ie <= 11' }], '@babel/preset-react'],
                        }
                    },
                    {
                        loader: 'ts-loader',
                        options: {
                            onlyCompileBundledFiles: false, // Keep the default of false, or build time will double.
                            transpileOnly: false, // Keep the default of false, or you won't get type-checking.
                            compilerOptions: {
                                sourceMap: false, // Personally, I have no need for sourcemaps with React Cosmos.
                                declaration: false, // No need for declarations.
                                declarationMap: false, // No need for declaration maps.
                                skipLibCheck: true, // No need to type-check .d.ts files from dependencies.
                                incremental: false // No need for incremental compilation (it doesn't work in webpack anyway).
                            }
                        }
                    }
                ]
            }
        ]
    }
}
```

The most important changes I needed to make were:
- Ensure the `ts-loader` option `onlyCompileBundledFiles` is kept at the default of `false`. The [documentation](https://github.com/TypeStrong/ts-loader#onlycompilebundledfiles) for that property had led me to believe it would be more strict about what files were compiled. In fact, it did the opposite. Changing this setting from `true` to `false` cut the startup time of React Cosmos in half. Perhaps I had used it to speed up Storybook long ago. 🤷‍♂️ 
- Ensure the `tsc` compiler option `declaration` is `false`. You don't need to output `.d.ts` files while using React Cosmos. This change cut the startup time in half again.

Now, my library's build and the React Cosmos startup take about the same time. That's exactly what I was looking for. It's about 2x better than I was getting with Storybook at best.
___

@skidding, thanks again for your assistance in debugging the issue. Feel free to rename this issue if you feel it would help others.

**Comment by skidding** [comment]
@messman Awesome! I'm glad to see you figured it out.

>  was vaguely aware of @babel/preset-typescript, and my understanding was that while it is capable of transpiling TypeScript to JavaScript it cannot perform the type-checking that the TypeScript compiler can.

Fair enough. My go to is to do basic type stripping in the build process and have a separate `check-types` command, which I usually keep in watch mode in a separate terminal. This allows me to keep going and get instant feedback even if I have a type error that I am aware of but want to iterate quickly before I tidy everything up. I still type errors in a separate terminal and of course I can't merge/deploy if the check-types command fails. But this is my approach and I'm aware that some people think it's wrong to allow building something with type errors. In principle I agree, but in practice I found the approach I use now to be the most comfortable / productive. I guess now I have another argument for my approach – it's faster 😄.

Thanks again for your detailed reporting. I'll think of a more "seo" friendly name for this issue and rename it.

**Comment by naomei** [comment]
Hi, @skidding 

I am facing the same problem now.

## What's happening

1. run react-cosmos
2. Webpack build time is fast (it doesn't matter)
3. The waiting time of the "Waiting for renderer ..." screen after building is quite long.

The initial display on the screen is quite slow even though the build is finished.
( wait a few minutes...)

## solution?

The story of ts-loader and babel-loder is mentioned above,
Is this related in the same way?

## webpack.config

Just in case, I will attach the config file.

```js
module.exports = (env) => {
  /** @type import('webpack').Configuration */
  const config = {
    mode: isDev ? "development" : "production",
    entry: {
      main: "./src/index.tsx",
    },
    output: {
      publicPath: "/",
      filename: "[name].[fullhash].js",
      clean: true,
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: [
            {
              loader: "babel-loader",
            },
            {
              loader: "ts-loader",
              options: { transpileOnly: true },
            },
          ],
        },
        {
          test: /\.less$/,
          use: [
            {
              loader: "style-loader",
            },
            {
              loader: "css-loader",
            },
            {
              loader: "less-loader",
              options: {
                lessOptions: {
                  modifyVars: { ...STYLE_VARS },
                  javascriptEnabled: true,
                },
              },
            },
          ],
        },
        {
          test: /\.(png|jpg|gif)$/i,
          use: [
            {
              loader: "url-loader",
              options: {
                limit: false,
                name: "assets/[name].[contenthash].[ext]",
              },
            },
          ],
        },
        {
          test: /\.svg$/,
          loader: "svg-inline-loader",
        },
      ],
    },
    devtool: isDev && "inline-source-map",
    devServer: {
      open: false,
      overlay: false,
      port: 1234,
      host: "0.0.0.0",
      contentBase: "public",
      hot: true,
      historyApiFallback: true,
      proxy: {},
    },
    plugins: [
      isDev && new ReactRefreshPlugin(),
      new ForkTsCheckerWebpackPlugin(),
      new HtmlWebpackPlugin({
        filename: "./index.html",
        template: "./public/index.html",
      }),
    ].filter(Boolean),
    resolve: {
      extensions: [".js", ".ts", ".tsx", ".test.tsx", ".less"],
      plugins: [
        new TsconfigPathsPlugin({
          configFile: "tsconfig.json",
        }),
      ],
    },
  };

  return config;
};
```

**Comment by calebpanza** [comment]
Hey all! I'm having some similar issues as described above. Does anyone have a project that I could check out to see how cosmos is set up with a **React Native app**?? I've referenced the [create-react-native-app-example](https://github.com/react-cosmos/create-react-native-app-example) repo but it's not working locally...
