### ISSUE TITLE
No longer possible to alias Preact?

### ISSUE THREAD

**Issue by birtles** [react-cosmos/react-cosmos#1316]
### What's wrong?

I'm not entirely sure, but it seems like it's no longer possible to substitute Preact for React.

### Steps to reproduce

1. Add `preact` to your project
2. Alias react to `preact` according to the [documentation](https://preactjs.com/guide/v10/getting-started/#aliasing-react-to-preact):

```json
const config = { 
  "resolve": { 
    "alias": { 
      "react": "preact/compat",
      "react-dom/test-utils": "preact/test-utils",
      "react-dom": "preact/compat",
    },
  }
}
```
3. Try running cosmos

### Screenshots

![image](https://user-images.githubusercontent.com/1232595/111751167-7eb3f080-88d7-11eb-81f0-485007d3f57d.png)

### User info

- Server terminal output (see above screenshot)
- Cosmos version: 5.6.0
- Cosmos config: n/a
- If applicable: webpack version 5.26.0

### Additional context

[This comment](https://github.com/react-cosmos/react-cosmos/issues/530#issuecomment-346583016) suggests this used to work (albeit with the Preact v8 aliases).

However, as best I can tell, bce0765b280d85150abcf5a87fcdf9ef7be1f6c5 introduced a check for local react dependencies that ignores `alias` settings in the user's webpack config when looking for react.

**Comment by skidding** [comment]
Hi @birtles,

You're probably be right. I believe the PR you referenced solved an issue where you called Cosmos from a different directory and you wanted it to resolve the React copy relative to the Cosmos config. Useful when you work Cosmos locally and you want to test it in a specific repo.

In any case, a solution would be update `resolveLocalReactDeps` and check if a `react` alias is already set in the user config, in which case we could log something like `[Cosmos] React alias found in webpack config` and return. Would you like to test this idea and submit a patch if it works?

**Comment by birtles** [comment]
Thank you! Yes, that solution seems good to me too. Let me see if I can make up a PR for it.

**Comment by birtles** [comment]
I've made up a PR at #1317 and I've verified that at least my local cosmos setup gets past the stage where it resolves React dependencies.

Unfortunately I'm now getting errors including CSS files in my fixtures and I'm not sure if it's a result of my changes or some other changes in Cosmos over the last few weeks that broke this without me noticing.

Specifically I now get:

```log
ERROR in ./public/src/components/AsyncButton.fixture.js 4:0-22
Module not found: Error: Can't resolve '../index.css' in '/home/birtles/project/public/src/components'
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 8:0-88 42:50-58
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js 23:17-38 37:2-42:4

ERROR in ./public/src/components/ExpandingErrorLine.fixture.js 4:0-22
Module not found: Error: Can't resolve '../index.css' in '/home/birtles/project/public/src/components'
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/userDeps.js 9:0-95 43:57-65
 @ ./node_modules/react-cosmos/dist/plugins/webpack/client/index.js 23:17-38 37:2-42:4
...
```

The source in question is:

```ts
import '../index.css';
```

which used to work, but no longer seems to.

**Comment by skidding** [comment]
@birtles Thanks a lot for your PR!

Your code was already in great shape, but I cleaned in up a bit in #1318. Moved the tests in a separate file, added a new test case and some minor style adjustments.

Already released this patch, so please try out `react-cosmos@5.6.1` and let me know if it works as expected.

**Comment by birtles** [comment]
> Your code was already in great shape, but I cleaned it up a bit in #1318. Moved the tests to a separate file, added a new test case and some minor style adjustments.

Looks a lot better. Thanks!

> Already released this patch, so please try out `react-cosmos@5.6.1` and let me know if it works as expected.

Works great! Thanks again.
