### ISSUE TITLE
How to ignore lint errors to enable transpiling cosmos 

### ISSUE THREAD

**Issue by EdmundsEcho** [react-cosmos/react-cosmos#1319]
### What's wrong?

Lint-related errors are preventing cosmos from transpiling.

### Context
This is a create-react-app.  The app itself compiles (i.e., `yarn install; yarn start` work).
 
### Question - Not a bug :))
May you remind me how to configure the transpiling process so as to ignore these non-critical errors?

**Comment by EdmundsEcho** [comment]
The answer: set the `.env` `ESLINT_NO_DEV_ERROR` to true.  I suspect that cosmos was accessing files that were not in the main app, thus failed to compile where the the "app itself" did.

Thank you for this great dev-tool!

**Comment by skidding** [comment]
@EdmundsEcho Haven't seen this one before, but glad you figured it out. Were the errors coming from `src` files, or somewhere else? (Not important to spend more time on this, just trying to see if we can avoid this inconvenience for other people in the future)

**Comment by EdmundsEcho** [comment]
This has been an issue since CRA v4.0  The coordination with webpack somewhat fell apart.  I ran into the issue a little while ago for the app.  I thought I fixed it... it compiled and I had made additional progress etc.  The issue came up again when as described. In CRA v4.0.3 they fixed the issue.  However, the settings need to be as described.
