### ISSUE TITLE
How to add react-cosmos to modern-monorepo-boilerplate

### ISSUE THREAD

**Issue by kfern** [react-cosmos/react-cosmos#1325]
### What's wrong?

I have installed react-cosmos in a [modern-monorepo-boilerplate](https://github.com/michaljach/modern-monorepo-boilerplate) root folder using yarn add react-cosmos -W -D

Works fine with jsx files:

yarn cosmos
yarn run v1.22.5
$ cosmos
[Cosmos] Using default cosmos config
[Cosmos] See you at http://localhost:5000
[Cosmos] Using default webpack config
[Cosmos] Building webpack...
webpack built 4e47cc95b9b0514c8794 in 1249ms
   285 modules

If I add a fixture.jsx file I get an error in cosmos:

Module parse failed: Unexpected token (5:2) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

What can I do or debug? Any advice?

### User info
react-cosmos: 5.6.2
[Cosmos] Using default cosmos config
[Cosmos] Using default webpack config

**Comment by skidding** [comment]
Hi @kfern,

modern-monorepo-boilerplate seems to use CRA under the hood. So I tried following the CRA setup for Cosmos and it almost worked. But CRA's webpack config uses some relative paths in a way that isn't compatible when part of a monorepo.

Luckily you can configure Babel manually to get going with Cosmos.

Install the following:

```
yarn add -W -D @babel/preset-typescript babel-loader
```

And add this `babel.config.js` in your repo root:

```js
module.exports = {
  presets: ['@babel/preset-env', '@babel/preset-react', '@babel/preset-typescript'],
};
```

`yarn cosmos` should load your fixtures OK after you do this. Let me know if you can confirm.

**Comment by kfern** [comment]
Hi @ovidiubute 

Thanks for your support, as usual :-)

I must force babel-loader version for CRA compatibility:

yarn start
@namespace/react-app: $ react-app-rewired start
@namespace/react-app: There might be a problem with the project dependency tree.
@namespace/react-app: It is likely not a bug in Create React App, but something you need to fix locally.
@namespace/react-app: The react-scripts package provided by Create React App requires a dependency:
@namespace/react-app:   "babel-loader": "8.0.6"
@namespace/react-app: Don't try to install it manually: your package manager does it automatically.
@namespace/react-app: However, a different version of babel-loader was detected higher up in the tree:
@namespace/react-app:   /modern-monorepo-boilerplate/node_modules/babel-loader (version: 8.2.2) 
@namespace/react-app: Manually installing incompatible versions is known to cause hard-to-debug issues.


yarn add -W -D @babel/preset-typescript babel-loader@8.0.6 fix this problem


Now I can run yarn start and yarn cosmos with fixtures :-)


The only errors are multiple from chokidar. I don't know how to exclude node_modules from watch

```

: Error: ENOSPC: System limit for number of file watchers reached, watch '/modern-monorepo-boilerplate/node_modules/babel-preset-react-app/node_modules/@babel/preset-react/node_modules/@babel/plugin-transform-react-display-name/node_modules/@babel/core/node_modules/.bin'
Error from chokidar (/modern-monorepo-boilerplate/node_modules/.bin): Error: ENOSPC: System limit for number of file watchers reached, watch '/modern-monorepo-boilerplate/node_modules/.bin'

```
Any idea?

**Comment by kfern** [comment]
I have solved it by creating a cosmos.config.json file:

# cosmos.config.json
{"watchDirs": ["./packages"]}

**Comment by skidding** [comment]
> I have solved it by creating a cosmos.config.json file:
> 
> cosmos.config.json:
> {"watchDirs": ["./packages"]}

Nice! Thanks for reporting your findings.

Might to useful to add a troubleshoot item for "System limit for number of file watchers reached", suggesting to set `watchDirs` to `src` or `packages` in case of a monorepo.

**Comment by kfern** [comment]
Can I have all config in one file?

**Comment by skidding** [comment]
> Can I have all config in one file?

What do you mean?

**Comment by kfern** [comment]
Sorry. Can I add the babel.config.presets to cosmos.config.json?

**Comment by skidding** [comment]
> Sorry. Can I add the babel.config.presets to cosmos.config.json?

I'm afraid not.

**Comment by kfern** [comment]
## Conclusion: How to add react-cosmos to modern-monorepo-boilerplate

[modern-monorepo-boilerplate](https://github.com/michaljach/modern-monorepo-boilerplate) is a lerna monorepo with 2 packages:

- react-app: react-app-rewired CRA
- components: used by react-app package

Steps:

Install react-cosmos

Add babel dependencies:

yarn add -W -D @babel/preset-typescript babel-loader

Add this babel.config.js in your repo root:

module.exports = {
  presets: ['@babel/preset-env', '@babel/preset-react', '@babel/preset-typescript'],
};

And  cosmos.config.json:

{"watchDirs": ["./packages"]}

All settings done!

run yarn start o similar

If you get a dependency error like:

@namespace/react-app: The react-scripts package provided by Create React App requires a dependency:
@namespace/react-app: "babel-loader": "8.0.6"

you can fix it by running in the repo root:

yarn add -W -D babel-loader@8.0.6

Now you can use react-cosmos fixtures :-)
yarn cosmos

@skidding Thanks
