### ISSUE TITLE
How to setup for Create-react-app with Tailwindcss?

### ISSUE THREAD

**Issue by zning** [react-cosmos/react-cosmos#1326]
Trying to install this with create-react-app with Tailwindcss. I followed the instructions on Tailwindcss's webpage. 

https://tailwindcss.com/docs/guides/create-react-app

But I have no idea how to make it work with Cosmos. Any working solutions will be a great help for anyone who's trying this. 

Thanks

**Comment by skidding** [comment]
@zning What exactly isn't working for you with Tailwind and Cosmos?

Did you follow the [CRA docs section](https://github.com/react-cosmos/react-cosmos/blob/b0fffb368d853378a95dfaffff2ee775cfcf99dd/docs/README.md#create-react-app) to make sure Cosmos is relying on CRA's internal webpack config?

**Comment by zning** [comment]
> @zning What exactly isn't working for you with Tailwind and Cosmos?
> 
> Did you follow the [CRA docs section](https://github.com/react-cosmos/react-cosmos/blob/b0fffb368d853378a95dfaffff2ee775cfcf99dd/docs/README.md#create-react-app) to make sure Cosmos is relying on CRA's internal webpack config?

Sorry, my bad, I should be more specific.
Yes, I did follow that.
First I got an "Already listening Error", which I fixed it follow your suggestion. 
Then the className of the Tailwindcss applied to the component just won't take effect. I tried to add style CSS manually and it works. So the real issue is not sure why the Tailwindcss won't affect the component.

I tried to fix this by:
Add globalImports to cosmos.config.jason like this: {"globalImports": ["tailwindcss/tailwind.css"],...} or {"globalImports": ["src/index.css"],...} both not working. So I guess it won't find the css from moduler or the gloabal css in the project.

I tried to import the 3.5M whole tailwindcss into the component directly and it works. But this hardly the ideal solution because I have to import the whole CSS file into every component and cannot use its 'JIT' feature or can't purge the final css file. 

I guess you have a more profound experience working with this kind of issue and I do believe your library really shines when combining with a utility CSS library like Tainlwindcss. So if you follow the guideline here, 

https://tailwindcss.com/docs/guides/create-react-app

you might have a more clear idea to see what's really going on here.

**Comment by skidding** [comment]
> So if you follow the guideline here [...], you might have a more clear idea to see what's really going on here.

I'm afraid the CRACO part exceeds my knowledge as well. It seems like it extends CRA's config, so even if you set up Cosmos to use CRA's webpack config, your webpack config is probably further extended by CRACO. Maybe there's a way to access the final config generated by CRACO and pass that to Cosmos, but unfortunately I don't have the time to search for this myself. Note that Cosmos also supports a webpack override file for complete control over the webpack config.

> I tried to import the 3.5M whole tailwindcss into the component directly and it works

Can you share an example of how you imported the whole tailwindcss into the component? If it's just an import then putting that import into `globalImports` should work the same.

**Comment by zning** [comment]
> > So if you follow the guideline here [...], you might have a more clear idea to see what's really going on here.
> 
> I'm afraid the CRACO part exceeds my knowledge as well. It seems like it extends CRA's config, so even if you set up Cosmos to use CRA's webpack config, your webpack config is probably further extended by CRACO. Maybe there's a way to access the final config generated by CRACO and pass that to Cosmos, but unfortunately I don't have the time to search for this myself. Note that Cosmos also supports a webpack override file for complete control over the webpack config.
> 
> > I tried to import the 3.5M whole tailwindcss into the component directly and it works
> 
> Can you share an example of how you imported the whole tailwindcss into the component? If it's just an import then putting that import into `globalImports` should work the same.

I've figured this out. Turn's out that just like "react-app-rewired', craco also offers a way to output the final webpack config file.

/* webpack.config.js */

const { createWebpackDevConfig } = require("@craco/craco");
const cracoConfig = require("./craco.config.js");
const webpackConfig = createWebpackDevConfig(cracoConfig);

module.exports = webpackConfig;

And finally, need to global import the index.css in the cosmos config file.

/*cosmos.config.json*/
{
  "globalImports": ["src/index.css"],
  "staticPath": "public"
}

And now everything just works!


Great library and I'll keep you updated if there's something wrong. 
Also please feel free to update the doc for any craco user maybe.

Thanks for your help. I'll just start to explore cosmo and dump storybook since they gave me so much trouble.

**Comment by skidding** [comment]
@zning Awesome, thanks for lettings us know!

You're also welcome to update the docs if you feel like making a repo contribution.

**Comment by zning** [comment]
> @zning Awesome, thanks for lettings us know!
> 
> You're also welcome to update the docs if you feel like making a repo contribution.

Sounds good, I'll lean how to do that and give a try, thanks

**Comment by zning** [comment]
> @zning Awesome, thanks for lettings us know!
> 
> You're also welcome to update the docs if you feel like making a repo contribution.

I made a pull request for the doc update. This is my first pull and I hope I did it right, otherwise please let me know. 
#1328
