### ISSUE TITLE
Critical security vulnerability: xmlhttprequest-ssl

### ISSUE THREAD

**Issue by sarahhayle** [react-cosmos/react-cosmos#1329]
### What's wrong?

On installing react-cosmos npm finds a critical vulnerability with xmlhttprequest-ssl. This dependency needs to be updated to >=1.6.1.

### Steps to reproduce

1.  Run `npm install react-cosmos` in the terminal in your project
2.  Run `npm audit`
3. See:

<img width="568" alt="Screenshot 2021-05-25 at 16 13 36" src="https://user-images.githubusercontent.com/36202134/119529238-d3f9fb80-bd79-11eb-8c78-4b5bd97b6824.png">

### User info

- Cosmos version: 5.6.2

**Comment by skidding** [comment]
@sarahhayle Thanks for reporting this.

`xmlhttprequest-ssl` is an indirect dependency of Cosmos. `socket.io-client` depends on it, but we can't just update it because newer versions of Socket.IO dropped support for IE11, which is still useful to preserve for some Cosmos users. To fix this vulnerability warning you probably need to create a fork of `socket.io-client` and/or `engine.io-client`, go back to the commit that corresponds to the version Cosmos is using, upgrade `xmlhttprequest-ssl` to the safe version and publish an npm package for the fork.

Let me know if you're interested in doing this and I'm happy to accept a PR that replaces Cosmos' Socket.IO dependency to this fork. But also keep in mind that Cosmos is a local dev tool so these security warnings don't affect production users.

**Comment by marienjus** [comment]
### *How do I fix* This?
```bash
ERROR in ./src/button.fixture.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/qodestackr/Desktop/SectionArticles/react-cosmos/src/button.fixture.js: Support for the experimental syntax 'jsx' isn't currently enabled (5:10):

  3 |
  4 | export default function Hello() {
> 5 |   return <h1>Hello, World</h1>
    |          ^
  6 | }

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
```

**Comment by skidding** [comment]
@marienjus Please read [this](https://github.com/react-cosmos/react-cosmos/blob/main/docs/README.md#compilation). Also, your question has no relation to this thread.

**Comment by rkuykendall** [comment]
@skidding Thoughts on bumping socket.io to a [version between 2.2.0 and 2.5.0](https://github.com/socketio/socket.io/compare/2.2.0...2.5.0)?

I have read through all the socket.io release notes and commits listed above and I can't find where they explicitly drop IE11 support, but assuming it was in version 3, version 2.5.0 should be fine?

**Comment by skidding** [comment]
@rkuykendall socket.io 2.3 dropped IE compatibility indirectly, as [noted here](https://github.com/react-cosmos/react-cosmos/blob/435c0b2be70fa756237d3bccdf8c0b205bf501bc/DEBT.md?plain=1#L16).

I've been working on and off on React Cosmos v6 which gives up IE11 and old Node versions. Can't give a release estimate as I'm busy with other stuff but after a few months off I resumed working on v6 this month and making some good progress already. Will probably take months to finalize but I'll try to release an alpha as soon as I can.

**Comment by rkuykendall** [comment]
@skidding Thank you for your response, I really appreciate it. That makes perfect sense.

For those who don't care about IE11 but want to close these vulnerabilities (even though, as said above, they are often local), I was able to override the resolutions of Socket.io in my package.json:

```
  "resolutions": {
    "socket.io": "2.5.0",
    "socket.io-client": "2.5.0"
  },
```

**Comment by Akiyamka** [comment]
@skidding can we help somehow?

**Comment by skidding** [comment]
@Akiyamka Thanks and sorry for the wait. Please see [this comment](https://github.com/react-cosmos/react-cosmos/pull/1394#issuecomment-13538878970). Major version 6 is in the works, which solves this as well. Actually, [Socket.IO was removed altogether in favor of native WebSocket](https://github.com/react-cosmos/react-cosmos/pull/1404/files). It's going to take a bit more time to finish up with the revamp but the new year will bring a fresh React Cosmos better than ever.

**Comment by skidding** [comment]
React Cosmos v6 alpha is here: https://github.com/react-cosmos/react-cosmos/blob/main/docs/MIGRATION_V6.md

As I was saying Socket.IO was removed altogether.
