### ISSUE TITLE
How to load only .js files as fixtures?

### ISSUE THREAD

**Issue by fredy31** [react-cosmos/react-cosmos#1331]
The way we build components in my company is components/[name]/[name].js and a [name.scss] next to it for the styles.

Thing is, in the sass there is some @imports that crash the cosmos.

<img width="958" alt="Screen Shot 2021-06-16 at 1 15 24 PM" src="https://user-images.githubusercontent.com/2183470/122263875-ea8d0180-cea4-11eb-9a33-30c778d96429.png">

Now, I do not need the scss for components. IDK why Cosmos just decides to load them just like if it was a component.

So is there a way to tell Cosmos, when it looks for fixtures, to just look for files ending in .js and to ignore the .scss files that crash the system.

**Comment by fredy31** [comment]
Or I guess the problem is that with Node-Sass you import the sass file and it just works (it compiles it as CSS on the build)

<img width="382" alt="Screen Shot 2021-06-16 at 1 50 04 PM" src="https://user-images.githubusercontent.com/2183470/122268189-c1bb3b00-cea9-11eb-948c-cc576356904c.png">

But I guess that Cosmos sees that and so tries to include SCSS as is and crashes. I don't know how hard it would be to support node-sass and this setup?

**Comment by skidding** [comment]
@fredy31 You need to tell Cosmos to use the same webpack configuration as your existing build to compile exotic modules like SASS modules. This depends on your setup (eg. if you use a framework or not). Please read the [Compilation](https://github.com/react-cosmos/react-cosmos/tree/main/docs#compilation) section and let us know if you can't figure it out. There's also a docs section on Create React App and Next in case you use one of them.

**Comment by fredy31** [comment]
Really I'm having a hard time making it work.

I do not have a babel or webpack config file, the packages handle it themselves when loaded.

But I have SCSS and SVGs that cause problem.

And what I shown you was with a babelrc with only 
```{
  "presets": ["@babel/env", "@babel/react"]
}```

In it. If I don't have it the code crashes on the `SyntaxError: Support for the experimental syntax 'jsx' isn't currently enabled (6:9):`

**Comment by fredy31** [comment]
Yeah I had to build a full webpack config since my project didnt have one. 

`````
const path = require('path');

module.exports = {
    mode: 'development',
    module: {
        rules:[
            {
                test: /\.m?js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ["@babel/env", "@babel/react"]
                    }
                }
            },
            { 
                test: /\.scss?$/, 
                use: [
                    // Creates `style` nodes from JS strings
                    "style-loader",
                    // Translates CSS into CommonJS
                    "css-loader",
                    // Compiles Sass to CSS
                    "sass-loader",
                ] 
            },
            { test: /\.(woff|ttf|otf|eot|woff2|svg|png|jpg)$/i, loader: "file-loader" }
        ]
    }
}
`````

**Comment by skidding** [comment]
You need to configure Cosmos with the webpack config used in the target app, so this makes sense. Otherwise the webpack build created by Cosmos can't know how to compile your modules, and it's not feasible for us to embed all possible webpack loaders inside Cosmos, not to mention each version of each loader.

If you're not happy with the config you added you could simplify it a bit by using the [webpack config override](https://github.com/react-cosmos/react-cosmos/blob/main/docs/README.md#webpack-config-override). You can extend the default webpack config created with Cosmos with just the `sass-loader` rule.

Please close this issue once you're satisfied with the solution.
