### ISSUE TITLE
Great live demo 

### ISSUE THREAD

**Issue by KhanhPham2411** [react-cosmos/react-cosmos#1344]
It's great to see live demo to have quick insight of how cosmos works before take our hand dirty digging into the framework.
But not sure if it's the full capability of framework? As I can see it's the same as storybook but lacking how can we reuse the component as no code is showed.

One more question related expo react native, is it supported for now as I currently cannot found any sample or blog related them?

**Comment by skidding** [comment]
Hi @KhanhPham2411,

- Always looking for ways to improve the live demo. If you have ideas let me know.
- You can read more about what Cosmos does and how it compares with other tools [here](https://github.com/react-cosmos/react-cosmos/tree/54669d1fab078c5469745a05b95b4c865a15ba2d#-why-react-cosmos).
- React Native is supported. See [this docs section](https://github.com/react-cosmos/react-cosmos/tree/main/docs#react-native).
- There is a Create React Native App (Expo) example repo but unfortunately it's outdated: https://github.com/react-cosmos/create-react-native-app-example. If anyone wants to update it / re-create an Expo example repo from scratch I'm more than happy to link it.

Thanks.
