### ISSUE TITLE
How to to use this with rollup? 

### ISSUE THREAD

**Issue by sidwebworks** [react-cosmos/react-cosmos#1347]
Hi, I wanted to use react-cosmos in my custom component library, I have a custom setup using Rollup, Esbuild and Typescript.

**Comment by tsanyqudsi** [comment]
you can see my vite example on https://github.com/viveljs/viveljs/tree/main/workspace/cosmos. Vite use rollup.

**Comment by supervanya** [comment]
@tsanyqudsi I see you switched to using StoryBook instead of cosmos, any reason why? I am considering wether to get cosmos to work with vite and rollup or to switch to StoryBook?

**Comment by tsanyqudsi** [comment]
@supervanya to be honest I like Cosmos more, But Storybook has https://github.com/storybookjs/builder-vite.

I will rethink my decision when Cosmos reach v 6.

**Comment by skidding** [comment]
React Cosmos v6 is here and it comes with a brand new Vite plugin. Check out the [migration guide](https://github.com/react-cosmos/react-cosmos/blob/main/docs/MIGRATION_V6.md) to try it out!
