### ISSUE TITLE
ignore a directory/filepath

### ISSUE THREAD

**Issue by crobinson42** [react-cosmos/react-cosmos#1348]
It would be spectacular if there was a config option to ignore fixture files, ie:
`"ignore": ["**/path/**"]`

**Comment by crobinson42** [comment]
My use case/issue is when the `dist/` dir is built for a typescript project, cosmos will pick-up and duplicate components from the `src/` & `dist/` dir :-(

**Comment by crobinson42** [comment]
![image](https://user-images.githubusercontent.com/5973579/133908989-a136020d-faf8-4b09-ad2c-c614f3524892.png)

**Comment by crobinson42** [comment]
Currently, my work-around is:

package.json
```json
 " scripts": {
  "cosmos": "rm -rf dist && cosmos",
  ...
 },
```

cosmos.config.js
```
{
 "watchDirs": ["src/"]
}
```

The problem with this solution is that when developing a package locally (running `npm link`) this breaks the workflow and requires the developer to run `npm run build` to get the `dist/` dir back :-(

**Comment by skidding** [comment]
The solution here should be `rootDir: "src"`. Is this not working for you? Can you post your cosmos config please if not.

`watchDirs` only restricts which folders are watched for changes, it doesn't affect the fixture files detected on Cosmos start.

**Comment by crobinson42** [comment]
When setting `rooDir: "src"` it interferes with typescript.config.json paths (alias imports, ie: `import MyComponent from '@root/components/MyComponent'`).

**Comment by skidding** [comment]
> When setting `rooDir: "src"` it interferes with typescript.config.json paths (alias imports, ie: `import MyComponent from '@root/components/MyComponent'`).

@crobinson42 I remember you shared this issue on Slack, but I don't understand why `rootDir` would influence your TS config. Could you extract a minimal reproducing repo from your project? I'd be interested to take a closer look.

In any case, does adding this config in `src/tsconfig.json` help?

```json
{
  "extends": "../tsconfig.json"
}
```

**Comment by philipnilsson** [comment]
FWIW I'm not using `rootDir` because it's led to a bunch of problems for me when also using `staticPath` (_renderer.html gets a 404, hot reloading problems etc). I'd be quite happy if you could just supply a ignore/include  options

**Comment by skidding** [comment]
@philipnilsson Could you provide a minimum reproducing example with one or more of the bunch of problems with rootDir + staticPath? I'd be curious to find a solution if that's the case.

Unfortunately more granular include/ignore options are still not available at the moment, aside from leveraging `fixturesDir` and `fixtureFileSuffix`.

https://github.com/react-cosmos/react-cosmos/blob/d3f8e4969bcec076483a8d9ea4a952c7ed95c520/packages/react-cosmos/src/userDeps/shared.ts#L11-L17

**Comment by skidding** [comment]
Great news! The `ignore` config option exactly as outlined by @crobinson42 at the start of this issue is now available.

Just published under `react-cosmos@next`. Make sure to check out the [migration guide](https://github.com/react-cosmos/react-cosmos/blob/main/docs/MIGRATION_V6.md) to upgrade to React Cosmos 6.
