### ISSUE TITLE
How to use typescript paths within react-cosmos?

### ISSUE THREAD

**Issue by lecoqjacob** [react-cosmos/react-cosmos#1349]
### What's wrong?
I have defined paths within my tsconfig.json file that is not being translated within react-cosmos. How would I use relatie paths within cosmos?

### Additional context
![image](https://user-images.githubusercontent.com/9278174/135186153-b37d4120-ad36-4ed6-852c-43db038e4978.png)

tsconfig.json
```
{
  "extends": "@nbm/tsconfig/module",
  "compilerOptions": {
    "baseUrl": "./",
    "plugins": [{ "transform": "@zerollup/ts-transform-paths" }],
    "typeRoots": ["index.d.ts", "node_modules/@types", "node_modules/@obp/types/index.d.ts"],
    "paths": {
      "@carbon-assign-fields/*": ["./src/*"]
    }
  }
}
```

**Comment by supervanya** [comment]
@lecoqjacob did you figure out how to do this?
