### ISSUE TITLE
Default port 5000 is taken on macOS 12

### ISSUE THREAD

**Issue by adesurirey** [react-cosmos/react-cosmos#1355]
### What's wrong?

Default port 5000 is already taken by a system process in the last version of macOS.

```
Error: listen EADDRINUSE: address already in use :::5000
```

https://utf9k.net/questions/macos-port-5000-monterey/

### User info

Cosmos: 5.6.4
macOS: 12.0.1

**Comment by skidding** [comment]
Unfortunately this is indeed the case. I plan to change the default port in v6.

Suggestions for a new default port welcome!

**Comment by brianespinosa** [comment]
I added port 4000 to our monorepo project configs today and can report back if we see any other port collisions here, but I suspect we are probably good.

**Comment by adesurirey** [comment]
I used 5001 🤷‍♂️

**Comment by frodosamoa** [comment]
this is due to new AirPlay functionality, "fix" is located here: https://developer.apple.com/forums/thread/682332

**Comment by georgebdavis** [comment]
Worth sharing here that you can add `"port": 5001` to your `cosmos.config.json` to override, in case anyone is looking for a quick fix.

**Comment by skidding** [comment]
Thanks to everyone who pitched in here!

Was thinking about changing the default port in v6 but in the end decided an even better strategy is to keep the same default for old and non-mac users and fix it more elegantly: If the selected or default port is taken Cosmos will keep searching until it finds an available port. So if 5000 is taken it will use 5001, if 5001 is also taken it will use 5002, etc.

Also added a new `portRetries` config that is the number of port it checks before giving up. The value default is `10`.

This is already published under `react-cosmos@next`. Check out the [migration guide](https://github.com/react-cosmos/react-cosmos/blob/main/docs/MIGRATION_V6.md) if you haven't already.

And see you on our brand new [Discord](https://discord.gg/3X95VgfnW5) for more discussions 🙏.
