### ISSUE TITLE
Cannot click buttons

### ISSUE THREAD

**Issue by farhat-h** [react-cosmos/react-cosmos#1359]
### What's wrong?
**Hey folks :wave:**

I'm trying to initialize a React component development environment using webpack and cosmos.
Everything seems to be working fine so far, except for the fact that I cannot click any button (selecting text also doesn't work).

### Steps to reproduce
I have set up a repository to illustrate the problem. Please take a look [here](https://github.com/farhat-h/cosmos-click-bug)
### Screenshots
After inspecting the UI in Chrome `devtools` I noticed an iframe is overlaid on top of the component display. Deleting the `iframe` resolves the issue.
![Screenshot from 2021-12-22 16-40-34](https://user-images.githubusercontent.com/34007389/147118548-4d135ee5-ad04-4260-8417-04abbd922c10.png)

### User info

- Server terminal output: nothing out of the ordinary
- Browser console output: no errors
- Cosmos version: `5.6.5`

### Additional context
Since this is using webpack, I tried overriding the webpack config and supplying a custom template to the `HTMLWebpackPlugin` in hopes that it just uses that without creating the iframe, but that doesn't work

Appreciate your hard work :bow:

**Comment by skidding** [comment]
Hi @farhat-h,

It appears that [somebody published](https://github.com/facebook/create-react-app/commit/221e511730ca51c036c6954a9d2ee7659ff860f9#diff-07cfb5d644b924ec776b496a52f8bfa9759ad5a4e7018e32f52c2f003ed71099) a major version of Create React App but only bumped `react-error-overlay` – a lower-level CRA package that Cosmos depends on – from `6.0.9` to `6.0.10` even though it seems to have breaking changes. 

Unfortunately this broke Cosmos for newcomers. So thanks a lot for reporting it!

Just pushed a patch that pins `react-error-overlay@6.0.9` in `react-cosmos@5.6.6`. Please upgrade and let me know once you can confirm the fix.

**Comment by farhat-h** [comment]
@skidding Thank you for the fast response!

The issue is gone after upgrading to version `5.6.5` :rocket:
