### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by equinusocio** [react-cosmos/react-cosmos#1361]
### What's wrong?

When I start cosmos I get the following warning:

```
(node:81830) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
: 	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
: 	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
 (Use `node --trace-deprecation ...` to show where the warning was created)
```

### Steps to reproduce

Init cosmos with custom babelrc config

```json
{
  "presets": [
    "@babel/env",
    "@babel/preset-typescript",
    ["@babel/preset-react", {
      "runtime": "automatic"
    }]
  ]
}

```

### Screenshots
![Screenshot 2022-01-15 at 10 36 58](https://user-images.githubusercontent.com/10454741/149617136-741ff39a-f8bd-4c63-b814-69446191fc76.png)

### User info

- Cosmos version
`5.6.6`
- Cosmos config
```json
{
  "$schema": "http://json.schemastore.org/cosmos-config",
  "port": 6006
}
```

**Comment by skidding** [comment]
There's no reference to `Compilation.assets` or `processAssets` in the Cosmos source code.

Can you provide a full example?

**Comment by equinusocio** [comment]
After 15 months... nope. Sorry.

**Comment by skidding** [comment]
Yeah.. time flies. No worries. 

[Just released a new major version](https://github.com/react-cosmos/react-cosmos/blob/main/docs/MIGRATION_V6.md), you're more than welcome to try it again if you get the chance.

Thanks!
