### ISSUE TITLE
High vulnerability in dependencies

### ISSUE THREAD

**Issue by equinusocio** [react-cosmos/react-cosmos#1362]
Github reported that [ansi-html](https://www.npmjs.com/package/ansi-html) package has a high vulnerability issue. That package is a dependency of cosmos, and it looks abandoned since the last update was 5 yrs ago. Is it possible to find an alternative package?

```sh
  └─┬ react-cosmos@5.6.6
    └─┬ @skidding/webpack-hot-middleware@2.25.0
      └── ansi-html@0.0.7
```

Temporary fix using npm force resolutions package

```json
"resolutions": {
    "ansi-html": "https://registry.npmjs.org/ansi-html-community/-/ansi-html-community-0.0.8.tgz"
}
```

**Comment by skidding** [comment]
Fixed this vulnerability in `react-cosmos@5.6.7`. Unfortunately Cosmos still has a few vulnerabilities due to socket.io that won't be fixed until the new major version (Cosmos 6) when IE support will be dropped.
