### ISSUE TITLE
useValue() inputs in the property panel redraw on every character, losing cursor position 

### ISSUE THREAD

**Issue by ehahn9** [react-cosmos/react-cosmos#1372]
### What's wrong?

value inputs in the property panel (from `useValue()`) move cursor to the end of the input
field on every keypress. 

### Steps to reproduce

1.  create a trivial fixture `export default () => <code>{useValue('foo', { defaultValue: 'abcdef' })[0]}</code>
2.  place the cursor in the middle of the 'abcdef' in the 'foo' input in the property control panel
3.  try typing - field redraws on every keystroke leaving the cursor at the end of the string each time
(screenshot below)

### Screenshots

watch where the cursor jumps to after I press a key:
https://user-images.githubusercontent.com/299134/152487494-ac804243-4d29-4db9-b407-260fc18f4d65.mov

### User info

- Cosmos version 5.6.8

**Comment by skidding** [comment]
Fixed by #1426

Will be included in next version and already published under `react-cosmos@canary`.
