### ISSUE TITLE
Going fullscreen ignores props panel state

### ISSUE THREAD

**Issue by tobias-edwards** [react-cosmos/react-cosmos#1377]
### What's wrong?

After configuring a component in the props panel, going full screen with that component will use the default state.

### User info

- Cosmos version: 5.7.2

**Comment by skidding** [comment]
Indeed this is expected. The URL in full screen mode only contains the fixture ID. Encoding state into the URL could be a nice to have for the future.

A full screen fixture URL is disconnected from the Cosmos UI. This offers a fixed URL you can share/bookmark that will always open that fixture. You could for example have two full screen fixtures opened simultaneously.

On the other hand, you could use a remote renderer.

Copy the renderer URL from the Cosmos UI homepage.
<img width="272" alt="image" src="https://user-images.githubusercontent.com/250750/155492786-cb5012cc-6e5a-4c00-828f-d5efa4ecfcbd.png">

Open it in a separate tab and it will be a full screen renderer that syncs with the iframe renderer from the Cosmos UI. So now if you configure the props panel it will be reflected in the full screen component as well.

Maybe this helps with what you were trying to do.

**Comment by tobias-edwards** [comment]
The enhancement of encoding state into the URL would be pretty neat!

The remote renderer works well, thank you.
