### ISSUE TITLE
Add support for react 18 - release is here

### ISSUE THREAD

**Issue by IgnusG** [react-cosmos/react-cosmos#1382]
### What's wrong?
Running react-cosmos with react 18 works but gives the infamous warning: "Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17."
with `ReactDOM.render()` now being [deprecated in future versions](https://github.com/facebook/react/blob/main/CHANGELOG.md#deprecations).

### Steps to reproduce

1. Install react@latest (react 18) and react-cosmos + setup a basic fixture project
2. See warning being displayed (with some functionality of React 18 potentially not working consistently)

### User info

- Cosmos version: 5.7.2

### Additional context

I've patched the behavior in my use case by simply switching to the new API through a node_modules patch file. Seems like this did not have any adverse effects but I've not tested this solution thoroughly :
```diff
diff --git a/dist/dom/index.js b/dist/dom/index.js
index 5828849f38032407426556541e27dd085a159c06..ed64872318e397e4059c662309ed2a92edbd36f7 100644
--- a/dist/dom/index.js
+++ b/dist/dom/index.js
@@ -19,7 +19,7 @@ Object.defineProperty(exports, "rendererId", {
 
 var _react = _interopRequireDefault(require("react"));
 
-var _reactDom = require("react-dom");
+var _reactDomClient = require("react-dom/client");
 
 var _container = require("./container");
 
@@ -39,9 +39,10 @@ function mountDomRenderer(_ref) {
       decorators = _ref.decorators,
       onErrorReset = _ref.onErrorReset;
   var domContainer = (0, _container.getDomContainer)(rendererConfig.containerQuerySelector);
-  (0, _reactDom.render)( /*#__PURE__*/_react.default.createElement(_DomFixtureLoader.DomFixtureLoader, {
+  var root = (0, _reactDomClient.createRoot)(domContainer);
+  root.render( /*#__PURE__*/_react.default.createElement(_DomFixtureLoader.DomFixtureLoader, {
     fixtures: fixtures,
     decorators: decorators,
     onErrorReset: onErrorReset
-  }), domContainer);
+  }));
 }
\ No newline at end of file
```

**Comment by Akiyamka** [comment]
Can confirm, work fine with this changes

**Comment by pomSense** [comment]
Has anyone tried to solve this for Yarn PnP?

**Comment by p0lax** [comment]
Any plans to apply this change?

**Comment by skidding** [comment]
> Any plans to apply this change?

React 18 will be supported in React Cosmos 6, [see this](https://github.com/react-cosmos/react-cosmos/issues/1329#issuecomment-1287439100) about release.

**Comment by skidding** [comment]
React Cosmos 6 runs on React 18 now and it's available for early testing at `react-cosmos@canary`. I'll post a migration guide this month.
