### ISSUE TITLE
The timing of when the second re-render takes place is not idempotent

### ISSUE THREAD

**Issue by EdmundsEcho** [react-cosmos/react-cosmos#1383]
First thank you for this great resource.

### What's wrong?

This is more of a "keep in mind" should  you see a way to solve it when next reviewing the codebase.  It is not critical in other words.

I have a series of calls to `console.debug`.  The sequence for the calls is not idempotent.  

### Steps to reproduce

```jsx
const Component = () => {
  return (
    <>
      <h1>Test</h1>
      {console.debug("------------------------------------")}
      {renderRoutes(routes)}
    </>
  );
};
export default <Component />;
```

The `renderRoutes` call has calls to `console.group` and the like.  Here is the output that seems to indicate that the **second** render is happening before the last line of the `renderRoutes` call.

<img width="1071" alt="Screen Shot 2022-03-31 at 2 52 41 PM" src="https://user-images.githubusercontent.com/11245417/161128659-dff472a8-d066-4599-a3a2-66f864a596cb.png">

Here is the relevant snippet in `renderRoutes` (called recursively):
```jsx
export function renderRoutes(config) {
  
  // case: array - resubmit for each element in the array
  if (Array.isArray(config)) {
    return config.map(renderRoutes);
  }

  const { type, children = false, ...props } = config;

  console.groupCollapsed(`config values for type: ${type}`);
  console.dir("config", config);
  console.dir("props", props);
  console.debug(`%cchildren? ${Boolean(children)}`, 'color: #bada55');

  if (typeof ComponentFromType(type) !== "undefined") {

    // close the current group when no children
    if (!children) console.groupEnd();

    return createElement(
      ComponentFromType(type),
      props,
      children &&
        (typeof children === "string" ? children : children.map(renderRoutes))
    );
  }
  console.groupEnd();  //  the first render skips this line (likely calls is it later)
}
```

Note: I tried to create a `result` value so that I could call the `groupEnd` function prior to returning, but after the `map` function had returned to no avail.

**Comment by skidding** [comment]
Maybe the problem is that you call `console.groupEnd` _after_ `createElement` which causes other children to render immediately and log their values to the console before the parent component finished. But I'm not sure because I don't fully grasp the situation. I can help more if you can reduce your example to a minimum reproducing case.
