### ISSUE TITLE
Add cosmos.decorator.tsx prompt need an additional loader

### ISSUE THREAD

**Issue by lvchenyang** [react-cosmos/react-cosmos#1387]
### What's wrong?

Typescript based CRA project prompt need an additional loader when add a cosmos decorator entry file.

### Steps to reproduce

1.  npx create-react-app test --template typescript
2.  config cosmos env
3.  Add cosmos.decorator.tsx in project root dir

### Screenshots

```
[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] Serving static files from public
[Cosmos] See you at http://localhost:5000
[Cosmos] Using webpack config found at node_modules/react-scripts/config/webpack.config.js
[Cosmos] Building webpack...
webpack built ca8907858621cce8f33e in 6641ms
WARNING in ../../node_modules/@base2/pretty-print-object/dist/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/lvchenyang/Projects/mintpie-pro/node_modules/@base2/pretty-print-object/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/lvchenyang/Projects/mintpie-pro/node_modules/@base2/pretty-print-object/src/index.ts'

WARNING in DefinePlugin
Conflicting values for 'process.env'

1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

ERROR in ./cosmos.decorator.tsx 6:4
Module parse failed: Unexpected token (6:4)
File was processed with these loaders:
 * ../../node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export default ({ children }) => {
|   return (
>     <MintpieThemeProvider theme={DEFAULT_THEME} remConfig={{ rootValue: 16 }}>
|       {children}
|     </MintpieThemeProvider>

webpack compiled with 1 error and 3 warnings
No issues found.

```

### User info

- Server terminal output
- Browser console output
- Cosmos version
```
^5.7.2
```
- If bug occurred on upgrade: Working Cosmos version
- Cosmos config
```
{
  "staticPath": "public",
  "watchDirs": ["src"],
  "webpack": {
    "configPath": "react-scripts/config/webpack.config"
  },
  "ui": {
    "responsivePreview": {
      "devices": [
        { "label": "iPhone 6", "width": 375, "height": 667 }
      ]
    }
  }
}
```
- If applicable: webpack version
- If applicable: webpack config

**Comment by skidding** [comment]
I think the problem is that with CRA you need to put `cosmos.decorator.tsx` and any other source file inside `src`, otherwise it won't be compiled.

**Comment by sshmyg** [comment]
Same for me.
https://github.com/sshmyg/frontend repo for reproducing.

**Comment by skidding** [comment]
> Same for me. Not CRA, but latest webpack and custom configs.
> https://github.com/sshmyg/frontend repo for reproducing.

Same issue. Babel is configured to compile `src` dir only: https://github.com/sshmyg/frontend/blob/85490fdd8a9a80e3fc3d76764679473bf94832b5/webpack.config.js#L96-L108

And Cosmos decorator (which is a JSX file that requires compilation) is placed outside src in the project root: https://github.com/sshmyg/frontend/blob/85490fdd8a9a80e3fc3d76764679473bf94832b5/cosmos.decorator.jsx

You have to either put the Cosmos decorator file in src or make Babel compile it as well.
