### ISSUE TITLE
Error of undefined `hook` in Brave -- Actually CORS error

### ISSUE THREAD

**Issue by TrySpace** [react-cosmos/react-cosmos#1400]
### What's wrong?

- When adding a component to a fixture like `Plate` it will give me tons of undefined errors (likely for each render). I could only narrow it down to this specific component.

- It does not occur when running my normal cra setup (with craco), so I'm wondering if there is some injection taking place from react-cosmos.  And it does not occur in Chrome, only Brave, probably because Brave is stricter in their CORS policy?

What I noticed that if I go to the fixture, and _modify/toggle a property in the right sidebar first, before interacting with the editor, **the errors don't occur!**_.

### Summary / Steps to reproduce

1.  Add basic `Plate` editor component
2.  Click in the editable body / try typing
3.  See the same error repeat

4. Change a prop on the right
5. Error changes into a CORS error, and seemingly has the same stacktrace, but more readable

### Screenshot
![image](https://user-images.githubusercontent.com/5586278/202170449-78f072ee-47e2-4037-bd0c-c2a8c3de5155.png)
```error 
react_devtools_backend.js TypeError: Cannot set properties of undefined (setting +'hook')
```

And I thought I couldn't debug this further because of the anonymity of the error, however, after toggling a property, the error happens only once, but in a different form, and I'm pretty sure it's the same, seeing the line: 4026 is the same:

![image](https://user-images.githubusercontent.com/5586278/202173501-381811ef-d88f-4528-a504-1be90c6b1d21.png)

```error
react_devtools_backend.js:4026 DOMException: Blocked a frame with origin "http://localhost:5000" from accessing a cross-origin frame.
    at JSON.stringify (<anonymous>)
    at Object.parseData (<anonymous>:8:116)
    at <anonymous>:10:2186
    at Array.reduce (<anonymous>)
    at <anonymous>:10:2114
    at i (<anonymous>:10:2706)
    at t.onCommitFiberRoot.t.onCommitFiberRoot (<anonymous>:10:3098)
```

So from what I can gather this is definitely a `react-cosmos` problem, but why it only occurs with `Plate` I have no clue. (I tried it with a simple component with `contentEditable` but no)

### User info
- Cosmos version 5.7.2
- Browser: Brave [Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by skidding** [comment]
The error comes from `react_devtools_backend.js` so I think this might be related to React Dev Tools.

@TrySpace closing this but feel free to reopen if you still have this issue. Maybe try with/without React Dev Tools and if you provide an example repo I'll take a look.
