### ISSUE TITLE
The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)

### ISSUE THREAD

**Issue by quassnoi** [react-cosmos/react-cosmos#1432]
### What's wrong?

On a fresh install, `npm cosmos` fails with:

```text
The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
```

### Steps to reproduce

```bash
npx create-react-app cosmos-bug --template typescript
cd cosmos-bug
npm i -D react-cosmos@next react-cosmos-plugin-webpack@next
```

cosmos.config.json:

```json
{
  "staticPath": "public",
  "plugins": [
    "react-cosmos-plugin-webpack"
  ],
  "watchDirs": [
    "src"
  ],
  "webpack": {
    "configPath": "react-scripts/config/webpack.config"
  }
}
```

package.json:

```json
{
  "name": "cosmos-bug",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.23",
    "@types/react": "^18.0.33",
    "@types/react-dom": "^18.0.11",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "cosmos": "cosmos",
    "cosmos:export": "cosmos-export"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "react-cosmos": "^6.0.0-alpha.9",
    "react-cosmos-plugin-webpack": "^6.0.0-alpha.9"
  }
}
```

```bash
npm run cosmos
```

Observe the error:

```text
{
  "name": "cosmos-bug",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.23",
    "@types/react": "^18.0.33",
    "@types/react-dom": "^18.0.11",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "cosmos": "cosmos",
    "cosmos:export": "cosmos-export"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "react-cosmos": "^6.0.0-alpha.9",
    "react-cosmos-plugin-webpack": "^6.0.0-alpha.9"
  }
}
```

### User info

```bash
$ npm --version
9.2.0

$ node --version
v19.3.0
```

**Comment by quassnoi** [comment]
It works now, thanks!

With create-react-app, it's not easy to change the webpack configuration without ejecting or rewiring, so this would definitely be useful for a lot of people.

**Comment by skidding** [comment]
> It works now, thanks!
> 
> With create-react-app, it's not easy to change the webpack configuration without ejecting or rewiring, so this would definitely be useful for a lot of people.

You're welcome!

Btw you can always override the webpack config as described here: https://github.com/react-cosmos/react-cosmos/tree/main/docs#webpack-config-override.

**Comment by quassnoi** [comment]
> > It works now, thanks!
> > With create-react-app, it's not easy to change the webpack configuration without ejecting or rewiring, so this would definitely be useful for a lot of people.
> 
> You're welcome!
> 
> Btw you can always override the webpack config as described here: https://github.com/react-cosmos/react-cosmos/tree/main/docs#webpack-config-override.

I didn't know that!

Can we emit something to this effect in the console log when you run cosmos with webpack?

```
[Cosmos] Learn how to override webpack for cosmos: https://github.com/react-cosmos/react-cosmos/tree/main/docs#webpack-config-override
```

, if you don't have a custom config already?

I can put together a PR if you want.

**Comment by skidding** [comment]
> I didn't know that!
> 
> Can we emit something to this effect in the console log when you run cosmos with webpack?
> 
> ```
> [Cosmos] Learn how to override webpack config for cosmos: https://github.com/react-cosmos/react-cosmos/tree/main/docs#webpack-config-override
> ```
> 
> , if you don't have a custom config already?
> 
> I can put together a PR if you want.

Sure, sounds like a good idea.

This is the file you're interested in https://github.com/react-cosmos/react-cosmos/blob/main/packages/react-cosmos-plugin-webpack/src/server/webpackConfig/getUserWebpackConfig.ts

Just note that this hint might be useful if you have a custom config, too. Like in your case, technically you're passing the CRA webpack config as a custom webpack config, and you might *still* want to override it.

So with cosmos you have a base webpack config, which could be the Cosmos-generated default webpack config or a custom config passed via `webpack.configPath`, and it both cases you can override it via `webpack.overridePath`.
