### ISSUE TITLE
Increase awareness of the ability to override Webpack config

### ISSUE THREAD

**Issue by quassnoi** [react-cosmos/react-cosmos#1436]
As a maintainer of a project developed by people not particularly familiar with Cosmos internals, I want the developers to know that Cosmos allows overriding Webpack settings easily, should the need arise.

This ability is mentioned in the documentation, but it's not easy to find unless you know what to look for. I wasn't aware of this ability when I had filed #1432

If the Webpack config is already overridden, Cosmos does mention this fact on each run. But it doesn't mention the ability to do that if it's not overridden.

Cosmos should tell about the ability to override Webpack config on each run, if the project is not doing it already.

**Comment by skidding** [comment]
@quassnoi Thanks for your contribution!
