### ISSUE TITLE
Unable to get started with vite plugin following the setup docs

### ISSUE THREAD

**Issue by ambadyanands** [react-cosmos/react-cosmos#1451]
### What's wrong?

I followed the [Getting Started](https://github.com/react-cosmos/react-cosmos/tree/main/docs#getting-started) section in the README with vite as the bundler and opening `localhost:5000` just keeps showing `Waiting for renderer...`.

### Steps to reproduce

1. Setup a vite react project
1.1 `npm create vite@latest cosmos-vite -- --template react`
1.2 `cd cosmos-vite`
1.3 `npm install`
2. Install react-cosmos and vite plugin:
`npm i -D react-cosmos@next react-cosmos-plugin-vite@next`
3. Create `cosmos.config.json` and enable vite plugin:
```
{
  "plugins": ["react-cosmos-plugin-vite"]
}
```
4. Add package.json scripts:
```
"scripts": {
  "cosmos": "cosmos",
  "cosmos:export": "cosmos-export",
  ...
}
```
5. Create `src/Hello.jsx` component as given in the docs:
```
import React from 'react';

export function Hello({ greeting, name }) {
  return <h1>{greeting}, {name}!</h1>;
}
```
6. Create `src/Hello.fixture.jsx` fixture as given in the docs:
```
import React from 'react';
import { Hello } from '../Hello';

export default <Hello greeting="Aloha" name="Alexa" />;
```
7. Run `npm run cosmos` and open `http://localhost:5000` in browser. It will just keep showing `Waiting for renderer...`.

### User info

- Server terminal output:
```
> cosmos-vite@0.0.0 cosmos
> cosmos

[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] Found 1 plugin: Vite
[Cosmos] See you at http://localhost:5000
  ➜  Local:   http://localhost:5050/
```
- Browser console output:
```
23:33:04.100 Feature Policy: Skipping unsupported feature name “clipboard-write”. [react-dom.production.min.js:24:219](webpack://mountPlayground/node_modules/react-dom/cjs/react-dom.production.min.js)
23:33:04.105 Feature Policy: Skipping unsupported feature name “clipboard-write”. [react-dom.production.min.js:248:85](webpack://mountPlayground/node_modules/react-dom/cjs/react-dom.production.min.js)
23:33:06.107 [vite] connecting... [client.ts:18:8](http://localhost:5050/@vite/client.ts)
23:33:06.208 [vite] connected. [client.ts:133:14](http://localhost:5050/@vite/client.ts)
```
- Cosmos version: `react-cosmos@6.0.0-alpha.13`
- If bug occurred on upgrade: Working Cosmos version: N/A
- Cosmos config:
```
{
  "plugins": ["react-cosmos-plugin-vite"]
}
```
- If applicable: webpack version: N/A
- If applicable: webpack config: N/A

### Additional context

Did I miss anything? 
Also, please let me know if I should provide any more details. 

Thanks.

**Comment by skidding** [comment]
@ambadyanands thanks for reporting this!

The Vite plugin is still early days but luckily the issue was easy to fix (see #1453 if you're curious).

Also fixed the example from the docs where the fixture should import the Hello component from a sibling path:

```diff
-import { Hello } from '../Hello';
+import { Hello } from './Hello';
```

That said, pushed a fix in `6.0.0-alpha.14` so please install `react-cosmos@next react-cosmos-plugin-vite@next` again and let me know if you experience other issues.

**Comment by ambadyanands** [comment]
@skidding Thanks a lot, that fixed the issue :+1:

**Comment by AlexEscalante** [comment]
I am having the same exact problem, but I went even more basic and my `Basic.fixture.tsx` is only:

```
export default <h1>Hello world!</h1>;
```

My `cosmos.config.json`:

```
{
  "plugins": ["react-cosmos-plugin-vite"],
  "staticPath": "./public/"
}
```
Cosmos seems to run without issues, and it even detects my `vite.config.ts`:

```
> cosmos
[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] Found 1 plugin: Vite                                                   
[Cosmos] Serving static files from public
[Cosmos] See you at http://localhost:5000
[Cosmos] Using vite config found at vite.config.ts
```

My `vite.config.ts` is here also, maybe there is something Cosmos doesn't like?:

```
import legacy from '@vitejs/plugin-legacy';
import react from '@vitejs/plugin-react';
import basicSsl from '@vitejs/plugin-basic-ssl';
import { VitePWA } from 'vite-plugin-pwa';
import { compression } from 'vite-plugin-compression2';

import { defineConfig, loadEnv } from 'vite';

export default defineConfig(({ command: _, mode }) => {
  const env = loadEnv(mode, process.cwd(), 'IRON_');
  return {
    build: {
      sourcemap: true, // Needed for Sentry
    },
    plugins: [
      react(),
      legacy(),
      basicSsl(),
      compression({ algorithm: 'gzip' }),
      VitePWA({
        strategies: 'injectManifest',
        srcDir: 'src',
        filename: 'service-worker.ts',
        registerType: 'autoUpdate',
        workbox: {
          clientsClaim: true,
          skipWaiting: true,
          globPatterns: ['**/*.{gz,css,html,ico,png,svg}'],
        },
      }),
    ],
    test: {
      globals: true,
      environment: 'jsdom',
      setupFiles: './src/setupTests.ts',
    },
    define: {
      'process.env': JSON.stringify(env),
    },
    server: {
      port: 8100,
    },
    environment: 'jsdom',
    setupFiles: './src/setupTests.ts',
  };
});
```

I will certainly appreciate any help! 😄

**Comment by crobinson42** [comment]
@ovidiuch I have this issue following the docs for Vite with a basic fixture:
<img width="1374" alt="image" src="https://github.com/react-cosmos/react-cosmos/assets/5973579/f16b0d54-cb50-4b32-b143-0955d3ec2c3b">

**Comment by ovidiuch** [comment]
@crobinson42 I don't know how to reproduce that locally. Do you have a public repo for me to look at?

**Comment by crobinson42** [comment]
@ovidiuch here you go: [https://github.com/crobinson42/react-cosmos-vite-issue](https://github.com/crobinson42/react-cosmos-vite-issue) pull, npm install, run `npm run cosmos` you'll see 1 fixture "Button" that fails to load in the network tab.

I also tried to use webpack and the same issue occurs where it waits for the renderer forever.

My env: Mac M3 Node v20.9.0 NPM v10.2.5.

**Comment by ovidiuch** [comment]
@crobinson42 It seems like your Vite app is missing an `index.html`.

If I add this `index.html` in your repo root:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/index.ts"></script>
  </body>
</html>
```

The vite renderer loads but now has some alias errors:

```
[plugin:vite:import-analysis] Failed to resolve import "@/components/ui/button" from "src/components/ui/button.fixture.tsx". Does the file exist?
/Users/[redacted]/Work/crobinson42/react-cosmos-vite-issue/src/components/ui/button.fixture.tsx:1:21
```

I'm guessing you need to configure some aliases in your Vite config.

---

Maybe it isn't visible enough but the Vite guide starts with this mention:

<img width="881" alt="image" src="https://github.com/react-cosmos/react-cosmos/assets/250750/c53b3be0-e314-421e-a484-1c11ac43c678">

**Comment by crobinson42** [comment]
Thank you @ovidiuch - it's a component lib so i need or think to add an index.html file 😶‍🌫️ it would be could if react-cosmos provided it automagically but probably not the responsible of the lib, just a nice-to-have.

**Comment by ovidiuch** [comment]
> Thank you @ovidiuch - it's a component lib so i need or think to add an index.html file 😶‍🌫️ it would be could if react-cosmos provided it automagically but probably not the responsible of the lib, just a nice-to-have.

That's fair. The Vite plugin should do this as bundlers are rather different so this would be Vite specific. For example webpack has the html-webpack-plugin which creates the html automatically but I don't know if there is something similar for Vite. It would be nice if we could surface this issue more clearly, though.
