### ISSUE TITLE
Respect SSL option when connecting to websocket

### ISSUE THREAD

**Issue by bpinto** [react-cosmos/react-cosmos#1525]
### What's wrong?

When `https: true` option is set cosmos is loaded through `https://` protocol. Trying to load a websocket through insecure protocols `ws://` instead of `wss://` breaks the app.

### Steps to reproduce

1.  Edit `cosmos.config.json` by adding `https: true, { httpsOptions }`.
2.  Try to load cosmos through `https://`.
3.  Page won't load.

### Screenshots

<img width="2332" alt="Screenshot 2023-06-06 at 15 14 19" src="https://github.com/react-cosmos/react-cosmos/assets/526122/4b94dd50-818b-4a41-9cc2-d1c6a0b528a6">

### Useful info

- Cosmos version: `6.0.0-beta.3`
- Cosmos config:

```js
{
  "globalImports": ["./webpack/global.css", "./front-end/config/cosmos.global.js"],
  "https": true,
  "httpsOptions": {
    "keyPath": "./sslcerts/development/server/cliniko.dev.key",
    "certPath": "./sslcerts/development/server/cliniko.dev.crt"
  },
  "plugins": ["react-cosmos-plugin-webpack"],
  "port": 5555,
  "rootDir": "../../",
  "watchDirs": [],
  "webpack": {
    "overridePath": "./front-end/config/cosmos.override"
  }
}
```

- Server terminal output.

```
[Cosmos] Using cosmos config found at front-end/config/cosmos.config.json
[Cosmos] Found 1 plugin: Webpack
[Cosmos] See you at https://localhost:5555
[Cosmos] Using default webpack config
[Cosmos] Overriding webpack config at front-end/config/cosmos.override.js
[Cosmos] Building webpack...
webpack built bb04ab5311aa00a580d2 in 12226ms
29 assets
2286 modules
webpack 5.76.1 compiled successfully in 12226 ms
```

- Browser console output.

(screenshot)

**Comment by skidding** [comment]
This seems to be an real issue that breaks remote renderers (including the React Native renderer) with https enabled.

Here are key places where the WebSockets protocol is hardcoded:

Cosmos UI connecting to the server
https://github.com/react-cosmos/react-cosmos/blob/main/packages/react-cosmos-ui/src/plugins/MessageHandler/socket.ts#L18

**Comment by kmjennison** [comment]
Our project is patching react-cosmos to deal with this issue. I'd be happy to submit a PR if it's welcome.

**Comment by skidding** [comment]
> Our project is patching react-cosmos to deal with this issue. I'd be happy to submit a PR if it's welcome.

@kmjennison A PR would be very welcome!
