### ISSUE TITLE
fixture fails to enter fullscreen mode

### ISSUE THREAD

**Issue by noahehall** [react-cosmos/react-cosmos#1529]
### What's wrong?

- fixture fails to enter fullscreen mode

### Steps to reproduce

- [clone this pr if it still exists](https://github.com/noahehall/react-fullerpage/pull/14/files)
  - else just clone develop branch
  - `bun install && bun run cosmos`
- Click on small button in the top left corner to request fullscreen mode
- See... error in console

### Screenshots

![image](https://github.com/react-cosmos/react-cosmos/assets/10324554/23d4202a-80a6-4a0d-9907-f6fb3bfeab7f)

- dont think its something in fscreen, as it works when rendered outside of react-cosmos
- but this is where its throwing

![image](https://github.com/react-cosmos/react-cosmos/assets/10324554/3b797f78-5904-4eae-8a53-9301306b7373)

### Useful info

- Cosmos version. `alpha`
- Cosmos config. `{port: 5000, rendererUrl: 0.0.0.0:5050}`
- Server terminal output.

```sh
03:05 AM (feat/silky-smooth-scroll $) 
$ bun run cosmos
$ bun run cosmos:start & bun run cosmos:bun
$ bun --watch cosmos.bunserver.ts
$ cosmos --expose-imports
[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] See you at http://localhost:5000
[Cosmos] Generated cosmos.imports.ts
app built: true; 1 files 
Started server http://0.0.0.0:5050

```
- Browser console output. `see screenshot`

### Additional context

Add any other context about the problem.

**Comment by skidding** [comment]
Hi @noahehall,

I'm not sure what the fullscreen functionality does in your app, but can you try something for starters: Can you open that fixture in full screen mode in Cosmos and see if you still get that error?

Basically press this button here and your fixture will break outside the Cosmos UI shell:
<img width="206" alt="image" src="https://github.com/react-cosmos/react-cosmos/assets/250750/aca4ba81-d94a-420f-8608-95dc4f3b7938">

**Comment by skidding** [comment]
Also, if you're calling the browser Fullscreen API – which I just found out about! – it seems like it only works inside an iframe that has the `allow fullscreen` on it: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen#usage_notes

Do you want to add this to Cosmos? I think it's just a matter of setting `allow="fullscreen"` on this iframe element:
https://github.com/react-cosmos/react-cosmos/blob/0755897983759b7c0062238c6ddf396dc9e1a842/packages/react-cosmos-ui/src/plugins/RendererPreview/RendererPreview.tsx#L35-L41

It already has `clipboard-write *` so combining both would result in `"clipboard-write *; fullscreen"`? Please double check that this is the syntax for combining two allow values if you make this PR. Thanks!

**Comment by noahehall** [comment]
will send a PR shortly

**Comment by noahehall** [comment]
> Basically press this button here and your fixture will break outside the Cosmos UI shell:

didnt even know that existed, but yea it works when it breaks out of the cosmo shell

im going to try your fix for the iframe

**Comment by noahehall** [comment]
@skidding you were correct, adding `fullscreen *;` to the iframe permission set worked perfectly in chromium and firefox developer

**Comment by skidding** [comment]
> @skidding you were correct, adding `fullscreen *;` to the iframe permission set worked perfectly in chromium and firefox developer

Cool! Will you submit a PR with that change?
