### ISSUE TITLE
`cosmos --expose-imports` seems to have stopped building imports at some point

### ISSUE THREAD

**Issue by oponder** [react-cosmos/react-cosmos#1545]
Hi cosmos team! 

I'm Oliver from Warmspace. We have been using and evaluating cosmos for a few months now, I've enjoyed the faster iteration cycles while working on a component :)  Here's a little bug report, not sure if we are doing something wrong, or if there has been a change recently.

### What's wrong?

Our `cosmos.imports` file is no longer being created or updated. This worked at some point when we started using cosmos, but we have actually started manually editing that file.. however it was our understanding that it should auto update with the `--expose-imports` flag.

### Steps to reproduce

1.  We're on `v6.0.0-beta.6`
2.  Running `yarn cosmos`   (with `"cosmos": "cosmos --expose-imports"` in our scripts in package.json)
3. We see

```
$ yarn cosmos
yarn run v1.22.19
$ cosmos --expose-imports
[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] See you at http://localhost:5000
```

4. However no `cosmos.imports` file is made or updated.

### Useful info

```
// cosmos.config.json
{
  "port": 5000,
  "rendererUrl": "http://localhost:5050"
}

```

### Additional context

We are using `parcel` as our bundler. To start the renderer we do something like `parcel serve -p 5050 ./cosmos/index.html`

Contents of `cosmos/index.html` point to `CosmosApp.tsx` which is built by Parcel and contains:

```
// cosmos/CosmosApp.tsx
import { mountDomRenderer } from "react-cosmos-dom";
import * as mountArgs from "../cosmos.imports";

mountDomRenderer(mountArgs);
```

Through following the guide: https://github.com/react-cosmos/react-cosmos/blob/main/docs/getting-started/custom-bundler.md

**Comment by oponder** [comment]
setting our package.json to `next` seems to fix the issue:

```
    "react-cosmos": "next",
    "react-cosmos-dom": "next",
    "react-cosmos-renderer": "next",
```

```
// yarn.lock

... 

react-cosmos-core@6.0.0-beta.5:
  version "6.0.0-beta.5"
  resolved "https://registry.yarnpkg.com/react-cosmos-core/-/react-cosmos-core-6.0.0-beta.5.tgz#66a1dbc2d234e2f55248be51b6dd06ed0be8a942"
  integrity sha512-6htNpF6YGQZIAWMRa+XZ9ltpIzIt0L2ZrrO+yXuTYH/OfQnvBb9awLvha/XT290KX/LVhKl+H95dMqBMuEENRA==
  dependencies:
    js-base64 "^3.7.5"
    lodash-es "^4.17.21"
    react-is "^18.2.0"

react-cosmos-dom@next:
  version "6.0.0-beta.6"
  resolved "https://registry.yarnpkg.com/react-cosmos-dom/-/react-cosmos-dom-6.0.0-beta.6.tgz#8c00ad94d8fb653739b98566dc8f0b8a61a27033"
  integrity sha512-3xZuIuJy3cjh+9m7E5TF4HUhJTj1KKtmHp4P0djfbvzZTvQsALLluQmn0OddU1RiSN98sJiPruWhcEZC2SmdRg==
  dependencies:
    lodash-es "^4.17.21"
    react-cosmos-core "6.0.0-beta.5"
    react-cosmos-renderer "6.0.0-beta.5"

react-cosmos-renderer@6.0.0-beta.5, react-cosmos-renderer@next:
  version "6.0.0-beta.5"
  resolved "https://registry.yarnpkg.com/react-cosmos-renderer/-/react-cosmos-renderer-6.0.0-beta.5.tgz#d51868f85383b2b3e73492dad07936f5c282df89"
  integrity sha512-8ZO7qg84TVW0qbRuMsQodLoKUxtkza0a2Vz+/bojekNZIG+CEHNNFgIHsXLSDrg2vlT97rLnrBaAoGUvLikouA==
  dependencies:
    lodash-es "^4.17.21"
    react-cosmos-core "6.0.0-beta.5"
    react-is "^18.2.0" 
    
... 
    
```

**Comment by skidding** [comment]
@oponder Maybe before when you were on `6.0.0-beta.6` some mismatched canary versions where installed? I've seen this before and it's an annoying issue with the next/canary channels. Because `c` comes after `b` if you have a `^x-beta` package you might get a `x-canary` version when you blow up your yarn.lock. For this reason I remove the `^` or `~` signs from beta versions to make sure I pin my dependencies strictly.

**Comment by oponder** [comment]
Yeah I think that was it, I didn't understand correctly how to set the versions matcher in this case. Thanks for the reply!
