### ISSUE TITLE
Fixture Error : Lazy element type must resolve to a class or function

### ISSUE THREAD

**Issue by Fridus** [react-cosmos/react-cosmos#1553]
### What's wrong?

Fixture works only if export function or class component.

### Steps to reproduce

```
// Button.fixture.tsx
"use client";
import { Button } from "./Button";
export default <Button disabled>Click me</Button>;
```

### Screenshots

```
Unhandled Runtime Error
Error: Element type is invalid. Received a promise that resolves to: [object Object]. Lazy element type must resolve to a class or function.

Call Stack
mountLazyComponent
node_modules/.pnpm/next@13.4.19_@babel+core@7.22.15_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom-experimental/cjs/react-dom.development.js (16430:0)
```

### Useful info

package.json
```
    "react-cosmos": "6.0.0-beta.6",
    "react-cosmos-next": "6.0.0-beta.6",
```

**Comment by skidding** [comment]
Known limitation with RSC & client component. Please see [this mention](https://github.com/react-cosmos/react-cosmos/blob/593608c7f857bd43872299edbedb8d4edccc13ad/docs/getting-started/next.md#limitations).

> Only [Component Fixtures](https://github.com/react-cosmos/react-cosmos/blob/593608c7f857bd43872299edbedb8d4edccc13ad/docs/usage/fixtures.md#component-fixtures) fixtures can be exported from a fixture module with the 'use client' descriptor. That's because Client fixture modules are passed as is to the Server render tree and their exports are expected to be components by design. While [Node Fixtures](https://github.com/react-cosmos/react-cosmos/blob/593608c7f857bd43872299edbedb8d4edccc13ad/docs/usage/fixtures.md#node-fixtures) and [Multi-Fixtures](https://github.com/react-cosmos/react-cosmos/blob/593608c7f857bd43872299edbedb8d4edccc13ad/docs/usage/fixtures.md#multi-fixtures) cannot be used in Client fixtures, all Cosmos fixture formats are supported in Server fixtures.

So if your fixture does indeed need to be a client component (ie. use `"use client"`) you can change the export to

```jsx
export default () => <Button disabled>Click me</Button>;
```

Otherwise remove the `"use client"` directive and the fixture will run as a server component and can export any Cosmos fixture format.

**Comment by ZeeshanMustfai** [comment]
You need to export as below and "use client"
export default () => <Button>Click Me</Button> or
export default ButtonDummy = () => {
  return <Button>Click Me</Button>
};

**Comment by Fridus** [comment]
Thanks for your answers :)
