### ISSUE TITLE
Next.js 14 no longer allows 'use client' and generateStaticParams() to be used together

### ISSUE THREAD

**Issue by jasonbert** [react-cosmos/react-cosmos#1577]
### What's wrong?

We're continuing our work to run Cosmos as a separate app from the main Next.js app (https://reactcosmos.org/docs/getting-started/next#separate-react-cosmos-from-nextjs-app). It looks like something has changed between Next.js 13 & 14 and the way the separation is solutioned no longer works. Originally the solution was running on Next.js 12 and upgrading to Next.js 13 all worked fine still.

I upgraded the setup to 14 and now it won't build. 'use client' was in .cosmos\src\app\cosmos\[fixture]\page.tsx, but Next.js 14 doesn't like this anymore.

```
Error: Page "/cosmos/[fixture]/page" cannot use both "use client" and export function "generateStaticParams()"
```

Taking it out, the build complains about a type issue and I'm not sure why.

```
 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
   Collecting page data  ..TypeError: H.createContext is not a function
    at 4837 (D:\...\.cosmos\.next\server\app\cosmos\[fixture]\page.js:22:39783)
    at Function.t (D:\...\.cosmos\.next\server\webpack-runtime.js:1:127)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (D:\...\.cosmos\node_modules\next\dist\build\utils.js:884:17)

> Build error occurred
Error: Failed to collect page data for /cosmos/[fixture]
    at D:\...\.cosmos\node_modules\next\dist\build\utils.js:1217:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  .
```

### Steps to reproduce

Build the below repository:

https://github.com/scorado-ltd/scorado-examples-nextjs-cosmos

_NOTE: I need to upgrade the repository to Next.js 14 for it to reproduce the issue, which we discovered on a different repository._

**Comment by jasonbert** [comment]
After doing some work on the example repository, I have working Next.js 13 & 14 builds. I don't know what was happening with the Next.js 14 builds where it was throwing a type error.

Next.js 14: https://scorado-examples-nextjs-cosmos.vercel.app/

Still worth noting that the example repository was using `'use client'` in `.cosmos\src\app\cosmos\[fixture]\page.tsx`, removing it doesn't seem to have had any effect. I don't know why it was using that directive though.

**Comment by skidding** [comment]
> After doing some work on the example repository, I have working Next.js 13 & 14 builds. I don't know what was happening with the Next.js 14 builds where it was throwing a type error.
> 
> Next.js 14: https://scorado-examples-nextjs-cosmos.vercel.app/
> 
> Still worth noting that the example repository was using `'use client'` in `.cosmos\src\app\cosmos\[fixture]\page.tsx`, removing it doesn't seem to have had any effect. I don't know why it was using that directive though.

Not sure why `'use client'` was used in [scorado-ltd/scorado-examples-nextjs-cosmos](https://github.com/scorado-ltd/scorado-examples-nextjs-cosmos). It essentially disables Server Components in Cosmos from the get-go, and it isn't used in the [react-cosmos/nextjs-example](https://github.com/react-cosmos/nextjs-example/blob/f6bc6bd313c5dc7b8ac33141822bead7e5290912/src/app/cosmos/%5Bfixture%5D/page.tsx) repo.

Also I upgraded the example repo to Next.js 14 and it seems to work just fine: https://github.com/react-cosmos/nextjs-example/pull/5.

@jasonbert Is everything working OK now for you as well?
