### ISSUE TITLE
Does not show multi fixture with custom bundler (Parcel)

### ISSUE THREAD

**Issue by FrancoRATOVOSON** [react-cosmos/react-cosmos#1606]
### What's wrong?

I use parcel with the instructions detailed [in the doc on custom bundlers](https://reactcosmos.org/docs/getting-started/custom-bundler) and everything worked fine 'til I tried to use [multi fixtures](https://reactcosmos.org/docs/fixtures/fixture-modules#multi-fixtures) for a component :

```
import Button from './Button'

const text = 'Action Button'

export default {
  Primary: <Button variant="default">{text}</Button>,
  Secondary: <Button variant="secondary">{text}</Button>
}
```

### Steps to reproduce

There's nothing really special, I just followed the instructions with copy-paste. Here's my `package.json`  :

```
  "devDependencies": {
    ...
    "react": "^18.2.0",
    "react-cosmos": "^6.0.0",
    "react-cosmos-dom": "^6.0.0-alpha.0",
    "react-cosmos-renderer": "^6.0.0",
    "react-dom": "^18.2.0",
    ...
  }
```

I have nothing special on my html or js file, it's just a basic empty html file from parcel doc and a copy-past of the js file in the reac-cosmos doc I mentionned earlier. And `cosmos.imports.js` is generated without any problems :

```
// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import * as fixture0 from './../src/components/Button/Button.fixture.tsx';

import * as decorator0 from './../src/cosmos.decorator.tsx';

export const rendererConfig = {
  "playgroundUrl": "http://localhost:5000",
  "rendererUrl": "http://localhost:1234"
};

const fixtures = {
  'src/components/Button/Button.fixture.tsx': { module: fixture0 }
};

const decorators = {
  'src/cosmos.decorator.tsx': { module: decorator0 }
};

export const moduleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
```

### Screenshots

The result :

![image](https://github.com/react-cosmos/react-cosmos/assets/56756707/3e1c3238-23ef-4e35-aeac-ad25a7c428c7)

As you can see...

### Useful info

- Cosmos version: in the `package.json` above
- Cosmos config: 
```
{
  "port": 5000,
  "rendererUrl": "http://localhost:1234"
}
```
- Server terminal output: nothing special, everything work fine
- Browser console output: nothing special

### Additional context

I have this `cosmos.decorator.tsx` if you need but I don't think it has some effect here, right ?

```
import React, { useState } from 'react'
import { MoonIcon, SunIcon } from './Icons'

import 'style-config/style.css'

export default ({ children }: { children: React.ReactNode }) => {
  const [dark, toggleDark] = useState<boolean>(
    document.documentElement.classList.contains('dark')
  )

  const toggleTheme = () => {
    if (!dark) document.documentElement.classList.add('dark')
    else document.documentElement.classList.remove('dark')
    toggleDark(!dark)
  }

  return (
    <div
      className={`
    flex flex-col w-screen h-screen gap-8
    `}
    >
      <div>
        <button
          className="flex items-center justify-center w-10 h-10"
          onClick={() => toggleTheme()}
        >
          {dark ? <MoonIcon /> : <SunIcon />}
        </button>
      </div>
      <div className="flex items-center justify-center w-full h-full">
        {children}
      </div>
    </div>
  )
}
```

**Comment by skidding** [comment]
@FrancoRATOVOSON Everything looks good to me in your example. Maybe the dev server stopped building and is out of date due to some error I'm not seeing. I can investigate for you if you have a public repo that reproduces this issue.

**Comment by FrancoRATOVOSON** [comment]
@skidding here's the repos https://github.com/FrancoRATOVOSON/e-commerce/tree/shadcn-migration
It's not a production app, just to try technos, so sorry for the mess.
Everything is inside `packages/ui` on this branch.

**Comment by skidding** [comment]
@FrancoRATOVOSON You're using mismatching versions of Cosmos packages.

Make this change in your package.json:

<img width="503" alt="image" src="https://github.com/react-cosmos/react-cosmos/assets/250750/7ec919ea-24a5-4bc5-b4bc-b9b36ad85ffb">

Delete `.parcel-cache`, then restart Cosmos and your multi-fixture should look fine.

**Comment by FrancoRATOVOSON** [comment]
Worked perfectly fine 👌🏾 thanks
