### ISSUE TITLE
Getting "Waiting for renderer" - how troubleshoot

### ISSUE THREAD

**Issue by EdmundsEcho** [react-cosmos/react-cosmos#1623]
### What's wrong?

I can see the list of fixtures.  When I click on any one of them, I get a "waiting for renderer" message.

### Useful info

- Cosmos version.
    "react-cosmos": "^6.0.3",
    "react-cosmos-plugin-webpack": "^6.0.3",
    "react-cosmos-redux": "^2.0.0",

- Cosmos config.
```json
{
  "port": 8989,
  "staticPath": "public",
  "watchDirs": ["src"],
  "webpack": {
    "configPath": "react-scripts/config/webpack.config",
    "includeHashInOutputFilename": true
  },
  "globalImports": [
    "src/assets/index.css",
    "src/assets/dashboard.css",
    "src/assets/fonts.css"
  ],
  "$schema": "http://json.schemastore.org/cosmos-config"
}
```
- Server terminal output.
None (other than the visit me on port ... message.

- Browser console output.
No messages.

### Additional context

I had everything working prior to upgrading cosmos to the latest version. 

I'm getting a 304 response from the GET request: http://localhost:8989/playground.bundle.js

Thank you for any help on how to troubleshoot the issue.

Add any other context about the problem.

**Comment by ovidiuch** [comment]
Hi @EdmundsEcho,

What was the previous version of Cosmos that worked for you?

**Comment by ovidiuch** [comment]
`react-cosmos-redux` hasn't been updated in 4 years and I don't think it will work with React Cosmos 6. See if removing it fixes your problem. Let me know and I can help you replace it with a solution that works with the latest Cosmos.

**Comment by ovidiuch** [comment]
Just realized the main problem with your config: `react-cosmos-plugin-webpack` isn't added to the `plugins` list.

Please follow the migration guide: https://reactcosmos.org/docs/migration-guide

**Comment by EdmundsEcho** [comment]
Thank you.
