### ISSUE TITLE
tsconfig and custom paths.

### ISSUE THREAD

**Issue by PiTiLeZarD** [react-cosmos/react-cosmos#1656]
I'm having an issue with tsconfigs and paths. I understand my situation is weird so if I'm pushing it, just tell me I'll remove this report.

It used to work fine, I'm changing it, all the things work except cosmos. I'm using vite. I'm adding nestjs at the moment.

What I used to have:
 - vite/cosmos
 - tsconfig.json with `"references": [{ "path": "./tsconfig.vite.json" }],` and
```
        "baseUrl": ".",
        "paths": {
            "@frontend/*": ["src/frontend/*"]
        }
```
 - ./tsconfig.vite.json has `"include": ["vite.config.mts"]` in there

What that allowed me to do was exporting apps with vite, running cosmos, importing from `@frontend/ui/mycomponent` everything was working great. 

I'm now adding nestjs. So what I have is:
 - vite/cosmos and nestjs
 - src/frontend/tsconfig.json with
```
        "baseUrl": "../..",
        "paths": {
            "@frontend/*": ["src/frontend/*"]
        }
```
 - src/node/tsconfig.json with
```
        "baseUrl": "../..",
        "paths": {
            "@node/*": ["src/node/*"]
        }
```
 - tsconfig.json with
```
{
    "extends": "./src/frontend/tsconfig.json",
    "include": ["src"],
    "references": [{ "path": "./tsconfig.vite.json" }],
    "exclude": ["./src/node", "./dist/**/*"]
}
```
 - and tsconfig.nestjs.json with
```
{
    "extends": "./src/node/tsconfig.json",
    "exclude": ["./src/frontend", "./dist/**/*", "./src/main.*"]
}
```

This way everything is nice and separated, I can configure nestjs to use the right tsconfig, vscode uses the right one as well based on the folder. Vite is fine too to export. Typescript is happy as well.

**The only thing I'm struggling with** is that cosmos doesn't pick up the `@frontend` anymore and I cannot figure out why :/ I've spent a couple of hours on this one, so I might need to take a breather and come back to it but if you have a pointer, I'll gratefully receive it. Please and thank you ;)

**Comment by PiTiLeZarD** [comment]
Ok I needed sleep, the only thing fixing this was to specify the vite config path in the cosmos config:

```
{
    "$schema": "http://json.schemastore.org/cosmos-config",
    "port": 19000,
    "plugins": ["react-cosmos-plugin-vite", "react-cosmos-plugin-boolean-input"],
    "vite": {
        "port": 19100,
        "configPath": "./vite.config.mts"
    },
    "ignore": ["./src/node"],
    "watchDirs": ["./src/frontend"]
}

```

Tell me if you want me to delete this?

**Comment by ovidiuch** [comment]
@PiTiLeZarD Glad you figured it out and thanks for posting the solution.
