### ISSUE TITLE
Upgrade dependencies to latest versions, in particular express to 4.21.2 ?

### ISSUE THREAD

**Issue by oponder** [react-cosmos/react-cosmos#1664]
### What's wrong?

There are some known security issues with express 4.19.2

### Steps to reproduce

1.  clone repo
2.  `npm audit`
      ```19 vulnerabilities (3 low, 6 moderate, 10 high)```
4.  see errors

### Useful info

- Cosmos version: main @ 8026efa

### Additional context

I'm not sure if this is just an easy fix, I wasn't fully understanding where the express dependency is coming from as it is not in package.json, but somehow ends up in package.lock

Thank you!

**Comment by ovidiuch** [comment]
@oponder Just published [v6.2.3](https://github.com/react-cosmos/react-cosmos/releases/tag/v6.2.3) with all dependencies upgraded to their latest minor version on the existing major version (I'll do more aggressive upgrades later), including `express` to `4.21.2` as mentioned in this issue.

The dependabot security warnings went from 32 to 1, and the remaining 1 is related to a `nextra` dev dependency that doesn't end up in the published Cosmos packages.
