### ISSUE TITLE
Problem loading fixtures

### ISSUE THREAD

**Issue by BrunoDF** [react-cosmos/react-cosmos#182]
Hey there!

I'm having some trouble loading fixtures im my project.

I have figured out a way to make it work, but wanted to check here if a
pull request would make sense, and discuss the change.

The project has the following structure:
![screen shot 2016-02-16 at 5 00 44 pm](https://cloud.githubusercontent.com/assets/3225834/13087412/e51e961c-d4ce-11e5-8d12-2b032295cead.png)

So, what I discovered is that in the **get-component-fixture-tree.js**,
there is a regex that checks if the path is actually a component path:

(LINE 27) `isComponent = /^\.\/(.+)\.jsx?$/,`

Taking the spinner component as example, the match returned is:
(LINE 37) `var componentName = match[1];`
**componentName === 'spinner/spinner'** (folder/filename)

So, the solution for now was to duplicate the fixture folder, so instead of:
**fixtures > spinner > default.js**
I have:
**fixtures > spinner > spinner> default.js**
This can be seen in the above screenshot.

I was thinking if it would make sense to change this regex to something
that would return just the component name or only the path, excluding the file name.

This way I think it would be good for projects with any kind of structure.

What do you think? Does this sounds right to you?
I have made this change and can send a pull request if agreed.

Regards

**Comment by rcbitencourt** [comment]
+1

**Comment by carloshpds** [comment]
+1 :+1:

**Comment by ovidiu-chereches-hs** [comment]
Hi @BrunoDF,

Grouping the component class with its style under a folder with the same name appears to be a common pattern, so I understand the problem. 

However, if we remove the namespace altogether, we'll run into another problem. Consider this scenario:

```
- components/dashboard/ProfilePic.jsx
- components/profile/ProfilePic.jsx
- components/Welcome.jsx

- fixtures/ProfilePic/default.js
- fixtures/ProfilePic/missing-image.js
```

You have two components named `ProfilePic` under different namespaces (which usually correspond to routes), also a common pattern. How would you separate fixtures for one component from the ones for the other?

**Comment by BrunoDF** [comment]
Hey, @ovidiu-chereches-hs,

You're right. I get what you're saying. 

Actually, thinking again, it makes sense having the 'spinner/spinner' pattern,
since it's a folder/file structure.

What brought me here was that it wasn't clear exactly why my fixtures weren't working.
My team also got kinda confused about it, and then I went to the code to understand what was going on.

Maybe just a note in the docs is enough.

**Comment by skidding** [comment]
Well the docs do show an [example of how the file structure works](https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.14#file-structure) and the fact that this can be overridden by adapting `get-component-fixture-tree.js` to your project. But it doesn't say how... which is probably the hardest part, since that file is embedded in the `cosmos-js` package, not in the boilerplate.

I think the best way here would be to make Cosmos configurable, by passing some optional RegExp objects or some callback functions. This would make it possible to configure the way [components](https://github.com/skidding/cosmos/blob/5e99788e2f1eb2907a7bcf965dfa372ec0098e56/src/get-component-fixture-tree.js#L31) and [fixtures](https://github.com/skidding/cosmos/blob/5e99788e2f1eb2907a7bcf965dfa372ec0098e56/src/get-component-fixture-tree.js#L54) are matched per project. What do you think?

**Comment by carloshpds** [comment]
That's good @skidding, Let's do it? @BrunoDF :)

**Comment by Diokuz** [comment]
+1

**Comment by TheSisb** [comment]
+1

**Comment by skidding** [comment]
Update: There's [a new CLI in town](https://github.com/react-cosmos/react-cosmos#webpack-cli) that hide a lot of the ugly config. This use case is not yet supported but I think the project is more modular and support for the nested file structure can be implemented without too much sweat. I'll provide hints to make it easy for anyone to get started:

The component path is [parsed](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-cosmos-webpack/src/build-module-paths.js#L38) like this 
```js
new RegExp(`^${componentsRootPath}/(.+).jsx?$`)
```
We could add a config flag like `componentsHaveOwnDir` that changes this to
```js
new RegExp(`^${componentsRootPath}/(.+)/(.+).jsx?$`)
```
This would turn `/path/to/components/dashboard/header/header.jsx` into
```
$0 /path/to/components/dashboard/header/header.jsx
$1 dashboard/header
$2 header
```
`${componentsRootPath}/$1` would be used to [search for fixtures](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-cosmos-webpack/src/build-module-paths.js#L50) inside component's own dir, and also `$1` (to include a possible namespace) for the component name (fixing the `spinner/spinner` issue @BrunoDF reported.

cc @carloshpds @catalinmiron

**Comment by skidding** [comment]
Support for nested component structure (like @BrunoDF was using when starting this thread) has been added in #237 and released under `react-cosmos-webpack2.0.0-beta2`.

Let me know if you try it out and/or have any problems with it. Thanks!
