### ISSUE TITLE
Redesign fixture to keep props separate from meta fields

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#217]
### Problem

Props are now root level fixture attributes. This means attrs like `state` or `reduxState` or other flags and modifiers that can power Proxies are "magic fields" next to props and you can't have props with those names. This wasn't a problem before Proxies because `state` was the only magic attr and it wasn't a common prop name anyway. The new Proxies might be interested in all sorts of attrs like `width`, `height` or `backgroundColor`, which would easily be in conflict with actual component props. 
### Solution

Have dedicated nesting for props inside fixture.

Current fixture format:

``` js
{
  fooProp: 'bar',
  state: {
    fooState: 'bar'
  },
  // meta data for Proxies. e.g. reduxState
}
```

Next fixture format:

``` js
{
  props: {
    fooProp: 'bar',
  },
  state: {
    fooState: 'bar'
  },
  // meta data for Proxies. e.g. reduxState
}
```

Also, remove component from fixture and send it as a separate prop to Proxies.

This is a small change but spans across many packages:
- [No longer attach component class to fixture in ComponentPlayground](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-component-playground/src/components/component-playground.jsx#L532)
- [Send component as separate prop to proxies in ComponentPlayground](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-component-playground/src/components/component-playground.jsx#L218-L225)
- [Use component proxy instead of fixture.component in PreviewLoader](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-cosmos/src/proxies/PreviewLoader.jsx#L11)
- [Use fixture.props instead mutated fixture in PreviewLoader](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-cosmos/src/proxies/PreviewLoader.jsx#L12-L14)
- [No longer mutate fixture in Redux proxy](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-cosmos-redux-proxy/src/index.jsx#L67-L69)
- [No longer mutate fixture in State proxy](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-cosmos/src/proxies/StateProxy.jsx#L97-L99)

This can be made backwards compatible by auto adding `fixture.props = clone(fixture)` when fixture `fixture.props` is missing ([here](https://github.com/react-cosmos/react-cosmos/blob/c3e023aec675079dfa952d5e391d521d745650c3/packages/react-cosmos/src/load-modules.js#L86-L95)).

**Comment by ovidiubute** [comment]
@skidding If I'm not mistaken, `children` is also a "magic field", correct?

**Comment by skidding** [comment]
[Indeed](https://facebook.github.io/react/docs/react-api.html#createelement). `children` used to be handled [differently](https://github.com/react-cosmos/react-cosmos/blob/9c4c843114777b0273cb55053af826ed397e315c/packages/react-component-tree/src/render.js#L22-L24), but is now [sent as a simple prop](https://github.com/react-cosmos/react-cosmos/blob/9c4c843114777b0273cb55053af826ed397e315c/packages/react-cosmos/src/components/proxies/PropsProxy.jsx#L15) via proxies. Might work either way but the right way is to separate `children` from `props` and use it properly as the 3rd arg of React.createElement in PropsProxy.

**Comment by jlc467** [comment]
This solution should make using fixtures more intuitive as well. New to fixtures, I took a glance at [the local-state example](https://github.com/react-cosmos/react-cosmos/blob/master/examples/local-state/components/CounterList/__fixtures__/oneTwoThree.js) and saw `state: { }` so assumed props was `props: { }`.

**Comment by skidding** [comment]
> This solution should make using fixtures more intuitive as well.

Agreed. I'm still for this 100%. I removed the `free for all` label because I believe it requires more thought, but if anybody is willing to pick it up and I'm more than happy to assist.

The key thing here is backwards compatibility. Changing hundreds of fixtures in existing projects is a pain. A codemod would be nice, but not enough. The easiest way I can think of to make this change while provide backwards compatibility is via a Proxy. E.g. a NormalizePropsProxy, applied before all other proxies, which looks for the `props` fixture attribute, and puts all root-level attrs in it if it doesn't exist (except for `state`, `context` and `reduxState` – this list could even be configurable).

@jlc467 wdyt?

**Comment by jlc467** [comment]
Since `2.0` is a major version, you are allowed to break the API, right? Code recipes for two upgrade paths (codemod or proxy) seems ample, with codemod being the preferred way (otherwise you have to maintain a list of proxies/magic attrs to exclude). Some fixtures won't have props on purpose, but I don't think that matters. That's all I can think of right now.

**Comment by skidding** [comment]
> Since 2.0 is a major version, you are allowed to break the API, right?

Right, but I want to avoid it as much as possible. People are already *fatigued* by JS tooling :).

> Code recipes for two upgrade paths (codemod or proxy) seems ample,

Agreed.

> with codemod being the preferred way (otherwise you have to maintain a list of proxies/magic attrs to exclude)

Amen. I started prefixing my proxy fields with `_` to avoid conflicts with props, which is not ideal.

@jlc467 would you be interested in working on this? It'd be sweet to include it in the `2.0` release.

**Comment by jlc467** [comment]
Sure...I'll take a crack at it this weekend. Never written a codemod before, or a proxy for that matter, so this will be a great exercise. I'll start with the fixture redesign first though, and see how it goes.

**Comment by skidding** [comment]
Awesome. You can find a few proxy examples in [here](https://github.com/skidding/illustrated-algorithms/tree/master/cosmos/proxies).

**Comment by skidding** [comment]
This was actually done a while back in #312!
