### ISSUE TITLE
"Cannot GET /" when access localhost:8989

### ISSUE THREAD

**Issue by xyx2011** [react-cosmos/react-cosmos#225]
after setup the cosmos in dev server, it compiled without error, but somehow when access localhost: 8989 I get blank page with text "Cannot GET /". I didn't do the customize config on port or path. what possibly could go wrong?

**Comment by skidding** [comment]
@xyx2011 did this happen in one of the examples from this repo or in your own project? Please provide more details or your code so we can get to the bottom of this. Thanks.

**Comment by BTMPL** [comment]
@skidding I'm running into the same issue. 

1. clone https://github.com/btmpl/react-hot-loader-example
2. `npm install`
3. `npm install react-cosmos-webpack`
4. create cosmos.config.js
5. `node_modules/.bin/cosmos`

When accessing localhost:8989 all I see is "Cannot GET /"

In the console I only see "Listening at ..." - no bundling etc. happens

**Comment by skidding** [comment]
> create cosmos.config.js

Can you please tell me what's inside the config?

**Comment by BTMPL** [comment]
I've copy&pasted the example from readme, so:

`module.exports = {
  componentPaths: ['src/components'],
};`

**Comment by skidding** [comment]
OK. I'll reproduce your steps & see what I find!

**Comment by skidding** [comment]
OK, I figured it out. It's because Cosmos doesn't know where to load the HTML from. Here are two solutions:

1. Set the `dist` as the public path and Cosmos will statically serve it and use the `index.html` inside
  ```diff
  module.exports = {
    componentPaths: ['src/components'], 
  +  publicPath: 'dist',
  };
  ```

2. Use [HTML Webpack Plugin](https://github.com/ampedandwired/html-webpack-plugin)

  `npm install html-webpack-plugin`
  ```diff
  +const HtmlWebpackPlugin = require('html-webpack-plugin');
  
  module.exports = {
    entry: [
      "webpack/hot/only-dev-server", // "only" stops HMR on syntax errors
      "react-hot-loader/patch", // make sure the HMR package is included
      "./src/index" // our application entry point
    ],
    output: {
      path: __dirname + "/dist",
      filename: 'bundle.js'
    },
    contentBase: "dist/",
    module: {
      loaders: [
        {
          test: /\.js$/,
          exclude: /(node_modules)/,
          loader: "babel-loader"
        },
        {
          test: /\.css$/,
          loader: "style-loader!css-loader"
        }
      ]
    },
  +  plugins: [
  +    new HtmlWebpackPlugin({
  +      template: 'dist/index.html',
  +    })
  +  ]
  }
  ```
  ```diff
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
    </head>
    <body>
      <div id="a"></div>
  -    <script src="bundle.js"></script>
    </body>
  </html>
  ```

Both solutions work and will yield this:
![cosmos](https://cloud.githubusercontent.com/assets/250750/20443981/e4f6c3de-add7-11e6-85de-7c829b574335.gif)

The problem is the HTML part is poorly documented. We need to make sure this doesn't happen to somebody else. Do you have any suggestions as to where this should be documented and how? Thanks.

**Comment by BTMPL** [comment]
Briliant! That solves my issue.

As for where to document it - if you aren't able to read the contentBase from webpack.conf.js it might be worth adding the line in the example cosmos.config.js in your README.md and add a not to make it the same as webpack.config.js or maybe in the [webpack example](https://github.com/react-cosmos/react-cosmos/blob/master/examples/flatris/webpack/cosmos.config.js) (as I now see it is explained in the full cosmos.config.js writeup).

**Comment by skidding** [comment]
> read the contentBase from webpack.conf.js

That's actually a good idea. Still needs documentation, but it will work out of the box for some of the users.

`contentBase` seems to be a webpack-dev-server setting and is used like this in the docs:
```
{
    devServer: {
        contentBase: "./build",
    }
}
```
Yet in your config `contentBase` is a root level property. Any idea why this works and did you find it documented somewhere?

**Comment by BTMPL** [comment]
Um, actually that might be an err on my side, as I still need to add --content-base=dist/ to my webpack-dev-server call - now I know why :)

devServer.contentBase is the correct key
