### ISSUE TITLE
Seems to break styles implemented with 'styled-components'

### ISSUE THREAD

**Issue by r24y** [react-cosmos/react-cosmos#226]
Real excited to start using Cosmos. I got it set up with my project, and it works, except for the styling which uses [`styled-components`](https://styled-components.com/). Inspecting the `<head>` tag in the Elements panel, I see all the CodeMirror injected styles, but not the ones generated by `styled-components`.

My setup is nearly an exact duplicate of the Browserify example. I realize that a full example would be useful in reproducing the bug; right now my example has proprietary code in it, so I'll come up with a minimum reproducing case soon.

**Comment by r24y** [comment]
Never mind. I'm an idiot. I injected some styles improperly into the `<head>` and ended up breaking everything.

**Comment by skidding** [comment]
@r24y glad to hear it worked out in the end. Let me know if you bump into any other roadblocks.
