### ISSUE TITLE
Make react-component-tree bundle smaller

### ISSUE THREAD

**Issue by flavius-tirnacop-hs** [react-cosmos/react-cosmos#235]
When using [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) on our project bundle the `react-component-tree` pulls the entire lodash and the result looks like this:
![image](https://cloud.githubusercontent.com/assets/13434505/20881278/47bcceb4-bae4-11e6-97d0-401bcc47c3bd.png)

We can shrink its size by using individual lodash packages like [lodash.omit](https://www.npmjs.com/package/lodash.omit)

**Comment by skidding** [comment]
Good idea. Already started [here](https://github.com/react-cosmos/react-cosmos/blob/1550d996303cbb8d7ce67784861709352f7100cb/packages/react-cosmos-utils/package.json#L12-L13), [here](https://github.com/react-cosmos/react-cosmos/blob/1550d996303cbb8d7ce67784861709352f7100cb/packages/react-cosmos/package.json#L13-L14) and [here](https://github.com/react-cosmos/react-cosmos/blob/8d5008a140f6610a075af2eea37d9f646cc9af03/packages/react-cosmos-redux-proxy/package.json#L13-Lundefined). Want to deal with the remaining?

**Comment by valentin-radulescu-hs** [comment]
💵
