### ISSUE TITLE
Need a standalone demo example

### ISSUE THREAD

**Issue by mocheng** [react-cosmos/react-cosmos#240]
This project `react-cosmos` looks really promising, but it already takes me one hour to set up first project but I didn't get it succeeded yet. The step-by-step tutorial doesn't mention about depended npm packages. Follow it and just get mysterious webpack errors. Then user like me have to consult to example code.  The `examples/context` must be the easiest example. However, the `package.json` file of `context` is not complete. The example project works just because there is a `node_modules` at the root of the repo. 

If there is a standalone demo example, it would helpful to newcomers.

**Comment by mocheng** [comment]
Finally I get it worked by downgrading webpack from `^2.1.0-beta.25` to `^1.13.2`.

**Comment by ovidiu-bute-hs** [comment]
@mocheng Webpack 2 is not stable yet, I wouldn't recommend using it until it's released.

**Comment by skidding** [comment]
Added standalone example in #301
