### ISSUE TITLE
Add the possibility of installing deps using yarn

### ISSUE THREAD

**Issue by ovidiubute** [react-cosmos/react-cosmos#245]
### Need
As a developer, I'd like to quickly install dependencies when developing `react-cosmos`, so that I can be more productive.

### Deliverables
- `yarn.lock` files for all packages, and top-level
- Modify the npm `install-react` task to use `yarn` if available

### Problems
- Lerna and Yarn don't play together... yet. There is however hope, as the code required measures about [two lines](https://github.com/motion/lerna/pull/4) and there is [active discussion](https://github.com/lerna/lerna/issues/371) around the topic.

**Comment by skidding** [comment]
I don't have experience with Yarn, but am behind this initiative if you can come up with an elegant workaround for Lerna.

Not sure what the implications are and it seems the [vision isn't clear](https://github.com/lerna/lerna/issues/371#issuecomment-265251561) either.
