### ISSUE TITLE
Fix eslint warning

### ISSUE THREAD

**Issue by ovidiubute** [react-cosmos/react-cosmos#246]
### Problem
- Console warning `The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.`

### Solution
- It looks like we can upgrade `eslint-config-airbnb` to version `12` to fix this. See issue [#978](https://github.com/airbnb/javascript/issues/978)

**Comment by skidding** [comment]
LGTM. The only downside is that v12 might come with additional changes that need to made throughout the codebase.
