### ISSUE TITLE
Add generic build npm task

### ISSUE THREAD

**Issue by ovidiubute** [react-cosmos/react-cosmos#247]
### Problem
- The list of npm targets is getting pretty big, and is unsustainable now that proxies are being added to `react-cosmos`. 
- The `build` target is error-prone since you need to call all of the above targets one by one

### Solution
- Have a generic `build:package` target that accepts CLI arguments and calls a separate script
- The script will call what `build-webpack` is calling, but instead of taking the argument from the environment, it will use the CLI argument
- The `build` target could also be a script that lists the packages and calls the `build:package` tasks one by one, eliminating the need to maintain it

**Comment by ovidiubute** [comment]
@skidding please review

**Comment by skidding** [comment]
> The build target is error-prone since you need to call all of the above targets one by one 

Good idea. I forgot to update this [long list](https://github.com/react-cosmos/react-cosmos/blob/7a90876a11ea257a122c2d25295c482abef2e30c/package.json#L23) more than once.

How would a targeted build command with the new script look? E.g. `npm run build:webpack` (used when working on a specific module)

**Comment by ovidiubute** [comment]
It would be something like `npm run build:package webpack`. Or, we could actually have `npm run build webpack` if the script checks its argument list and builds one package or all of them.

**Comment by skidding** [comment]
> Or, we could actually have npm run build webpack if the script checks its argument list and builds one package or all of them.

LGTM!
