### ISSUE TITLE
Playground welcome screen

### ISSUE THREAD

**Issue by ovidiubute** [react-cosmos/react-cosmos#252]
### Problem
When you open Playground, the component list on the left is loaded, but there is nothing on the right except a blank screen. This is not very inviting to new users.

### Solution
- Have a welcome panel that states briefly what you can do within Playground:
  - Browse and search through components and fixtures
  - Click the edit button to modify your fixtures in real time
  - Click the play button to return to this screen
- UI TBD

**Comment by skidding** [comment]
This would be a great addition, long overdue. I'd like to turn this welcome screen into a minimal onboarding flow, consisting of 3 possible states (more can be added later):
1. Playground has no components and no fixtures. Either a new project or some error in configuration. Here's a draft I wrote a while ago:

> Congratulations! You're on your way to designing beautiful components.

> It looks like you have no components. If you're just starting a new project, this is fine and I envy you. If this isn't a new project and your components aren't showing up, then your setup needs some tweaking. Try the following:
> - Adjust `componentPaths` in cosmos.config.js to match your file structure
> - Open up a GitHub issue and ask for help by sharing your config and file structure

2. Playground has components but no fixture created. The large majority of users land here. Instructions on how to create fixtures is the priority here. E.g.

> Your components are listed the left side. It looks like you haven't created fixtures for them yet. An empty fixture is available for each component, but chances are your components depend on one or more props to function.

> A fixture is a JSON-like object, except it contains functions and any other types components receive via props. 

> Here's a guide for getting started with fixtures:...

3. Playground has components and fixtures created. At this step we assume the user understands how React Cosmos works and can inform them of navigation, advanced features and maybe encourage them to contribute, etc.

Wdyt?

**Comment by ovidiubute** [comment]
SGTM

**Comment by skidding** [comment]
Closed via #273
