### ISSUE TITLE
Decouple file discovery from webpack package

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#268]
## Need

The module that looks inside the user's codebase and gathers component and fixture paths, based on `componentPaths` and `fixturePaths` options, needs to:

- Be used independently, e.g. for an integration with [React Tree Snapshot Testing](https://facebook.github.io/jest/blog/2016/07/27/jest-14.html)
- Support advanced matching, for monorepos like this one (more below)

## Solution

Deliver a new package (maybe called `react-cosmos-voyager` for fun), that "Explores your codebase to find component and fixture files." This would fix all file matching problems for good and make `react-cosmos-webpack` a 1st class citizen.

Here are the use cases supported by this package (also test cases):

### Relative fixtures

```js
componentPaths: ['components']
```

```bash
components/Foo.js
components/nested/Bar.jsx
components/__fixtures__/Foo/blank.js
components/__fixtures__/nested/Bar/one.js
components/__fixtures__/nested/Bar/two.js
```

```js
components: {
  Foo: 'components/Foo.js',
  'nested/Bar': 'components/nested/Bar.jsx'
}
fixtures: {
  Foo: {
    blank: 'components/__fixtures__/Foo/blank.js'
  }
  'nested/Bar': {
    one: 'components/__fixtures__/nested/Bar/one.js',
    two: 'components/__fixtures__/nested/Bar/two.js'
  }
}
```

### Relative fixtures, component dir

```js
componentPaths: ['components']
```

```bash
components/Foo/Foo.js
components/Foo/__fixtures__/blank.js
components/nested/Bar/Bar.jsx
components/nested/Bar/__fixtures__/one.js
components/nested/Bar/__fixtures__/two.js
```

```js
components: {
  Foo: 'components/Foo/Foo.js',
  'nested/Bar': 'components/nested/Bar/Bar.jsx'
}
fixtures: {
  Foo: {
    blank: 'components/Foo/__fixtures__/blank.js'
  }
  'nested/Bar': {
    one: 'components/nested/Bar/__fixtures__/one.js',
    two: 'components/nested/Bar/__fixtures__/two.js'
  }
}
```

### External fixtures

```js
componentPaths: ['components']
fixturePaths: ['fixtures']
```

```bash
components/Foo.js
components/nested/Bar.jsx
fixtures/Foo/blank.js
fixtures/nested/Bar/one.js
fixtures/nested/Bar/two.js
```

```js
components: {
  Foo: 'components/Foo.js',
  'nested/Bar': 'components/nested/Bar.jsx'
}
fixtures: {
  Foo: {
    blank: 'fixtures/Foo/blank.js'
  }
  'nested/Bar': {
    one: 'fixtures/Bar/one.js',
    two: 'fixtures/Bar/two.js'
  }
}
```

### Separate packages

```js
componentPaths: [
  'packages/Foo/src/index.js',
  'packages/nested/Bar/src/index.jsx',
],
getComponentName: componentPath =>
  componentPath.match(/packages/(.+)/src/index/)[1],

```

```bash
packages/Foo/src/index.js
packages/Foo/src/__fixtures__/blank.js
packages/nested/Bar/src/index.jsx
packages/nested/Bar/src/__fixtures__/one.js
packages/nested/Bar/src/__fixtures__/two.js
```

```js
components: {
  Foo: 'packages/Foo/src/index.js',
  'nested/Bar': 'packages/nested/Bar/src/index.jsx'
}
fixtures: {
  Foo: {
    blank: 'packages/Foo/src/__fixtures__/blank.js'
  }
  'nested/Bar': {
    one: 'packages/nested/Bar/src/__fixtures__/one.js',
    two: 'packages/nested/Bar/src/__fixtures__/two.js'
  }
}
```

### Separate packages, external fixtures

```js
componentPaths: [
  'packages/Foo/src/index.js',
  'packages/nested/Bar/src/index.jsx',
],
fixturePaths: ['fixtures']
getComponentName: componentPath =>
  componentPath.match(/packages/(.+)/src/index/)[1],

```

```bash
packages/Foo/src/index.js
packages/nested/Bar/src/index.jsx
fixtures/Foo/blank.js
fixtures/nested/Bar/one.js
fixtures/nested/Bar/two.js
```

```js
components: {
  Foo: 'packages/Foo/src/index.js',
  'nested/Bar': 'packages/nested/Bar/src/index.jsx'
}
fixtures: {
  Foo: {
    blank: 'fixtures/Foo/blank.js'
  }
  'nested/Bar': {
    one: 'fixtures/nested/Bar/one.js',
    two: 'fixtures/nested/Bar/two.js'
  }
}
```

@ovidiubute @RadValentin @flaviusone @catalinmiron would this cover all your use cases? (hs-components, web-ui & insights)

**Comment by ovidiubute** [comment]
Does ignoring paths still work? We have Redux associated files under `components`, along with actual components. Right now there's a field that allows us to ignore those files (I forget the name of the field), is that going away?

**Comment by skidding** [comment]
> Does ignoring paths still work?

Yes, forgot to add it in the initial spec.

> Right now there's a field that allows us to ignore those files (I forget the name of the field), is that going away?

The field is just `ignore`, a list of regular expressions. It stays the same.

You can see the use cases supported better in the [test file](https://github.com/react-cosmos/react-cosmos/blob/654f27ec96c14888b67641d95257d20475a64650/packages/react-cosmos-voyager/src/__tests__/index.js). There's even a [test that resembles to hs-components structure](https://github.com/react-cosmos/react-cosmos/blob/654f27ec96c14888b67641d95257d20475a64650/packages/react-cosmos-voyager/src/__tests__/index.js#L144-L156)

**Comment by ovidiubute** [comment]
Yup, the list of Regexes is the one we're using. All good 😄

**Comment by skidding** [comment]
@ovidiubute wasn't aware you're using the `react-cosmos-webpack` package for Insights. any complaints? :)

**Comment by ovidiubute** [comment]
Sure, we integrated it right around the 1.0.0-beta release. The only issue I could find is sometimes the CSS is not hot reloaded. I didn't have time to investigate what's going on, so I don't know if it's a problem with the Playground or just the project setup.

Other than that, it would be awesome to mock the backend requests, like I explained in issue #253, because right now you can't test certain components end-to-end.

**Comment by skidding** [comment]
Would you be interested in Jest snapshot testing? This what I'm trying to accomplish. The idea is to add a single test with a call to a cosmos package inside a Jest test, and you automatically get a test suite for all components/fixtures. Like Mugshot, but comparing html markup instead of pixels.

**Comment by ovidiubute** [comment]
How would it work? Would you run a CLI to generate the snapshots and tests and update them later on?

**Comment by skidding** [comment]
You'd have to install Jest and run the Just CLI on a test file. The test file would do something like

```js
import testSnapshots from 'react-cosmos-snapshot';

testSnapshots({
  config: '/path/to/cosmos.config.js'
});
```

What `react-cosmos-snapshot` would do is iterate through all your component/fixtures and do a test, knowing it's inside the Jest environment:

```js
import renderer from 'react-test-renderer';
import { createElement } from 'react-cosmos';

// for each component/fixture
test(`Render ${component}/${fixture}`, () => {
  const tree = renderer.create(
    createElement(component, fixture)
  ).toJSON();
  expect(tree).toMatchSnapshot();
});
```

> generate the snapshots and tests and update them later on?

Yes, Jest has built-in mechanism for this. It will use the `__snapshots__` folder by default.

**Comment by ovidiubute** [comment]
LGTM, it would have the advantage of being faster than any UI integration testing tool could ever be. I'm a bit worried that you can become totally dependent on the snapshot, to the point of not writing any tests and just checking the component that it always renders the same, but I'd still like to try it out.

**Comment by skidding** [comment]
> I'm a bit worried that you can become totally dependent on the snapshot, to the point of not writing any tests and just checking the component that it always renders the same, but I'd still like to try it out.

That's up to the developer's will :)

I'm looking forward to use it on pet projects where I don't have time or it's too early to unit test components, like [illustrated-algorithms](https://github.com/skidding/illustrated-algorithms). Would give me extra confidence to make changes after taking a break and defamiliarizing myself with the repo.

**Comment by ovidiubute** [comment]
Interestingly enough almost all of the components in [ant.design](https://ant.design) are tested this way. That's a pretty big library so it's certainly feasible.
