### ISSUE TITLE
Isolate and no longer import config in client bundle

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#272]
#### What's up?

Three reasons for this:

- We need a modular way to read the cosmos config for the Jest snapshot integration
- So far the config file has been "universal" (loaded on the server as well as client side). It seemed like a good idea, but this restricts us from doing any fs operations in the config (lest the client bundle explode). Thus we should select the settings that are client facing, serialize and inject them into the client bundle using webpack DefinePlugin. `proxies` is the only client-facing setting that can't be serialized, but we can go around this by moving the Proxy code outside of configs and only keeping proxy file paths in config/proxies
- Support package paths in `globalImports` (e.g. `babel-polyfill`)

#### Mkay, tell me more

Here's how proxies will be configured:

```js
// .cosmos.config.js
proxies: [
  'react-cosmos-no-options-proxy',
  './custom-proxy.js'
]
```
```js
// .custom-proxy.js
import configurableProxy from 'react-cosmos-conf-proxy';

export default function() {
  return configurableProxy({
    myOption: 3,
    myOtherOption: require('./foobar.js')
  });
}
```

Moreover, there will be a new `react-cosmos-config` package, used like this:

```js
import getCosmosConfig from 'react-cosmos-config';

const cosmosConfig = getCosmosConfig({
  // optional
  configPath: './custom/cosmos/config/path.js'
});
```

This package will:

- [x] Load the config path, default to `CWD/cosmos.config.js`
- [x] Resolve `componentPaths` and `fixturePaths` to absolute paths
- [x] Resolve `globalImports` to absolute paths (or package paths, e.g. `babel-polyfill`)
- [x] Resolve `webpackConfigPath` to absolute path (default to `webpack.config.js` first)
- [x] Resolve `publicPath`
- [x] Provide other defaults for the rest of the options (e.g. enable `hot` and `hmrPlugin`)

**Comment by skidding** [comment]
@ovidiubute one last stop before Jest snapshotting, would appreciate your thoughts as well.

**Comment by ovidiubute** [comment]
I can see why this is needed, good call. Just a thought: the impact on the end users needs to be minimal, in order to speed up the migration from 1.0 to 2.0, so this needs to handled carefully.
