### ISSUE TITLE
Simplify project tagline

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#280]
### What's up?

`truly encapsulated` feels superfluous and doesn't speak about the problem we're trying to solve. Encapsulation is a solution not a problem/need. 

### Mkay, tell me more...

`reusable` is the main reason behind encapsulation and seems like a good replacement. E.g.

```diff
-DX tool for designing truly encapsulated React components
+DX tool for designing reusable React components
```

@catalinmiron @flaviusone @ovidiubute @RadValentin wdyt?

**Comment by valentin-radulescu-hs** [comment]
I'd go as far as even removing the `reusable` part as I feel it's the `designing` part that should stand out. Either way I think it's worthwhile improvement 👍

**Comment by skidding** [comment]
I see your point. Still leaning on keeping the `reusable` since it's part of the philosophy (defining input via fixtures makes you think of components outside of their parent context).

**Comment by ovidiubute** [comment]
`reusable` basically means `pure` in functional terms, which is the hallmark of this project, in my opinion. LGTM from me to make the change 👍
