### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#282]
### What's up?

Getting a blank page after you remove or rename a fixture is annoying.

### Mkay, tell me more...

CP should check whether the component and fixture paths are valid and if not render a new 404 screen, similar to [how the welcome screen is shown](https://github.com/react-cosmos/react-cosmos/blob/ed8ef3e09645cd69d0086339ea6e169294bd4aef/packages/react-component-playground/src/components/component-playground.jsx#L197). Would look great on the new space bg @RadValentin created.

E.g.

> Invalid coordinates
> No astronomical object found at ${COMPONENT}:${FIXTURE}

**Comment by ganderzz** [comment]
@skidding If no one is opposed, I'll try my hand at this. 😄

**Comment by skidding** [comment]
It's all you @ganderzz!

**Comment by skidding** [comment]
Thank you @ganderzz! This has been a long time pain, especially when switching between projects.
