### ISSUE TITLE
Cosmos + React Boilerplate

### ISSUE THREAD

**Issue by newswim** [react-cosmos/react-cosmos#296]
Has anyone sucessfully used Cosmos with [React Boilerplate](https://www.reactboilerplate.com/)?

I've been trying to the past 3 hours and hit one roadblock after another. Just curious if anyone else has tried and had any luck, thanks.

**Comment by skidding** [comment]
Hi @newswim. I personally haven't, but am happy to help you get past those roadblocks and maybe improve on what created them in the first place. What sort of trouble did you run into and at what step?

PS. Make sure you're using the latest release (`2.0.0-beta.8`)

**Comment by newswim** [comment]
Hey @skidding, I've started a [fork](https://github.com/newswim/react-boilerplate) of react-boilerplate with a [feature/cosmos](https://github.com/newswim/react-boilerplate/tree/feature/cosmos) branch. The best way to install is with `yarn install` (there are some issues with running npm setup, though that's another thing...).

If you run `npm run cosmos` or `yarnpkg cosmos`, you'll notice the following error:

```
Uncaught ReferenceError: reactBoilerplateDeps is not defined
    at eval (eval at 2 (bundle.js:4125), <anonymous>:1:18)
    at Object.2 (bundle.js:4125)
    at __webpack_require__ (bundle.js:1299)
    at fn (bundle.js:720)
    at eval (eval at 4 (bundle.js:4162), <anonymous>:1:19)
    at Object.4 (bundle.js:4162)
    at __webpack_require__ (bundle.js:1299)
    at fn (bundle.js:720)
    at eval (eval at ./node_modules/webpack-hot-middleware/client.js?reload=true (bundle.js:4020), <anonymous>:193:60)
    at Object../node_modules/webpack-hot-middleware/client.js?reload=true (bundle.js:4020)
```

It's likely that this is coming from the [DLLPlugin](https://github.com/carteb/carte-blanche/issues/386), which can be gotten around by removing [these lines](https://github.com/newswim/react-boilerplate/blob/feature/cosmos/package.json#L168-L184).

If you do that, and then run `npm run cosmos` again, you get a very interesting error stemming from `node_modules/react-cosmos-webpack/lib/entry.js`

```
8020:56 Uncaught SyntaxError: missing ) after argument list
    at Object../node_modules/react-cosmos-webpack/lib/entry.js (bundle.js:4310)
    at __webpack_require__ (bundle.js:1299)
    at fn (bundle.js:720)
    at Object.1 (bundle.js:6452)
    at __webpack_require__ (bundle.js:1299)
    at ./app/components/A \.jsx?$ (bundle.js:1351)
    at bundle.js:1354
```

This is the code, which doesn't appear to have the syntax error, but this _might be_ something with the compiled code..

```javascript
// react-cosmos-webpack/lib/entry.js [54-59]
if (module.hot) {
  module.hot.accept('./user-modules', function () {
    start();
  });
}
```

Comment that out, and you get a new error from Sagas which is complaining about not having access to the Regenerator runtime..

```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (eval at ./app/containers/HomePage/sagas.js (bundle.js:1956), <anonymous>:12:42)
    at Object../app/containers/HomePage/sagas.js (bundle.js:1956)
    at __webpack_require__ (bundle.js:1299)
    at fn (bundle.js:720)
    at getUserModules (eval at ./node_modules/react-cosmos-webpack/lib/user-modules.js (bundle.js:4318), <anonymous>:19:4303)
    at start (eval at ./node_modules/react-cosmos-webpack/lib/entry.js (bundle.js:4310), <anonymous>:33:25)
    at eval (eval at ./node_modules/react-cosmos-webpack/lib/entry.js (bundle.js:4310), <anonymous>:53:1)
    at Object../node_modules/react-cosmos-webpack/lib/entry.js (bundle.js:4310)
    at __webpack_require__ (bundle.js:1299)
    at fn (bundle.js:720)
```

If you look at that you'll see a generator function, and this is where my eyes start getting really tired. Also, I'm very new to Webpack, so I'm not in a place to make guesses, but I think there needs to maybe be a hook before cosmos starts to make sure webpack is transforming generators?

/shrug

**Comment by newswim** [comment]
Progress! Added `import regeneratorRuntime from "regenerator-runtime";` to the sagas.js file in `containers/HomePage` -- Now Cosmos is loading!

.. just none of the components load 🤦‍♂️ 

Getting a lot of errors about stateProxy. I'll have to pick this up tomorrow..
```
`Warning: Failed prop type: The prop `component` is marked as required in `StateProxy`, but its value is `undefined`.
```

**Comment by skidding** [comment]
Hi @newswim,

Sorry to hear you lost so much time with this. Webpack projects can get hairy!

I managed to make it work! 💡 

- I skipped the DLL plugin to save some time and because you found a temporary workaround
- The parsing errors was due to the hmr plugin being applied twice, adding `hmrPlugin: false` to cosmos config fixes this
- Then Cosmos was detecting too many component files, so I improved on that by globbing component paths by hand (need to install `glob`)

Here's my latest config
```js
const glob = require('glob');

const components = glob.sync('app/components/**/index.js');
const containers = glob.sync('app/containers/**/index.js');

module.exports = {
  componentPaths: components.concat(containers),
  getComponentName: (componentPath) =>
    componentPath.match(/app\/(?:components|containers)\/(.+)\/index.js$/)[1],
  ignore: ['tests'],
  webpackConfigPath: './internals/webpack/webpack.dev.babel',
  hmrPlugin: false
};

```

Which looks like this 🎉 
![image](https://cloud.githubusercontent.com/assets/250750/23358074/2be6849a-fce9-11e6-8ca2-00126592b6e6.png)

Next stop: fixtures! 🚌

**Comment by newswim** [comment]
Cool!!!!!

That looks like a much more stable workaround, the components did actually load after exposing the Regenerator runtime to that sagas file, but no props or anything see: no fixtures. I'll work on adding some since it would be really nice to have a functioning Cosmos+React-Boilerplate put together.

**Comment by skidding** [comment]
Right on. Let me know if there's else blocking you in the future.

Also, if you manage to get to the bottom of that DLLPlugin thing, I'd very curious to hear about it.

**Comment by skidding** [comment]
Now that I think of it, the DLLPlugin issue might be related to @reinei's [comment](https://github.com/react-cosmos/react-cosmos/issues/297#issuecomment-284510403) from a different issue, which might be fixed if we go back to using the user's index.html for the playground frame as well.

**Comment by newswim** [comment]
Interesting 🤔

**Comment by DJTB** [comment]
FYI: @skidding I'm using your config above, with your PR (1849) from RBP and the webpack 3 PR (1823) and everything is going great so far :+1:

**Comment by skidding** [comment]
@DJTB great! Looking forward to see https://github.com/react-boilerplate/react-boilerplate/pull/1849 merged so I can feature React Boilerplate next to the other [popular integrations](https://github.com/react-cosmos/react-cosmos#integration-with-popular-tools).

**Comment by skidding** [comment]
The PR was merged, but it's still on the `dev` branch. As soon as it hits master, a Cosmos config like this should do the trick:

```
module.exports = {
  componentPaths: ['app/components'],
  ignore: ['tests', 'messages', /.+Styles/],
  webpackConfigPath: './internals/webpack/webpack.dev.babel',
};
```

**Comment by newswim** [comment]
Awesome!! Thank you, can't wait to try it out.

**Comment by skidding** [comment]
RB 3.5 was released and it works as expected. Just pulled their master and followed these steps:

![image](https://user-images.githubusercontent.com/250750/30786062-5b232e76-a170-11e7-8e5b-f658defe37aa.png)
![image](https://user-images.githubusercontent.com/250750/30786066-61bd5342-a170-11e7-8623-6e53e5d139d7.png)
![image](https://user-images.githubusercontent.com/250750/30786071-66925aa2-a170-11e7-8f9f-262f132e195d.png)

And voila!
![image](https://user-images.githubusercontent.com/250750/30786072-75daa0a0-a170-11e7-926e-cf7caedd207b.png)
