### ISSUE TITLE
Improve publicPath

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#297]
### What's up?

`publicPath` currently maps a static dir to the `/loader/` path (which is `/` as far as the user bundle is concerned). This works for some, but a common pattern is to map the static folder to a path other than `/`, like `/static/`), which means `publicPath` should maybe become a dict, like:

```js
publicPath: {
  '/static/': '/path/to/static/files/'
}
```

### Mkay, tell me more...

This is going to make sense after #284 is merged. Exporting needs to be taken into account fully in this issue.

TODO: Provide more context

**Comment by reinei** [comment]
Another suggestion from my side would be to somehow check (maybe hasOwnKey?) if the webpack-dev-middleware can serve an index.html and rewrite requests to that address instead of serving your own static index.html .

In my use case I have 3 bundled files to serve and am using WebpackHtmlPlugin as well as the AddAsset plugin to build a nice index.html to load all required files in the required order, however simply executing ```npm run cosmos``` will serve the static index.html and thus fail due to my main bundle not containing the react libs (they are in a special vendor.dll chunk).

So I currently rigged my local copy of the server.js file to serve my own copy of index.html from the memory-fs instance, but as anyone can guess, this is a bad solution due to using private properties of the dev-middleware and requiring modification of files inside node_modules.

**Comment by skidding** [comment]
Let's see if I got this straight. You have an `index.html` in your publicPath, which serves as a template for `html-webpack-plugin`. Normally, webpack would use the `index.html` generated by the `html-webpack-plugin` but Cosmos instead uses the `index.html` template from your publicPath. Is this right?

**Comment by reinei** [comment]
Not quite,
I have the following Plugin stack:
```
DllReferencePlugin(s)
WebpackHtmlPlugin (using src/index.ejs and outputting to index.html in output dir)
AddAssetPlugin (to add the required dll files)
```

now my `src/index.ejs` is pretty simple and looks like:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
    <div id="main">
    </div>
  </body>
</html>
```

Its just there so I can deploy with my bundle instantly (my app renders into #main)

Now my problem comes from cosmos mounting the webpack-dev-middleware into /loader and serving its own static index.html which (obviously) does not include my dll files and thus has no react loaded.

I currently work around this by hacking the server.js by commenting out the index.html route and adding
```js
app.get('*', function(req, res){
    res.write(middleware.fileSystem.data['index.html']);
    res.end();
  });
```
With `middleware` being the instance of webpack-dev-middleware

**Comment by skidding** [comment]
I'm on vacation so I apologize for not being more through. This thing stood out:

> Now my problem comes from cosmos mounting the webpack-dev-middleware into /loader and **serving its own static index.html**

Cosmos doesn't have a dedicated index.html for the /loader path. It either
1. uses the index.html generated by html-webpack-plugin, which should be identical with the one generated in your own build
2. serves the index.html found in the public path (but I don't see why you'd have an index.html in your public path since you already use `src/index.ejs`

Which option do you think you fall into? Or more concretely, is there an `index.html` file in your public path?

**Comment by reinei** [comment]
I should fall into the first category (and I kinda do), however [this line](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-webpack/src/server.js#L62) in combination with line 65 & 66 result in cosmos serving its own index.html for the `/` path.

I was now supporting this cause in order to change line 67 to (somehow, thats up to you guys) not mount the middleware at `/loader/` but at my public path (which I could then change to `/` and circumvent your static index.html from ever being served)

**Comment by skidding** [comment]
It seems like you want your index.html for the playground frame. So / loads
the playground and /loader/ loads you components. The idea is that you
shouldn't need your own index for the playground frame, because it doesn't
render user components. The problem is, however, that the playground does
load user fixtures (for the editor), which is essentially user code and can
import anything from the user codebase. I wasn't sure if this would ever
cause problems, but it seems to de so in your case.

In the past we'd use the same index.html for both the playground and the
loader, but that also comes with a few problems. You might end up loading
unnecessary things in the playground frame and you need to know where to
render the playground in the user's index.html file.

Not sure how to fix this situation elegantly. Any further insights
appreciated!

On Mar 6, 2017 21:26, "reinei" <notifications@github.com> wrote:

I should fall into the first category (and I kinda do), however this line
<https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-webpack/src/server.js#L62>
in combination with line 65 & 66 result in cosmos serving its own
index.html for the / path.

I was now supporting this cause in order to change line 67 to (somehow,
thats up to you guys) not mount the middleware at /loader/ but at my public
path (which I could then change to / and circumvent your static index.html
from ever being served)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/react-cosmos/react-cosmos/issues/297#issuecomment-284521318>,
or mute the thread

**Comment by reinei** [comment]
Well as a side note: serving my own index.html works incredibly well for the playground and as far as I can tell the extra <div> is harmless

**Comment by skidding** [comment]
@reinei since this is a [recurring theme](https://github.com/react-cosmos/react-cosmos/issues/296), I'm considering a refactor to use the user's index.html for the playground frame as well, to include in the upcoming 2.0 release. Say we were to go down this route, how would you go about it?

Minor issue: user's favicon would be used instead of the React Cosmos one.

**Comment by skidding** [comment]
Update: The purpose of this issue is to ensure that static assets are accessible inside the Cosmos playground as they are in development. Here are two popular scenarios that we're going to test against:

1. Create React App: Public URL [is](https://github.com/facebookincubator/create-react-app/blob/e12d053c273037c5ec75971ddcd117b3e9858cdf/packages/react-scripts/config/webpack.config.dev.js#L31) equal to root path, so `/foo-asset.svg` will be a sibling of `/index.html` (WDS.contentBase is set to public dir and `process.env.PUBLIC_URL` will always be `''` in dev)
1. Next.js: Public URL [is](https://github.com/zeit/next.js/tree/6d572ee0871072a505f4fc929e555ff567453937#static-file-serving-eg-images) different than root path, so `/static/foo-asset.svg` will not be a sibling of `/index.html`. 

Current conclusions: 
- Because `/static/*` is hardcoded in Next.js, we need a `publicUrl` config option
- Because of CRA, the Loader index.js needs to be served from `${publicUrl}/index.html`
