### ISSUE TITLE
componentPaths cannot have a folder with a `index.js` in it

### ISSUE THREAD

**Issue by mocheng** [react-cosmos/react-cosmos#298]
### What's up?

I happened to put one folder with `index.js` in `componentPaths`. The `cosmos.config.js` is like below.

```
module.exports = {
  componentPaths: [
      'src/components/Home'
  ]
};
```

The `src/components/Home` folder has one `index.js` file in it. After launching cosmos, it fails with error message 
>ERROR in ./~/react-cosmos-webpack/lib/user-modules.js
Module build failed: Error: Must implement getComponentName when using exact file paths in componentPaths

I dug into the code and found [this line](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-voyager/src/index.js#L56) throws the Error. It turns out that [`react-cosmos-config`](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-config/src/index.js#L7) utilizes `resolveFrom` to normalize component path. The npm `resolveFrom` returns path with `index.js` if there is `index.js` in given folder, which make `react-cosmos-voyager` think it is exact file paths.

IMHO, `componentPaths` should allow existence of `index.js` without requiring `getComponentName`.

### Mkay, tell me more...

There is no documentation about `getComponentName` found.

**Comment by skidding** [comment]
Hey, I'd like to understand your use case before coming up with a solution.

- Do you have more than one component inside `src/components/Home`?
- Is `src/components/Home/index.js` a component?

**Comment by mocheng** [comment]
@skidding I'm organizing code in feature-based way similar to [ducks](https://github.com/erikras/ducks-modular-redux), which means Redux reducers, actions and React components of same feature in same folder.

> Do you have more than one component inside src/components/Home?

Yes, there are more than one component inside. And, there is a `index.js` file that is not actually not React component.

> Is src/components/Home/index.js a component?

No, `src/components/Home/index.js` is not a React component. It is just imports all reducers, actions and React component; and export them. So, it basically is public API for given feature.

**Comment by mocheng** [comment]
@skidding Since we have `getComponentName`, it seems that, in my case, it would be better to specify `compoentPaths` to be exact file paths aside with `getComponentName` definition. Documentation on `getComponentName` would be helpful for other users.
