### ISSUE TITLE
Move conversation from Gitter with Slack

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#306]
### What's up?

Most people already have Slack installed and the engagement is nicer.

### Mkay, tell me more...

@flaviusone created the `react-cosmos` team and I created a Slackin instance at [join-react-cosmos.now.sh](https://join-react-cosmos.now.sh/)

TODO:
- [x] ~~Find Slack badge~~ [![Slack](https://join-react-cosmos.now.sh/badge.svg)](https://join-react-cosmos.now.sh/)
- [x] Replace Gitter badge with Slack badge in README
- [x] Announce on [Gitter](https://gitter.im/skidding/cosmos) that we moved to Slack

**Comment by sapegin** [comment]
The problem with Slack is that you have to register again for each new project ;-|

**Comment by flaviusone** [comment]
I would also have something written in the Readme like [Babel does](https://github.com/babel/babel#looking-for-support)

**Comment by skidding** [comment]
@sapegin I'm not completely happy with Slack, but most people I've talked to preferred it and most devs already have the client installed on their devices.
