### ISSUE TITLE
Use user index.html for playground frame

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#313]
Spin off of #297 

### What's up?

The Component Playground has two frames, the playground frame (menu, left nav, fixture editor) and the loader frame (loaded component). Right now the loader frame uses the user's index.html (as [per docs](https://github.com/react-cosmos/react-cosmos#configuring-indexhtml)), and the playground frame uses a [basic index.html](https://github.com/react-cosmos/react-cosmos/blob/c3ff73fd47a56c4ebb1314ace41aab4587cebb71/packages/react-cosmos-webpack/src/static/index.html) embedded in react-cosmos-webpack.

This works well in theory, since the playground is decoupled from the user code, except there's a catch. The playground loads the user fixtures, which can (and often do) import other user modules. This isn't a problem, until you start adding vendor script tags directly in your index.html, or use DllPlugin to split your code into multiple bundles.

Concrete example:
- Add a separate script tag for the lodash lib, loaded from CDN.
- Use webpack externals to map `window.lodash` to `import 'lodash'`
- Import lodash inside a fixture
- Playground frame will cry `lodash is undefined`

This issue has become apparent in and #296 (@newswim) and #297 (@reinei).

### Mkay, tell me more...

TODO
- [ ] Create a DllPlugin examples in the examples folder (failing at first)
- [ ] Remove [custom playground index and favicon](https://github.com/react-cosmos/react-cosmos/blob/9159b55c11d40d62e437bf88da02a1fb7ccced3e/packages/react-cosmos-webpack/src/server.js#L65-L71) 😢 – User's index & favicon will be used
- [ ] Should probably load both playground and loader frames from the same `window.location.pathname` (right now the former is `/` and the latter is `/loader/`). See [here](https://github.com/react-cosmos/react-cosmos/blob/9159b55c11d40d62e437bf88da02a1fb7ccced3e/packages/react-cosmos-webpack/src/server.js#L51), [here](https://github.com/react-cosmos/react-cosmos/blob/9159b55c11d40d62e437bf88da02a1fb7ccced3e/packages/react-cosmos-webpack/src/server.js#L62) and [here](https://github.com/react-cosmos/react-cosmos/blob/9159b55c11d40d62e437bf88da02a1fb7ccced3e/packages/react-cosmos-webpack/src/webpack-config.js#L39).  Related: [publicPath](https://github.com/react-cosmos/react-cosmos/issues/297)
  - [ ] If so, also change [the way routes are separated between playground and loader frame](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-webpack/src/entry.js#L3-L5)

**Comment by skidding** [comment]
@ovidiubute any thoughts on this?

**Comment by ovidiubute** [comment]
I never really understood the appeal of having fixtures so complicated that they need dependencies (the only time I kind of understood it was with random fixtures). I guess you could handle it in the same way we handle external CSS files: configure all of your "externals" in `cosmos.config.js`. You could technically provide static links towards whatever files you want and the loader frame could inject them via script tags. 

But I still feel that this is totally breaking the isolation of the components.

**Comment by skidding** [comment]
> I never really understood the appeal of having fixtures so complicated
that they need dependencies

I'm with you on this one, but it's enough to include lodash to use a helper
to hit this wall. If you also use DllPlugin to do code splitting (or add
the vendor script in your html by hand), that is.

> But I still feel that this is totally breaking the isolation of the
components.

Well, this is about the playground frame. The loader frame (which loads the
component) isn't affected by this change.

**Comment by ovidiubute** [comment]
You're right, yeah, I was thinking about the loader frame. 😞

**Comment by skidding** [comment]
@jlc467 based on your recent in depth experience with the RC architecture, do you have any thoughts on this?

I've not had much time to work on this lately but I still feel it's somewhat of a blocker for the next major release and making RC more accessible at large.

**Comment by jlc467** [comment]
Trying to see if I understand the issue. 

- This is only an issue for scripts loaded in the user's index.html that we want to make use of in a fixture
- Fixtures can use modules imported from the user's node_modules with no issue in the current beta

With this understanding, my questions are:
- Why would one use code splitting with cosmos? I would think that would be part of a prod webpack config, not a cosmos one.
- Can we think of a better example besides lodash that someone would want to use in a fixture? Since fixtures aren't shipped to the user, I would be less concerned if fixtures imported their own version of lodash instead of wanting to use one in the index.html

**Comment by reinei** [comment]
To answer your first question: My current cosmos config uses my production webpack config, so compilation is just as fast as production (as well as to check that everything actually works)

Towards the second question, a similar problem (though much more severe) is encountered when outsourcing react itself, because then the cosmos page won't even load to display the fixture frame

I hope this helps clarify the problem a bit, but if not feel free to ask me more about my setup

**Comment by flaviusone** [comment]
> To answer your first question: My current cosmos config uses my production webpack config, so compilation is just as fast as production (as well as to check that everything actually works)

+1 for this. We recently wanted to speed-up our dev bundle build time and using the DllPlugin decreased our initial build time by around 18%. Unfortunately we can't use that yet with cosmos and we have to pop DllReferencePlugin from the `config.plugins` inside our `playground.config.js`.

**Comment by skidding** [comment]
It's pretty clear this is needed at this point. I've updated the issue body with some guidance and labelled this issue as `free for all`. It would be great if somebody offered to pick this up! 🎖

 Can't find the time to do this myself, but I'm here to add any support needed. @flaviusone, since you also feel the pain, what say you, has the time finally come to add a contribution with your @flaviusone username? :P

**Comment by skidding** [comment]
Closed in favor of #360 (continue discussion there)
