### ISSUE TITLE
Custom config not using loaders

### ISSUE THREAD

**Issue by rchanou** [react-cosmos/react-cosmos#323]
### What's up?

Great project, but I need some help getting a simple custom config to work. The loaders are not being used at all and "You may need an appropriate loader" errors occur.

### Mkay, tell me more...

In my **`package.json`**
```json
"devDependencies": {
    "babel-loader": "^6.3.2",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.2.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.22.0",
    "css-loader": "^0.27.3",
    "json-loader": "^0.5.4",
    "react-cosmos-webpack": "^2.0.0-beta.8",
    "style-loader": "^0.15.0",
    "url-loader": "^0.5.8",
    "webpack": "^2.2.1"
  }
```

**`cosmos.config.js`**
```javascript
module.exports = {
  componentPaths: ['src/react'],
  publicPath: 'public',
  hostname: process.env.COSMOS_HOST || 'localhost',
  webpackConfigPath: 'base-webpack.config.js'
};
```
**`base-webpack.config.js`** (just tweaked the default a little)
```javascript
const HtmlWebpackPlugin = require('html-webpack-plugin');

// This config doesn't have entry and output set up because it's not meant to
// work standalone. react-cosmos-webpack adds an entry & output when extending this.

module.exports = function () {
  return {
    devtool: 'eval',
    resolve: {
      extensions: ['.js', '.jsx']
    },
    module: {
      rules: [{
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: [{
          loader: 'babel-loader',
          options: {
            "presets": [
              "react",
              "stage-0",
              [
                "env",
                {
                  "modules": false
                }
              ]
            ],
            "plugins": [
              "transform-runtime",
              "transform-class-properties"
            ]
          }
        }]
      }, {
        test: /\.css$/,
        use: [require.resolve('style-loader'), require.resolve('css-loader')]
      }, {
        test: /\.(eot|woff|ttf|svg|otf|png|jpg|jpeg)/,
        use: require.resolve('url-loader')
      }]
    },
    plugins: [
      new HtmlWebpackPlugin({
        title: 'React Cosmos'
      })
    ]
  };
};
```

When I run `cosmos`, none of my files get transpiled. They get an `Unexpected token...You may need an appropriate loader to handle this file type.` at the first sign of CSS, JSX, or ES2015+ syntax.

It works fine with the default config. I also have a build script which uses the same `base-webpack.config.js` and transpiles everything absolutely fine:

**build.js**
```javascript
const webpack = require("webpack");
const path = require("path");

const getbaseConfig = require('./base-webpack.config.js');

const entry = "./src/app.js";

const config = Object.assign(
  getbaseConfig(), {
    entry: entry,

    output: {
      path: path.resolve(__dirname, "public"),
      filename: "app.min.js",
      publicPath: "/"
    },

    plugins: [
      new webpack.NoErrorsPlugin(),
      // builds production version of React
      new webpack.DefinePlugin({
        "process.env": {
          NODE_ENV: JSON.stringify("production")
        }
      }),
      new webpack.optimize.UglifyJsPlugin()
    ]
});

const compiler = webpack(config);

console.log("Started file-watching and build process. Press Ctrl+C to exit.");

compiler.plugin("compile", () => console.log("Building..."));

compiler.watch(300, (err, stats) => {
  if (stats) {
    if (stats.hasErrors()) {
      console.log(stats.toJson().errors[0]);
    } else {
      console.log(
        `Build done at ${Date()}`
      );
      console.log(`Took ${(stats.endTime - stats.startTime) / 1000} seconds.`);
    }
  }
});
```
Any help appreciated. Thanks!

EDIT: I'm on Windows 10, BTW. I noticed the `cosmos` script won't print out console.logs inside the webpack config, and it won't error out on unresolvable loaders like a normal build script would, is there some crazy child process thing going on or something?

**Comment by rchanou** [comment]
After many tears trying many different configurations to get this to work, I decided to follow the create-react-app instructions you recently (thankfully) added, and just port my project over and move on. Now I can finally load CSS with links to font files in `globalImports`! Thanks again for the awesome project!

**Comment by skidding** [comment]
Glad to hear this worked out for you @rchanou!

**Comment by vjpr** [comment]
I have the same issue with a next.js project.

I tried adding a `babel-loader` to compile the exact file that said it required a loader. Didn't work. `react-cosmos` must be doing some magic I'm guessing...

**Comment by skidding** [comment]
> I have the same issue with a next.js project.

@vjpr Which version of Next.js?

I recently upgraded from an older version to 4.3 and struggled a bit to get Babel to work. In the end this config works just right:

.babelrc
```
{
  "presets": ["env", "next/babel"]
}
```

cosmos.config.js
```
module.exports = {
  publicPath: 'static',
  publicUrl: '/static/'
};
```
But if I recall correctly, if you reverse the order of presets to `["next/babel", "env"]`, which is what the Next.js docs recommend, it stops working.

**Comment by vjpr** [comment]
> "next": "^3.2.2"

Got it working!

I am using a custom webpack config because I modify the Next webpack config in `next.config.js`.

I am also using a custom babel preset (see `babel-preset-foo` below) which I keep in my project's monorepo.

I added a `babel-loader` like so:

```
config.module.rules.push({
  test: /.js$/,
  loader: 'babel-loader',
  query: {
    babelrc: true,
    presets: [join(process.cwd(), './packages/babel-preset-foo')],
    cacheDirectory: false,
  }
})
```

**Comment by skidding** [comment]
Cool.

I'd like to make integrating Cosmos a better experience for new users but unfortunately both Next.js and Cosmos are experimental tech, because they rely on so many new technologies that need to work well together across versions. I think this is the price that we'll continue to pay going forward, at least for the foreseeable future. Anyway, I'm happy you're on board!
