### ISSUE TITLE
Constants in user-modules.js non interpolated

### ISSUE THREAD

**Issue by mattiaocchiuto** [react-cosmos/react-cosmos#324]
### What's up?
Actually I have configured react-cosmos and the build ends with success, if I go to localhost:8989 I see in cosole this error: `Uncaught ReferenceError: CONTEXTS is not defined`

Inspecting the user-modules.js file I noticed that the variable CONTEXTS, COMPONENTS, FIXTURES, PROXIES are not been interpolated by webpack.

My configuration is composed by a webpack.cosmos.config.js file and the cosmos.config.js, what I'm doing wrong?

Thanks in advance.

**Comment by mattiaocchiuto** [comment]
Update: Actually I solved the problem using the webpack 1 syntax in the loader configuration, so I replaced the `use` in favour of `loaders`.

**Comment by skidding** [comment]
Good to hear you solved it!

Weird that it wasn't working before, though, as Cosmos is [designed to work with both webpack 1 and 2](https://github.com/react-cosmos/react-cosmos/blob/4d387737954eaed43c8512d6af25188850bd0221/packages/react-cosmos-webpack/src/webpack-config.js#L42-L54). It might be useful to add your initial config to this issue if you still have it, for further investigation or if somebody else reports something similar. Thanks!
