### ISSUE TITLE
Support .jsx fixtures

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#333]
### What's up?

As reported by @robbert229, `.jsx` fixtures are no longer supported. JSX works inside `.js` components at the moment, but this is still no ideal.

### Mkay, tell me more...

The `js,json` whitelisting on fixture extensions is currently hardcoded in two files:
- `packages/react-cosmos-voyager/src/index.js` ([here](https://github.com/react-cosmos/react-cosmos/blob/9d8e38999990361addf06a55323830075df24e65/packages/react-cosmos-voyager/src/index.js#L12), [here](https://github.com/react-cosmos/react-cosmos/blob/9d8e38999990361addf06a55323830075df24e65/packages/react-cosmos-voyager/src/index.js#L70) and [here](https://github.com/react-cosmos/react-cosmos/blob/9d8e38999990361addf06a55323830075df24e65/packages/react-cosmos-voyager/src/index.js#L66))
- `packages/react-cosmos-voyager/src/match-fixture-path.js` ([here](https://github.com/react-cosmos/react-cosmos/blob/ca471cb75cd1dab556a3ea68fcf3864e62015fd1/packages/react-cosmos-voyager/src/match-fixture-path.js#L2-L4))

We should create a single constant for extension types to keep them in a single place and use that constant in all places enumerated above.

**Comment by JohnRowleySEL** [comment]
@skidding, I can take this on. 

@robbert229 is my personal account, and this account is my work account.

**Comment by JohnRowleySEL** [comment]
Implemented the fix, just waiting for corporate approval.. btw this usually takes a while.

**Comment by skidding** [comment]
> Implemented the fix + tests

Awesome.

> just waiting for corporate approval

What do you mean by corporate approval? 🤔

**Comment by JohnRowleySEL** [comment]
My workplace requires that I get approval from my boss, my bosses boss, his boss, and a guy from legal before I can create a pull request with code that I wrote on the job. It usually just takes a while... but at least I can contribute and get paid for it! :smile:

**Comment by skidding** [comment]
Haha. Well maybe they all get excited about the project and contribute as well! 👨‍👩‍👦‍👦

**Comment by JohnRowleySEL** [comment]
@skidding That is the goal! :smile:

**Comment by RobertPepkaSEL** [comment]
It's not THAT cumbersome. ;)

**Comment by skidding** [comment]
Closed in #335
