### ISSUE TITLE
Drop React 0.13 support

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#340]
### What's up?

It became apparent in #339 that we no longer fully support 0.13 so it's time to move on and remove it completely.

### Mkay, tell me more...

This has a number of advantages:
- Smaller maintenance cost
- We can get rid of `react-dom-polyfill`
- We can get rid of `react-split-pane` and `react-codemirror` forks
- Unit tests can be run on all supported React versions (they weren't running on 0.13 for a long time)

**Comment by skidding** [comment]
@ovidiubute @flaviusone @RadValentin @catalinmiron thoughts? What React version are you rocking nowadays?

**Comment by flaviusone** [comment]
I think we're good to go! We switched from 0.13 and also removed the `react-dom-polyfill` usages from our codebase.

**Comment by skidding** [comment]
@flaviusone @RadValentin do we still need the `ubervu-react-split-pane` fork once `react-dom-polyfill` is gone?

**Comment by flaviusone** [comment]
> @flaviusone @RadValentin do we still need the ubervu-react-split-pane fork once react-dom-polyfill is gone?

That was only used by cosmos so I don't think we need it anymore.

**Comment by skidding** [comment]
@flaviusone I was wondering if you put any features into that fork (besides the 0.13 support) that we might lose now?

**Comment by flaviusone** [comment]
@skidding no additional features besides the 0.13 support (using `react-dom-polyfill`). We should be ok 👍 .

**Comment by skidding** [comment]
@flaviusone cool! Take a look over https://github.com/react-cosmos/react-cosmos/pull/342 if you have a few minutes then! 🙇
