### ISSUE TITLE
Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#350]
Hey, guys. I am trying to test a react component, which is based on vendor's [redux-state](https://github.com/galkinrost/redux-state) library. This library requires to connect its reducer to make it work. I created a fixture for the component, included redux-proxy and created redux store with necessary reducers. Everything is ok. But when I run the component in cosmos I get the next error:

![image](https://cloud.githubusercontent.com/assets/7403902/25640672/20696730-2f99-11e7-98e1-3be98de4f869.png)

The error occurs in the next method:
```
function onFixtureUpdate(fixtureBody) {
      parent.postMessage({
        type: 'fixtureUpdate',
        fixtureBody: fixtureBody
      }, '*');
    }
```
Yes, fixtureBody is a complex object indeed. But I need it. I found the similar [issue](https://github.com/goatslacker/alt-devtool/issues/5) from another project. The authors fixed it by using JSON.stringify to leverage cloning complex objects.

Could you take a look or try to reproduce this issue in your sandbox?

**Comment by skidding** [comment]
It's not clear to me what `redux-state` does, but I understand where the problem occurs. Could you share the `fixtureBody` object somehow (screenshot if nothing better comes to mind) to analyze its contents?

The issue occurs inside [splitUnserializableParts](https://github.com/react-cosmos/react-cosmos/blob/f8fd621a906fc3ea95df370f83d11dbba832b836/packages/react-cosmos-utils/src/unserializable-parts.js#L30-L53) where we wrongly mark a part of the fixture as serializale, when in fact it appears unserializable. I'd like to understand what that is it your case so that we can mark it appropriately.

**Comment by dfedynich** [comment]
@skidding, sorry for misunderstanding about `redux-state`. I mentioned this library for only one reason - to outline, that the redux state can contain data from vendor's library and I can't control that. 

I guess, that the clue of the issue in fields of `function` type. Here is the part of fixtureBody that is the most suspicious in my view.

![image](https://cloud.githubusercontent.com/assets/7403902/25656555/406d2c74-3002-11e7-8c98-277fdc0f33cc.png)

**Comment by skidding** [comment]
OK, this appears to be the problem: Your Redux state is unserializable and Cosmos cannot send unserializable state updates from the loader frame to the playground frame. I have a few solutions in mind but I need a way to test them on your example to make sure it fixes it completely. @dfedynich do you have the React Cosmos repo installed locally? I could show you how to run your project with your development copy of React Cosmos and then try a few fixes together. If we find the right one we can turn it into a proper PR afterwards.

**Comment by skidding** [comment]
@dfedynich please check if this is still a problem in `react-cosmos-webpack@2.0.0-beta.16`. It shouldn't crash anymore.

**Comment by skidding** [comment]
Please reopen if the issue still occurs.
