### ISSUE TITLE
Playground Fullscreen/Editor on Welcome & 404 screens

### ISSUE THREAD

**Issue by ganderzz** [react-cosmos/react-cosmos#351]
### What's up?

When on the 404 page, the editor button is visible on the left nav though clicking it provides no editor. Like on the welcome page, both the editor and fullscreen buttons probably shouldn't be visible.

Also, navigating to a page with a starry bg (welcome & 404) and `fullScreen=true` in the url causes the page to go fullscreen, but the content area doesn't go fullscreen. Even though the buttons are disabled, this should still be a caught case with url parameters.

Thoughts?

### Mkay, tell me more...

- Update `component-playground` to only render the renderMenu when both `isFixtureSelected` and `doesSelectedFixtureExist` is true
- `display-screen__display-screen` has a css left property of 250px. This should be 0px during fullscreen mode.

**Comment by skidding** [comment]
Good catch! Your action items are sound. Feel free to take a stab at it ⚔️

**Comment by ganderzz** [comment]
Sounds good. I'll have a PR tonight! 👍
