### ISSUE TITLE
Cannot GET /loader/index.html

### ISSUE THREAD

**Issue by everdimension** [react-cosmos/react-cosmos#358]
### What's up?
Getting this error: `Cannot GET /loader/index.html`

### Mkay, tell me more...
here's my `cosmos.config.js`:

```javascript
module.exports = {
  componentPaths: [
    'src/components/shared/NumberInput',
  ],
};
```

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/5347023/25946306/31053f04-3653-11e7-8314-84f4dcd8dc23.png)

The bundle seems to get built successfully.

I'm using `react-cosmos@2.0.0-beta.12`

**Comment by skidding** [comment]
Hey, did you try any of the top options from [Configuring index.html](https://github.com/react-cosmos/react-cosmos#configuring-indexhtml)?

**Comment by everdimension** [comment]
Thanks, adding a custom webpack config with html-webpack-plugin worked.

But I remember now that I have one problem with your library: it always bothered me that it tried to use my existing webpack config by default.

I would prefer that this library used its own config by default.

Right now, if I *don't* want it to use my config, I *have to* create another config and point to it with `webpackConfigPath`. There's no way to say "don't use mine, use your default config please".

**Comment by skidding** [comment]
> Thanks, adding a custom webpack config with html-webpack-plugin worked.

Great!

> There's no way to say "don't use mine, use your default config please".

Interesting. Curious what the reasons for wanting this are. Feel free to open a new issue to propose an enhancement for this.
