### ISSUE TITLE
All fixtures matched under component with same name as project

### ISSUE THREAD

**Issue by flaviusone** [react-cosmos/react-cosmos#387]
### What's up?

All fixtures are matched under a component that has the same name as the project (found in absolute path).

### Mkay, tell me more...

This helps recreate the failing scenario:
```
{
  base: '/Users/foo/PROJECTNAME/tests/fixtures/components/PROJECTNAME/base.js',
  filtered: '/Users/foo/PROJECTNAME/src/scripts/components/somecomponent/__fixtures__/filtered.js',
}
```

Failing condition: https://github.com/react-cosmos/react-cosmos/blob/a2f5a2f3ab1ae1d82675c3ab663103883d118405/packages/react-cosmos-voyager/src/match-fixture-path.js#L5

**Comment by skidding** [comment]
Fixed by #398
