### ISSUE TITLE
Bring back jump to fixture in CP

### ISSUE THREAD

**Issue by flaviusone** [react-cosmos/react-cosmos#388]
### What's up?

CP used to automatically scroll to selected fixture in the list after a hard refresh.

### Mkay, tell me more...

Here is the old code: https://github.com/react-cosmos/react-cosmos/blob/fe8542357b119ba72499634200e9a44269bf4d51/packages/react-component-playground/src/components/component-playground.jsx#L441-L444

**Comment by adelinaenache** [comment]
May I take this?

**Comment by skidding** [comment]
Yes 👌
