### ISSUE TITLE
Prevent duplicate HotModuleReplacementPlugin

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#393]
### What's up?

Webpack HMR is enabled by default in Cosmos, but users usually already have `HotModuleReplacementPlugin` added to their webpack config. Unless we pass `hmrPlugin: false` in cosmos.config, Cosmos blindly duplicates it, causing a build error with an unclear error message. I've seen this many times.

### Mkay, tell me more...

- [x] We can use [merge.unique](https://github.com/survivejs/webpack-merge#mergeuniquefield-fields-field--field) from webpack-merge! Or just check for `plugin.constructor && plugin.constructor.name` manually.

Bonus:
- [x] Set `output.filename` to `'[name].js'` (makes Cosmos webpack config work when user uses CommonsChunkPlugin)
- [x] Create example with CommonsChunkPlugin using [manifest](https://webpack.js.org/plugins/commons-chunk-plugin/#manifest-file)
- [ ] Update React Redux Starter Kit docs (integration is much more smooth now)

```js
// Plugins
new webpack.optimize.CommonsChunkPlugin({ names: ['manifest'] })
```

Inspiration: [react-styleguidist](https://github.com/styleguidist/react-styleguidist/blob/f7876503e5a070c3de08c032727107e7802298f6/scripts/utils/mergeWebpackConfig.js#L17-L33)

**Comment by jlc467** [comment]
Trying to understand the benefit of `CommonsChunkPlugin` in cosmos. Since we replace `output` anyway, wouldn't a user webpack config with `CommonsChunkPlugin` _work_ without cosmos supporting it? Maybe if they use their own index.html file with script references to the common chunks, but otherwise, I'm not understanding the benefit.

Seems like this PR gets rid of `hmrPlugin` option in cosmos.config and only adds `HotModuleReplacementPlugin` if it hasn't been added in user's config and `hot` is true. LGTM. I will try to check out and test tomorrow.

**Comment by skidding** [comment]
> Trying to understand the benefit of `CommonsChunkPlugin` in cosmos. Since we replace `output` anyway, wouldn't a user webpack config with `CommonsChunkPlugin` _work_ without cosmos supporting it? Maybe if they use their own index.html file with script references to the common chunks, but otherwise, I'm not understanding the benefit.

For the most part, you're right. Cosmos *does* replace `entry` and `output`, but webpack can still generate two chunks if you configure CommonsChunkPlugin to generate a separate chunk for the webpack *manifest*. See this [section from the webpack docs](https://webpack.js.org/plugins/commons-chunk-plugin/#manifest-file). I wasn't familiar with it either.

> To extract the webpack bootstrap logic into a separate file, use the CommonsChunkPlugin on a name which is not defined as entry. Commonly the name manifest is used. See the caching guide for details.

The example I created does just [that](https://github.com/react-cosmos/react-cosmos/blob/9972061c7b102b850d99860a55f7ab425a6f8ad7/examples/webpack-commons-chunk/webpack.config.js#L24).

---

> Seems like this PR gets rid of `hmrPlugin` option in cosmos.config and only adds `HotModuleReplacementPlugin` if it hasn't been added in user's config and `hot` is true. LGTM. I will try to check out and test tomorrow.

Correct!
