### ISSUE TITLE
Fixtures being ignored?

### ISSUE THREAD

**Issue by sashafklein** [react-cosmos/react-cosmos#400]
I've set up react-cosmos in my repo mostly successfully, I think. I whittled the components folder down to one component, and built out a fixture for it that should contain all the data it needs to get going. My file structure looks like this:

```
- components
  - Dropdown
    - index.js
  - __fixtures__
    - Dropdown
      - index.json
```

And the index.json file contains a JSON blob that would be the props the component needs to render. Cosmos doesn't complain about missing fixtures, and the JSON shows up correctly in the left panel. 

**BUT**, the component isn't actually receiving the props declared in the fixture, and it runs into predictable errors as a result. 

Am I understanding Fixtures correctly? Why would they be ignored? Anything I need to do to ensure the fixture data is injected correctly?

**Comment by skidding** [comment]
He @sashakflein. You're very close. Wrap the fixture blob inside a `props` key.

```json
{
  "props": { }
}
```

Let me know if it works. The latest docs (WIP) might be more helpful https://github.com/react-cosmos/react-cosmos/blob/refresh-docs/README.md#fixtures (feedback appreciated)

**Comment by sashafklein** [comment]
Yes! Actually just saw that in the new docs. Thanks! Yeah. The old video on Fixtures didn't have that.
