### ISSUE TITLE
Component not connecting

### ISSUE THREAD

**Issue by sashafklein** [react-cosmos/react-cosmos#401]
I've got one component. It is exported directly, and also by default as a connected component (with `mapStateToProps` etc):

```
export function Dropdown (props) {
  ...
}
...
export default connect(mapStateToProps)(Dropdown);
```

This component has a functioning fixture, but when ReactCosmos is pulling it to display it, it never enters the `mapStateToProps` function (where I've got a `debugger`), and so, as a result, doesn't inject some props or function as expected.

I've added a Redux proxy, very similar to the given example, and point to it successfully (another `debugger` is hit) in the `cosmos.config.js` file. But when I inspect the Redux panel (using Redux Devtools), Cosmos doesn't seem to have any of my reducers stored anywhere either. 

Do I have to do something to have Cosmos render the connected component? Should I be able to see my reducers in the Redux console anywhere?

**Comment by skidding** [comment]
Hi @sashafklein 

- Do you have any errors in the console?
- Did you add `reduxState` to the fixture? Like [this](https://github.com/skidding/flatris/blob/6a451ae7313c389af982bc3d88666d70670ab51c/src/components/__fixtures__/FlatrisGame/new-game.js#L4-L10)
- Can you show me ho your Redux proxy looks like?

> Should I be able to see my reducers in the Redux console anywhere?

It should work if Redux devtools is already configured in your project.

**Comment by sashafklein** [comment]
Thanks for the quick response @skidding !

The only errors I'm seeing in the console (of the cosmos server/app) are ones caused by missing attributes handed into the component by Redux.

So specifically, I'm seeing:

![image](https://user-images.githubusercontent.com/1746778/28684399-13d058a4-72b9-11e7-87f3-8a67a95e430c.png)

I haven't tried `reduxState`, because as I understand it I'm looking for something different: Because the components visually react by changing and responding to Redux state, the hope was to have them have normal access to Redux as they would in an app -- without passing any specially initialized state object, or having that be fixed to the state passed in and having Redux state only be editable in the left panel. Effectively, I'd like to have `initialState` passed in as declared in my proxy, and then have it update as in the normal app.

I'll just paste in all the relevant files here:

**src/components/Dropdown/index.js**
```
import { connect } from 'react-redux';
import React from 'react';
import classNames from 'classnames';
import PropTypes from 'prop-types';

import { setOpenDropdownID, setDropdownValues } from 'store/actions';
import 'styles/components/Dropdown.scss';

/**
 * A basic dropdown. With the callbacks (onTitleClick and onItemClick) unspecified, will behave sensibly, allowing
 * a single item to be selected at a time, and storing that information in the Redux store.
 * Custom behavior can be tweaked through those components.
 * This dropdown also allows for simple or complex (object) items.
 *
 * @param {Object} props
 * @param {Array} props.items Array of objects or strings representing a dropdown item
 * @param {string} props.items[].label String to show as dropdown option (req)
 * @param {string} props.items[].value String, object, or any other type representing the data to be stored if item selected
 * @param {string[]} props.items[].className Optional additional class to apply to each item
 * @param {string} props.title Title to display before a value is selected (or after, if replaceTitle is false)
 * @param {boolean} props.replaceTitle Whether to replace the title with the current selection
 * @param {boolean} props.multipleSelect Where more than one item can be selected at once
 * @param {Object[]} props.style Optional styles object
 * @param {boolean} props.open - Whether the dropdown is open
 * @param {string} props.className - Optional string of class to apply to Dropdown
 *
 * @returns {React.Component} - A component representing a dropdown connected to the Redux store
 */
export function Dropdown (props) {
  const { items, className, title, open, onTitleClick, style, selectedIndices, onItemClick, replaceTitle, multipleSelect } = props;

  const finalItems = typeof items[0] === 'string'
    ? items.map(item => ({ value: item, label: item }))
    : items;

  const titleIndex = selectedIndices[0];

  const finalTitle = selectedIndices.length === 1 && replaceTitle && !multipleSelect
    ? finalItems[titleIndex].label
    : title;

  return (
    <div className={ classNames([open && 'is-open', className, 'dropdown rs-comp']) } style={ style }>
      <div className="dropdown__toggle" onClick={ onTitleClick }>
        <span className="dropdown__title">{ finalTitle }</span>
        <span className="icon-arrow-down dropdown__icon" />
      </div>
      { open &&
        <div className="dropdown__menu">
          <ul className="list--block">
            {
              finalItems.map((item, index) => (
                <li
                  className={ classNames([selectedIndices.includes(index) && 'is-active', 'dropdown__item', item.className]) }
                  key={ index }
                  onClick={ () => onItemClick({ index, value: item.value || item.label }) }
                >
                  { item.label || item.value }
                </li>
              ))
            }
          </ul>
        </div>
      }
    </div>
  );
}

const { object, bool, string, arrayOf, shape, any, func, number, oneOfType } = PropTypes;

Dropdown.propTypes = {
  items: oneOfType([
    arrayOf(shape({
      label: string,
      value: any,
      className: string
    })),
    arrayOf(string)
  ]).isRequired,
  title: string.isRequired,
  onTitleClick: func.isRequired,
  onItemClick: func.isRequired,
  selectedIndices: arrayOf(number).isRequired,
  replaceTitle: bool,
  open: bool,
  className: string,
  style: object,
  multipleSelect: bool
};

Dropdown.defaultProps = {
  replaceTitle: true,
  open: false,
  title: 'Select One'
};

const mapStateToProps = (state, ownProps) => {
  debugger // Never hit!
  const { dropID } = ownProps;
  const open = state.openDropdownID === dropID;
  const element = state.dropdowns.get(dropID) ? state.dropdowns.get(dropID).toJS() : [];

  return {
    open,
    element,
    selectedIndices: element.map(obj => obj.index)
  };
};

const mergeProps = (stateProps, { dispatch }, ownProps) => ({
  ...stateProps,
  ...ownProps,
  element: undefined,
  onItemClick: (item) => {
    let toDispatch = [item];

    if (ownProps.multipleSelect) {
      const previousSelections = stateProps.element;
      const preexisting = previousSelections.find(obj => obj.index === item.index);

      toDispatch = preexisting
        ? [...previousSelections, item].filter(i => i.index !== item.index)
        : previousSelections.concat(item);
    }

    dispatch(setDropdownValues(ownProps.dropID, toDispatch));
    dispatch(setOpenDropdownID(null));
  },
  onTitleClick: () => dispatch(setOpenDropdownID(stateProps.open ? null : ownProps.dropID))
});

export default connect(mapStateToProps, undefined, mergeProps)(Dropdown);
```

**src/components/__fixtures__/Dropdown/index.json** 
```
{
  "props": {
    "open": true,
    "element": [],
    "selectedIndices": [],
    "dropID": "whatever",
    "items": [
      "Item 1",
      "Item 2",
      "Item 3"
    ],
    "title": "Whatever Dropdown",
    "replaceTitle": true
  }
}
```

> I'll add more fixtures for other Dropdown types/states once I figure this out.

**config/cosmos.config.js**
```
module.exports = {
  componentPaths: ['../src/components'],
  webpackConfigPath: '../build/webpack.config.js',
  proxies: ['./proxies/redux-proxy.js']
};
```

**config/proxies/redux-proxy.js**
```
import { fromJS } from 'immutable';
import Redux from 'react-redux';
import createReduxProxy from 'react-cosmos-redux-proxy';

const reducers = {
  dropdowns: (state = fromJS({}), action) => {
    switch (action.type) {
      case 'SET_DROPDOWN_VALUES': {
        return state.merge({ [action.id]: action.values });
      }
      default: {
        return state;
      }
    }
  },
  openDropdownID: (state = null, action) => {
    if (action.type === 'SET_OPEN_DROPDOWN_ID') {
      return action.id;
    } else {
      return state;
    }
  }
};

export default () => createReduxProxy({
  // Called when fixture loads with fixture.reduxState as initial state.
  // See https://github.com/skidding/flatris/blob/master/cosmos/redux-proxy.js
  createStore: (initialState) => Redux.createStore(reducers, initialState, [])
});
```

> Yesterday, I was seeing the Redux console, without either of the above reducers. But today, when I tried it (not sure which change is responsible, unfortunately), it gives me a warning saying Devtools aren't set up (`No store found. Make sure to follow the instructions.`). If I figure out what's blocking Redux Devtools, I'll update the ticket.

**Comment by skidding** [comment]
I think I got it!

There's an undocumented behavior where we look for [named exports before the default one](https://github.com/react-cosmos/react-cosmos/blob/b1f3f89a37dddf3af5fe843789f9c836ed6d4d28/packages/react-cosmos-utils/src/import-module.js#L10). So Cosmos uses the `Dropdown` class export instead of the `connect` HOC default export. 🙃

Do you need to export the class itself? The problem should go away if you replace `export function Dropdown` with `function Dropdown`.

If you set `alwaysCreateStore: true` you should no longer have to define `reduxState` in fixtures. E.g.

```js
import createReduxProxy from 'react-cosmos-redux-proxy';
import createStore from 'store/createStore'; // See below file

export default () => createReduxProxy({
  // Called when fixture loads with fixture.reduxState as initial state.
  // See https://github.com/skidding/flatris/blob/master/cosmos/redux-proxy.js
  createStore,
  alwaysCreateStore: true
});
```

Let me know if it works.

**Comment by sashafklein** [comment]
Hmm. The reason I'm exporting the class directly is for tests - so that I can mock out Redux without the test attempting to "connect" to store. Is there a way to still export the component both by default and by name? Would it work if I renamed the named export? That could work?

**Comment by sashafklein** [comment]
To answer my own question, yes, exporting it under a different name from the file name works!

I just ran into another issue, but I'll look into that and raise a separate issue if I can't figure it out. Thanks!

**Comment by skidding** [comment]
> Would it work if I renamed the named export?

Yes because Cosmos only looks for a named export equal to the file name.
