### ISSUE TITLE
Improved proxy config API

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#420]
### What's up?

Based on feedback from a number of people, I've found existing way to configure proxies to be confusing and not pleasant to use. 

The confusion stems from the fact that all other options are configured in `cosmos.config.js` yet proxies need to be placed in their own file, even if they only have 2-3 lines of code. There's a good explanation for this, but the reason isn't obvious and the current solution isn't great.

After some brainstorming with @xavcz, he proposed an alternative way of configuring proxies which makes more sense (that's also backwards compatible).

### Mkay, tell me more...

First of all, why can't proxy code be inlined in `cosmos.config.js`? 

Because `cosmos.config.js` is meant to be imported on the server, and proxy code is client side code (loaded in the user bundle). If we imported cosmos.config in the client bundle then any Node-specific import like `fs` or `path` would corrupt the bundle and overall make Cosmos fragile.

So, given that the proxy config needs to be in a separate file than the main config, the proposal is to **keep all proxies in the same file instead of having one file per proxy.** This makes sense because proxy config tends to be small, while the number of proxies can get large in mature projects.

### Meet `cosmos.proxies.js`

Instead of defining `proxies` in cosmos.config.js, we'll have `proxiesPath`, which defaults to `./cosmos.proxies.js` so in most cases it won't need to be defined.

Here's an example of how cosmos.proxies.js would look like:

```js
import createReduxProxy from 'react-cosmos-redux-proxy';
// We can import anything from our codebase in this file
import configureStore from '../configureStore';

const ReduxProxy = createReduxProxy({
  createStore: state => configureStore(state)
});

const MyCustomProxy = props => {
  const { value: NextProxy, next } = props.nextProxy;
  return (
    <FooProvider>
      <NextProxy {...props} nextProxy={next()} />
    </FooProvider>
  );
};

// We can still ensure a specific proxy order
export default [
  ReduxProxy,
  // No need to import proxies if we rely on defaults
  'react-cosmos-router-proxy',
  'react-cosmos-fetch-proxy',
  MyCustomProxy
];
```

Just one file to define/mock the entire component context!

This solution has two other side benefits:
- This file can be easily imported and reused in other places like unit/integration tests, where we also need proxies to create component context as part of the test setup.
- This format is a bit more flexible, no need to return each proxy as a function any more (e.g. `() => createReduxProxy({ ... })`)

What do you think? @tkjone @xavcz @ovidiubute

**Comment by xavcz** [comment]
I find this a really nice way to define proxies!

I love the flexibility, especially for tests!

**Comment by ovidiubute** [comment]
Cool proposal, @skidding 👍
