### ISSUE TITLE
Error occurs after defining containerQuerySelector option

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#425]
### What's up?

> Cannot read property 'replaceChild' of null

This error occurs when we set **containerQuerySelector** option in _cosmos.config.js_

### Mkay, tell me more...

- **template** option is used in _HtmlWebpackPlugin_
- **containerQuerySelector** option is used in _cosmos.config.js_

After a fixture is selected, the error occurs. However, the Loader and Playground keep working as expected. So, it's a minor issue, in my view. But I suppose, it needs to be sorted out anyway.

Target vesrion is _2.0.0-beta.23_

**Comment by skidding** [comment]
Maybe the element targeted by `containerQuerySelector` doesn't exist? Please share the template and cosmos.config to have a more accurate response. You can strip any business related parts.

**Comment by skidding** [comment]
@dfedynich does this still occur now that you upgraded?

**Comment by skidding** [comment]
I will close this due to inactivity. Please reply if the issue still exists and I'll reopen.
