### ISSUE TITLE
HMR warnings about duplicated module names

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#426]
### What's up?

HMR plugin notifies of dozens of warnings about duplicated module names.

![image](https://user-images.githubusercontent.com/7403902/30162268-d4bd4696-93dc-11e7-826d-03d296f9e9e9.png)

### Mkay, tell me more...

I use the custom webpack.config.js, which is also used at the main development project. There are no such warnings in the dev environment. 

Does it relate to Playground and Loader communication or their separate configuration?
There were no these warnings when I used the latest version of react-cosmos two months ago.

**Comment by skidding** [comment]
> Does it relate to Playground and Loader communication or their separate configuration?

It shouldn't. The separation prevents similar conflicts.

Can you please share your configs? A minimal failing example would be great so I could debug on it, otherwise it's guesswork.

**Comment by skidding** [comment]
@dfedynich does this still occur now that you upgraded?

**Comment by skidding** [comment]
I will close this due to inactivity. Please reply if the issue still exists and I'll reopen.
