### ISSUE TITLE
NPM error occurs when trying to install 2.0.0-beta.24

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#427]
### What's up?

> npm ERR! cb() never called!

This npm error occurs during _'npm install'_ execution. 

### Mkay, tell me more...

- I was trying to update react-cosmom-webpack from 2.0.0-beta.23 to 2.0.0-beta.24
- I have "react-cosmos-webpack": "2.0.0-beta.24" item in my devDependencies in package.json
- npm install fails for 2.0.0-beta.24, However, if I change it back to 2.0.0-beta.23, installation completes successfully. 
- _npm clear cache_ doesn't help

**Comment by skidding** [comment]
Are you sure it's not an npm problem? I just installed in from scratch and it worked:

![image](https://user-images.githubusercontent.com/250750/30166642-321f74a6-93e4-11e7-9577-89099777c990.png)

What is your node version?

**Comment by skidding** [comment]
Have you seen [this thread](https://stackoverflow.com/questions/15393821/npm-err-cb-never-called)? Most responses suggest upgrading node fixed it.

**Comment by dfedynich** [comment]
Yes, updating node from 5.9.1 to 5.12.0 fixed the issue. Thank you.
