### ISSUE TITLE
Mocking server responses blocks HMR to reload modules

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#430]
### What's up?

Mocking server responses allows us to completely isolate components. And that's a great idea. But it blocks HMR to load update modules in the current implementation.

### Mkay, tell me more...

Xhr and fetch proxies use _xhr-mock_ library to mock server responses. This library makes monkey patching of XmlHttpRequest under the hood. This library catches all requests by default and provides mocks only for specified URLs. So, when HRM sends the request for the update module, it will get the response with status '0' and dive in endless checking cycle. To sort this issue out I suggest one of the next solutions:
- Update xhr-mock library to the new version. This library has got some new commits recently, where we can use the factory to mock only specific requests and pass the rest out. However, the current version **2.0.0-preview.5** is rather raw and got some other glitches. So, I don't recommend to update to this version until it becomes robust.
- Fix xhr and fetch proxies to teardown mocks for HMR requests. If you are interested in this fix and choose this way I can create a pull request in the nearest time. Please, let me know if you want me to do that.

**Comment by skidding** [comment]
Good catch! Flagging this as a bug.

A few notes:
- Fetch proxy doesn't use xhr-mock, but [fetch-mock](http://www.wheresrhys.co.uk/fetch-mock/), which doesn't interfere with XHR requests so HMR works just fine with Fetch proxy.
- I agree we should wait until xhr-mock@2.0 becomes stable before upgrading. After that, it would be ideal if we can rely mainly on it to do the job and not have to maintain intricate customizations
- It would be great if you could contribute to fix this! My only ask is to please describe the technical solution before implementing, to make sure we're on the same page.

**Comment by dfedynich** [comment]
Actually, you can add the next check to your xhr-proxy in the constructor

```
if (module.hot) {
  module.hot.status((status) => {
    if (status === 'check') {
      xhrMock.teardown();
    }
  });
}
```

`module.hot.status` is the part of [management API of HMR](https://webpack.github.io/docs/hot-module-replacement.html)

**Comment by skidding** [comment]
Interesting. And then the constructor will run again and the mocks will continue to work?

**Comment by dfedynich** [comment]
Yes, exactly.

**Comment by skidding** [comment]
Interested in making the patch yourself? Contributions are highly appreciated.

**Comment by dfedynich** [comment]
I'd be delighted to make the patch.

**Comment by skidding** [comment]
That would be great. I'm publishing the 2.0 release candidate very soon and this would make a great addition because it fixes a bug.

**Comment by maxsalven** [comment]
Is this something that might make it into 3.0? Thanks :)

**Comment by skidding** [comment]
It isn't planned. Since it's a bug fix and not a breaking change in can be added at any time in the development cycle. I focused more on the fetch proxy which doesn't have this sort of problems. Are you using Axios (which uses XHR internally)?

**Comment by maxsalven** [comment]
Yes, am on Axios. I submitted a PR for this, thanks both.
