### ISSUE TITLE
Not all props from fixture are displayed in code mirror

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#433]
### What's up?

A fixture is a JS object used to mock component input and external dependencies. But as far as I understand, the code mirror gets only valid JSON object. So, it sanitizes all invalid props such as function, for example. 

So, if we define this fixture

```
export default {
  props: {
    value: 'Lorem ipsum',
    disabled: true,
    onChange: value => console.log(`Select: ${value}`)
  }
}
```

The code mirror will cut **onChange** property and display the next result. 

![image](https://user-images.githubusercontent.com/7403902/30166836-36a9c978-93ed-11e7-8257-635df2480130.png)

Is there any way to improve the code mirror to display all kind of props?

### Mkay, tell me more...

The code mirror will cut the property even if it will contain any invalid JSON property inside. So, xhr fixture property (for xhr proxy) will be always cut off, because it contains a mock function.

**Comment by skidding** [comment]
> The code mirror will cut the property even if it will contain any invalid JSON property inside. So, xhr fixture property (for xhr proxy) will be always cut off, because it contains a mock function.

Indeed that is the drawback of the fixture editor. It only works with the *serializable* parts of the fixture. The fixture editor is meant to show *raw data* instead of source code. Eg. if your fixture references several imports and generate data using loops, you still see the exact data generated in the editor. Doing this while also maintaining source code and styling definitely sounds good, but I think it would be 5x the effort compared to the actual functionality. It would involve AST manipulation and I can only imagine how many corner cases we could hit. A complex scenario that works currently is state changes. Notice that if your local state or Redux state changes, the fixture editor is updated with the new state. Not sure how we could do this if we put source code in the editor.

That's not to say that we can't be ambitions. If you have any ideas I'm happy to discuss. It's important to understand the current functionality. Most importantly, the fact that state updates are received from the Loader iframe and get merged into the initial iframe, updating this editor.

But, I do have a small idea that would make this better with very little effort. We already know which props are "unserializable" and do not display. We could show a yellow band at the bottom of the fixture editor saying

> The following props could not be displayed: `onChange`. The reason for this is yata yata link to docs (or even this issue!)

What do you think?

**Comment by dfedynich** [comment]
I understand your concerns and your reasoning is clear. I think, that the rule of thumb is "to make the understanding as simple as possible". You have a good [documentation](https://github.com/react-cosmos/react-cosmos/blob/master/docs/playground-loader.md) about playground and loader communication, where users can get knowledge about how the code mirror gets the fixture. However, I suggest to update Readme to note about JSON restrictions in code mirror too.  

Yellow band at the bottom of the code mirror is a good idea as well. It will let users know, that the actual state of affairs is expected. It stops users think, why they lost some props in the fixture :)

**Comment by skidding** [comment]
> It stops users think, why they lost some props in the fixture :)

Good point :)

**Comment by DJTB** [comment]
Having missing props would be very helpful, currently it's really confusing and misleading seeing components with empty props :sob: 

Could we type check and include that as well for unserialized props?
```
The following props could not be displayed:   
render: function
someProp: Date
```

**Comment by skidding** [comment]
@DJTB I agree. When we send the serialized fixture body from Loader to Playground, via fixtureLoad event [here](https://github.com/react-cosmos/react-cosmos/blob/da8d6594a5f2d92c1ce2d1ac46eaf674c1c5f3c7/packages/react-cosmos-loader/src/connect-loader.js#L55-L60) we could easily extract the names and types of the unserializable parts and add that information (which *is* serializable) to the event. Then, in the Playground, we could show a yellow band at the top of the fixture editor (similar to the red error band at the bottom when JSON has syntax errors) with this information.

Happy to accept a PR on this one and to give more instructions if needed. Labeled this as a `free for all` feature request.

**Comment by charliedotau** [comment]
I'm new to Cosmos - frustrated with Storybook - and I find it very promising. It's essentially exactly what I've been looking for.  So, props (pardon the pun) to all involved.

Nothing I'm going to say below is, per se, new.  My aim is simply to emphasise the issue and hopefully encourage the community to redouble their efforts to bring about a resolution.

## Dealbreaker
With respect, I find this issue - that the Cosmos user interface only shows a subset of all a component's props - to be a major design flaw and a total deal breaker.      

"Cosmos forces us to define sane component inputs".  But how sane is an input that can't be seen?     

As long as this issue persists, the user experience of Cosmos will be greatly diminished.      

## Visibility is key
Visibility is key here.  As such, whilst imperfect, the "yellow band" solution would greatly improve the user experience, especially if it could call out those props that couldn't be rendered in the editor *and* show what the values of those props are.

I'm time poor at present, and an occasional coder, so  I'm not able to provide a PR, and nor would you want me to!  

Love your work
Thanks

**Comment by Izhaki** [comment]
@skidding 

> Notice that if your local state or Redux state changes, the fixture editor is updated with the new state.

Is this the really working for `reduxState`? 

With the following fixture:

```javascript
import Brain from '../containers/Brain';

const excitatory = x => x;
const inhibitory = x => !x;

export default {
  component: Brain,
  reduxState: {
    neurons: {
      I1: {
        shouldFire: () => true,
        charge: 0,
        x: 50,
        y: 100,
      },
      P: {
        shouldFire: () => true,
        charge: 0,
        x: 200,
        y: 50,
      },
    },
  },
  props: {
    neurons: {},
  },
};
```

And:

```javascript
const mapStateToProps = state => ({
  neurons: state.neurons,
});
```
I can't see anything redux or props on the editor:

```json
{
  "props": {
    "neurons": {}
  }
}
```

**Comment by skidding** [comment]
Hey @Izhaki,

> Is this the really working for reduxState?

The editor only works for serializable values. It looks like your state contains functions (eg. `shouldFire`), which make the whole redux state unserializable and thus hidden from the JSON editor.

This will improve in the mid/distant future, but for the moment you might want to consider making your state serializable, which is a best practice anyway. Anything else can be derived.

**Comment by Izhaki** [comment]
Indeed this was the issue.

I am soooo happy you've explained that (and also just realised this was mentioned in previous comments).

Thanks!

**Comment by skidding** [comment]
This will be covered in the future Props Panel in Cosmos Next. Reopen under http://github.com/react-cosmos/react-cosmos-classic if needed
