### ISSUE TITLE
Fine-tune the Apollo Proxy with custom responses

### ISSUE THREAD

**Issue by maxsalven** [react-cosmos/react-cosmos#445]
Awesome work on the apollo proxy!

As an idea for an improvement, can we locate the mock response in the fixture file instead of in the proxy config? I think this makes more sense and aligns better with the way the other proxies work. It would allow me to mock multiple different server responses by using different fixtures, and I don't have to worry about the proxy config and my fixtures getting out of sync (e.g. if I remove a component from cosmos, I now have to remember to modify the proxy config to remove the mock).

**Comment by xavcz** [comment]
Hey Max! 👋 

Yeah, mocks at the fixture-level would be interesting! 

To do that, let give me you some info on the current solution! 

Mocks independent from the fixtures
---

➡️  **[Current Solution]**

The goal of global mocks is to map the way we would mock a GraphQL API server-side, like when we create a GraphQL schema for a GraphQL API with `apollo-server-*`: we are **mocking responses based on the schema** ([see docs](http://dev.apollodata.com/tools/graphql-tools/mocking.html)).

```js
// somewhere in your app's API server, you create your GraphQL Schema
const typeDefs = `
  type Query {
    hello(who: String): String
  }
`;

const mocks = {
  Query: () => ({
    hello: (root, { who }) => `Hello ${who ? who : 'C O S M O S'}`,
  }),
};

const schema = makeExecutableSchema({ typeDefs });

addMockFunctionsToSchema({ schema, mocks });
```

With this in mind, let's take this assumption:

> worry about the proxy config and my fixtures getting out of sync (e.g. if I remove a component from cosmos, I now have to remember to modify the proxy config to remove the mock).

At the moment, you don't really need to update the proxy config when you modify components shown in Cosmos: we mock the "interface" where are sent the GraphQL requests. 

This is done by allowing Cosmos to load a component enhanced with `graphql` higher-order component from `react-apollo` and to "send" its queries/mutations/subscriptions to a schema that will treat the request and return data based on the mock functions defined.

We mock the schema defined in the proxy config thanks to `graphql-tools` and its default mocking logic ([see an example here](https://launchpad.graphql.com/98lq7vz8r)).

You need to update the config only if you want custom return value for a query / mutation / subscription / type defined in your schema.

Mock per fixtures
---

➡️  **[Proposed Improvement]**

Looks like having mock per fixtures is a different approach! 🤔  

> I think this makes more sense and aligns better with the way the other proxies work.

Yeah, that would definitely be more aligned with the way Cosmos proxies are used 💯 

> It would allow me to mock multiple different server responses by using different fixtures

We would be able to bypass the "top-level mocks" (defined in the config), and return a custom `data` object from a query/subscription or from a `mutate` function.

It would be much easier to display a component enhanced with a query in its loading state or to display an error (network failure, not allowed to do that, ...)!

Conclusion
---
➡️  **I would tend to make these approaches live together!**  🌮 

In my honest opinion, having a top-level schema+mocks acting as the interface where GraphQL requests are sent from the client is required (it's the API contract after all).

By the way, if your schema is not written in JS or doesn't live "nearby" your client app, you can still mock it easily on the client using introspection:
```js
import { buildClientSchema } from 'graphql';
import * as introspectionResult from 'schema.json';

const schema = buildClientSchema(introspectionResult);
addMockFunctionsToSchema({schema});
```
([see Apollo docs](http://dev.apollodata.com/tools/graphql-tools/mocking.html#Mocking-a-schema-using-introspection))

And having custom values at the level of the fixture is also important for flexibility and alignment on how we use Cosmos!

---

➡️ **So what do you think?** 😄 

You may have different use cases? How do you use currently the Apollo Proxy?

**Comment by maxsalven** [comment]
Thanks, appreciate the thoughtful response and sorry for my slow feedback.

Unfortunately I don't have much to say, as I'm very new to graphql/apollo.

I guess what I'd like to do is in my cosmos fixture provide something like what I get back from a GraphQL network request:

```
"data": {
  "currentUser": {
    "name": "Max",
    "__typename": "User"
  }
}
```

Then I can easily make multiple mocks for a single component with different responses.

Perhaps you might want to go one level up the abstraction tree and instead of the raw network responses, mock what the `graphql` container returns:
```
  "data": {
    "variables": {
      "userId": "1"
    },
    "loading": false,
    "networkStatus": 7,
    "currentUser": {
      "name": "Max",
      "__typename": "User"
    }
  }
```

This way I don't have to worry about setting up any schemas etc.

**Comment by dan-weaver** [comment]
I like the proposal here.  I don't really see why fixture level and config level mocks can't coexist!

>By the way, if your schema is not written in JS or doesn't live "nearby" your client app, you can still mock it easily on the client using introspection:

@xavcz is this currently actually possible?  The current proxy just takes typeDefs.  I had to modify the default createAplloProxy to take a prebuilt  in our case since our .NET server houses our schema definitions.

**Comment by xavcz** [comment]
Yeah, you're right, the proxy only allows for raw type definitions, it should allow for a schema too!

So here are the improvements I'm going to work on:
- [ ] make it possible to pass a `GraphQLSchema` instance
- [ ] make it possible to pass a schema as a JSON file and build it thanks to introspection query
- [ ] make it possible to mock what the `graphql` container returns
- [ ] update the proxy to use Apollo Client 2 and so links instead of `networkInterface`, it would open the door to pass custom links down the road!
