### ISSUE TITLE
Doesn't seem to do anything (empty star background).

### ISSUE THREAD

**Issue by shadowmint** [react-cosmos/react-cosmos#449]
### What's up?

Running 'cosmos' just gave an empty starry background.

On the cli:

```
$ npm start

> react-template@0.0.1 start /home/doug/react-play/tmp
> NODE_ENV=development cosmos

[ 'src/foo/foo.jsx', 'src/template.jsx' ]
[ 'foo', 'template' ]
[Cosmos] Using webpack config found at /home/doug/react-play/tmp/webpack.config.js
[Cosmos] See you at http://localhost:8989/
webpack built 83acf38b0ad6dacb23f5 in 3129ms
```

In the browser:

> bundle.js:810 GET http://localhost:8989/loader/index.html 404 (Not Found)

### Mkay, tell me more...

```
import * as glob from "glob";

var namer = componentPath => componentPath.match(/.*\/([^/]+)\.jsx$/)[1];
var components = glob.sync('src/**/*.jsx');
console.log(components);
console.log(components.map(namer));

module.exports = {
  componentPaths: components,
  webpackConfigPath: './webpack.config.js',
  getComponentName: namer
};
```

and in for example, foo.jsx:

```
import React from 'react';
import './template.scss';

export class foo extends React.Component {
  constructor() {
    super();
    this.state = {
      objects: [
        {type: "text", x: 10, y: 20, text: "Hello!", fill: "red"},
        {type: "rect", x: 50, y: 70, fill: "red"}
      ]
    };
  }

  render() {
    return (<div>hi</div>);
  }
}
```

As you can see from the console logs its certainly finding the components and mapping to the component name correctly, but... ?

Am I doing something wrong?

**Comment by skidding** [comment]
Hi @shadowmint,

It seems like Cosmos can't find an index.html for the Loader iframe. Please see [Loader index.html](https://github.com/react-cosmos/react-cosmos#loader-indexhtml) and let me know if it works or have any other question.

> #### Loader index.html
>
> *GET http://localhost:8989/loader/index.html 404 (Not Found)*
>
> The browser console might greet you with this error when using a custom webpack config. There are two methods for configuring the Loader index.html page:
>
> 1. Use [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin)
> 2. Put a static index.html file in your public path (see `publicPath` option below)
>
> **Using `html-webpack-plugin` is recommended** because it automatically injects the `<script>` tag in index.html. If you create your own index.html then make sure the script tag points to "main.js".
> 
> ```html
> <script src="./main.js"></script>
> ```

**Comment by skidding** [comment]
Please let us know if the issue persists.
