### ISSUE TITLE
Integrate react-error-overlay from Create React App

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#451]
### What's up?

CRA's react-error-overlay is pretty awesome. It handles build time and run time errors elegantly and has extra features like the ability to click on file paths and have them open inside the default OS editor.

### Mkay, tell me more...

Haven't investigated properly, but @gaearon said react-error-overlay is modular enough to be reused.

Free for all.

**Comment by gaearon** [comment]
cc @tharakawj @timer for awareness

**Comment by skidding** [comment]
For the record, I looked into this and here are my findings:
- Using `react-error-overlay` requires replacing the `webpack-hot-middleware/client` with `react-dev-utils/webpackHotDevClient`, which only supports webpack 3.x. This means we can't use it for now since Cosmos supports webpack 1 & 2 as well.
- A good strategy would be to check if the host project uses Create Create App and only use `react-dev-utils/webpackHotDevClient` in that case, defaulting to webpack-hot-middleware. This is great because we would know for sure CRA's error overlay works in a CRA project. Only problem is webpackHotDevClient works in tandem with webpack-dev-server, whereas Cosmos runs on a custom Express server with webpack-dev-middleware attached. Converting react-cosmos-webpack  to use webpack-dev-server might be good idea, but once again we're hit by compatibility issues. The latest WDS only works with webpack 2.x and above. The least intrusive strategy would be to conditionally use webpack-dev-server if host project already has it installed, maintaining the current implementation as a fallback. The nice think about webpack-dev-middleware is its webpack 1.x support. But I'm not sure if maintaining two server implementations is worth the effort, we might drop webpack 1.x before going to such lengths. Asking users to install a compatible version of webpack-dev-server on their own is also suboptimal, since some webpack frameworks (eg. Next.js) also don't use WDS.

Useful links:
- [CRA entry](https://github.com/facebookincubator/create-react-app/blob/2e82ebb3371731a5c4e346f310848ddb23fd0976/packages/react-scripts/config/webpack.config.dev.js#L56)
- [CRA dev server setup](https://github.com/facebookincubator/create-react-app/blob/01a0d737c79e02140c3cc0996d05ebd8a4eb3f84/packages/react-scripts/config/webpackDevServer.config.js#L97-L106)

I'm putting this on hold, but I welcome any ideas or initiatives. It's a pity we can't just piggy back on CRA's outstanding error handling when present, especially since we already reuse the webpack config.

**Comment by Timer** [comment]
https://github.com/react-cosmos/react-cosmos/pull/484

**Comment by skidding** [comment]
Closed by #484
