### ISSUE TITLE
Option to hide components without fixtures

### ISSUE THREAD

**Issue by aurbano** [react-cosmos/react-cosmos#459]
I've searched for similar issues but haven't found them - so apologies if this has been covered before.

I'm adding Cosmos to an existing large React app, and we'll add fixtures as we need them - so we have hundreds of components without a fixture showing up in the list, which is unnecessary for us.

Would it be possible to have a config setting/UI toggle to hide components that don't have a fixture?

**Comment by skidding** [comment]
Hi @aurbano,

I'm happy you brought this up. Components used to show up with an automatic empty fixture (another bad idea), and after a major refactor they ended up showing up without any action. I would like to get rid of this behavior and I am willing to push a patch release with the change because I'm 100% nobody depends on a list of actionless component names.

It would be great if somebody offered to create a PR for this. The solution is basically adding something like the following [here](https://github.com/react-cosmos/react-cosmos/blob/b5074fe4c81fc73869e5709ff56d414a2af43ee7/packages/react-cosmos-component-playground/src/components/FixtureList/index.js#L119)

```js
components.filter(c => Object.keys(filteredFixtures[c]).length > 0)
```

Thanks!

**Comment by everdimension** [comment]
> Components used to show up with an automatic empty fixture (another bad idea)

huh
I was about to create an issue that after updating to `2.0.0` components without fixtures do not work

How am I supposed to test `onChange` handlers on inputs with fixtures? Is there a `setState` method somewhere? May be docs are not good enough...

**Comment by skidding** [comment]
> huh
I was about to create an issue that after updating to 2.0.0 components without fixtures do not work

https://github.com/react-cosmos/react-cosmos/issues/431

**Comment by skidding** [comment]
> huh
I was about to create an issue that after updating to 2.0.0 components without fixtures do not work

Sorry for the confusion. If you were relying on empty fixtures you'll have to create those empty fixtures by hand for now.

> How am I supposed to test onChange handlers on inputs with fixtures? Is there a setState method somewhere? May be docs are not good enough...

All you can do at the moment is `onChange: val => console.log('change', val)` to see the selected value in your console log. This could be made better by https://github.com/react-cosmos/react-cosmos/issues/431, if @dfedynich or anybody else is able to make it happen.

**Comment by amrdraz** [comment]
Is this not effectively closed now?

**Comment by everdimension** [comment]
I guess so. Would be great though if documentation mentioned that creating at least an empty fixture is required.

**Comment by skidding** [comment]
@amrdraz Yes. But let's wait until #469 is merged, docs are updated and we move from v3 alpha to beta. Otherwise we might leave other people wondering the same thing hanging...

**Comment by skidding** [comment]
> I guess so. Would be great though if documentation mentioned that creating at least an empty fixture is required.

I agree. Once we get the v3 beta out the door the docs will be property updated. Can't wait to remove the docs sections regarding to `componentPaths` 😈

**Comment by skidding** [comment]
Closing this because in v3 only components with fixtures show up in the playground. See [Cosmos v3 BETA TESTING thread](https://github.com/react-cosmos/react-cosmos/issues/475).
