### ISSUE TITLE
`npm install --dev` is deprecated

### ISSUE THREAD

**Issue by joncass** [react-cosmos/react-cosmos#461]
### What's up?

The "getting started" section gives `npm install --dev react-cosmos-webpack` as a recommended command, but the `--dev` flag is deprecated in `npm install` (see e.g. https://github.com/npm/npm/issues/6200)

### Mkay, tell me more...

I think replacing it with either `--save-dev` or `--only=development` would work (to be honest, I'm actually not sure what the difference between those two flags is ...)

**Comment by skidding** [comment]
@joncass feel free to open a PR replacing `npm install --dev` with `npm install --save-dev` in docs and I will merge it.

**Comment by skidding** [comment]
Closed by #462
