### ISSUE TITLE
The `Loader` from `react-cosmos-loader` does not pass the state from fixture to the component

### ISSUE THREAD

**Issue by dedan** [react-cosmos/react-cosmos#466]
### What's up?

I have a fixture that passes state to the component, so I can easily observe how it looks for different internal states. Actually, I even pass down the state of a child component that I marked via a `ref`. My fixture currently looks the following:

```js
{
  "props": {
    "isShown": true,
    "event": {
      "isTemp": false
    }
  },
  "state": {
    "test": true,
    "children": {
      "content": {
        "localEvent": {
          "isTemp": false
        },
        "isConfigMode": true
      }
    }
  }
}
```

That works perfectly fine in the cosmo explorer, however the state is not passed down when I use the `Loader`.

### Mkay, tell me more...

I had a quick look at the code and it looks like implementing a `StateProxy` similar to the [`PropsProxy`](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-loader/src/components/PropsProxy/index.js) should be the right thing to do.

**Comment by skidding** [comment]
@dedan the docs aren't great for using the Loader programmatically, but luckily you're only one step away!

The State proxy already exists and is [always added](https://github.com/react-cosmos/react-cosmos/blob/ec89e3964f2e8c84455f3fcb20c8f7cb9041b8ed/packages/react-cosmos-loader/src/mount.js#L28-L450) when using the UI. But, we need to manually pass it when using the `<Loader />` component manually.

Your code should look like this:

```jsx
import createStateProxy from 'react-cosmos-state-proxy';

const StateProxy = createStateProxy();

render(
  <Loader
    proxies={[StateProxy]}
    component={Component}
    fixture={fixture}
  />
);
```

Let me know if this works.

**Comment by dedan** [comment]
Hey @skidding, thanks a lot for the fast and super helpful response. That's exactly what I needed!

Thanks a lot, I'm closing the issue.

**Comment by skidding** [comment]
Perfect! Happy to help.
