### ISSUE TITLE
Wrapper/Parent for component in fixture (v3)

### ISSUE THREAD

**Issue by mbohgard** [react-cosmos/react-cosmos#489]
I'm trying to wrap my component in the fixture file or set parent styles or something to the playground.
My last try was to wrap my component in a HOC like so:
```
import * as React from "react";
import { Input } from "common-components/components/Atoms/Input";

const padded = (WrappedComponent: any) => {
  class Wrapper extends React.Component {
    static displayName = WrappedComponent.name;

    render() {
      return (
        <div style={{ padding: "50px", background: "white" }}>
          <WrappedComponent {...this.props} />
        </div>
      );
    }
  }

  return Wrapper;
};

export default {
  component: padded(Input),
  props: {
    label: "Username",
    type: "text"
  }
};
```
but Cosmos is unable to merge several fixtures for the Input component, only showing the last one (alphabetically).

Since there are no really documentation for v3, is there a better way to do this or to override default playground styles in a fixture?

**Comment by skidding** [comment]
Proxies are great for this. Here's an ad-hoc example:

```js
import React from 'react';

const DEFAULT_PADDING = 50;

const PaddingProxy = props => {
  const { value: NextProxy, next } = props.nextProxy;
  const { padding = DEFAULT_PADDING } = props.fixture;

  return (
    <div style={{ padding, background: 'white' }}>
      <NextProxy {...props} nextProxy={next()} />
    </div>
  );
};

export default PaddingProxy;
```

Now, if you've not configured any other proxies so far, create `cosmos.proxies.js` next to your `cosmos.config.js`. Inside, put this:

```js
import PaddingProxy from './whever-you-want-to-put-it';

export default [PaddingProxy];
```

Works?

**Comment by mbohgard** [comment]
Actually it does... :P But I need to read up on that.. don't really understand what's going on. How can I, from my fixtures, choose what proxies to use? I mean if I don't want that padding in all my fixtures for ex.

**Comment by skidding** [comment]
Almost nothing changed in v3 regarding proxies, so you can check out the [Proxies docs](https://github.com/react-cosmos/react-cosmos#proxies).

There's no way to select proxies per fixture, but proxies are usually **activated** via fixtures.

I don't know if you realized, but in the proxy I put together the padding is read from `fixture.padding`, so you can set a different padding per fixture. Now if you wanted to make it opt-in, you could change the proxy to something like this:

```js
const PaddingProxy = props => {
  const { value: NextProxy, next } = props.nextProxy;
  const { padded, padding = DEFAULT_PADDING } = props.fixture;

  // Proxy isn't activated unless fixture.padded is true
  if (!padded) {
    return <NextProxy {...props} nextProxy={next()} />;
  }

  return (
    <div style={{ padding, background: 'white' }}>
      <NextProxy {...props} nextProxy={next()} />
    </div>
  );
};
```

Then fixtures could look like this:

```js
// Not padded
{
  props: {}
}
```

```js
// Padded with default 50px padding
{
  padded: true,
  props: {}
}
```

```js
// Padded with custom 100px padding
{
  padded: true,
  padding: 100,
  props: {}
}
```

**Comment by mbohgard** [comment]
Yes I realised the padding prop. Ah, that's awesome. Looks great :) Nice API! ;P

**Comment by mbohgard** [comment]
Now I'm just missing some TypeScript types.. ;P

**Comment by skidding** [comment]
Haha, v3 [includes Flow types](https://github.com/react-cosmos/react-cosmos/blob/v3-docs/packages/react-cosmos-shared/src/react/types.js#L6-L11). Maybe we can include TS types on the side for Proxy props specifically.

**Comment by mbohgard** [comment]
Right, nice, here are the proxy TypeScript types needed for this specific case:
```
export type LinkedItem<Item> = {
  value: Item;
  next: () => LinkedItem<Item>;
};

export type ProxyProps = {
  nextProxy: LinkedItem<React.ComponentType<ProxyProps>>;
  fixture: { [s: string]: string };
  onComponentRef: Function;
  onFixtureUpdate: Function;
};
```

**Comment by skidding** [comment]
Cool! Pretty similar. 

But fixtures can contain more than strings, so maybe `fixture: { [s: string]: any }`? BTW, I know zero TS.

Also, might be a silly question, but how does React export both Flow & TS types. More specifically, where does `React.ComponentType` come from? 🤔

**Comment by mbohgard** [comment]
Yes, I guess in this case "any" could be an option, though it hurts every time you set an any type.... 😅

Microsoft owns the organization @types on npm and you have to do a `yarn add @types/react` (if the lib doesn't provide types built in), but when you have, React and the React types share it's namespace so the types are automagically available like that for convenience 😎

**Comment by skidding** [comment]
Good to know. Did a bit of digging to understand how it works on the Flow side. It seems React types are  [included in Flow itself](https://github.com/facebook/flow/blob/2a8bc500500a0d208e604bbb6dad4195154f39fa/lib/react.js#L136) and bundled in the standard Flow binary. Weird.

![image](https://user-images.githubusercontent.com/250750/32246861-aad6a8d0-be80-11e7-8278-5566773dc843.png)
