### ISSUE TITLE
Resulting Folder Tree structure with more depth?

### ISSUE THREAD

**Issue by alp82** [react-cosmos/react-cosmos#496]
### What's up?

I would like to have the root folders containing my components also shown in react-cosmos so that i can better navigate and collapse the view.

### Mkay, tell me more...

Let's take this folder structure:
![image](https://user-images.githubusercontent.com/966342/32415248-e48d2630-c236-11e7-8031-7ab919ce5497.png)

This results in:
![image](https://user-images.githubusercontent.com/966342/32415252-f6d13372-c236-11e7-90ea-a8ff59bb6ee6.png)

Is it possible to have the `ui` folder as parent of that tree as well? The reason is that i have multiple folders on the same level as `ui` and i want to resemble the same structure in react-cosmos.

**Comment by skidding** [comment]
Cosmos determines the common dir between all components and removes it to keep the tree clean. 
Do you have any fixture in any other sibling of `ui`? As soon as you do, `ui` along with the sibling dir with components will show up.

I think it's redundant to show a single dir. It's the same as `Show all / Hide all` (or Expand/Collapse), a feature I'd like to add in the future. 

There are a number of ways Cosmos could be configured to achieve this:
- A `showParentDir` bool option
- A `transformNamespace` func option which could be useful in other situations as well. In this case it would be
  ```
  transformNamespace: ns =>  ns ? `ui/${ns}` : 'ui'
  ```

But I personally don't find this very useful so unless someone offers to help I don't think it will be implemented very soon.

**Comment by alp82** [comment]
I completely agree witrh you that redundancy is not needed. However, there is one other component with  fixtures placed in another root folder `modules`. It is shown without any parent folder at all:

![image](https://user-images.githubusercontent.com/966342/32604356-9fb690ae-c54d-11e7-8d5e-e7b49a075df1.png)

`CommentWithReplies` should be in `modules`, everything else in `ui`.

I suspect this is related to #495.

**Comment by skidding** [comment]
> I suspect this is related to #495.

I agree. Unless a different bug is discovered, we can expect the tree to have the proper depth once the nesting of each fixture is properly determined. So I think we can close this for now and focus on #495

**Comment by alp82** [comment]
#495 indeed solved this one, this wasn't a problem after all and works as expected
