### ISSUE TITLE
File paths not resolved for components in .jsx files when importing them in fixtures

### ISSUE THREAD

**Issue by iw-dweaver** [react-cosmos/react-cosmos#505]
### What's up?
In the latest beta (3.0.0-beta.9), when components are imported into fixture files from files with a .jsx extension (or any extension that is not .js for that matter), cosmos is unable to resolve that file path.

### Mkay, tell me more...

The issue is `require.resolve` throws and we end up with null in our component filePaths.

https://github.com/react-cosmos/react-cosmos/blob/385c1218a74fb3350e42fc41698d1c49924656b5/packages/react-cosmos-voyager2/src/server/extract-components-from-fixture-file.js#L103

**Comment by skidding** [comment]
@dan-weaver please try `react-cosmos@3.0.0-beta.10`

**Comment by dan-weaver** [comment]
@skidding thanks works nicely and thanks for the test case!
