### ISSUE TITLE
Add fixture handler for custom component setup

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#519]
### What's up?

Quick intro to get to the core of the problem. Bear with me...

Fixtures are responsible to take a component into any of its supported states. Let's think of a component with three possible states: A (init), B (fetching) and C (with data loaded). We might know what C looks like (be it local state or Redux state), but we often don't want to inject it directly because it's not representative of the component's real life behavior. It's common for actions to be dispatched in `componentDidMount`, so we end up with situations where we mock C but component will go to B anyway once mounted. With this in mind, I think **fixtures should *guide* components as they follow their natural state transition path instead of injecting the _final_ state.** The fetch/XHR proxies are good examples for this.

But we can't mock everything (yet), so sometimes we need a simulate some actions to put components in some states. Here's an example: The Playground component itself. It loads an iframe and expects a `loaderReady` event via `window.postMessage` to get the fixture list. How do we simulate the `ready` Playground state in tests? We trigger fake postMessage events ourselves. But how can we do this with fixtures? Context: My plan is to have fixtures control 100% of the component setup, and make it available in both tests or the Playground UI.

Here's an example of something I've been experimenting with. Meet `fixture.onInit`.

```js
export default {
  component: ComponentPlayground,
  // other parts of fixture not relevant...
  onInit() {
    window.postMessage(
      {
        type: 'loaderReady',
        fixtures: {
          ComponentA: ['foo', 'bar'],
          ComponentB: ['baz', 'qux']
        }
      },
      '*'
    );
  }
};
```

### Mkay, tell me more...

The above example has actually been simplified. Two things to consider:
- Sometimes we need the component ref here, so it's an argument of `fixture.onInit`.
- There are a number of **async** events that take place before it's natural to trigger the `loaderReady` event. No problem, `fixture.onInit` works great with async/await. Here's the full example:

```js
export default {
  component: ComponentPlayground,
  // other parts of fixture not relevant...
  async onInit(componentInstance) {
    await until(() => componentInstance.state.loaderStatus === OK);
    window.postMessage(
      {
        type: 'loaderReady',
        fixtures: {
          ComponentA: ['foo', 'bar'],
          ComponentB: ['baz', 'qux']
        }
      },
      '*'
    );
  }
};
```

This works pretty well. The test helpers wait for the async `onInit` to be resolved before entering the tests and the UI gets to share the same setup. This is the first step in introducing the test helpers most of you heard me talk about. 

@flaviusone @maxsalven @NiGhTTraX @ovidiubute @tkjone @xavcz I'd love to get some feedback on this. Eg.
- Does this make sense or have I explained it poorly?
- Is the API intuitive? I'm open to naming suggestions for `onInit`
- Any concerns, possible bugs or unexpected behavior?

Thanks!

**Comment by xavcz** [comment]
> fixtures should guide components as they follow their natural state transition path instead of injecting the final state

These are wise words (that resonate strongly with me): this makes a lot of sense!

As far as I'm concerned, using Cosmos mainly in the context of Apollo, I'm expecting an API like that to work really well to deal with loading / error / success states.

Using an API like `until`, could it also open the door to work with observables? Staying in the context of this component usually going from A (init) -> B (fetching) -> C (success) and an occasional state D (error), we could listen to these states with `next`/`complete`/`error` native observables methods and provide it the relevant fixture?

**Comment by skidding** [comment]
@xavcz I'm happy you say that because I wasn't sure if that idea is going to resonate with others. It took me a lot to realize something that seems obvious in retrospect.

I don't have experience with Observables but I see what you mean. Not sure how they could be integrated at the Cosmos level, but they can definitely be used to complement this feature. `until` is a different topic, but a helper I think will reshape how I write a lot of async component tests. I've been using `await afterOngoingPromises` to wait for mocked async actions to resolve, but found that sometimes a component has a chain of async actions which take more than one micro loops (re JS's event loop), so I wouldn't know when the component is ready for assertions. This is where `until` comes in, a concept I borrowed from E2E testing. You give it a callback that returns a Boolean and it returns a promise that resolves the first time the callback response is true. It works great with await to "pause" execution. It's very agnostic. You might seem the source here https://github.com/skidding/async-until/blob/master/index.js. Coupled with the fact that onInit receives the component instance, you can wait until the component is in an actual state, which is a 100% guarantee you can start asserting on it. If you only got a confirmation that an API request completed it might still take an extra async step for that to reflect into the component's state (especially given how setState is now async and all), so we couldn't confidently follow up with assertions after a data event we subscribed to.

**Comment by maxsalven** [comment]
I don't really understand this, sorry. Is it possible to get a real world style example of what you're talking about? Thanks!

**Comment by skidding** [comment]
@maxsalven Sure. The philosophy was meant to provide more context but is probably more confusing than helpful at this point. Here's a concrete example.

Going back to the Playground fixture.

```js
export default {
  component: ComponentPlayground,

  props: {
    /* not important */
  },

  state: {
    loaderStatus: READY,
    fixtures: {
      ComponentA: ['foo', 'bar'],
      ComponentB: ['baz', 'qux']
    }
  },

  fetch: [
    {
      matcher: 'end:/mock/loader/index.html',
      response: 200
    }
  ]
};
```

Flow: The playground does a fetch call to see if Loader html URL is responding positively. If it does, Playground renders the iframe and then expects for a message from inside the iframe.

The problem here is that the **`state` needs to be applied LATER, after the component does (and responds to) the fetch call.** Our "ready" state will be overridden as soon as the fetch call ends and Playground goes into an intermediary "ok" state. This [ugly hack](https://github.com/react-cosmos/react-cosmos/blob/2c71da7f489080837229eff70e86bf5020d3db5c/packages/react-cosmos-playground/src/components/ComponentPlayground/index.js#L259-L268) was added to make this fixture work.

A first iteration with `onInit` would look like this:

```js
export default {
  component: ComponentPlayground,

  props: {
    /* not important */
  },

  fetch: [
    {
      matcher: 'end:/mock/loader/index.html',
      response: 200
    }
  ],

  async onInit(component) {
    // fetch and setState is async, so we have to wait until loaderStatus has been updated
    await until(() => component.state.loaderStatus === OK);

    component.setState({
      loaderStatus: READY,
      fixtures: {
        ComponentA: ['foo', 'bar'],
        ComponentB: ['baz', 'qux']
      }
    });
  }
};
```

This is better, but still not ideal. Instead of mocking the "ready" state, it's better to **fake the postMessage event from the iframe and let the component react and generate its state.** This provides more code coverage.

```js
export default {
  component: ComponentPlayground,

  props: {
    /* not important */
  },

  fetch: [
    {
      matcher: 'end:/mock/loader/index.html',
      response: 200
    }
  ],

  async onInit(component) {
    // fetch and setState is async, so we have to wait until loaderStatus has been updated
    await until(() => component.state.loaderStatus === OK);

    window.postMessage(
      {
        type: 'loaderReady',
        fixtures: {
          ComponentA: ['foo', 'bar'],
          ComponentB: ['baz', 'qux']
        }
      },
      '*'
    );
  }
};
```

Does this help?

**Comment by skidding** [comment]
Update. I've completed the work for this in #528

Here's the gist:
- Renamed `fixture.onInit` to `fixture.ref` to make it more self explanatory and to emphasize it's a class component feature.
- This feature allowed removing a hack in the Playground and shortened the Playground test files by aprox. 500 LOC, which I believe makes them a lot easier to follow and extend.
- This paves the way for the `createContext` test API. It's already included in this PR but not as a public API.
- Added a brief README section on this:

<img width="914" alt="screenshot 2017-11-23 16 21 22" src="https://user-images.githubusercontent.com/250750/33179619-5e56d9e8-d06a-11e7-89af-08a0ed4d923f.png">

Still, I'm aware this is too low level to understand if you're not as intimate with Cosmos as I am, so I don't expect any review at this point (tho **any feedback is highly appreciated**). The subsequent PR related to this will be more intuitive.
