### ISSUE TITLE
Dismiss run time error overlay on fixture change

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#521]
### What's up?

After the CRA runtime error overlay is triggered it stays open indefinitely until we click on the X button. This makes sense in a normal app because runtime errors can corrupt the App state. However, in Cosmos we can move from one component to another and the error overlay becomes irrelevant.

### Mkay, tell me more...

To close the error overlay programmatically we can import and call the `dismissRuntimeErrors` function from the `react-error-overlay` package. **Note: [this PR](https://github.com/facebookincubator/create-react-app/pull/3414) needs to be published for this method to be available.**

I see two possibilities here:
1. Automatically close error overlay when component changes
2. Automatically close error overlay when fixture changes

The 1st is more conservative, but I think we can safely go with the 2nd as well. The only risk when dismissing the runtime overlay and opening a fixture of the same component is that we might get the same error and the overlay will be triggered again.

Suggestion for where to implement this: In the [Router's onChange hander](https://github.com/react-cosmos/react-cosmos/blob/2c71da7f489080837229eff70e86bf5020d3db5c/packages/react-cosmos-playground/src/index.js#L40), which gets triggered when the URL changes and receives `component` and `fixture` as params.

**Comment by maxsalven** [comment]
A related item, if you click on a fixture and get the overlay, then pressing escape doesn't clear the overlay until you click on the iframe. Would be nice to wire up an escape click in the FixtureList to close the overlay as well.

**Comment by jozsi** [comment]
Done via #535 - still depends on the new version of `create-react-app`

**Comment by jozsi** [comment]
Updated `react-error-overlay` via #574
