### ISSUE TITLE
cosmos 3 starts up with Target container is not a DOM element.

### ISSUE THREAD

**Issue by bugzpodder** [react-cosmos/react-cosmos#526]
### What's up?
Installed Cosmos 3.0 got the following error.  I briefly looked around for a solution but was not able to found one.  I usually have issues with the other tools (styleguidist/story book) and were fixed by adding NODE_PATH=src/ but it did not make a difference here.

Target container is not a DOM element.
▼ 13 stack frames were expanded.
invariant
node_modules/fbjs/lib/invariant.js:42
renderSubtreeIntoContainer
node_modules/react-dom/cjs/react-dom.development.js:15186
render
node_modules/react-dom/cjs/react-dom.development.js:15296
mount
node_modules/react-cosmos-loader/lib/mount.js:63
./node_modules/react-cosmos/lib/client/mount.js.exports.default
node_modules/react-cosmos/lib/client/mount.js:44
run
node_modules/react-cosmos/lib/client/loader-entry.js:11
./node_modules/react-cosmos/lib/client/loader-entry.js
node_modules/react-cosmos/lib/client/loader-entry.js:14

**Comment by bugzpodder** [comment]
ok fixed cosmos-config with the correct root element

**Comment by skidding** [comment]
> ok fixed cosmos-config with the correct root element

Happy to hear! 

But I'm a bit curious about the initial error. If you don't specify a `containerQuerySelector` Cosmos should [automatically create a new div](https://github.com/react-cosmos/react-cosmos/blob/0aa23a8de11f9190e1b86813b7d0668f8e224f83/packages/react-cosmos-loader/src/mount.js#L10-L21) and put everything there.

So maybe you had already set `containerQuerySelector` to an invalid value? Thanks!

**Comment by bugzpodder** [comment]
Yeah containerQuerySelector was added automatically for me, but my app had a custom element.  instead of #root, it was #react-root.  As you mentioned modifying containerQuerySelector and updating it to the correct id fixed it for me.
