### ISSUE TITLE
proxies needs to be installed as dev-dependencies

### ISSUE THREAD

**Issue by bugzpodder** [react-cosmos/react-cosmos#533]
### What's up?

When I tried to use cosmos proxies as explained in README, they could not be resolved when starting cosmos server.
I am using CRA with cosmos 3.0
> cat src/cosmos.proxies.js 
import createFetchProxy from 'react-cosmos-fetch-proxy';
import createReduxProxy from 'react-cosmos-redux-proxy';
import createRouterProxy from 'react-cosmos-router-proxy';
import createLocalStorageProxy from 'react-cosmos-localstorage-proxy';
import { configureStore } from './configureStore';

I had to install them as dev-dependencies separately using npm install --save-dev:
  "devDependencies": {
    "react-cosmos-fetch-proxy": "^3.0.0",
    "react-cosmos-localstorage-proxy": "^3.0.0",
    "react-cosmos-redux-proxy": "^3.0.0",
    "react-cosmos-router-proxy": "^3.0.0"

### Mkay, tell me more...

I am not sure this is actually needed, if it is it should be mentioned in the README.  but I looked over in the examples and didn't see anyone else doing it.

**Comment by skidding** [comment]
@bugzpodder this is the expected behavior. Proxies are optional and thus are only installed when/where needed. Do you think the docs are misleading? Feel free to suggest improvements.

**Comment by bugzpodder** [comment]
Thanks, just want to confirm this behavior.  I will see if I can create a PR for updating the doc.
