### ISSUE TITLE
Sorting of HOC'd Components in File Tree

### ISSUE THREAD

**Issue by maxsalven** [react-cosmos/react-cosmos#544]
### What's up?

Components with HOC names get sorted based on their actual component names (`withRouter(Import)`) rather than their parsed component names (`Import withRouter`), which means the order in which we display components can be 'wrong' with respect to what UI displays.

<img width="225" alt="screen shot 2017-12-09 at 5 04 43 pm" src="https://user-images.githubusercontent.com/4144910/33794268-6be63e82-dd03-11e7-8ed9-fad84d3e7ef0.png">

**Comment by skidding** [comment]
Fixed by #876
