### ISSUE TITLE
Trying to install, can't find loader/index.html

### ISSUE THREAD

**Issue by llimllib** [react-cosmos/react-cosmos#551]
### What's up?

Trying to install cosmos for [CMS Design System](https://github.cms.gov/CMS-WDS/pet-shared-components) I followed the install instructions in this way:

```
mkdir examples/cosmos && cd examples/cosmos
yarn init -y
yarn add --dev react-cosmos babel-preset-env babel-preset-react babel-loader style-loader css-loader html-webpack-plugin
echo "module.exports = {
  rootPath: '../..',
};
" > cosmos.config.js
# edit package.json to add 
# "scripts": {
#  "cosmos": "cosmos",
#  "cosmos:export": "cosmos-export"
# }
yarn cosmos
```

What I get at localhost:8989 is the spaceman with the message `Almost there... Install html-webpack-plugin in your dev dependencies `, which I have already done. I also get `GET http://localhost:8989/loader/index.html 404 (Not Found)`.

From browsing the issues, It seems like there used to be docs on what to do about that message, but there are no longer?

### Mkay, tell me more...

Have I failed to follow the instructions somehow? Are the instructions missing a step? What should I try next?

**Comment by llimllib** [comment]
Ummm, I was sure that was what I did, but the process of recreating the issue for this ticket caused it to work. Very weird.

**Comment by skidding** [comment]
> Ummm, I was sure that was what I did, but the process of recreating the issue for this ticket caused it to work. Very weird.

😄

Maybe you had to restart the server. Happy to hear it works.

**Comment by llimllib** [comment]
I definitely restarted the server many times before. Very strange. :shrug:
