### ISSUE TITLE
Create webpack context matching config.fileMatch

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#555]
### What's up?

Follow-up to #542 and #531 

Sometimes you create a new fixture and Cosmos doesn't detect it, so you have to restart the server (annoying). At first we made a very broad `require.context` which detected all files changes but caused issues with a number of people because too many files were bundled, leading to either errors or poor build performance. We've reverted that, but there's a possibility to fix this in an elegant way.

### Mkay, tell me more...

We could use https://github.com/fitzgen/glob-to-regexp to convert `config.filePaths` globs to a regexp which we could send to `require.context`. The only issue is that config.filePaths is an array of globs. If we manage to merge the globs or the resulting regular expressions, and `glob-to-regexp` is reliable, we no longer have to watch for file changes ourselves and this becomes a much easier task.

**Comment by xavcz** [comment]
Discussion moved in #613 🆗
