### ISSUE TITLE
React Native using proxies and fixtures with Enzyme

### ISSUE THREAD

**Issue by Aidurber** [react-cosmos/react-cosmos#562]
The fixtures and proxies are so beautifully useful, I'd love to be able to use them in React Native. I tried to get them working in a small project but the dependency on React DOM makes it throw a wobbler. I thought using Enzyme with react-native-mock (Airbnbs recommended lib for using Enzyme with RN).

I couldn't get it working due to react native mock having a few issues at the minute.

My question is, when those issues are resolved. Do you believe that I could use the proxies and fixtures from react-cosmos?

**Comment by skidding** [comment]
> My question is, when those issues are resolved. Do you believe that I could use the proxies and fixtures from react-cosmos?

I hope so. In theory you should and I'd be happy to help investigate if something unexpected occurs.

Enzyme or not, I'd be very curios to see how Cosmos behaves with RN. I don't have experience so I never got around to testing it. 

To make the Playground UI work with RN requires some foundational work, as mentioned in this passage from the [Roadmap discussion](https://github.com/react-cosmos/react-cosmos/issues/546):

> 
![image](https://user-images.githubusercontent.com/250750/34178106-51958b0e-e506-11e7-9c5e-b3a2818d5531.png)

But, unless I'm missing something, the headless Loader should be fairly easy to set up. For example, here are the few lines that tie the Cosmos Loader to ReactDOM: [packages/react-cosmos-loader/src/dom-renderer](https://github.com/react-cosmos/react-cosmos/blob/f26b084d36a3472dafcb89a95e87a1c070713b2d/packages/react-cosmos-loader/src/dom-renderer.js#L8-L21). The rest of that file is just finding a dom element based on an optional query selector or creating on the spot.

**Comment by skidding** [comment]
Both Cosmos Classic and Next _do_ work with React Native now.
