### ISSUE TITLE
Support webpack config that exports a function

### ISSUE THREAD

**Issue by mmacaula** [react-cosmos/react-cosmos#564]
### What's up?
react-cosmos seems to not support a webpack configuration that exported a function as defined [here](https://webpack.js.org/configuration/configuration-types/#exporting-a-function).  This led the output to suggest I needed the HTML plugin (which I did have).  

### Mkay, tell me more...
I tried solutions described in #449 but ultimately only got it to work when I duplicated our webpack function config to a custom config file that exported a plain JS object.  Obviously this works in the short term but overall found the experience difficult from the false positive (`[Cosmos] Using webpack config found at webpack.config`), without any other errors.

**Comment by evilj0e** [comment]
It supported by default, i think.
I found that you should specify path to webpack config from root. And it works.

**Comment by skidding** [comment]
Hi @mmacaula, I just opened a PR #647 to add support for function webpack configs. I followed the specs from [your link](https://webpack.js.org/configuration/configuration-types/#exporting-a-function) and the config function is called with `(env, argv)`. Can you please take a look?

**Comment by mmacaula** [comment]
Yep worked for me on my function webpack config!  Sorry it took awhile to confirm.  Thanks!!!
