### ISSUE TITLE
Decorator Proxy

### ISSUE THREAD

**Issue by maxsalven** [react-cosmos/react-cosmos#568]
I'd like to create a proxy that allows me to specify a `Decorator` component that wraps my actual fixture `component`.

```jsx
import MyComponent from "../"
const SimpleDecorator = ({children}) => (<div style={{backgroundColor: 'red'}}>{children}</div>)

export default {
  component: MyComponent,
  decorator: SimpleDecorator,
}
```

I appreciate I could just create a new component that is already decorated, however then the component name in the fixture file tree will be that of the decorator. Plus I have to manually create the new wrapped component in any fixture where I want to decorate something.

I thought a simple proxy might work:
```jsx
import React from "react";

export default () => {
  const DecoratorProxy = (props: ProxyProps) => {
    const { nextProxy, fixture } = props;
    const { value: NextProxy, next } = nextProxy;

    const nextProxyEl = <NextProxy {...props} nextProxy={next()} />;

    if (!fixture.decorator) {
      return nextProxyEl;
    }

    const Decorator = fixture.decorator;
    return <Decorator>{nextProxyEl}</Decorator>;
  };

  return DecoratorProxy;
};
```

However, if I want a more advanced decorator, such as decorating a controlled input so that changes can be seen:

```jsx
// @flow

import React from "react";

import type { Element } from "react";
type Props = { value: string, children: Element<any> };
type State = { value: string };

class Decorator extends React.Component<Props, State> {
  state = { value: this.props.value };
  render() {
    const { value, children, ...childProps } = this.props;
    const stateValue = this.state.value;
    return React.cloneElement(children, {
      value: stateValue,
      onChange: value => {
        this.setState({ value });
      },
      ...childProps,
    });
  }
}

export default Decorator;
```

Then this does not work, as I get an error saying "this.props.onChange is not a function". I'm assuming it's something to do with the PropsProxy simply passing the `fixture.props` and not including those props injected by the decorator? If so, would we be interested in adding 'proper' support for `fixture.decorator`?

**Comment by skidding** [comment]
Before addressing the bigger question about how to handle decorators in general, I'll tweak your example to try to make it work and see if I understood what you're trying to do.

```diff
import React from "react";

export default () => {
  const DecoratorProxy = (props: ProxyProps) => {
    const { nextProxy, fixture } = props;
    const { value: NextProxy, next } = nextProxy;

    const nextProxyEl = <NextProxy {...props} nextProxy={next()} />;

    if (!fixture.decorator) {
      return nextProxyEl;
    }

    const Decorator = fixture.decorator;
-    return <Decorator>{nextProxyEl}</Decorator>;
+    return <Decorator {...fixture.props}>{nextProxyEl}</Decorator>;
  };

  return DecoratorProxy;
};
```

In other words, the DecoratorProxy is creating the Decorator element and should pass it the props it needs (in this case fixture.props but you could also send it the entire fixture).

@maxsalven Does this work?

**Comment by jozsi** [comment]
@maxsalven - you might want to take a look at my [wrapper proxy](https://github.com/jozsi/react-cosmos-wrapper-proxy). I wonder if we could make it support more use cases, like this. Any ideas/contributions are welcome!

**Comment by jozsi** [comment]
HOC/Decorator support has landed in [react-cosmos-wrapper-proxy](https://github.com/jozsi/react-cosmos-wrapper-proxy#hoc) `v1.2.0`

**Comment by skidding** [comment]
@jozsi cool stuff!

For the record, I'll be drafting a new Cosmos API that might make the need for this proxy obsolete (sorry 😅), but for the moment it's very useful!

**Comment by skidding** [comment]
Cosmos Next decorators remove the need for this.
