### ISSUE TITLE
What is required NodeJS version to run react-cosmos?

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#573]
### What's up?

Could you specify the required version of NodeJS to be installed to run react-cosmos?
Could you compile the final bundle according to ES5 syntax rules?

### Mkay, tell me more...

We have to use NodeJS 5.x.x version for several reasons for the current project. We are using react-cosmos 2.0.0-beta.x (react-cosmos-webpack to be exactly) for now. It works almost fine. But we want to update it to the latest version. Unfortunately NodeJS 5.x.x. can't process ECMAScript 2015 syntax, that you use in your bundle. Could we assume, that react-cosmos final bundle will be fully compiled according to ES5 syntax rules in the future updates or did you decide to move to ECMAScript 2015 finally?

**Comment by skidding** [comment]
> Could you specify the required version of NodeJS to be installed to run react-cosmos?

Unfortunately we lost track of that. If anyone wants to do some testing that would be great. But it should work with old versions of Node. Cosmos repo requires Node >=6.x **if you want to be a developer to Cosmos.** As a user, Node 5 and older should work.

> Could you compile the final bundle according to ES5 syntax rules?

All packages are already compiled and published as ES5 on npm. If you look each `package.json` they point to `packages/*/lib/*`, which is where we generate the compiled `src` dirs.

> We are using react-cosmos 2.0.0-beta.x (react-cosmos-webpack to be exactly) for now. It works almost fine. But we want to update it to the latest version.

It should continue to work. Please let us know if it doesn't.

> Could we assume, that react-cosmos final bundle will be fully compiled according to ES5 syntax rules in the future updates or did you decide to move to ECMAScript 2015 finally?

The former. Every Cosmos package is published as compiled ES5. 👌

**Comment by skidding** [comment]
Closing this as there doesn't seem to be any issue. Let me know otherwise.
