### ISSUE TITLE
Integration with redux-form

### ISSUE THREAD

**Issue by razagill** [react-cosmos/react-cosmos#575]
### What's up?
Trying to integrate `react-cosmos` with `redux-form` using the redux proxy. The dispatch isn't working.

### Mkay, tell me more...
The reducer is working fine as I can see in the redux devTools, however, when clicking on the submit button of the form, instead of getting the actual form values i'm getting a `Proxy` object.

Simple form component:
```
mport * as React from 'react';
import { Field, reduxForm } from 'redux-form';

class SimpleForm extends React.Component<{}, {}> {
  public render() {
    return (
      <form onSubmit={(val) => console.log(val)}>
        <div>
          <label htmlFor="firstName">First Name</label>
          <Field name="firstName" component="input" type="text"/>
        </div>
        <div>
          <label htmlFor="lastName">Last Name</label>
          <Field name="lastName" component="input" type="text"/>
        </div>
        <div>
          <label htmlFor="email">Email</label>
          <Field name="email" component="input" type="email"/>
        </div>
        <button type="submit">Submit</button>
      </form>
    );
  }
}
export default reduxForm({
  form: 'seatReservation'
})(SimpleForm);
```

cosmos.proxies.js
```
import createReduxProxy from 'react-cosmos-redux-proxy';
import { createStore, applyMiddleware } from 'redux';
import { rootReducer } from '../../src/store';
import { devToolsEnhancer } from 'redux-devtools-extension';

const ReduxProxy = createReduxProxy({
  createStore: (initialState) => {
    const store = createStore(
      rootReducer,
      initialState,
      devToolsEnhancer()
    );

    return store;
  }
});

export default [
  ReduxProxy
];
```
my fixture file
```
import SimpleForm from '../../components/SimpleForm';

export default {
  component: SimpleForm,
  reduxState: {}
};
```
On clicking submit I'm getting this in the console
`Proxy {dispatchConfig: {…}, _targetInst: FiberNode, nativeEvent: Event, type: "submit", target: form, …}`

**Comment by skidding** [comment]
Hi @razagill

At a glance it doesn't look like anything's wrong. The `Proxy` object is probably just a submit event, but it looks odd because React generates synthetic (custom) DOM events.

I'm not experienced with `redux-form`, but it seems like `form onSubmit` should be bound to a specific prop generated by the `reduxForm` HoC. I was looking at this example: https://codesandbox.io/s/mZRjw05yp

**Comment by razagill** [comment]
@skidding damn that was it. I just had to wrap it in another component and pass `onSubmit` instead of `handleSubmit`. Thanks a lot :)

**Comment by kfern** [comment]
@razagill @skidding 

Would be possible a simple and complete example?

**Comment by skidding** [comment]
@kfern I linked a [CodeSandbox example](https://codesandbox.io/s/mZRjw05yp) in my previous message. It's taken from the [redux-form README](https://github.com/erikras/redux-form#-code-sandboxes-). Are you having trouble making Cosmos work with redux-form?

**Comment by kfern** [comment]
@skidding I want to try cosmos with redux but I have not started yet. In the repo there is no example

**Comment by skidding** [comment]
You're right. There used to be but now there isn't! 🤕

If you don't mind, can you please create an issue for this? Myself or someone else can pick it up later. Thanks!

**Comment by kfern** [comment]
@skidding Done. https://github.com/react-cosmos/react-cosmos/issues/576. Thanks :-)

**Comment by razagill** [comment]
@kfern sure, I already posted my example code in the issue so taking from there here are the two changes you need to make.
The `onSubmit` hook needs to be passed as props to your form component, since redux-form will wrap that component this will mostly be any other component that is using the form component.

Taking the above example calling `SimpleForm` would then be something like:
```
<SimpleForm onSubmit={(val) => console.log(val)}/>
```

And remove the hook within `SimpleForm`
```
<form onSubmit={(val) => console.log(val)}> <-- remove this prop hook
```

Hope this helps you.

**Comment by kfern** [comment]
Thanks!! I guess next week I'll do some tests. I'll comment in https://github.com/react-cosmos/react-cosmos/issues/576
