### ISSUE TITLE
How to integrate react-cosmos with redux-form using the redux proxy

### ISSUE THREAD

**Issue by kfern** [react-cosmos/react-cosmos#576]
### What's up?

I want to try cosmos with redux but I have not started yet. 

### Mkay, tell me more...

Would be possible a simple and complete example?

Thanks in advance

**Comment by mmacaula** [comment]
@kfern I was able to get it running with redux form.  My case is a little different. I'm trying to test a single `<Field>` component but maybe this would work for you?  Here's an example test fixture and test. 

```
import { reduxForm } from 'redux-form';
import FieldToTest from '../fieldToTest';

const formName = 'absVal';
const fieldName = 'textField';
export default {
  component: reduxForm({ form: formName })(FieldToTest),
  props: {
    name: 'textField'
  },
  reduxState: {},
  formName,
  fieldName,
};
```

Then in my test, I had to do a couple of 'interesting' things, that may or may not be fully necessary.  For instance to get redux form to trigger its actions, i first had to focus it then 'blur' it.  I made a helper function to do this.  I also made a helper to get my redux form state out:

```
const setInputVal = (input, val) => {
  input.simulate('focus');
  input.simulate('change', { target: { value: val } });
  input.simulate('blur');
};
const getStoreValue = () => get('reduxState').form[fixture.formName].values[fixture.fieldName];

describe('when setting input value', () => {
  let input;
  beforeEach(() => {
    input = getWrapper().find('input').first();
  });
  it('should set value in store', () => {
    setInputVal(input, '123');
    expect(getStoreValue()).toBe('123');
  });
});
```

**Comment by kfern** [comment]
@mmacaula Thanks!!  I guess next week I'll do some tests

**Comment by kfern** [comment]
This PR https://github.com/react-cosmos/react-cosmos/pull/586 is a first basic redux form example. All suggestions are welcome.

**Comment by kfern** [comment]
@skidding @mmacaula Thanks again for building this great tool! 🥇

**Comment by mmacaula** [comment]
no credit due here!  Just trying to help with a simple example.  @skidding is awesome though! :)
