### ISSUE TITLE
No fixtures detected after following create-react-app setup

### ISSUE THREAD

**Issue by alexvpickering** [react-cosmos/react-cosmos#604]
### What's up?

**No fixtures detected** after following create-react-app setup.

### Mkay, tell me more...

I tried to follow the readme/create-react-app section as best I could but I get **No fixtures detected** screen at http://localhost:8989/

My setup can be found here: https://github.com/alexvpickering/cosmos-example

**Comment by skidding** [comment]
@alexvpickering you forgot to add `.js` extension to [your fixture file](https://github.com/alexvpickering/cosmos-example/blob/abef4ebf4acef3d89437a6f0c06baf070a0661f4/src/__fixtures__/Input.fixture). 🙃

**Comment by skidding** [comment]
OH, just realized the docs are at fault. 

A small PR to correct this `s/*.fixture/*.fixture.js` would be appreciated!

**Comment by alexvpickering** [comment]
Thank you for the quick response. Yeah the docs confused me - I thought it was a custom file extension.
