### ISSUE TITLE
Detect fixtures of new components without server reload

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#613]
### What's up?

> This has been implemented partially and discussed more in the past, but that discussion has been lost and I believe it's important to track this.

Cosmos does a good job of detecting new fixtures files of components that already have fixtures, because **Cosmos creates a webpack context for folder with fixtures**. But this falls short when we create a new component and fixture for it. *Crickets*. We have to re-start the Cosmos process for the them to show up.

I've worked with Cosmos a lot lately and I've found this pretty upsetting.

### Mkay, tell me more...

Context: Initial contribution from @xavcz which fixed a part of these cases: #531 

Bookmarks:
- https://github.com/paulmillr/chokidar
- https://github.com/webpack/watchpack
- https://webpack.js.org/api/node/
- https://github.com/webpack/webpack-dev-middleware/tree/v2.0.6 (webpack <4 compat)
- https://github.com/webpack/webpack-dev-middleware/pull/267/files

Question:
- How to tell webpack to re-build after Cosmos server is notified of new fixture files?

**Comment by xavcz** [comment]
> I've found this pretty upsetting.

Yep, same! Another part of the discussion: https://github.com/react-cosmos/react-cosmos/issues/542

**Comment by xavcz** [comment]
Would using `glob-to-regexp` as mentioned in https://github.com/react-cosmos/react-cosmos/issues/555 would reduce the need of `react-cosmos-voyager2` ?

`require.context` would be run from root directory with a regexp created from the glob pattern?

By the way, `embedModules`, where we watch files, still depends ([source](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos/src/server/embed-modules-webpack-loader.js#L6)) on the deprecated `react-cosmos-voyager(1)` for [`getFilePath` (voyager source)](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-voyager/src/index.js#L63-L135). Is this a possible issue?

**Comment by skidding** [comment]
> Would using glob-to-regexp as mentioned in #555 would reduce the need of react-cosmos-voyager2?

Maybe, but I remember trying it and it fell short in some way. I can't remember for sure, but I think it's the highlighted part from this passage:

> We could use https://github.com/fitzgen/glob-to-regexp to convert config.filePaths globs to a regexp which we could send to require.context. **The only issue is that config.filePaths is an array of globs.** If we manage to merge the globs or the resulting regular expressions, and glob-to-regexp is reliable, we no longer have to watch for file changes ourselves and this becomes a much easier task.

I believe I couldn't find a way to merge more than one regexp and send it to webpack, which expects one.

> By the way, embedModules, where we watch files, still depends (source) on the deprecated react-cosmos-voyager(1) for getFilePath (voyager source). Is this a possible issue?

Shouldn't be an issue, this code path only activates when `config.componentPaths` is set up, which is still supported as backwards compatibility but removed from docs and those users shouldn't expect new features like "Detect fixtures of new components without server reload".

**Comment by xavcz** [comment]
> I believe I couldn't find a way to merge more than one regexp and send it to webpack, which expects one.

What if we don't merge the regexp but actually uses multiple `require.context`? 😄

**Comment by skidding** [comment]
> What if we don't merge the regexp but actually uses multiple `require.context`? 😄

Maybe... 

Eventually we need to do some filesystem watching in the Cosmos server to not depend on webpack for this sort of thing. And sorting out this issue is on my personal short list for next month.

But if we can get this to work with multiple require.contexts, by joining the results (and maybe removing duplicates) than it could be a quicker win.

**Comment by skidding** [comment]
🥁🥁🥁

I think I found a fix that was right under out nose all the time. I'll skip the details for now to make sure it works as expected.

@xavczen @jozsi @maxsalven if you have a few minutes, can you please try `v4.0.0-beta.13` (lucky number) in your project to see if one or both of two wonderful things happen:

1. Fixtures for new components, under any dir, show up in Cosmos without having to restart the process
2. Test files (using `react-cosmos-test`) can be placed in the same dir with one or more fixtures, and the Playground doesn't pick them up and thus doesn't crash

Thanks!

**Comment by xavczen** [comment]
Wunderbar, it works!! 🌮 

Great job, high five coaie!
