### ISSUE TITLE
Allow loading 3rd party CSS from a Node package

### ISSUE THREAD

**Issue by xavcz** [react-cosmos/react-cosmos#631]
### What's up?

Let's say you want to use CSS from a third party Node package, like [Semantic UI](https://react.semantic-ui.com), [Material UI](https://github.com/mui-org/material-ui) or [Blueprint](https://blueprintcss.io/).

To have these global styles available for each fixture, we can use `globalImports` in the Cosmos config:

```js
module.exports = {
	// ...
	globalImports: ['semantic-ui/semantic.min.css'] // or './node_modules/semantic-ui-css/semantic.min.css'
};
```

This import refers to a file inside the `node_modules` directory, that will be loaded by Webpack at some point.

The thing is that when Webpack tries to load this file, we get the following error:

```sh
ERROR in ./node_modules/semantic-ui-css/semantic.min.css
Module parse failed: Unexpected character '@' (11:0)
You may need an appropriate loader to handle this file type.
|  *
|  */
| @
```

Neither `css-loader` (here) or `style-loader` are used by Webpack to load this css file.

I've hit this issue on Friday, and @cfnelson also hit it hard with Material this weekend (and maybe also @cal0610 in https://github.com/react-cosmos/react-cosmos/issues/579#issuecomment-375195649 ?) 

### Mkay, tell me more...

Using the default webpack config provided by Cosmos, this is actually what is intended: [we `exclude` the `node_modules` directory when using `css+style-loader` (code)](https://github.com/react-cosmos/react-cosmos/blob/58bcd54e28a3e151813b9ef49e120a88bb2fbc2f/packages/react-cosmos/src/server/default-webpack-config.js#L30).

Is this line set to avoid parsing the 📦 `node_modules` rabbit hole?

My workaround so far has been to recreate my own basic config, without this line 🗡 

It has been a pretty frustrating experience when hitting this bug, should we allow loading CSS from `node_modules` by default?

**Comment by cal0610** [comment]
@xavcz i had no problem referencing css file from node modules, this could be something else..

**Comment by xavcz** [comment]
It looks like you are using a custom webpack config, the one from `react-boilerplate` (awesome project btw!), which is actually preprocessing 3rd party CSS separately: https://github.com/react-boilerplate/react-boilerplate/blob/5b58dd97d0e9dc39799c345f1bcbf1333bde92b1/internals/webpack/webpack.base.babel.js#L30-L43

**Comment by cal0610** [comment]
Indeed. Let me know how you go im happy to share my config you you need

**Comment by skidding** [comment]
> Is this line set to avoid parsing the 📦 node_modules rabbit hole?

Yes. But it might not be relevant for CSS. So I think we can safely remove `exclude` part for the CSS loader.

My only question is, is there any difference between

```js
      {
        // Preprocess both own and 3rd party CSS files
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      },
```

and (how react-boilerplate does it)

```js
      {
        // Preprocess our own .css files
        // This is the place to add your own loaders (e.g. sass/less etc.)
        // for a list of loaders, see https://webpack.js.org/loaders/#styling
        test: /\.css$/,
        exclude: /node_modules/,
        use: ['style-loader', 'css-loader'],
      },
      {
        // Preprocess 3rd party .css files located in node_modules
        test: /\.css$/,
        include: /node_modules/,
        use: ['style-loader', 'css-loader'],
      },
```

I'm fine with either. The first is simpler (if it actually works) but the latter lets users know more about what's happening.

**Comment by xavcz** [comment]
The former works,  but the latter brings more clarity! I'll submit a PR tomorrow ✌️

**Comment by cfnelson** [comment]
I ran into this issue as I assumed the default config would work after reading the documentation. The solution was to create a webpack config with the main difference being to remove the `exclude: /node_modules/` line.

Would be happy to assist on the PR for this. 🐇 As well as updating the docs to explain to others who may encounter this.

**Comment by skidding** [comment]
Great! This should prevent future confusion.
