### ISSUE TITLE
react-cosmos-test does not work with xhr-proxy

### ISSUE THREAD

**Issue by kekkeme** [react-cosmos/react-cosmos#638]
### What's up?

I have started last week to use react-cosmos, i have liked the idea. 
About my problem
- I have already created proxies Redux, route and xhr proxies. 
Inside my action creators, i use axios to get datas from server. 
My xhr proxy works and returns correct data from fixture if i use it with npm run cosmos.
However, if i use it inside my test code it does not mock or return anything.

To be clear: 
below you can see my service call with axios. 
If i use npm run cosmos i can see that my xhr proxy works and it shows 1000, 2000 logs.
```

export const fetchSpaces = (token, userId) => {
    return dispatch => {
        
        dispatch(fetchSpacesStart());
        console.log('1000');
        console.log(axios.defaults.baseURL);
        
        axios.get( '/bff/api/spaces' )
            .then( res => {
                console.log('2000');
                dispatch(fetchSpacesSuccess(res.data.spaceItems));
            } )
            .catch( err => {
                console.log("3000");
                dispatch(fetchSpacesFail(err));
            });

    };
};
```

However, if i try to use those proxies inside my test file. I only see 1000. Not even 3000(which if there is exception)

```

import React from 'react';
import createTestContext from 'react-cosmos-test/enzyme';
import { create as renderer } from 'react-test-renderer';
import { Input, Select, Row } from 'antd';
import createXhrProxy from 'react-cosmos-xhr-proxy';
import proxies from '../../../../cosmos.proxies';
import Space from '../../Spaces/Space/Space';
import fixture from '../__fixtures__/Hello.fixture'
import axios from '../../../store/axios';
console.log(fixture.xhr);
console.log(axios.defaults.baseURL);
const { mount, getWrapper, get } = createTestContext({ fixture, proxies: [...proxies] });

describe('Hello', () => {
    
    describe("always renders", () => {
        
        it("always renders a one select", () => {
            mount();
           //
           console.log(get('reduxState'));
           
           //console.log(getWrapper(Space));
           getWrapper(Input).simulate('click');
            expect(1).toBe(1);
        });
    });
});

```

I have tried lots of things but couldnt figure out

**Comment by skidding** [comment]
@kekkeme can you provide a _minimum reproducing repo_ or a public repo that I can clone and debug? I'd love to get to the bottom of this!

**Comment by skidding** [comment]
I added a working example here: https://react-testing-examples.com/#6-xhr

Also, your example probably didn't work because you need to call `await mount()` and make the test async.
