### ISSUE TITLE
override action-creators from `bindActionCreators`

### ISSUE THREAD

**Issue by fnbk** [react-cosmos/react-cosmos#640]
When using react-cosmos I would like to provide custom action-creators in the props. 

<img width="559" alt="screen shot 2018-04-04 at 20 05 28" src="https://user-images.githubusercontent.com/729151/38325767-4076e0b6-3844-11e8-94a6-b024f88ddfbe.png">

Currently these action-creators are mapped into the props with `bindActionCreators` when exporting a React.Component and override the fixture-props , see here:

<img width="474" alt="screen shot 2018-04-04 at 20 08 14" src="https://user-images.githubusercontent.com/729151/38325769-40b2dfa8-3844-11e8-8ae5-38d4f8a05ba3.png">

So my idea was to conditionally export the action-creators the following way.

<img width="408" alt="screen shot 2018-04-04 at 20 06 23" src="https://user-images.githubusercontent.com/729151/38325768-40963b3c-3844-11e8-9d44-1b0cf1616319.png">

It works well, except the condition in the if-statement. How can I get a handle on the condition beeing checked? What can I do to check if I am running in 'development' mode or 'cosmos' mode? Do you have any suggestions? That would be gread, Thanks.

**Comment by fnbk** [comment]
Yeah, I found a simple solution!

I used environment variables. In my example I had to make sure to prefix the environent variable with 'REACT_APP_...', otherwise it would just be ignored.

<img width="610" alt="screen shot 2018-04-04 at 22 37 16" src="https://user-images.githubusercontent.com/729151/38333391-c68debea-3858-11e8-8f04-44760fefd474.png">

**Comment by skidding** [comment]
@fnbk I'm glad you made your use case work!

FYI, you can
- Use the redux-proxy and your wrapper components can work inside Cosmos as they do in your app
- Export the (unwrapped) component as well and use that in your fixtures if you want to mock the "inner" props

Cheers!
