### ISSUE TITLE
Cosmos continually rebundling on me

### ISSUE THREAD

**Issue by mmacaula** [react-cosmos/react-cosmos#661]
### What's up?

Trying out rc-3 with fancy new webpack #564  support but something is up and it continually rebundles over and over, maxing my cpu.  

### Mkay, tell me more...

Not sure what's going on really.  Here's some output from one of the rebundles:

```
WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks             Chunk Names
                              index.html  1.38 MiB       1
    8db36aa05a42dc4b4991.hot-update.json  44 bytes          [emitted]
    Entrypoint undefined = index.html

```

I only see those warnings when i'm not setting the mode to 'development', so maybe its related to the mode somehow?  I'm using webpack 4.6. 

Almost seems like its watching the filesystem and the bundling writes to it which causes a rebundling process again?

**Comment by mmacaula** [comment]
ok, the mode was my fault, I was checking if mode was development and then using `production` if not, which I'm guessing cosmos is sending in test or something else.  That fixed that. 

I tried it again this morning and now its no longer continuously rebundling.  So problem went away...  I suspect that since i was in production mode for webpack it was dumping the built file and cosmos was perhaps watching that build dir and triggering a rebuild?  Either way it seems fixed now.  Thanks for the quick response as always!

**Comment by skidding** [comment]
🙌

**Comment by jlyman** [comment]
For those who arrive here in the future and may be a Webpack neophyte like myself, adding `mode` to Webpack (when not using the command line switch) is pretty simple. In your webpack.config.js, add something similar to the following:

```
const config = {
  mode: process.env.NODE_ENV === 'development' ? 'development' : 'production',

  ... [other webpack config items like plugins and modules] ...
}
```

[Webpack docs for mode](https://webpack.js.org/configuration/mode/)
