### ISSUE TITLE
react-cosmos-xhr-proxy doesn't support adding query params

### ISSUE THREAD

**Issue by Melocaster** [react-cosmos/react-cosmos#665]
### What's up?

Using query params in axios like `axios.get('/user', {
    params: reqParas,
  })` will break xhr-proxy, showing the error of 
```
Network error in mockHttpRequest
```

**Comment by SimeonC** [comment]
I'll copy paste my code here for handling it, basically you need to use regex not string.
```
{
    url: /\/ga-translate\?value=[^&]+&from=[a-z]+&to=[a-z]+$/i,
    method: 'post',
    response: ({ _url: { query } }, res) => {
      const { value, to: targetLocale } = query;
      const translatedText = `${targetLocale}-${value}`;
      return res.status(200).body({
        data: {
          translation: translatedText
        }
      });
    }
  }
```

**Comment by Melocaster** [comment]
@SimeonC It works now! Thank you so much!!!

**Comment by skidding** [comment]
Thanks @SimeonC!

Wouldn't `/ga-translate/` be enough for most cases? Or something more exact like `/\/user\?/` in @Melocaster case.

**Comment by Melocaster** [comment]
@skidding Thx for the quick responding. I just give a try for only using `/\/user\?/` and it doesn't quite work. Seems detailed query paras need to be given. Otherwise an error is thrown

**Comment by Melocaster** [comment]
It is 
```
url: /user\?query=[0-9]+$/
```
as an example for with `query` as a number

**Comment by skidding** [comment]
Cool. I'm happy it worked out!

Please close the issue unless there's more you want to discuss on this topic.
