### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by charliedotau** [react-cosmos/react-cosmos#670]
### What's up?
The doco on the `namespace` property in a fixture is a bit light so maybe I don't understand but...

I'm getting this error on the front-end when I try and use a namespace.  The tree appears as expected, but when I click an item in the tree, I get a styled error on the front-end in the main pane, that reads:

Invalid Coordinates
No astronomical object found at:
MyMoviesComponent:listview/directors

### Mkay, tell me more...

My fixture looks like this.  It's just one file in the `__fixtures__` folder.

    export default [
 	{
    	component: MyMoviesComponent,
    	name: 'movies - actors view',
    	namespace: 'listview/actors',
    	props: {

    	}
    },
    {
		component: MyMoviesComponent,
    	name: 'movies - directors view',
    	namespace: 'listview/directors',
    	props: {

    	}
    }
    ]

I've restarted the server after making this change.  Not sure if there should be a relationship between my namespace and my fixture file name(s)?

Apologies if I've totalled misunderstood how  to use `namespace`

thanks

**Comment by skidding** [comment]
Hi @charliedotau,

Thanks for sharing your issue. You've understood `namespace` just fine. The thing is, at the moment we only support one level of nesting for fixtures. Components don't have this restriction, they can be nested as deep as the UI affords.

That said, what you were experiencing was a bug related to this functinality. Althogh we don't support deep fixture nesting, the slash from `listview/actors` was being processed incorrectly.

I pushed a fix and in version `4.1.1` you should see this:
![image](https://user-images.githubusercontent.com/250750/39768941-e2a7cea0-5314-11e8-9b83-ca90786ade03.png)

Can you please upgrade and see if you get the same result?
