### ISSUE TITLE
Call webpack config function with env object

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#676]
### What's up?

Right now a function webpack config is called with env string (eg. "development" or "production"). But webpack calls it with all environment vars, which looks like `{ prod: true }`.

* [Read about the feature here](https://github.com/react-cosmos/react-cosmos#custom-webpack-config)
* [Here is where the function is current called](https://github.com/react-cosmos/react-cosmos/blob/4a13b775617a031817008a8611e70db515dc355e/packages/react-cosmos/src/server/extend-webpack-config.js#L43)

### Mkay, tell me more...

- https://webpack.js.org/configuration/configuration-types/#exporting-a-function
- https://webpack.js.org/api/cli/#environment-options
- https://webpack.js.org/guides/environment-variables/

**Comment by radhakri555** [comment]
Can I have a look at this issue?

**Comment by skidding** [comment]
@radhakri555 Yes, that would be great!

**Comment by radhakri555** [comment]
@skidding: can you confirm my understanding here?. Instead of passing string variabke, we have to pass Boolean variable(prod: true or false) depends on environment.

**Comment by skidding** [comment]
[That's what it looks like](https://webpack.js.org/api/cli/#environment-options). 

What we're trying is to have parity with webpack. 

So to be 100% sure I recommend creating a dummy webpack config that returns a function and console logging the arguments webpack passes to that function when you're passing the dummy config to the webpack compiler. It's probably easiest using the webpack CLI.

```js
// dummy-webpack.config.js
module.exports = env => {
  console.log({ env });

  return {
    // Webpack will complain about missing options but the env should be printed by then
  };
};
```

```bash
webpack --config dummy-webpack.config.js
webpack --config dummy-webpack.config.js --mode=production
```

Thanks!
