### ISSUE TITLE
AWS Cloud9 support

### ISSUE THREAD

**Issue by MattReimer** [react-cosmos/react-cosmos#677]
### What's up?

Has anyone tried to run this inside [AWS's Cloud9 IDE](https://aws.amazon.com/cloud9/)? I'm trying to suggest cosmos in my workplace as a way to do rapid-prototyping of components to help developers and non-devs communicate. 

I have a really basic app created using `create-react-app` and I've followed the instructions to get `react-cosmos` working on my local machine (OSX + Visual Studio Code). Everything, including `react-cosmos` works great on my local machine. 

Then I clone the repo into an AWS Cloud9 environment. The `create-react-app` start and test scripts work fine but `react-cosmos` gives me the 'ol "It looks like you're using a custom webpack config that isn't outputting an index.html" page. 

Sample Repo here: <https://github.com/MattReimer/react-cosmos-cloud9>

I'm not saying this problem is particular to Cloud9. I'm just not sure what to try when I get this error message:

![screen shot 2018-05-14 at 3 39 13 pm](https://user-images.githubusercontent.com/1063391/40027060-003f987c-578d-11e8-8e06-65c60cf82075.png)

Is there a `--verbose` I can use to find out what's going on?

**Comment by skidding** [comment]
Hi @MattReimer,

Can you try upgrading to `4.2` and see if changes anything?

**Comment by MattReimer** [comment]
Ok. 4.2.0. Different symptoms:

![screen shot 2018-05-15 at 9 44 10 am](https://user-images.githubusercontent.com/1063391/40071014-8c33729e-5824-11e8-861c-2cbb57ee0f99.png)

There's not much going on in the console window:

``` bash
yarn run v1.6.0
$ cosmos
[Cosmos] Using webpack config found at node_modules/react-scripts/config/webpack.config.dev.js
[Cosmos] Serving static files from public
[Cosmos] See you at http://localhost:8080/
webpack built 940cb10eb295271cd10f in 12998ms
[Cosmos] webpack build invalidated by .c9/state.hashArgs.settings
webpack building...
webpack built faf4396d84748400c297 in 8787ms
```

**Comment by skidding** [comment]
Hmm,

I clone the repo, run `yarn` and `yarn cosmos` and I see this

![image](https://user-images.githubusercontent.com/250750/40092195-3fb06d42-58e6-11e8-860a-770a3d719866.png)

**Comment by MattReimer** [comment]
I see that too....on my local machine (OSX).  When I try it on Cloud9 I get the same symptoms. Weird. 

I realize this might just be something weird in the way C9 does its thing but I'm having real trouble figuring out what's wrong here and I can't figure out why the `create-react-app` runner would work fine but not cosmos and there's no error message except "something is breaking the webpack build :/"

**Comment by skidding** [comment]
Anything in the browser console? Maybe a 404 request to the component loader iframe?

**Comment by MattReimer** [comment]
Nope. What I put in [the original comment](https://github.com/react-cosmos/react-cosmos/issues/677#issuecomment-389234912) was all there was. 

Is there a secret `verbose` mode you know of that would give me more output?

**Comment by skidding** [comment]
> Is there a secret verbose mode you know of that would give me more output?

Unfortunately, no. But it seems like the server is running OK.

The logs in your original comment are server logs. I meant browser logs, from the client-side. 

The Cosmos UI has two frames, the playground `index.html` and the component loader `_loader.html`. Before loading the iframe, the playground does a fetch request to `_loader.html` to see if it returns 200 OK, otherwise it tell you that the build isn't OK without knowing what when wrong without checking the server console. Maybe in this case the server _is_ OK, but the fetch request fails from some other reason (browser security...?). So are you able to see the browser console?

**Comment by MattReimer** [comment]
Huh. Didn't even think to check the browser console. Sure enough there's a 499 error on the GET request for _loader.html:

![screen shot 2018-05-17 at 9 23 14 am](https://user-images.githubusercontent.com/1063391/40190514-f96aa14e-59b3-11e8-986b-473d6eed0199.png)

I did a bit of reading and it has [something to do with the way Cloud9's vfs url works](https://forums.aws.amazon.com/thread.jspa?messageID=838556&tstart=0). 

I think the solution here is to follow the directions here in order to serve it from its IP address:

<https://docs.aws.amazon.com/cloud9/latest/user-guide/app-preview.html#app-preview-preview-app>

This is annoying though because the public IP changes whenever the server restarts and configuring the VPC properly is not totally trivial so makes things a lot more complicated than just clicking "run" and "preview". I'm trying to develop a cosmos workflow for Windows-based designers who may not be that comfortable on the console.

I don't think this is `cosmos`' fault so if you want to close this issue that's totally cool. It would be amazing to know why cosmos generates the 499 error but... I'll post back here if I figure it out so others can use it.

**Comment by skidding** [comment]
> **499 Token Required (Esri)**
> Returned by ArcGIS for Server. Code 499 indicates that a token is required but was not submitted.[72]

Maybe when we do the fetch request we must [include cookies](https://github.com/github/fetch#sending-cookies) via `credentials: 'same-origin'`.

**Comment by skidding** [comment]
@MattReimer Can you please try version `4.3.0-0`? Make sure to clear cache.

**Comment by MattReimer** [comment]
It worked!!!!!

Thank you so much. You have succeeded in making my day.

**Comment by skidding** [comment]
🙏
