### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by nickluger** [react-cosmos/react-cosmos#681]
Are there plans to upgrade to Babel 7?

Is necessary to work with Next.js 6, for example. I think the current documentation example with Next is not working, because of Babel 7 beta.

**Comment by skidding** [comment]
Do you get any error?

I used Babel 7, Next 6 and Cosmos in [react-testing-components](https://github.com/skidding/react-testing-examples).

I do remember Next 6 and Babel 7.0.0-beta.46 were not working and I had to downgrade to Babel 7.0.0-beta.42, but maybe that was fixed with newer releases.

**Comment by skidding** [comment]
Please post any detailed conflicts with Babel 7 if they exist. Closing this as Babel is not a Cosmos dependency anyway, it's part of the user land and the Cosmos webpack conflict merely picks up babel-loader when it is installed by the user.
