### ISSUE TITLE
REST GET API for isolated components

### ISSUE THREAD

**Issue by stellarhoof** [react-cosmos/react-cosmos#684]
### What's up?

I'd like to screenshot isolated components without the cosmos dev UI.

### Mkay, tell me more...

 Wouldn't it be awesome to:
- Run cosmos server
- Use puppeteer to navigate to say... `http://localhost/MyComponent/{fixtureName}` and get only the component (no cosmos UI). Bonus: `http://localhost/MyComponent` renders all fixtures ;)
- Screenshot! And then... Assert with https://github.com/americanexpress/jest-image-snapshot!

I think this is nicer than the iframe approach Storybook uses.

**Comment by skidding** [comment]
> Use puppeteer to navigate to say... http://localhost/MyComponent/{fixtureName} and get only the component (no cosmos UI)

You can already do this via `http://host:port/?component=MyComponent&fixture=myFixture&fullScreen=true`

**Comment by stellarhoof** [comment]
Ahhh. Well thought! It didn't occur to me to check the URL. Thanks!
