### ISSUE TITLE
react-cosmos readme && React v16 context changes

### ISSUE THREAD

**Issue by mpachin** [react-cosmos/react-cosmos#693]
### What's up?

Right now react-cosmos readme have [this notes about react's context](https://github.com/react-cosmos/react-cosmos#context). This info is outdated.

### Mkay, tell me more...

Since React's context dramatically changed in React v16, and even official docs have been changed and do not warn now that context is experimental api, I think we should delete this notes.

**Comment by skidding** [comment]
> Since React's context dramatically changed in React v16, and even official docs have been changed and do not warn now that context is experimental api, I think we should delete this notes.

That's true. But React 16 comes with a completely new Context API. So removing the notes that say that the context API is experimental wouldn't be enough. We need to create examples using the new Context API first.

**Comment by skidding** [comment]
That's right. We need a new proxy. Should be fairly simple, though. Eg. Pass the Provider in the config and the context value in the fixture.

**Comment by SimeonC** [comment]
I think this is the kind of thing that you have to customise per context.
Here's an example of how I do it https://gist.github.com/SimeonC/0a4e21c0e5406d28bdde4d824986279f

As a full solution, the proxy constructor would probably end up like taking a map of `key:Provider`.
Not sure how much time I have in the foreseeable future to run this up as a PR so probably a good one for someone else to do 😜 

```js
createNewContextProxy({
  shopsContext: Provider1,
  otherContext: Provider2
});
```

**Comment by skidding** [comment]
> As a full solution, the proxy constructor would probably end up like taking a map of `key:Provider`

Good idea!

**Comment by SimeonC** [comment]
I've updated the gist with that idea - @skidding feel free to add this to react-cosmos, I'd create a PR but a bit short on time and not sure where you want it. I don't think it'd make much sense to make this an external proxy as context is kinda core to react.

**Comment by skidding** [comment]
> I've updated the gist with that idea 

Looks pretty good to me!

> feel free to add this to react-cosmos, I'd create a PR but a bit short on time and not sure where you want it

Here what I'm thinking: To be able to release it under a minor version, we add the new proxy under a new [entry point](https://github.com/react-cosmos/react-cosmos/blob/ca53b2fcbc709cf2270a846ca73157ae0ca06d9d/CONTRIBUTING.md#compiled-vs-source-code) in the existing package. Eg. `react-cosmos-context-proxy/new`.

And in the next major version we swap entry points, exporting the new proxy as the index and the old one under `react-cosmos-context-proxy/old`. 

As a bonus we avoid creating yet another Cosmos package.

What do you think?

> I don't think it'd make much sense to make this an external proxy as context is kinda core to react.

Agreed. Actually in the future I'd like to reduce the number of Cosmos packages and provide more core plugins as named exports. But no need to worry about this for now.

**Comment by skidding** [comment]
@vget98 For now you can use the ["wrapper component fixture pattern](https://github.com/react-cosmos/react-cosmos#wrapper-component) to wrap a component with a new-style context provider.

In the future it will be even easier but don't have an ETA for that.

**Comment by vget98** [comment]
@skidding sounds good thank you

**Comment by hudde91** [comment]
@skidding Hi is there any new documentation or proxy for react hook useContext in Cosmos?

**Comment by skidding** [comment]
@hudde91 Context providers are configured the same with or without hooks. Whether you use `Context.Consumer` with render prop or `useContext` hook in your component doesn't make a difference for Cosmos. See the comments above for putting the Provider in a proxy. But if you're using Cosmos Next it's even easier to put your context Provider(s) in a [decorator](https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md#decorators).

**Comment by hudde91** [comment]
@skidding Okay thanks!

**Comment by skidding** [comment]
Cosmos Next is designed to work with the new Context API. Feel free to move to http://github.com/react-cosmos/react-cosmos-classic.
