### ISSUE TITLE
react-dnd: Could not find the drag and drop manager in the context

### ISSUE THREAD

**Issue by kfern** [react-cosmos/react-cosmos#694]
### What's up?

How could I use react-dnd with cosmos?

### Mkay, tell me more...

How can I wrap a cosmos fixture with a DragDropContext?

I have not found any issue, documentation or source code to help me

Thanks in advance

**Comment by skidding** [comment]
Can you please provide a repo reproducing an error? If I could take a look I'll be able to point to a solution. Thanks!

**Comment by kfern** [comment]
@skidding 

Of course :-)

https://github.com/kfern/ToyboxDnD/tree/feature-react-cosmos

Toybox DnD is a very basic example of React Drag and Drop

App works fine:

![image](https://user-images.githubusercontent.com/1898891/40544846-e2953d54-6029-11e8-9b23-562dd7bcbe4c.png)

Box can not find the drag and drop manager in the context:

![image](https://user-images.githubusercontent.com/1898891/40544858-ed413f0a-6029-11e8-8364-85c868d69a8f.png)

**Comment by skidding** [comment]
@kfern I've not worked with react-dnd before, but you can make it work with these two changes:

Create `src/cosmos.proxies.js`

```js
import React from 'react';
import HTML5Backend from 'react-dnd-html5-backend';
import { DragDropContext } from 'react-dnd';

// Create plain wrapper with dnd context
const DDContext = DragDropContext(HTML5Backend)(props => props.children);

function DDProxy(props) {
  const { nextProxy, fixture } = props;
  const children = <nextProxy.value {...props} nextProxy={nextProxy.next()} />;

  // Apply wrapper when fixture.ddContext is true
  return fixture.ddContext ? <DDContext>{children}</DDContext> : children;
}

export default [DDProxy];
```

In the Box fixture:

```diff
import Box from '../../Components/Box';

const identity = el => el;

export default [
  {
    component: Box,
+    ddContext: true,
    props: {
      connectDragSource: identity()
    }
  }
];

```

At first I wanted to apply the dnd context globally, without the need of `fixture.ddContext`, but then I realized App already has dnd context applied and there might be some conflicts if you apply it twice. Let me know if you need explanations.

**Comment by kfern** [comment]
@skidding Thank you. It works perfectly :1st_place_medal: 

![image](https://user-images.githubusercontent.com/1898891/40725037-b6d104f8-6422-11e8-939e-05641238e146.png)
