### ISSUE TITLE
Shareable component/ComponentEditor in addition to FixtureEditor

### ISSUE THREAD

**Issue by mentaman** [react-cosmos/react-cosmos#695]
### What's up?

Right now when working with fixture, you can edit and play with it. But after you're done and you want to copy it to your project, you have to replace this json:

{
component: MyComponent
props: {param: "value"}
}

into this:

 < MyComponent param="value">

It can be annoying when there are many props and less fluent.
It would be useful for exported components, so users can just copy it and use it in their application without the struggle of transporting json to react props.

### Mkay, tell me more...

I made this so far:
![cosmos](https://user-images.githubusercontent.com/2057934/40565253-72cdf024-6074-11e8-9c37-0d1236ae9455.gif)
So you can just look at fixtures and copy them.

For now it's just this line in packages/react-cosmos-playground/components/ComponentPlayground/index.js:
![image](https://user-images.githubusercontent.com/2057934/40559775-8a930d34-6060-11e8-82c8-0936baa7d23b.png)

**Comment by skidding** [comment]
This is very cool!

How about creating a proxy for this instead of putting it in the playground (which is not pluggable yet)?

It's as simple as putting this in `cosmos.proxies.js`

```js
import React from 'react';

function JSXPreview(props) {
  const { nextProxy, fixture } = props;

  return (
    <div>
      <div>GENERATE THE JSX PREVIEW HERE</div>
      <nextProxy.value {...props} nextProxy={nextProxy.next()} />
    </div>
  );
}

export default [JSXPreview];
```

**Comment by mentaman** [comment]
Looking good. So you mean it would be a plugin and by default it wont show up?
If someone who is not me would want to use it, how would he do it? Or you think it would not be useful for the rest of the community?

Also from the playground I am able to edit the fixture, and update it with the "onFixtureEditorChange" function, is it possible to do it with a proxy too?
Because I thought about letting them edit the component preview.

But I guess just the option of sharing it easily without editing can be enough.

![image](https://user-images.githubusercontent.com/2057934/40574637-4f8ae0c6-60de-11e8-8836-7b6c74ae9b31.png)

This is what it looks like as a proxy.

It doesn't support yet functions & jsx & children prop

**Comment by skidding** [comment]
> Looking good. So you mean it would be a plugin and by default it wont show up?

Yes

> If someone who is not me would want to use it, how would he do it? Or you think it would not be useful for the rest of the community?

You can publish your proxy as a package, and others can do

```js
import createJSXPreviewProxy from 'your-proxy-package-name'

export default [createJSXPreviewProxy({ fooOption: 'barValue' })]
```

This is a practice to support options. It can also be just

```js
import JSXPreview from 'your-proxy-package-name'

export default [JSXPreview]
```

> Also from the playground I am able to edit the fixture, and update it with the "onFixtureEditorChange" function, is it possible to do it with a proxy too?

Not at the moment. But there will likely be a similar API in the future.

> This is what it looks like as a proxy.

Cool stuff!
