### ISSUE TITLE
Apollo response mock fixtures seem to persist across tests and when switching components

### ISSUE THREAD

**Issue by begedin** [react-cosmos/react-cosmos#698]
# What's up?

Apollo mock responses seem to stick around when switching fixtures and between different tests.

# Mkay, tell me more...

I have multiple different components with multiple different fixtures defined for each.

Whenever I try to view a component with a fixture which involves an apollo response (or failure), that fixture seems to persist when I switch to a different component or fixture, meaning the first mocked response is the one I keep getting back. 

The only way to kill the issue is if I do a manual browser refresh.

## Same thing happens in tests

As the title says, the same thing seems to be happening in tests.

If I have multiple jest tests in a single suite, each of which is using a different fixture, all of them seem to end up with the response received by the first test.

In both cases, it doesn't matter if I switch between responses and failures or vice-versa, the original outcome persists, whichever of the two it was.

# Potential solution

My initial assumption was that there's a caching issue (my apollo client client uses in memory cache), but I'm unable to figure out how to get around it, if that even is the issue.

I would hate to take debugging in the wrong direction, though.

**Comment by skidding** [comment]
Hi @begedin,

I think similar issues have been reported in the past as well with the Apollo proxy. There were also some console errors until recently, which revealed some statefulness, but maybe the underlying problem is still there even if the error disappeared.

Unfortunately I have minimal Apollo experience so I don't have any insight at the moment. Any help getting to the bottom of this would be greatly appreciated.

https://github.com/react-cosmos/react-cosmos/tree/master/packages/react-cosmos-apollo-proxy/src

I can help explain any Cosmos related code from the Apollo proxy.

Thanks!

**Comment by begedin** [comment]
@skidding The code there, the fixtureLink especially, seems to basic to be the direct cause. Maybe the problem is in us not understanding how apollo internals work and in some way, the proxy isn't even being hit.

I'll be happy to look into it, but maybe someone with deeper knowledge of apollo itself could do more.

**Comment by JannesV** [comment]
@begedin I've come across this same issue too. I've fixed it by replacing this 

```
 if (isMockedFixture) {
      this.client.link = createFixtureLink({
        apolloFixture,
        cache,
        fixture: this.props.fixture
      });
    }
```

with:

```
if (isMockedFixture) {
    this.client = new ApolloClient({
        cache,
        link: createFixtureLink({
            apolloFixture,
            cache,
            fixture: this.props.fixture
        })
    });
}
```
It seems like apollo doesn't like to get it's link changed once initiated.
Do note this is a quick and easy fix and does not take in account if the user has supplied it's own client.

**Comment by xavczen** [comment]
Creating a new client instead of hardcorely replacing the link is a great move, @JannesV !

**Comment by JannesV** [comment]
@skidding This one can be closed up now I believe.

**Comment by skidding** [comment]
Yes! 👍
