### ISSUE TITLE
Config for app in separate folder from package.json

### ISSUE THREAD

**Issue by rchamberlin** [react-cosmos/react-cosmos#702]
### What's up?

I have an Electron app that uses a two package.json structure.  All of the scripts are in the root of the project, but the app itself lives in ./app, including all of its dependencies (React etc).  Is there a way to set up the config so this will work?  I've tried setting the rootPath to everything I can think of but no luck.  Thanks!

**Comment by skidding** [comment]
Hi @rchamberlin,

Can you point to a repo with this structure? Either your project is public
or you can create a minimal reproducing repo. This way I can debug and see
what the issue is.

**Comment by skidding** [comment]
@rchamberlin Did you manage to get Cosmos working?

**Comment by skidding** [comment]
Let me know if you still have this issue.
