### ISSUE TITLE
You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by teimurjan** [react-cosmos/react-cosmos#703]
I faced a problem with creating a fixture for a component which has <Link> but without wrapping with `withRouter`. I have such a component:
```js
const AuthForm = ({ intl }: Props) => (
  <div className="auth-form">
    <Link to="/auth/login">
      <Button className="login-button mt-5 py-2" size="lg" color="primary" block>
        {intl.formatMessage({ id: 'authForm.button.login' })}
      </Button>
    </Link>

    <Link to="/auth/register">
      <button className="btn btn-lg btn-white-outline sign-up-button mt-4 mb-5 btn-block py-2">
        {intl.formatMessage({ id: 'authForm.button.signUp' })}
      </button>
    </Link>
  </div>
);

export default AuthForm;
```

My cosmos.proxies.js looks like:
```js
// @flow
import createRouterProxy from 'react-cosmos-router-proxy';

export default [createRouterProxy()];
```
And my fixture:
```js
export default [
  {
    name: 'Initial state',
    component: AuthForm,
    props: {
      intl: stubIntl,
    },
    url: '/auth',
  }
]
```

I also tried:
```js
// @flow
import createContextProxy from 'react-cosmos-context-proxy';
import PropTypes from 'prop-types';

const ContextProxy = createContextProxy({
  childContextTypes: {
    router: PropTypes.object.isRequired,
  },
});

export default [ContextProxy];
```
When the fixture was:
```js
export default [
  {
    name: 'Initial state',
    component: AuthForm,
    props: {
      intl: stubIntl,
    },
    context: {
      router: {},
    },
  },
];

```
None of these methods are working. Everytime I refresh the page I see `You should not use <Link> outside a <Router>`. What do I do wrong?

**Comment by teimurjan** [comment]
I found out the problem. As I've changed `rootPath` in configs, file with proxies should be in the root folder, not near the config file.

**Comment by mpachin** [comment]
Faced the same problem since my projects config files placed outside of rootPath.
[Here we can see](https://github.com/react-cosmos/react-cosmos/blob/e70ef0fe9a0cd982b8245ab1ebaceaa0647bbdd3/packages/react-cosmos-config/src/index.js#L117) that proxies taken from `rootPath`/`proxiesPath`.
In case similar with mine:
```
projectFolder
│
└─── configFiles
│   │
│   └─── react-cosmos
│       │
│       └─── cosmos.config.js
│       │
│       └─── cosmos.proxies.js
│   
└─── src
│   │
│   └─── ...
...
```
you should have config look like this:
```js
module.exports = {
    rootPath: '../../src/',
    proxiesPath: '../../config/react-cosmos/cosmos.proxies',
}
```
Then proxies path will be resolved like `path.join(rootPath, proxiesPath)`, so you can skip placing `cosmos.proxies.js` in `src` directory and instead keep it in `config`.

**Comment by iamchathu** [comment]
This is happening to me using a project bootstrapped from `create-react-app` and followed readme guide and created `cosmos.config.js` and `cosmos.proxies.js` and added router proxy but still get <Link> can not be used without <Router> issue.
