### ISSUE TITLE
Fetch proxy only use first matcher's response and matcher can't use RegExp

### ISSUE THREAD

**Issue by linonetwo** [react-cosmos/react-cosmos#710]
### What's up?

Fetch proxy only use first response, and will pass the first response to all fetch request.

```js
fetch: [
      {
        matcher: () => `${API}/stats`,
        response: () =>
          import('../../store/aggregation.data')
            .then(({ statsData1 }) => statsData1)
            .then(res => JSON.stringify(res)),
      },
      {
        matcher: () => `${API}/block?page=0&size=${getDefaultPageSize()}`,
        response: () =>
          import('../../store/block.data')
            .then(({ listData1 }) => listData1)
            .then(res => JSON.stringify(res)),
      },
    ]
```
Here `statsData1` is passed to second fetch, so second fetch don't receive `listData1` but `statsData1`. 

SO, every fetch in this fixture, will receive `statsData1`. This seems to be a bug.

**Comment by skidding** [comment]
Hey @linonetwo,

It's possible that your `matcher` values are not working as expected. From the `fetch-mock` docs (we're using v5):

> `matcher`: Function(url, opts): A function (returning a Boolean) that is passed the url and opts fetch() is called with (or, if fetch() was called with one, the Request instance)

So your URL strings are always evaluated as `true`, which results in the first mock being chosen all the time.

Try this:

```js
fetch: [
  {
    matcher: `${API}/stats`,
    response: () =>
      import('../../store/aggregation.data')
        .then(({ statsData1 }) => statsData1)
        .then(res => JSON.stringify(res)),
  },
  {
    matcher: `${API}/block?page=0&size=${getDefaultPageSize()}`,
    response: () =>
      import('../../store/block.data')
        .then(({ listData1 }) => listData1)
        .then(res => JSON.stringify(res)),
  },
]
```
