### ISSUE TITLE
Functions on local-state breaks fixture

### ISSUE THREAD

**Issue by Pyrolistical** [react-cosmos/react-cosmos#719]
### What's up?
When there is a function on `this.state`, react-cosmos crashes.

### Mkay, tell me more...

This works: https://github.com/Pyrolistical/react-cosmos-function-on-state-bug/blob/master/src/index.js#L14
but this does not: https://github.com/Pyrolistical/react-cosmos-function-on-state-bug/blob/master/src/index.js#L31

Demo
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/463642/41496386-b1a2b124-70f3-11e8-8b12-2abd9975ad59.gif)

The stack trace of the crash
```
index.js:2178 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in UpdateNameOnStateBreaks (created by PropsProxy)
    in PropsProxy (created by StateProxy)
    in StateProxy (created by ErrorCatchProxy)
    in ErrorCatchProxy (created by Loader)
    in Loader
```

Full source: https://github.com/Pyrolistical/react-cosmos-function-on-state-bug

**Comment by skidding** [comment]
I don't get that warning on my machine. But the fixture editor does indeed not updated. Which is expected at the moment. Please [see this thread](https://github.com/react-cosmos/react-cosmos/issues/433#issuecomment-396859540).

But why would you like to put a handler in the state? Only data that can't be derived should normally be put into the state.

**Comment by Pyrolistical** [comment]
Mainly because functions on state have access to this and don't need babel-plugin-transform-class-properties

Also I'm one of those weird guys who thinks state = data + actions.

**Comment by skidding** [comment]
> Mainly because functions on state have access to this and don't need babel-plugin-transform-class-properties

You can also do this in the constructor

```js
this.state = {
  name
}
this.updateName = ({target: {value: name}}) => {
  this.setState({
    name
  })
}
```

> Also I'm one of those weird guys who thinks state = data + actions.

Interesting. I like to think of state as a serializable snapshot which can be persisted offline, and of actions as part of the program code which can transform state on events.

**Comment by skidding** [comment]
So I've recently learned that putting actions inside state is actually a pattern advocated by the React team, at least when using the new Context API.

I think this issue and #433 should be merged.

**Comment by skidding** [comment]
Fixed in Cosmos Next.
