### ISSUE TITLE
Compatibale with react 16 (enzyme)

### ISSUE THREAD

**Issue by extramuros** [react-cosmos/react-cosmos#722]
Please, tell me what I can do, to simulate events using react-cosmos, with Enzyme or anything?

I'd tried to use react-cosmos-test package (to simulate events by Enzyme), but I got an error: "Enzyme expects an adapter to be configured, but found none."

Looking for this issue gave me some link: https://github.com/react-cosmos/react-cosmos/pull/467. But I think, that it's out of date.
I`d tried to add Enzyme's adapter for React 16:
```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });
```
But got follow error:
"Method "simulate" is only meant to be run on a single node."

That is my test file:
```
import createTestContext from 'react-cosmos-test/enzyme';
import fixture from '../__fixtures__/someFixture';

const { mount, getWrapper, get } = createTestContext({ fixture });
beforeEach(mount);

test('redirects to home page after signing out', () => {
    getWrapper('button').simulate('click');
    expect(get('url')).toBe('/');
});
```
Thanks a lot, for attention

**Comment by skidding** [comment]
Hi @extramuros,

It sounds like you have more buttons. Try logging `getWrapper('button').length` to see if this is the case.

**Comment by skidding** [comment]
In any case, if you got the Enzyme error it seems like the Cosmos+Enzyme integration is working just fine.

You have to narrow down the selector to a single button. Probably `getWrapper('button:first-child')` would work as a first step.

Learn more about selectors here: http://airbnb.io/enzyme/docs/api/selector.html

**Comment by extramuros** [comment]
I'm sorry, I didn't tell

**Comment by extramuros** [comment]
@skidding, thank for reply.

I'd tried, before I wrote the issue, to use getWrapper by id. And I'v repeated with other selectors.
Nothing changes.
I'd logged getWraper with different selectors and all of them had length=0.
Besides, if I comment manually added Enzyme's adapter in my test file, I get an Enzyme's error. I looking for Enzyme's adapter in all my cosmos files installed by npm and have nothing. Is this right?
I think, should be adapter in it. My version of react-cosmos is 4.5, I have installed:
```
    "react-cosmos": "^4.5.0",
    "react-cosmos-redux-proxy": "^4.4.0",
    "react-cosmos-router-proxy": "^4.5.0",
    "react-cosmos-test": "^4.5.0",
    "react-cosmos-wrapper-proxy": "^1.4.0",
    "react-cosmos-xhr-proxy": "^4.5.0",
```
now.

**Comment by skidding** [comment]
Try something like `console.log(getWrapper().html())` to check that Cosmos is rendering what you expect.

**Comment by extramuros** [comment]
Yes, you are right. As I understand, getWrapper, in my case, is object with only "length" prop, sort of `ReactWrapper { length: 0 }` (it is `console.log(getWrapper('#id'))` result). But I have no idea, what it mean. Because, without Enzyme, react-cosmos-test is worked perfectly for me, I get right snapshots and all.

**Comment by skidding** [comment]
If you have a public repo I can take a look.

**Comment by extramuros** [comment]
No, I haven't. But I'm starting to do it (only example of error reproducing). I'll be done tomorrow, I suppose.

**Comment by extramuros** [comment]
Hi, @skidding 
I have prepared example here:
https://github.com/extramuros/cosmos-error-reproducing

**Comment by skidding** [comment]
@extramuros the component doesn't render in Jest because `Errors` [returns null](https://github.com/extramuros/cosmos-error-reproducing/blob/3ee7d8bf4f953c9c45ac2485e40db2364c15d768/src/components/auxiliary/errors.jsx#L26). The Cosmos UI works because `DEBUG` somehow ends up being true in the client bundle, yet it's not defined in Jest environment. Not sure what the purpose of the Errors component is, but you might want to consider returning `this.props.children` instead of null.

Also, you can create `src/setupTests.js` (CRA specific) and put this there:

```js
import Adapter from 'enzyme-adapter-react-16';
import { configure } from 'enzyme';

configure({ adapter: new Adapter() });
```

So you don't have to do it in every test.

**Comment by extramuros** [comment]
I need to inspect it again, something is broken at my side. Now snapshots also returns null. I guess, there's no issue. I'm sorry for your time.

**Comment by extramuros** [comment]
@skidding, thank you for feedback. I had returned for working on tests and found my mystake in `Errors` component. Your was right. Everything works perfectly now.
