### ISSUE TITLE
Error babel dependency with create-react-app

### ISSUE THREAD

**Issue by extramuros** [react-cosmos/react-cosmos#726]
With my first installition of react-cosmos at create-react-app project I've got an error:
> Error: only one instance of babel-polyfill is allowed

I've avoided it by comment:
`require('babel-polyfill');`
in 
> react-cosmos/dist/client/loader-entry.js

But i guess, that isn't rigth way. Please, could you fixed it or documented right way of installation for this case?

![firefox_screenshot_2018-06-20t10-51-49 541z](https://user-images.githubusercontent.com/40386068/41663326-d5148d2e-74ab-11e8-831e-a66c41f1639a.png)

**Comment by skidding** [comment]
This is a bug. An oversight of #656.

At the time it seemed like a good idea but I failed to recognize that the user bundle should be as unopinionated as possible. The fetch polyfill in `react-cosmos-playground` was a good idea, as that is already bundled when it reaches the user. But the polyfilling in `loader-entry` (which is synonym with "user entry") should be reverted. It's up to the user to customize its bundle based on its requirements, either via a custom webpack config or `globalImports` in Cosmos config.

@extramuros @cbranch101 if any of you wants to open a PR to fix this I'd be grateful!

**Comment by extramuros** [comment]
As for me, I have no expirience for that. If I would have a time, I'll tried. But not for this weekend.
