### ISSUE TITLE
Setting root container styles for an individual fixture?

### ISSUE THREAD

**Issue by callumlocke** [react-cosmos/react-cosmos#727]
It's possible to define global `#root` styles via `containerQuerySelector`, but I often find myself wanting to style the root container **per fixture**. Does react-cosmos offer any method or convention for doing this?

Use cases:

- Showing 100%-wide components in a container that constrains the width, so they don't look [weird/disproportionate](https://react-cosmos.github.io/?component=Tetromino&fixture=I-tetromino) when viewed in isolation.
- Demoing how a responsive component looks at different available widths (or on different background colors) using multiple fixtures.
- Demoing how a component respects certain inherited styles like font-size, by showing a few different fixtures with different container styles.

**Comment by skidding** [comment]
> Demoing how a responsive component looks at different available widths

This is being [worked on](https://github.com/react-cosmos/react-cosmos/pull/539) and I suspect will be released soon.

For the rest you can create a custom proxy and customize its CSS via custom fixture attrs.

Here's an example:

```js
class ContainerProxy extends Component {
  render() {
    const {
      nextProxy: { value: NextProxy, next },
      fixture: { containerStyle }
    } = this.props;
    const nextEl = <NextProxy {...this.props} nextProxy={next()} />;

    return containerStyle ? <div style={containerStyle}>{nextEl}</div> : nextEl;
  }
}
```

If you add this to your `cosmos.proxies` file then you'll be able to pass container style under `fixture.containerStyles`. 

This is rudimentary, but I think from here you'll be able to extend with presets and more high level container constructs.

**Comment by callumlocke** [comment]
Awesome, thanks. After reading your reply and investigating proxies more, I found [react-cosmos-wrapper-proxy](https://github.com/jozsi/react-cosmos-wrapper-proxy) also works well for this, if you want to create an actual wrapper component with more than just styles. This is very flexible and I'm happy to go with this approach.
