### ISSUE TITLE
Router proxy makes lost sync between mock state from fixture and component state

### ISSUE THREAD

**Issue by bslipek** [react-cosmos/react-cosmos#729]
Hi guys! We just start working with react-cosmos and the first impression is great!
However, we have a small issue. 

![components_withrouter_counter__counter_ _react_cosmos](https://user-images.githubusercontent.com/2363946/41722441-e219346c-7568-11e8-9b1f-6ac0b95c4b11.png)

So we have component that need router, so `export default withRouter(Counter);`
We used `react-cosmos-router-proxy` and configured is as follow:

```js
// @flow
import createReactRouterProxy from 'react-cosmos-router-proxy';

export default [createReactRouterProxy()];
```

and we created our fixture as: 
```js
import Counter from '../Counter';

export default {
  component: Counter,

  state: {
    count: 10,
  },
  url: '/counter',
};

```

And after that, we ***lost sync between mock state from fixture and component state***.

**Comment by skidding** [comment]
Hi @bslipek,

Fixture state doesn't work on connected components. Technically speaking, Cosmos injects state in the exported component and can't (easily) access the inner component that holds the state.

> Note that, in case you weren't aware, higher order components like `withRouter` create a new component that loads yours as a child.

I am planning a big Cosmos change that will enable this, but realistically speaking that will come "sometime this summer".

There are still a few things you could do:

1. Export the raw component as well and use it in state-related fixtures. Simple but kinda goes against Cosmos principles.

2. Make use of [wrapperComponentRef](https://github.com/ReactTraining/react-router/blob/f184bd897f3b9ad3a32eaa8060539ad7f4c233b4/packages/react-router/modules/withRouter.js#L18)

```js
export default {
  component: Counter,

  props: {
    wrappedComponentRef(innerRef) {
      if (innerRef) {
        innerRef.setState({ count: 10 });
      }
    }
  },

  url: '/counter'
};
```

But this is _ugly_ and you don't see the state in the fixture editor this way.

Hope this helps.

**Comment by bslipek** [comment]
@skidding thank you!
