### ISSUE TITLE
How to await for async state updates (via setState)?

### ISSUE THREAD

**Issue by callumlocke** [react-cosmos/react-cosmos#731]
Thanks for writing this amazing tool.

After reading the docs on [capturing state changes](https://github.com/react-cosmos/react-cosmos#capturing-state-changes) in headless tests, I've managed to use `get('state')` to check if my component's state got updated after a simulated change event, using `.simulate('change')`. I'm using the bundled enzyme adaptor.

But in my component's handler, I'm using `.setState(fn)` to update the state. So the state isn't updated immediately, therefore I have to do something like `await delay(100)` before I can check the state again. I've tried a shorter delay of 10ms but it's not long enough :/

Is there any way to be notified when the state actually got updated, so I can avoid including an arbitrary timeout (which might cause occasional flakey test failures, and wastes time)?

**Comment by skidding** [comment]
Hi @callumlocke,

I recommend using [async-await](https://github.com/skidding/async-until). I do stuff like:

```js
await until(() => get('state').something === 'somevalue')
```

Which also doubles as an assertion. If it times out you'll get a failed test with a customizable error message.
