### ISSUE TITLE
Add to readme a more precise info about using custom webpack

### ISSUE THREAD

**Issue by ktunkiewicz** [react-cosmos/react-cosmos#753]
**What's up?**
In situation where react-cosmos is to be used with existing webpack config it is really not straightforward how to do this. Or am I doing it wrong?

**Mkay, tell me more...**
I have a fairly complicated webpack that loads a whole ton of module rules, plugins, aliases etc. and I simply cannot use the default Cosmos' webpack config.

My main webpack.config.js spits out multiple configurations, so I also have a `/webpack/common.config.js` file with everything *except* `entry`, `output` and HtmlWebpackPlugin in there. This looks like a good candidate for providing `webpackConfigPath` to Cosmos.

But I first tried outputing only single configuration from the main webpack file to see if Cosmos can override my webpack config's HtmlWebpackPlugin.

Once I run `npm run cosmos` I get the happy `webpack built ... in ... ms` message. Great, but once I navigate to `http://localhost:8989/` I see HTTP 404 on `_loader.html`.

Obviously the HtmlWebpackPlugin did not output `_loader.html`.

Then I tried with `webpackConfigPath: './webpack/common.config.js'`, and it's the same story. Now that's probably because if `webpackConfigPath` is provided, it is not "enhanced" by Cosmos anymore, to have the HtmlWebpackPlugin adde, am I right?

After some time I figured out that the solution that works is:
```
// cosmos.config.js
const HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
  publicPath: 'dist',
  publicUrl: '/widget/',
  watchDirs: ['src'],
  webpackConfigPath: './webpack/common.config.js',
  webpack: (config) => {
    // add Cosmos' HtmlWebpackPlugin
    config.plugins.push(new HtmlWebpackPlugin({ title: 'React Cosmos', filename: '_loader.html' }));
    return config;
  },
};
```

where the `./webpack/common.config.js'` holds all webpack config **except** these pieces:
```
  // NOT in ./webpack/common.config.js
  entry: { ... },
  output: { ... },
  plugins: [
    new HtmlWebpackPlugin({
      ...
    }),
  ],
```

It would be nice to mention in the readme that the config provided with `webpackConfigPath` option does not get HtmlWebPackPlugin injected into plugins and you have to do it yourself.

**Comment by skidding** [comment]
> It would be nice to mention in the readme that the config provided with `webpackConfigPath` option does not get HtmlWebPackPlugin injected into plugins and you have to do it yourself.

This shouldn't be the case. This is a bug that has been reported a few times lately, so I'm really interested in tracking it down.

The webpack config should be enhanced, like your say, regardless of being the default or a custom one.

Can you provide a public repository that reproduces this? It would be of great help and I'll make sure to find a fix and publish it in a few days.

Thanks!

**Comment by skidding** [comment]
@ktunkiewicz can you please try `react-cosmos@4.6.0-3`?

`html-webpack-plugin` should be added automatically to your custom webpack config now.
