### ISSUE TITLE
Unable to mock out props added by mapDispatchToProps

### ISSUE THREAD

**Issue by sdgandhi** [react-cosmos/react-cosmos#763]
### Unable to mock out props added by mapDispatchToProps

I'm using react-redux and have mocked out the state part of redux using react-cosmos. However, I'm unable to mock out the actions added by `mapDispatchToProps` by setting them in the fixture.

### Steps to reproduce

1.  Create fixture for component that uses redux state, but also dispatches actions via `mapDispatchToProps` and the `connect` HOC.
2. Try to mock out the dispatch props in the fixture
3. Observe that original dispatch functions are called instead of mock ones from the fixture

### User info

- Cosmos version 4.5.0
- Proxies:

```js
import createReduxProxy from "react-cosmos-redux-proxy";
import createRouterProxy from "react-cosmos-router-proxy";
import configureStore from "./store/configureStore";

const ReduxProxy = createReduxProxy({
    createStore: state => configureStore(state),
});

export default [
    ReduxProxy,
    createRouterProxy(),
];
```

### Additional context

Mocking redux state works, so the proxy is working correctly.

**Comment by skidding** [comment]
Hi @sdgandhi,

Note that when you wrap a component with Redux's `connect`, you're no longer exporting your component, but a "higher order component" that implicity renders your component with some props derived from various the global Redux store.

In React, you can only set the props of the top component you're rendering, the rest derive their props from their parent component, in cascading fashion.

So you have two options:
- Recommended: Rely on Redux state mocks, because the Redux state controls entirly the props sent to your component, because what `connect` does is map Redux data to component props.
- Export your unwrapped component under a named export, and use that in your fixture. Then you're free to mock any props that usually come from Redux's connect.

**Comment by sdgandhi** [comment]
@skidding I'd love to use the first option, but I can't find how to set the mocked dispatch props in the redux state in the fixture. I tried something like this:

```js
// Fixture
...
    props: {
        loadData: null, // dispatch function name, doesn't work
        error: null, // state, works
        loading: false, // state, works
    },
```

**Comment by skidding** [comment]
@sdgandhi Could you share a broader example of what you'd like to achieve? I don't quite understand what you mean. Thanks!

**Comment by skidding** [comment]
I read your initial post again and maybe, you want a way to stub the `dispatch` calls from inside the component, to avoid calling the actual action functions?

**Comment by skidding** [comment]
Well I'd say that the point of the redux proxy is to allow real dispatch functions to be called and not have to mock them. This leads to less time writing tests and, most importantly, tests cover more code paths than if everything was mocked, and thus less in touch with how to app runs in real life.

Is there a reason why having the real dispatch functions run bothers you?

**Comment by sdgandhi** [comment]
So I've separated my UI tests (with cosmos) from unit tests (with jest). So I *only* want to test the UI component without having to worry about the rest of my redux stack.

Additionally, since by using redux-thunk, my redux dispatch calls out to external services and loads data from them. I would rather that not happen when testing UI in cosmos.

Perhaps I'm not understanding redux proxy. I was under the impression that it is supposed to completely mock out the redux state, so none of the rest of the redux stack affects the component except for the redux state specified by the `reduxState` key in the fixture?

**Comment by skidding** [comment]
> So I've separated my UI tests (with cosmos) from unit tests (with jest). So I only want to test the UI component without having to worry about the rest of my redux stack.

This is also fine. Definitely simpler.

> Additionally, by using redux-thunk, my redux dispatch calls out to external services and loads data from them. I would rather that not happen when testing UI in cosmos.

XHR or Fetch requests can also be mocked in Cosmos, in case you want to go down this road in the future.

> Perhaps I'm not understanding redux proxy. I was under the impression that it is supposed to completely mock out the redux state, so none of the rest of the redux stack affects the component except for the redux state specified by the reduxState key in the fixture?

Not quite. The purpose of the Redux proxy is so that all Redux side effects _do_ occur outside your component, just as they would in a the entire app, except you're focusing on a single component. It's more tedious, but once set up can give you more confidence in your app. I try to explain this philosophy in [this Medium article](https://medium.com/@skidding/testing-react-components-30516bc6a1b3).

But it's more important to do what feels practical and you enjoy!

**Comment by sdgandhi** [comment]
> Not quite. The purpose of the Redux proxy is so that all Redux side effects do occur outside your component, just as they would in a the entire app, except you're focusing on a single component. It's more tedious, but once set up can give you more confidence in your app. I try to explain this philosophy in this Medium article.

Ah yes I remember reading that now. This is a great option for "integration" level UI tests when you're testing on the level of the app. But I can just run my app fully to test this anyways. However, for "unit" level tests for the UI, I still think I need a way to mock the dispatch calls.

Practically I would love to do the following:
```js
    props: {
        error: null,
        loading: false,
    },
    reduxState: {
    ...
    },
    reduxDispatch: {
        fetchStuff: () => { return ... },
    },
```

**Comment by skidding** [comment]
> Practically I would love to do the following:

I understand, but it's not possible. 😅

A React app is a tree of component, all derived from the root one. Each component converts their props into props for their children. You can't run your code and also interfere with this relationship.

If you want to control the props a component gives to one of its children (`connect` to the wrapped component in your case), you take the parent component out of the equation and render the child directly. If you render the parent you let its do its thing and decide what props its children get.

It's not a thing of principle, it's how React works.

On another note, you _can_ mock your actions by mocking their connection to the outside. If an action does an API request, a get in localStorage, a read from the global window object, you can mock all of those.

**Comment by skidding** [comment]
I'll close this for now. Hope you got started one way or another, and feel free to open other threads.

**Comment by dhaval-radadiya** [comment]
any solution?

**Comment by skidding** [comment]
> any solution?

Yes, mentioned in [this comment](https://github.com/react-cosmos/react-cosmos/issues/763#issuecomment-407142157). If you're using connect you can export the inner component and provide the props to it directly in your fixture. If you want to use the connected component in the fixture you need to wrap it in the Redux Provider and mock the entire Redux state.
