### ISSUE TITLE
Ability to configure fixture editor theme 

### ISSUE THREAD

**Issue by prashant-andani** [react-cosmos/react-cosmos#765]
### **Feature**
Ability to configure Code Mirror theme from cosmos.config.js

In the current implementation, As far as I know, there is no way we can customize the Code Mirror theme.

### **Implementation Details**
We can provide a way for the user to set a theme for the Fixture Editor in cosmos.config.js
something like
```
{
 editorTheme: 'material'
}
```

**Comment by skidding** [comment]
Belongs to http://github.com/react-cosmos/react-cosmos-classic
