### ISSUE TITLE
React Native cannot resolve fixture.

### ISSUE THREAD

**Issue by TwFlem** [react-cosmos/react-cosmos#774]
### What's wrong?
When making a fixture under __fixtures__, the path generated in cosmos.modules.js cannot be resolved.

The metro bundler cannot resolve the path generated in cosmos.modules.js. 

"error: bundling failed: Error: Unable to resolve module... Indeed, none of these files exist:"

However, the files clearly exist.

### Steps to reproduce

1. Create a react native project.
2. Install cosmos
3. Make a fixture under __fixtures__
4. Start cosmos
5. Run the app
6. Observe the error.

### User info

"react-cosmos": "^4.6.0-3",
 "react-cosmos-loader": "^4.6.0-6",
default cosmos config (none)

**Comment by skidding** [comment]
Hi @TwFlem,

I ran into this as well. Have you seen this? https://github.com/react-cosmos/react-cosmos/commit/816cb94ff21449b9902cab22191f52c6eca9ba7b?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by skidding** [comment]
@TwFlem any luck?

You hate to options:
1. Whitelist `__fixtures__` in React Native
2. [Configure Cosmos to use a different file pattern via `fileMatch`](https://github.com/react-cosmos/react-cosmos#custom-fixture-paths)

**Comment by TwFlem** [comment]
@skidding Hey, I did not see 816cb94. I'm good to go. Thank you.
