### ISSUE TITLE
Cosmos not recognizing paths set in tsconfig

### ISSUE THREAD

**Issue by tdelang** [react-cosmos/react-cosmos#775]
In tsconfig I have something like
```
"paths": {
	...
    "@components/*": ["components/*"],
	...
}
```

In my components I use imports like 

`import { ProfileMenu } from '@components/profile-menu/ProfileMenu';`

When I run cosmos, I get

```
ERROR in ./src/components/topbar/Topbar.tsx
Module not found: Error: Can't resolve '@components/profile-menu/ProfileMenu' in 'C:\code\src\components\topbar'
 @ ./src/components/topbar/Topbar.tsx 17:0-67
```

How can I have Cosmos understand where to find `@components`?

My config is:

```module.exports = {
  webpackConfigPath: '/config/webpack.config.dev.js',
  webpack: (config, { env }) => ({
    ...config,
    module: {
      ...config.module,
      rules: [
        ...config.module.rules,
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'babel-loader',
            },
            {
              loader: 'ts-loader',
            },
          ],
        },
      ],
    },
    resolve: {
      extensions: [
        ...config.resolve.extensions,
        '.ts',
        '.tsx',
      ],
    },
  }),
};

**Comment by skidding** [comment]
Hi @tdelang,

> How can I have Cosmos understand where to find `@components`?

Well, how does your app understand where to find `@components`?

> `webpackConfigPath: '/config/webpack.config.dev.js',`

Maybe your webpack config isn't loaded properly, as `webpackConfigPath` should be a relative path. Eg. `'./config/webpack.config.dev.js'`or `'config/webpack.config.dev.js'`. A path that begins `/` will likely be resolved from the root of your file system.

If your existing webpack config is loaded successfully by Cosmos you probably don't need the manual overriding via `webpack` option.

**Comment by tdelang** [comment]
That was it, thank you!
