### ISSUE TITLE
Relative publicPath doesn't work

### ISSUE THREAD

**Issue by shahkashani** [react-cosmos/react-cosmos#777]
### What's wrong?

We ran into some `cosmos-export` issues with the default options. Essentially, `loaderUri` is set to `/loader.html` in the markup, but we're exporting Cosmos into a folder that gets served on gh-pages, and for this to work, we need the loader URL to be relative to the export folder.

Configuring `publicUrl` to be `'./'` in `cosmos.config.js` fixes the exported Cosmos version (`cosmos-export`), but for some reason breaks regular `cosmos`.

(I think we can get around this by having two config files, but that seems like might cause problems down the line.)

### Steps to reproduce

1.  Set publicUrl to `./` in `cosmos.config.js`
2.  Run `cosmos`
3.  Note error below

### Screenshots

![screen shot 2018-07-31 at 3 14 41 pm](https://user-images.githubusercontent.com/1395893/43481641-85163c48-94d4-11e8-8d14-695c2ed19d5b.png)

Interestingly, it ultimately loads the loader from the _same exact URL_ when publicUrl is `/`, and in that instance it works.

### Full config

```
module.exports = {
  fileMatch: [
    '**/fixtures/components/**/*.{js,jsx,ts,tsx}',
    '**/components/**/fixtures/**/*.{js,jsx,ts,tsx}',
  ],
  globalImports: ['src/global-styles/base.scss'],
  webpackConfigPath: 'config/webpack/cosmos.js',
  port: 8989,
  publicUrl: './'
};
```

**Comment by skidding** [comment]
Just published a fix. Please try `4.6.3` and see if it works as expected.

Keep `publicUrl: './'` in your config. I thought about making it the default, but decided against it as it can cause errors for other users. 

> There are edge cases when `./` is still not ideal. publicUrl also sets the value for `PUBLIC_URL` env var, which you may be using to construct URLs in your components. This is not recommended, but if you do and have nested routes in your app, it can create wrong URLs as they will always begin with `./` relative to current router path.

**Comment by shahkashani** [comment]
Wow, you guys rule. Thanks so much for the extremely quick fix! This seems to do the trick.

**Comment by skidding** [comment]
You're welcome!
