### ISSUE TITLE
documentation request: accessing apollo cache from test

### ISSUE THREAD

**Issue by jeznag** [react-cosmos/react-cosmos#783]
### What's up?
I'm trying to figure out how to access the apollo cache when I've mocked it using cosmos. I assumed I could use the `get` helper but that doesn't seem to work properly. It just returns the value that I set in the fixture.

e.g.

```
it.skip('should trigger mutation when submit button clicked', () => {
    const origapolloState = get('apollo');

    const button = getWrapper('button');
    button.simulate('click');

    const apolloState = get('apollo');
    expect(
      apolloState.getAvailableOptions.resolveWith.availableOptions.submitted
    ).toEqual(true);
  });
```

There's probably a way to achieve this but I'm not sure how. Can we add documentation to explain it?

**Comment by xavczen** [comment]
Interesting question! 🤔 

The fixture value will never change, it may help to consider it as a description of what Apollo Client should give as a result of a query/mutation.

What will change is the cache (👍) and the props received by your component if they depend on some query / mutation result.

If you really need to read from the cache directly, you could try to find the `ApolloProvider` in the tree and grab the `client` prop.

Once you have the cache, you can either `cache.readQuery/readFragment` to get data out of it or inspect the proxy object directly.

If I can give my 2 cents, asserting the result with the component props sounds like the best option if possible as it may test what's reflected in the UI and doesn't test implementation details. 🙂

I hope you'll find a solution that fits your application needs!

**Comment by jeznag** [comment]
Thanks for the tips. Here's what I came up with: https://medium.com/energylinkapp/testing-graphql-mutations-using-apollo-cosmos-becab1ea9ac9

**Comment by xavczen** [comment]
Wow, awesome!

**Comment by skidding** [comment]
@jeznag Thanks for the link, it was cool to read about your testing journey!

Personally, I've lately tried to keep my tests as decoupled as possible from internals. So triggering actions and checking for changes in the render output (eg. Success message is shown).

But of course the testing style depends on each type of situation and there's no single right way to do it.
