### ISSUE TITLE
Configurable viewport sizes for the viewport view

### ISSUE THREAD

**Issue by rkclark** [react-cosmos/react-cosmos#787]
### What's up?

In the viewport view you can select from some preset sizes, such as Medium, Large, 1080p, etc. It would be useful these could be configured so that you could create presets that match the major design breakpoints (or target device sizes) for your project.

### Mkay, tell me more...

You could specify the desired viewport presets in the cosmos config file.

Thanks for making Cosmos, it is awesome 💖

**Comment by skidding** [comment]
Hi @rkclark,

They are configurable, I just didn't get to documenting it yet. Let me know if the following works.

```js
// cosmos.config
module.exports = {
  // other options...
  plugin: {
    responsivePreview: {
      devices: [
        { label: 'iPhone 5', width: 320, height: 568 },
        { label: 'iPhone 6', width: 375, height: 667 },
        { label: 'iPhone 6 Plus', width: 414, height: 736 }
      ]
    }
  }
}
```

Note that this overrides all the default devices, so here's the original list in case you want to extend it:

```js
devices: [
  { label: 'iPhone 5', width: 320, height: 568 },
  { label: 'iPhone 6', width: 375, height: 667 },
  { label: 'iPhone 6 Plus', width: 414, height: 736 },
  { label: 'Medium', width: 1024, height: 768 },
  { label: 'Large', width: 1440, height: 900 },
  { label: '1080p', width: 1920, height: 1080 }
]
```

**Comment by rkclark** [comment]
@skidding Brilliant, thank you!
