### ISSUE TITLE
Fullscreen keyboard shortcut

### ISSUE THREAD

**Issue by rkclark** [react-cosmos/react-cosmos#789]
Hey there,

Is there a keyboard shortcut to enter/exit full screen mode? Once I'm in fullscreen mode, I can't get out without setting fullscreen to false in the URL.

Sorry if I've missed it in the docs!

PS: I replaced Storybook with Cosmos in my team's front end app and everyone is loving it. Thanks for making it!

Cheers

**Comment by skidding** [comment]
> PS: I replaced Storybook with Cosmos in my team's front end app and everyone is loving it. Thanks for making it!

🎉

> Is there a keyboard shortcut to enter/exit full screen mode? Once I'm in fullscreen mode, I can't get out without setting fullscreen to false in the URL.

At the moment you can only go back using the browser back button.

The only keyboard shortcuts at the moment are "s" and "escape" to focus/blur the fixture search box on the left. Adding another shortcut for full screen would be easy, but there is a catch.

The component renders in an iframe, and shortcuts are captured outside the iframe. When you go full screen, as soon as you click or focus on an element from your components the Cosmos UI will stop capturing key events, and there's no place to click outside to focus on the Cosmos UI since you're in full screen mode.

There is a possible solution that I've been pondering. We could capture key events in the component iframe as well and comunicate the keyCode via postMessage event as we do with all the other messages (eg. fixture loaded, runtime error, etc). But beside the extra work involved, I wonder if adding event listeners in the iframe where the user code runs can cause any conflict with user code.

Feel free to share you thoughts on this!

**Comment by rkclark** [comment]
Hmm I've never worked with iframes to be honest so not an area where I can offer much expertise unfortunately.

Can you position a browser element over an iframe? If so a non-intrusive exit (X) button could be added in one of the corners to allow the user to exit fullscreen with a mouse click. I realise that it would be preferable to not obstruct any of the screen when the user is viewing their component but if it was suitably small it might not be a problem.

**Comment by skidding** [comment]
> Can you position a browser element over an iframe? If so a non-intrusive exit (X) button could be added in one of the corners to allow the user to exit fullscreen with a mouse click. I realise that it would be preferable to not obstruct any of the screen when the user is viewing their component but if it was suitably small it might not be a problem.

An overlapping button is also an option. As well as a thin side bar on the left with a few key controls, similar to how most apps "minimize" their left nav.

I'll leave this thread open and we should pursue one of these options at some point in the future. But for now I hope the back button is something you can work with.

**Comment by rkclark** [comment]
> An overlapping button is also an option. As well as a thin side bar on the left with a few key controls, similar to how most apps "minimize" their left nav.

I'd try to avoid a left bar as usually when I go into fullscreen mode its to totally control the viewport width to test my component's responsiveness - guess it may be the same for others!

> But for now I hope the back button is something you can work with.

Sure no worries! If I can make some contributions in the future I will do. Kinda busy with my own open source project atm!

**Comment by skidding** [comment]
> I'd try to avoid a left bar as usually when I go into fullscreen mode its to totally control the viewport width to test my component's responsiveness - guess it may be the same for others!

Have you tried the lastest responsive controls added in Cosmos 4.6?

**Comment by rkclark** [comment]
>Have you tried the lastest responsive controls added in Cosmos 4.6?

I'm on 4.6.4, which ones do you mean?

**Comment by skidding** [comment]
I mean the feature mentioned in the 2nd part of [this article.](https://medium.com/@skidding/cosmos-4-6-a-minor-version-with-major-updates-27654de7f0c8)

I'm wondering if going full screen offers responsive capabilities not provided by the responsive controls available.

**Comment by rkclark** [comment]
@skidding Yeah so that feature is really useful, and I use it to target the main breakpoints in my project. However, I then switch to full screen mode to drag the viewport size in Chrome dev tools to see how my component behaves as the viewport expands/shrinks - rather than just looking at specific breakpoints. This is to check there is no weird behaviour between breakpoints.

**Comment by maxsalven** [comment]
@skidding not something I have bandwidth for at the moment, but perhaps making the responsive iframe resizable by dragging on an edge (just as if it were a window) might be a nice feature (the tab at the top would then switch to 'Custom' with live display of your iframe size whilst you're resizing it).

**Comment by skidding** [comment]
> @skidding not something I have bandwidth for at the moment, but perhaps making the responsive iframe resizable by dragging on an edge (just as if it were a window) might be a nice feature (the tab at the top would then switch to 'Custom' with live display of your iframe size whilst you're resizing it).

Definitely! I was thinking the same thing. Can't make any promises either but it's definitely on my radar. I also felt the need.

**Comment by Izhaki** [comment]
Some apps and many web site use mouse proximity to the client edge and scroll-in the hidden panel if the mouse is, say, 5 px from the client edge.

You may have seen this with Webpack-Bundle-Analyser.

Just an idea.

**Comment by skidding** [comment]
FYI, a keyboard shortcut was added for going full screen in #1070. Another big improvement is that all keyboard shortcuts now work even when focused inside the renderer iframe. This will be available starting with `5.0.0-beta.11` and above.

![image](https://user-images.githubusercontent.com/250750/67159223-8e2db380-f34a-11e9-9629-af39ea2a7ad0.png)
