### ISSUE TITLE
react-cosmos-playground configuration

### ISSUE THREAD

**Issue by ibrahimovfuad** [react-cosmos/react-cosmos#790]
### What's up?

I am using react-cosmos-playground with responsive breackpoints, but i can't configure breackpoints for myself.
I think it will be good if you will add an ability to customize responsive breackpoints globally.

### Mkay, tell me more...

I think it would be nice to configure any plugin inside react-cosmos config.

**Comment by skidding** [comment]
Please see https://github.com/react-cosmos/react-cosmos/issues/787#issuecomment-411355703

**Comment by ibrahimovfuad** [comment]
Thanks a lot. it is worked for me.
