### ISSUE TITLE
React devtools "Select element" can't be used with cosmos

### ISSUE THREAD

**Issue by cbranch101** [react-cosmos/react-cosmos#791]
### What's wrong?

The fact that everything in Cosmos now renders in an iframe means that there's no way to inspect components in React DevTools, it just always points back to the iframe.  I wasn't sure if this qualified as a bug or feature request, but this is definitely a serious impediment to working with Cosmos. 

### Steps to reproduce
1. Try to inspect any element in cosmos in React DevTools
2. Notice that you get pointed to an iframe

**Comment by zach-albia** [comment]
If anyone's looking for a workaround for now, select the element in the 'Elements' tab then just jump to the 'React' tabs in chrome dev tools. That way, the element I selected gets selected in react dev tools as well.

**Comment by skidding** [comment]
As @zach-albia pointed out, this is also the flow I generally use. For some reason selecting a DOM element sometimes doesn't get selected in the React panel, but usually the 2nd time it does.

![cosmos-react-devtools](https://user-images.githubusercontent.com/250750/44022893-a04087b8-9ef1-11e8-85e7-9a06fd424c22.gif)


Alternatively, it is recommended to use the [standalone react-devtools](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools) with iframes. But I tried it out and it provides a lesser experience. 

![screenshot 2018-08-13 12 40 41](https://user-images.githubusercontent.com/250750/44024662-99b4d868-9ef6-11e8-8fe8-28a8b90c87a0.png)

Besides a few hard-to-understand errors, the offseting of the selected element seems to be off, and the "Inspect" tool is missing altogether, so using the regular devtools React panel seems like the best option.

---

The only possible improvement I can imagine is this: Rendering the component in the root frame when going full screen. It will degrade the performance of going back and forth in the browser history, as currently the state is preserved when toggling full screen. But for some edge cases it offers the possiblity to render a component directly (no iframe) as a regular app is. 

Still, most of the time we'll develop with the Cosmos UI present and the component rendered in an iframe, and the iframe limitations of the react-devtools are something we have to live with for now.

**Comment by cbranch101** [comment]
Awesome, this is a great workaround, thanks guys!
