### ISSUE TITLE
Browserify example is broken

### ISSUE THREAD

**Issue by terrierscript** [react-cosmos/react-cosmos#793]
### What's wrong?

Occure error when try `example/browserify`.

### Steps to reproduce

1.  clone this repo
2.  move examples/browserify
3.  node ./server.js
4. I got error.

```
index.js:71 TypeError: Cannot read property 'responsivePreview' of undefined
    at t.getPluginConfig (index.js:23)
    at t.value (index.js:31)
    at Ai (index.js:71)
    at Fi (index.js:71)
    at pa (index.js:71)
    at ha (index.js:71)
    at Ga (index.js:71)
    at Ka (index.js:71)
    at qa (index.js:71)
    at Ha (index.js:71)
```

### User info

- Server terminal output
- Browser console output : pasted
- Cosmos version : HEAD
- If bug occurred on upgrade: Working Cosmos version
- Cosmos config
- If applicable: webpack version
- If applicable: webpack config

**Comment by skidding** [comment]
@terrierscript Sorry about that! I've fixed the example in #798.

Please try again on the latest master branch, and make sure to follow the [special instructions for the Browserify example](https://github.com/react-cosmos/react-cosmos/blob/9cbe76fa83a29a2790ae62ee2adca16f6fd6db7e/examples/browserify/README.md).

![cosmos-browserify](https://user-images.githubusercontent.com/250750/44026776-e25a388c-9efc-11e8-9b9d-f1c022f9c19a.gif)
