### ISSUE TITLE
A next.js/typescript/react-cosmos example

### ISSUE THREAD

**Issue by zach-albia** [react-cosmos/react-cosmos#795]
### What's up?

While adding react-cosmos to a new typescript next.js project, I've had to remove TS just to get cosmos to play nicely and run at all. I'd like to be able to return to using TS and a minimal example integrating all three would be immensely useful.

### Mkay, tell me more...

From what I've read, react-cosmos uses userland webpack and babel config. I'm not a config expert. What I'm probably missing is some next.js, webpack or babel configuration. I've tried this and that but I'm afraid I'm out of my depth on this one. :(

EDIT: Adding a link to my attempt here: https://github.com/zach-albia/with-typescript-react-cosmos

**Comment by zach-albia** [comment]
Ok, I [got it to work](https://github.com/zach-albia/with-typescript-react-cosmos/commit/e8478155f7ba630d27ab1025acbea45b741cf098) by configuring cosmos to use its _own_ webpack config _separate_ from next.js. I took a page out of #767's config.

**Comment by skidding** [comment]
@zach-albia Happy to hear you made it work!

I've also got better results from _not_ using Next's webpack config in Cosmos. The Next.js example doesn't use `webpackConfigPath` and as a matter of fact I don't even know how to import Next's webpack config.

Anyway, is there anything we can add to the README to save people from digging on their own in the future? Maybe the `resolve.extensions` bit. It can be in the Next.js section or we can create a dedicated TypeScript section if it's not Next related.

**Comment by zach-albia** [comment]
>  I don't even know how to import Next's webpack config.

@skidding Yeah, that was my line of thinking as well. I've scrounged around next.js' docs many times for it but came up with nothing every time.

At any rate, I don't see the `resolve.extensions` part of README but we can probably start adding a dedicated TypeScript section like you said. I'm thinking we can add subsections for create-react-app-typescript, TypeScript-React-Starter and a next-js-typescript example.

That said, it begs the question: do you think it's time for react-cosmos to have TS type declarations? Is TS support somewhere on the project roadmap BTW?

**Comment by Rhagaer** [comment]
Hey guys I used #767 webpack config in my react typescript project. But webpack can't seem to handle jpg's
`ERROR in ./src/assets/img/as-featured-in/uct.png
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type` 

Nor anything to do with graphql 
`ERROR in ./src/apollo/queries/getNotifications.gql
Module parse failed: Unexpected token (1:6)
You may need an appropriate loader to handle this file type`

I have 0 experience with web pack so any help with configuring my project to work would be immensely appreciated

**Comment by skidding** [comment]
@Rhagaer you need to add these two loaders to your webpack config as well:

- https://github.com/vanwagonet/img-loader#usage
- https://github.com/smitt04/gql-loader#config

**Comment by skidding** [comment]
> That said, it begs the question: do you think it's time for react-cosmos to have TS type declarations? Are they somewhere on the project roadmap BTW?

@zach-albia It's not on the roadmap but it would be a great addition for sure. Note that while Cosmos has a lot of Flow types, they are for internal use. The only public types here https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos/index.js.flow and they should be easy to reproduce in TS (they might work as is), but I don't have experience with publishing TS types. If you do let me know!

**Comment by zach-albia** [comment]
@skidding I actually just finished making some public-facing type declarations for Cosmos for use in my project based off of your flow typings. I also have typings for some out-of-the-box proxies that I've used, namely redux, context, and apollo proxies. At any rate, would you rather have typings bundled with Cosmos' npm packages or have them published separately in DefinitelyTyped?

**Comment by skidding** [comment]
>  I actually just finished making some public-facing type declarations for Cosmos for use in my project based off of your flow typings. I also have typings for some out-of-the-box proxies that I've used, namely redux, context, and apollo proxies.

Sound great!

> At any rate, would you rather have typings bundled with Cosmos' npm packages or have them published separately in DefinitelyTyped?

Whichever you think is more suited based on your experience with TS. I'm open to both.

**Comment by jcarraway** [comment]
@zach-albia @skidding any more progress on publishing types for Cosmos? 

It would definitely be helpful to add a Typescript section with this example to the README as well. Thanks for the help!

**Comment by BjoernRave** [comment]
@zach-albia are you still using cosmos with next.js and typescript? I tried using your repo with the latests `react-cosmos`, but it's not working anymore

**Comment by skidding** [comment]
@BjoernRave What's the issue? React Cosmos 5 is fully written in TypeScript and it should also work well with Next.js. Did you see this section? https://github.com/react-cosmos/react-cosmos#using-nextjs
