### ISSUE TITLE
Playground doesn't scale correctly in fullscreen mode

### ISSUE THREAD

**Issue by ibrahimovfuad** [react-cosmos/react-cosmos#805]
### What's up?

When i use react-cosmos in fullscreen mode and mobile device emulation in chrome is enabled, playground doesn't scale correctly.

### Mkay, tell me more...

The solution is in adding this META-tag to the head section of your index.html.
`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`

**Comment by skidding** [comment]
Hi @ibrahimovfuad,

Components are loaded in an iframe to isolate from the Cosmos UI, and that's why mobile device emulation doesn't work as expected. Did you try the built in responsive controls in Cosmos?

**Comment by ibrahimovfuad** [comment]
Hi @skidding 
I mean the problem is in the mobile chrome emulation in full screen mode.
See how i fixed it on screenshots below.

Without meta tag
![without-meta-tag](https://user-images.githubusercontent.com/10096764/44258719-4d06b480-a218-11e8-9818-a7c262339dc4.PNG)

With meta tag
![with-meta-tag](https://user-images.githubusercontent.com/10096764/44258718-4d06b480-a218-11e8-9a68-7030443de84d.PNG)

**Comment by skidding** [comment]
Hmm, I think you're right. I didn't think this would work given that the component renders in an iframe. My bad.

This should be easy to add. [This is where it should be added](https://github.com/react-cosmos/react-cosmos/blob/5beaa1ddbd1db42344b968fe9304adb7e10df749/packages/react-cosmos/src/server/shared/static/index.html). Feel free to open a PR.

In what situations is `shrink-to-fit` useful? I've used the other values before but it's the first time I see this one.

**Comment by ibrahimovfuad** [comment]
@skidding , [Here](https://stackoverflow.com/questions/33767533/what-does-the-shrink-to-fit-viewport-meta-attribute-do) you can find extended explanation of `shrink-to-fit` usage.

**Comment by ibrahimovfuad** [comment]
I don't have permission to push in react-cosmos repository

**Comment by skidding** [comment]
You can create a pull request from a fork https://guides.github.com/activities/forking/
