### ISSUE TITLE
CSS Modules custom web pack failing 

### ISSUE THREAD

**Issue by Rhagaer** [react-cosmos/react-cosmos#811]
Trying to get CSS modules working with my typescript project. 
Using the config for CSS found [here](https://github.com/react-cosmos/react-cosmos/issues/631#issuecomment-376151216 ): 
I get the following error 

```
ERROR in ./node_modules/css-loader!./node_modules/style-loader!./node_modules/css-loader!./src/containers/Sell/Head.css
Module build failed: Unknown word (5:1)
  3 | // load the styles
  4 | var content = require("!!../../../node_modules/css-loader/index.js!./Head.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
     | ^
  6 | // Prepare cssTransformation
  7 | var transform;
  8 | 
```

My webpack config: 

```
module.exports = {
  webpack: (config, { env }) => ({
    ...config,
    module: {
      ...config.module,
      rules: [
        ...config.module.rules,
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,

          use: [
            {
              loader: "babel-loader"
            },
            {
              loader: "ts-loader"
            }
          ]
        },
        {
          test: /\.(graphql|gql)$/,
          exclude: /node_modules/,
          loader: ["graphql-tag/loader"]
        },
        {
          test: /\.(png|jp(e*)g|svg)$/,
          exclude: /node_modules/,
          use: [
            {
              loader: "url-loader",
              options: {
                limit: 8000,
                name: "images/[hash]-[name].[ext]"
              }
            }
          ]
        },

        {
          // Preprocess both own and 3rd party CSS files
          test: /\.css$/,
          use: ["style-loader", "css-loader"]
        }
      ]
    },
    resolve: {
      extensions: [
        ...config.resolve.extensions,
        ".ts",
        ".tsx",
        ".gql",
        ".graphql",
        ".css"
      ]
    }
  })
};
```

Been playing around with a lot of different configs for CSS modules and none seem to work, they all yield the same issue. 

Any help would be immensely appreciated

**Comment by Rhagaer** [comment]
I don't know if I was being thick but the default cosmos settings were not working for me. So I figured I had to write my own webpack config. I read that you can use your existing webpack config only now. So fixed my problem by simply changing my cosmos.config.js to 

```
module.exports = {
  webpackConfigPath: "./config/webpack.config.dev.js"
};
``` 

Perhaps make that more clear in the readme to prevent a noob such as myself spending hours trying to create my own webpack config.

**Comment by skidding** [comment]
@Rhagaer happy to hear it worked out!

Here's the existing docs:

![image](https://user-images.githubusercontent.com/250750/44348480-36c05900-a4a3-11e8-9160-cd936922d2f8.png)

Any ideas to make it more obvious? Maybe a small code sample underneath like:

```js
// cosmos.config.js
module.exports = {
  webpackConfigPath: './config/webpack.config.dev.js'
};
```

**Comment by Rhagaer** [comment]
Ye I think a code sample like that would be perfect :)

**Comment by skidding** [comment]
@Rhagaer If you feel like making a contribution this PR should be very easy to make! :D

**Comment by skidding** [comment]
Done https://github.com/react-cosmos/react-cosmos#custom-webpack-config
