### ISSUE TITLE
Add support for ParcelJS 

### ISSUE THREAD

**Issue by RPDeshaies** [react-cosmos/react-cosmos#812]
### What's up?

ParcelJS has more than 25K ⭐️ on github and is a fantastic library.
Right now, react cosmos supports webpack and browserify out of the box.
Adding support for ParcelJS would be fantastic because you could setup react-cosmos, without config using a "no config"  bundler !

https://github.com/parcel-bundler/parcel

### Mkay, tell me more...
I was able to make ParcelJS work with React Cosmos, but there's a lot of things to do to make it work.

Here is what I had to do, from start to finish. Maybe it can be a good starting point...

I created a index.html for the playground

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <script src="./playground.tsx"></script>
</body>

</html>
```

I created the `playground.tsx` file:

```
const mountPlayground = require("react-cosmos-playground");

mountPlayground({
  platform: "web",
  plugin: {
    responsivePreview: undefined
  },
  loaderUri: "/playground/loader"
});

```

---

Then I create the loader html/typescript files

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <script src="./loader.tsx"></script>
</body>

</html>
```

```
import { mount } from "react-cosmos-loader/dom";

mount({
  proxies: [],
  fixtures: {
    "A Fixture": someFixture
  }
})
```

---

Here are the tasks in my `package.json`

```
 "playground": "concurrently --kill-others \"npm run playground:watch:index\" \"npm run playground:watch:loader\" \"nodemon playground.js\"",
    "playground:watch:index": "parcel watch src/modules/playground/app/index.html --out-dir static/playground --public-url /static/playground",
    "playground:watch:loader": "parcel watch src/modules/playground/loader/index.html --out-dir static/playground/loader --public-url /static/playground/loader",
    "playground:build:index": "parcel build src/modules/playground/app/index.html --out-dir static/playground --no-cache --public-url /static/playground",
    "playground:build:loader": "parcel build src/modules/playground/loader/index.html --out-dir static/playground/loader --no-cache --public-url /static/playground/loader",
```

And then to start the react-cosmos server, I add to do this:

```
const express = require("express");
const path = require("path");
const fs = require("fs-extra");
const app = express();

app.get("/playground/loader", (req, res) => {
  const file = fs.readFileSync(
    path.join(__dirname + "/static/playground/loader/index.html")
  );
  res.write(file);
  res.end();
});

app.get("/playground", (req, res) => {
  const file = fs.readFileSync(
    path.join(__dirname + "/static/playground/index.html")
  );
  res.write(file);
  res.end();
});

app.use("/static", express.static(path.join(__dirname, "static")));

app.listen(3000, () => console.log("Listening on localhost:3000"));

```

**Comment by skidding** [comment]
@RPDeshaies Thanks for your detailed analysis! 

I've been thinking about earlier today actually. :)

I'm currently deeply engaged in executing a [roadmap](https://github.com/react-cosmos/react-cosmos/blob/81623835232b2cd2d7f097ea16b4d1b9605dcc40/TODO.md). It's probably going to take another 2 months to complete and deliver the new APIs I'm working on. Afterwards I'll draft a new roadmap which will most likely include opening up a plugin API on the server side, extracting the current webpack support into a plugin and surely creating a core plugin for Parcel.

Let's keep this thread open until we get there and if anybody wants to get on board with React Cosmos + Parcel sooner hopefully they can use your notes as inspiration.

**Comment by RPDeshaies** [comment]
>@RPDeshaies Thanks for your detailed analysis!

Always happy to help !

>I've been thinking about earlier today actually. :)

Hahaha nice !

>plugin API on the server side, extracting the current webpack support into a plugin and surely creating a core plugin for Parcel.

That is a very good idea..
Also as a side note, thanks for this awesome project. We use it on a day to day basis at my job now.

Maybe for the time being, since those APIs are not ready, we could include more doc on how to spin up react cosmos with your own integration. 

Because when you guys released the newest version of the app, I had to check the code diff in the source code of that project to realized that you added a `platform` and `plugin.responsivePreview` property to the object of `mountPlayground` that crashed react cosmos when undefined ! 😅

**Comment by skidding** [comment]
> Also as a side note, thanks for this awesome project. We use it on a day to day basis at my job now.

🤘

> Because when you guys released the newest version of the app, I had to check the code diff in the source code of that project to realized that you added a platform and plugin.responsivePreview property to the object of mountPlayground that crashed react cosmos when undefined ! 

Ouch! I'll be more careful the next time I introduce a change like this!

> Maybe for the time being, since those APIs are not ready, we could include more doc on how to spin up react cosmos with your own integration.

Good idea. The only problem is I'm reshaping those building blocks at the moment and I would prefer documenting them afterwards.

Here's another idea: Since you already figured out the Parcel integration, maybe we can create a `parcel-example` repo in the [Cosmos organization](https://github.com/react-cosmos) to help people get started until better support arrives? I know we all have tons of things to do, but if you're interested in setting this up I'd be more than happy to create the repo and give you write permissions!

**Comment by RPDeshaies** [comment]
> But if you're interested in setting this up I'd be more than happy to create the repo and give you write permissions!
I'm down :) It's still pretty fresh in my mind it should not take me too much time.
I'll still create a PR to have your feedback if you don't mind !

**Comment by skidding** [comment]
I'm down :) It's still pretty fresh in my mind it should not take me too much time.

Nice! https://github.com/react-cosmos/parcel-example

> I'll still create a PR to have your feedback if you don't mind !

For sure.

**Comment by RPDeshaies** [comment]
First PR is there for the curious

https://github.com/react-cosmos/parcel-example/pull/1

Sorry for the delay :)

**Comment by skidding** [comment]
Link to example was added in README.
