### ISSUE TITLE
IE11 maintenance

### ISSUE THREAD

**Issue by kbirulia** [react-cosmos/react-cosmos#813]
Application doesn't work in IE11. Using of babel polyfills solve this problem. I saw it is switched off in .babelrc. As written in babel-plugin-transform-runtime documentation all boolean options are set into true by default. I propose remove transform-runtime options in order to get the same result and turn on polyfills.

**Comment by skidding** [comment]
@kbirulia Can you please show me a screenshot of the error where it occurs? 

As Cosmos has two separate builds (the first is built before being published on npm and the second is built using the user's configuration when running Cosmos), I'd like to understand which is the issue related to.

Thanks for your help!

**Comment by kbirulia** [comment]
This issue related to building packages on publishing, when packages dist directories is being generated. Ie11 error has little information about where errors occur. But the best way to find places, where unsupported features are used, is run build in react-cosmos with my proposal config and search by code babel-runtime/core-js. It shows polyfills imports, that is necessary for certain file. 
![image](https://user-images.githubusercontent.com/22476665/44577383-9ff0e680-a799-11e8-8a8b-56b99ee6d388.png)
![image](https://user-images.githubusercontent.com/22476665/44577598-36250c80-a79a-11e8-8260-8867e960d0fb.png)

**Comment by skidding** [comment]
Thanks @kbirulia!

I tested in a Window VM and could confirm your experience. I also discovered a few other small problems when working on Cosmos on Windows that I'll address shortly.

**Comment by skidding** [comment]
@kbirulia This is fixed `react-cosmos@4.7.0-4` (beta release). Let me know if all's good if you have the chance.
