### ISSUE TITLE
Documentation for custom plugins

### ISSUE THREAD

**Issue by ibrahimovfuad** [react-cosmos/react-cosmos#815]
### What's up?

I need to write plugin for toggling languages for react-cosmos. So can you provide some documentation for adding custom plugins ?

**Comment by skidding** [comment]
Hi @ibrahimovfuad,

At the moment you can create plugins through [Proxies](https://github.com/react-cosmos/react-cosmos#proxies). To learn how to create one, check out [the Proxy boilerplate](https://github.com/react-cosmos/react-cosmos/blob/master/CONTRIBUTING.md#proxy-boilerplate). It also mentions a few key points on how proxies work. You can ignore the Flow types from the  example.

Also relevant, I'm working on opening up more powerful plugin API, but it's going take some time before those become available. To make my working agenda as tranparent as I can, I just added this banner on the [README](https://github.com/react-cosmos/react-cosmos/blob/master/README.md):

> **Major changes are afoot!** In a nutshell, you'll get an easier, more flexible way to express fixtures, as well as a powerful plugin API for extending the Cosmos UI. The plan is outlined [here](https://github.com/react-cosmos/react-cosmos/blob/master/TODO.md).
>
> Meanwhile, I apologize if this creates a period of confusion. Soon I'll dark launch new functionality that Cosmos early adopters can enable to peak into the future and help shape it. Follow [@ReactCosmos](https://twitter.com/ReactCosmos) to get notified.

I'll close this for now to prevent spending time on too many threads, but feel free to ask further questions. Thanks!
