### ISSUE TITLE
Is there a way to provide the component name when using Wrapper Component functions?

### ISSUE THREAD

**Issue by tryggvigy** [react-cosmos/react-cosmos#826]
Hey! Nifty library. Really happy with it so far! Thanks for the hard work.

I've searched previous issues and also briefly looked at the src code without finding an answer to this:

When using a [Wrapper Component](https://github.com/react-cosmos/react-cosmos#wrapper-component)

The catalog looks like this:
![image](https://user-images.githubusercontent.com/2373958/44789421-ce593200-ab9c-11e8-8b6f-34ca8faee01f.png)

I'm using a function for the `component` key because I want to decorate the component with additional information:

```js
  component: props => (
    <ComponentPresenter>
      <PropTable type={Carousel}>
        <ConnectedCarousel {...props} />
      </PropTable>
    </ComponentPresenter>
  ),
```

Is there a way for me to specify a displayName that will be used for the top-level component name in the catalog?

**Comment by xavczen** [comment]
Hey! Yeah, `displayName` is the key to this problem :+1: 

You can create a separate variable for the wrapper component and assign it a `displayName`:

```jsx
const WrapperComponent = props => (
  <ComponentPresenter>
    <PropTable type={Carousel}>
      <ConnectedCarousel {...props} />
    </PropTable>
  </ComponentPresenter>
);

// The fixture will be shown in the tree as ComponentPresenter
WrapperComponent.displayName = "ComponentPresenter";

// separating names with a / will make the fixture ComponentPresenter 
// appear in a nested folder called "directory".
// WrapperComponent.displayName = "directory/ComponentPresenter";

export default {
  component: WrapperComponent,
  // ...
};
```
