### ISSUE TITLE
React Native integration `no fixture selected` message

### ISSUE THREAD

**Issue by keyserfaty** [react-cosmos/react-cosmos#832]
### What's wrong?
Hi! I'm trying to implement the library on a preexisting React Native app (an ejected one). I've reproduced every step in the guide and I'm getting a `no fixture selected` on the device while getting a `Waiting for a signal from your React Native build ` in the browser.

The way i'm running it is by running `react-native run-android` + `yarn run cosmos` -> `cosmos-native`. I'm also not sure if I should run the app or just the bundler (tried both).

### Steps to reproduce

Files: 

``` js
// index.js
import RootNavigator from './src/app/Root'

AppRegistry.registerComponent('MyApp', () => RootNavigator)
```

``` js
// src/app/Root.js

module.exports = global.__DEV__
  ? require('./Root.cosmos')
  : require('./Root.main')
```

``` js
// src/app/Root.cosmos.js

import React, { Component } from 'react'
import { CosmosNativeLoader } from 'react-cosmos-loader/native'
/* eslint-disable-next-line import/no-unresolved */
import { options, getUserModules } from '../../cosmos.modules'

export default class App extends Component {
  render () {
    return <CosmosNativeLoader options={options} modules={getUserModules()} />
  }
}

```

``` js
// src/app/Root.main.js

import React, { Component } from 'react'
import { Provider } from 'react-redux'

import AppWithNavigationState from './App'

import configureStore from './configureStore'
const store = configureStore()

class Root extends Component {
  render () {
    return (
      <Provider store={store}>
        <AppWithNavigationState />
      </Provider>
    )
  }
}

export default Root

```

### User info

```
"react-cosmos": "^4.6.4",
"react-cosmos-loader": "^4.6.4",
"react-cosmos-test": "^4.6.4",
```

Thanks!!

**Comment by skidding** [comment]
Hey @keyserfaty,

Did you create any fixture? And can you please share the contents of the auto-generated `cosmos.modules` file?

Thanks!

**Comment by keyserfaty** [comment]
Sure:

``` js
// This file is automatically generated by Cosmos. Best ignore it.
export const options = {
  port: 8989
};

export function getUserModules() {
  return {
    fixtureModules: {'/Users/karen/Code/nilus/Shipper/src/components/ButtonPrimary/__fixtures__/index.js':require('/Users/karen/Code/nilus/Shipper/src/components/ButtonPrimary/__fixtures__/index.js')},
    fixtureFiles: [{"filePath":"/Users/karen/Code/nilus/Shipper/src/components/ButtonPrimary/__fixtures__/index.js","components":[{"name":"ButtonPrimary","filePath":"/Users/karen/Code/nilus/Shipper/src/components/ButtonPrimary/ButtonPrimary.js"}]}],
    proxies: []
  }
};

```

This is the content of the fixture:
``` js
import ButtonPrimary from '../ButtonPrimary'

export default {
  component: ButtonPrimary,
  props: {
    text: 'Lorem ipsum',
    disabled: true,
    onPress: value => console.log(`Select: ${value}`)
  }
}
```

**Comment by skidding** [comment]
Hmm, they both look right.

Not getting any error/weird message in either the browser console of the React Native build log?

It's likely that the React Native runtime can't connect to the browser remotely. Most of my experience is with [create-react-native-app](https://github.com/react-community/create-react-native-app) (Expo), so maybe there's a blind spot in the current Cosmos integration with regards to the larger RN landscape.

[Here's how the websockets URL is constructed](https://github.com/react-cosmos/react-cosmos/blob/6347b3e8ac8c7c7d45bc1f8529ffdceefcab11cf/packages/react-cosmos-loader/src/native.js#L132).

```js
import parse from 'url-parse';

function getSocketUrl(port: number) {
  const host = parse(NativeModules.SourceCode.scriptURL).hostname;

  return `ws://${host}:${port}`;
}
```

If you can, try logging the value returned by this function to see if the URL is valid and if it points to your local computer, where the Cosmos server and UI are running.

**Comment by keyserfaty** [comment]
Don't know exactly where to print that out but the connection seems correct:
`ws://localhost:8989/socket.io/?EIO=3&transport=websocket&sid=-b-P0w8t8EwztTe2AAAB`

And I'm not getting any errors of connecting in the console of the playground.

**Comment by skidding** [comment]
> Was able to do it. It prints out: `ws://localhost:8989`

I'm not sure if it should be _localhost_, given that the Native code runs in a sandboxed environment.

I just ran [react-cosmos/create-react-native-app-example](https://github.com/react-cosmos/create-react-native-app-example) on my Android phone and the socket URL ends up being `ws://10.0.1.4:8989`.

Until we come up with a better idea, can you also try the example repo above to determine if the problem is project related or if you're getting a different experience on your system?

**Comment by skidding** [comment]
Unfortunately I'm afraid this is outside my area of knowledge. It would be great if someone with more React Native experience could pitch in.

If you think you can obtain the IP address some other way (if indeed this is the issue), I could add an option to `CosmosNativeLoader` to pass down the URL manually.

**Comment by zedtux** [comment]
I'm also looking for this. In the case I find something, I'll update the issue.

**Comment by zedtux** [comment]
BTW @keyserfaty do you know about https://github.com/jerolimov/react-native-cosmos ?

**Comment by skidding** [comment]
> BTW @keyserfaty do you know about https://github.com/jerolimov/react-native-cosmos ?

The project hasn't been updated in 2/3 years so I doubt it still works with latest react-cosmos.

**Comment by zedtux** [comment]
You are right @skidding, I was just posting it regarding the way it has been achieved, in the case a new angle of view would help here, but as I just discovered today Cosmos, I couldn't figured out if this lib was relevant or not, sorry.

**Comment by skidding** [comment]
No worries! Thanks for sharing. I just wanted to throw in my 2 cents and potentially save someone headaches from using outdated stuff :D

**Comment by skidding** [comment]
Please create new threads for an RN issues.

**Comment by tinahollybunch** [comment]
The `adb` command here works nicely to get this working on Android: https://github.com/infinitered/reactotron/issues/815#issuecomment-645829046
