### ISSUE TITLE
Webpack errors should fail the export command

### ISSUE THREAD

**Issue by koggdal** [react-cosmos/react-cosmos#834]
### What's wrong?

When running the regular dev command you will see Webpack errors like `Module not found: Error: Can't resolve......`, but the export command completely hides that and from the console output it looks like a successful build.

### Steps to reproduce

_(I'm running this on latest version, 4.6.4)_

1. Introduce a bug where a file is importing another file that doesn't exist.
2. `cosmos-export`
3. The build should now fail and display the errors, but instead the output looks the same as a successful build.

### Additional context

I looked into it a bit and it looks like we might want to check the `stats` object here: https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos/src/server/web/export.js#L31 (webpack docs: https://webpack.js.org/api/node/#stats-haserrors-). Unfortunately I ran into build issues with Babel when trying to get the `react-cosmos` repo running locally, and I don't have time currently to dig deeper to fix it. But maybe someone else can pick up from here :)

**Comment by skidding** [comment]
@koggdal Turns out the examples were no longer working since upgrading to Babel 7. Maybe this is what you were experiencing it. FYI I fixed it in #839.

**Comment by koggdal** [comment]
Thanks for fixing it @skidding! 👍 It works great now, and I sent a fix for this issue here: https://github.com/react-cosmos/react-cosmos/pull/849
