### ISSUE TITLE
Use with Next.js and custom next.config.js

### ISSUE THREAD

**Issue by alfredvaa** [react-cosmos/react-cosmos#854]
### What's wrong?

I am getting this, which is inside a .scss in my project:

```
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '../../colors';
```

I am using next.js with next-sass to have css modules and sass working. This is configured in next.config.js:

```
const withSass = require('@zeit/next-sass');
const webpack = require('webpack');

module.exports = withSass({
  cssModules: true,
  cssLoaderOptions: {
    localIdentName: '[local]___[hash:base64:5]',
  },
  webpack(config) {
    return config;
  },
});
```

### Steps to reproduce

install next.js and next-sass

### User info

I tried something like this to get it working but that did not do it:

```
const nextConfig = require('./next.config');

module.exports = {
  publicPath: 'static',
  publicUrl: '/static/',
  webpack: config => ({ ...config, ...nextConfig.webpack() }),
};
```

**Comment by skidding** [comment]
`({ ...config, ...nextConfig.webpack() })` does shallow merging, which is not enough for merging webpack configs. 

Does this work?

```js
webpack: () => nextConfig.webpack()
```

Ie. Use Next's webpack config entirely.

**Comment by hobofan** [comment]
That doesn't work, as the `nextConfig.webpack` function only allows you to decorate the webpack config during a next.js build, so what we want would actually be its parameter. After some searching through the source, there seems to be no way to obtain the webpack config used by next.js. There exists a related closed issue (https://github.com/zeit/next.js/issues/1641).

**Comment by Ken123777** [comment]
@alfredvaa @hobofan Have you guys found a solution for this?

**Comment by skidding** [comment]
Please reopen if you still have this issue with Cosmos Next.
