### ISSUE TITLE
Cannot make reduxState to work

### ISSUE THREAD

**Issue by alfredvaa** [react-cosmos/react-cosmos#891]
### What's wrong?

I cannot use the reduxState prop in fixtures to set the redux state.

### Steps to reproduce

I installed the proxy plugin 

`yarn add react-cosmos-redux-proxy`

And then added a proxy config in the root of my project

```
import createReduxProxy from 'react-cosmos-redux-proxy';
import { configureStore } from './client/app/store/rootStore';

const ReduxProxy = createReduxProxy({
  createStore: state => configureStore(state),
});

export default [
  ReduxProxy,
  // ...other proxies
];
```

If I do a console.log in the mapStateToProps in a container component (which is connected to redux) I can see the initial state of my store, which seems good.

I can not however update that initial state with the reduxState prop in the fixture.

```
import CosmosWrapper from 'UI/CosmosWrapper';
import Component from './Component';

const WrappedComponent = CosmosWrapper(Component);

export default [
  {
    name: 'Default',
    component: WrappedComponent,
    props: {
    },
    reduxState: { testReducer: { testvalue: true } },
  },
];
```

I excpected the initial state to be updated with testvalue: true inside the testReducer, but I can't see any changes. I cannot in any way see the value of testvalue inside Component. Is this how it is supposed to work? What am I missing here?

### User info

- Cosmos version 4.6.4

**Comment by skidding** [comment]
Hi @alfredvaa,

Are you using React devtools? I think it's the easiest way to see if the Redux state gets populated.

Also, make sure `testReducer` is the state attribute the testReducer gets assigned to when you compose reducers into the root one. Feel free to share your store/reducer config and I'll be able to tell more.
