### ISSUE TITLE
Update fetch-mock to the latest version

### ISSUE THREAD

**Issue by callumlocke** [react-cosmos/react-cosmos#892]
### What's up?

The fetch proxy uses a version of fetch-mock that is really old, and 2 major versions behind stable. This makes looking up docs difficult and means we don't have access to the modern API. 

### Mkay, tell me more...

In particular I want its new `fallbackToNetwork: false` behaviour. I think it's really confusing if the mocked fetch falls back to doing a real network request just because you made a typo in your mock endpoint interceptor. Serious footgun.

**Comment by skidding** [comment]
I'd be great if someone could pick this up. 

For what it's worth [@react-mock/fetch](https://github.com/skidding/react-mock/blob/master/packages/fetch/src/index.js) uses `fetch-mock@7.x` so we can use that for inspiration.

As long as the proxy API doesn't change we can publish this with the next patch version.

**Comment by skidding** [comment]
Reopen in http://github.com/react-cosmos/react-cosmos-classic if needed.
