### ISSUE TITLE
React-JSS hot reload loses styles

### ISSUE THREAD

**Issue by furious-luke** [react-cosmos/react-cosmos#894]
### What's wrong?

Using React-JSS with Cosmos, hot reloading components lose their styles until either the Cosmos page is reloaded, or the component is selected again from the left menu.

### Steps to reproduce

1.  Create a component using React-JSS.
2.  View component in Cosmos.
3.  Make a change to the component's styling.
4. The component as rendered in Cosmos will lose all styling, reverting to the CSS defaults.
5. Click the component's name in the left menu in Cosmos.
6. The component's JSS styling will return.

### User info

 - Cosmos 4.6.4
 - React-JSS 8.6.1

**Comment by skidding** [comment]
Hi @furious-luke,

Thanks for reporting this. Odd behavior :)

Could you share a minimal repo reproducing this? I'm willing to investigate, but unfortunately it would take more time than I have at the moment to create everything from scratch myself.

**Comment by skidding** [comment]
Feel free to reopen if you have a minimal repro.
