### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by nsisodiya** [react-cosmos/react-cosmos#922]
My code work perfect with create-react-app. but when I am trying to integrate react-cosmos, I am getting following error.

Can I fix it without updating my `.babelrc` file ?

```
ERROR in ./src/components/Avatar/Avatar.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/narendrasisodiya/rivigoCode/rivigo-ui/src/components/Avatar/Avatar.js: Support for the experimental syntax 'classProperties' isn't currently enabled (36:9):

  34 |
  35 | class Avatar extends Component {
> 36 |   state = {
     |         ^
  37 |     isImageBroken: false
  38 |   };
  39 |
```

![image](https://user-images.githubusercontent.com/333455/51750955-9a495500-20d9-11e9-9d2a-62c831c03fc2.png)

**Comment by skidding** [comment]
Did you config Cosmos to use CRA's webpack config? See https://github.com/react-cosmos/react-cosmos#create-react-app

**Comment by skidding** [comment]
This has to do with your webpack config and not Cosmos. It's likely that the wanted webpack config isn't passed to Cosmos correctly. Let me know if you still have this issue.

**Comment by stvmachine** [comment]
+1. The problem appears with react-scripts@2.1.3 . With react-scripts@1.1.4. Happy to help to make it work on the last version of create-react-app.

**Comment by skidding** [comment]
@stvmachine Thanks for looking into this! I think the webpack config path changed. The Cosmos docs say you have to set `webpackConfigPath: 'react-scripts/config/webpack.config.dev'`, but I think the webpack path changed in the last versions of CRA. Can you try setting `webpackConfigPath: 'react-scripts/config/webpack.config'` instead please? Any in any case, check the terminal logs to see if Cosmos manages to pick up the CRA webpack config or uses a default one.

**Comment by stvmachine** [comment]
@skidding  I followed your suggestion and guess what, totally works!. Thanks! 👍

**Comment by skidding** [comment]
I've updated the docs to reflect this: https://github.com/react-cosmos/react-cosmos#create-react-app

Thank you both for reporting this!

**Comment by pravin7891** [comment]
same problem i faced while working in Laravel with React scaffolding.
Simply create .babelrc file in root folder and paste below code and save.
```
{
  "plugins": [
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}
```
run npm run watch again.
Worked for me
