### ISSUE TITLE
Github Pages needs .nojekyll file

### ISSUE THREAD

**Issue by MattReimer** [react-cosmos/react-cosmos#925]
We want to use cosmos as a communciation tool with a client but I couldn't get `cosmos-export` to run correctly on GHPages. It kept throwing 404 errors on the playground file:

    GET https://myaccount.github.io/whatever/_playground.js 404

It turns out that Github Pages uses Jekyll which filters out any file starting with an underscore so `_playground.js` and other files will be gone when `index.html` needs them

The solution for me was to put an empty `.nojekyll` file in my /public/ folder. 

https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

Just thought I'd post this here to save anyone else trouble. It took me forever to figure out this wasn't a problem with Cosmos at all.

**Comment by skidding** [comment]
Hey @MattReimer, thanks for sharing this!

Would you mind putting this info in the README somewhere? Either under [Integration with popular tools](https://github.com/react-cosmos/react-cosmos#integration-with-popular-tools) or [Exporting](https://github.com/react-cosmos/react-cosmos#exporting). Thanks!
