### ISSUE TITLE
Cosmos-next: Fixture components not mounting in container set by containerQuerySelector

### ISSUE THREAD

**Issue by TheAncientGoat** [react-cosmos/react-cosmos#930]
### What's wrong?

Using react-boilerplate-typescript, setting `containerQuerySelector` in `cosmos.config.js` results in 2 containers being rendered, an empty `#app` div and and a `#root` div that contains the components specified in my tsx fixture.

When trying to reproduce - with the jsx-fixtures example, it seems like the #app div doesn't get created at all.

Looking at https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-shared2/src/dom.js#L7 - it seems like the container name will always be root?

### Steps to reproduce

1.  Create new react-cosmos project
2.  Configure with 
```
module.exports = {
  next: true,
  containerQuerySelector: '#app'
};
```
3.  Inspect iframe's DOM - components are mounted in a div with id="root"

### Screenshots

NA

### User info

- Server terminal output
- Browser console output
- Cosmos version: 4.7.0
- If bug occurred on upgrade: Working Cosmos version
- Cosmos config
- If applicable: webpack version
- If applicable: webpack config

### Additional context

Tested in both js-flow and typescript

**Comment by skidding** [comment]
Hi Ryan (awesome handle btw 😄)

You're right, `containerQuerySelector` isn't supported by Cosmos Next. I cut a lot of corners to release it as soon as possible and this was one of those corners.

But this is also something easy to add so I'm bookmarking this issue to fix it in the next release of Cosmos Next, which is going to include a bunch of other goodies like support for multiple named fixtures in a fixture file.

**Comment by TheAncientGoat** [comment]
Thanks for the quick reply - managed to work around it by just manually
providing a wrapper div - maybe all that is necessary is an update to the
documentation, it's not a huge hassle to add the wrapper, seeing as you
pretty much need to make a global style decorator anyhow to render
react-boilerplate correctly.

**Comment by skidding** [comment]
Just merged a fix for this. Make sure to subscribe to project releases to get notified when I publish the next version, which will include this fix.
