### ISSUE TITLE
util.promisify missing from react-cosmos/package.json

### ISSUE THREAD

**Issue by trsvax** [react-cosmos/react-cosmos#943]
### What's wrong?

server.js imports util.prosmisify but it's not in package.json. The import usually works because other packages have util.promisify in package.json

### Steps to reproduce

Ran across this getting cosmos to run under a rush/pnpm repo. 

### Workaround

add the following to pnpmfile.js

function readPackage(packageJson, context) {

      switch (packageJson.name) {
        case 'react-cosmos':
          packageJson.dependencies['util.promisify'] = '^1.0.0'
          break
        case 'babel-loader':
          packageJson.dependencies['@babel/core'] = '^7.3.3'
          break;
      }

  return packageJson;
}

**Comment by skidding** [comment]
Thanks for reporting this @trsvax!

I added the missing deps and released `4.8.1`. Let me know if the issue is solved.
