### ISSUE TITLE
Location to add script to package.json after installation?

### ISSUE THREAD

**Issue by protodonata** [react-cosmos/react-cosmos#945]
Hi! I know it's kind of stupid question but I am very new to React. I would like to know where to add the script below to package.json after the installation ? Thank you so much!

`"scripts": {
  "cosmos": "cosmos",
  "cosmos:export": "cosmos-export"
}`

**Comment by skidding** [comment]
Do you have a `package.json` in your project? If you do, does it have a `scripts` field?

**Comment by protodonata** [comment]
I found package.json in and out of my project. And now I found that the scripts seem like "add by its own" to the package.json file out of my project. So I am not sure where I should add.
In this case, does it mean that I gotta add to each of my projects if I use more than one?

Many thanks!

**Comment by skidding** [comment]
Sorry, but I don't quite understand your language. Yes, React Cosmos is installed separately per each project if that's what you ask. Is this a problem for you?
