### ISSUE TITLE
I can´t view fixtures

### ISSUE THREAD

**Issue by Talasaty** [react-cosmos/react-cosmos#954]
Hi!

In the root of my project I created the file cosmos.config.js and in it I put: 
```
module.exports = {
     rootPaths: ['src / components'],
     fileMatch: ['** / fixtures-in-here / ** / *. js', '** / __ fixture? (s) __ / ** / *. {js, jsx, ts, tsx}',
     '** /? (*.) fixture? (s). {js, jsx, ts, tsx}'],
}
```

the first fixture I created was a hello word tsx file in the directory:

/src/components/__fixtures__/hello_world.tsx

with the following code:

`export default 'Hello World!';`

When I launch npm run cosmos no component appears,
Can anybody help me?

Thank you!

**Comment by skidding** [comment]
It seems like you're on the 5.0 alpha version, right? Please see the latest docs regarding config and paths https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md

**Comment by skidding** [comment]
Let me know if you're still experiencing problems.

**Comment by chovy** [comment]
I'm having this issue on 4.8.1

**Comment by skidding** [comment]
@chovy Please use `react-cosmos@5.0.0-rc.0`, it will become official in a few days and it's more stable than 4.x.

**Comment by chovy** [comment]
Can't. I'm stuck on webpack3 for now.

**Comment by skidding** [comment]
Then you should use https://github.com/react-cosmos/react-cosmos-classic instead. This repo is repo is strictly about React Cosmos 5 now.
