### ISSUE TITLE
React Cosmos is unable to run on IE11

### ISSUE THREAD

**Issue by nhieunguyen1510** [react-cosmos/react-cosmos#956]
### What's wrong?

React Cosmos is unable to run on IE11 because of the "_playground.js"

### Steps to reproduce

1. Start cosmos
2. Open cosmos on IE11
3. React cosmos can't start, open the DevTool
4. The console in DevTool show `Syntax error` in `_playground.js`

### Screenshots

![image](https://user-images.githubusercontent.com/18672467/57127840-344d2780-6dc4-11e9-8f1b-12cb899b5f74.png)

### User info

- Browser: IE11
- Version: 4.8.1
- Next: true

### Reason

I spent a little time to dig in the react-cosmos source code and i see it import the _playground.js file from `react-cosmos-playground2` and when i open `node_modules/react-cosmos-playground2/dist/index.js`, the file is not bundled to target IE11

### Solution

Update the config of babel in `react-cosmos-playground2` to target IE11

**Comment by skidding** [comment]
Cosmos Next hasn't been optimized for IE11, at least yet.

What is your use case? I don't imagine you develop on IE11 primarily so are you occasionally checking how your components look on IE11?

The new remote renderer feature has been partially built for this use case. Have you tried it?

**Comment by nhieunguyen1510** [comment]
@skidding IE11 is part of our browser scope so we need to check the UI on it (we're building bunch on components before integrating with APIs). 
I didn't hear about remote renderer feature, can you provide a tutorial link ?

**Comment by skidding** [comment]
What version of Cosmos are you using? I'm assuming the 5.0 alpha.

Check out "Synced remote renderers" in https://medium.com/@skidding/cosmos-4-8-the-version-that-keeps-on-giving-746d6265f81d

**Comment by nhieunguyen1510** [comment]
@skidding Thanks for your helpful advice. Your answer match my need.
