### ISSUE TITLE
Cosmos NEXT support for React Native

### ISSUE THREAD

**Issue by betoharres** [react-cosmos/react-cosmos#966]
### What's wrong?

I'm getting this error when trying to load `cosmos-native` using the steps from the main docs(main README):
```
ExceptionsManager.js:82 Unhandled promise rejection TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at getNormalizedFixtureModules (blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:120223:37)
    at CosmosNativeLoader._callee$ (blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:111515:86)
    at tryCatch (blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:112014:19)
    at Generator.invoke [as _invoke] (blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:112189:24)
    at Generator.prototype.(anonymous function) [as next] (blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:112057:23)
    at asyncGeneratorStep (blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:112565:26)
    at _next (blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:112587:11)
    at blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:112594:9
    at new Promise (blob:file:///54ae7c43-2913-43af-b57a-d975ae6f1023:113336:9)
```

Here's how my `index.js` looks like: ( brand new app ):
```
/**
 * @format
 */

import React, {Component} from 'react'
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import { CosmosNativeLoader } from 'react-cosmos-loader/native';
import { rendererConfig, fixtures } from './cosmos.userdeps.js';

class Cosmos extends Component {
  render() {
    return <CosmosNativeLoader options={rendererConfig} modules={fixtures} />;
  }
}

AppRegistry.registerComponent(appName, () => Cosmos);
```
### Steps to reproduce

Here's my test app:
`git clone git@github.com:betoharres/cosmos-test.git`

### User info
- Browser console output: **Sarafi Version 12.1 (13607.1.40.1.5)**
- Cosmos version: **react-cosmos@^5.0.0-alpha.7** / **react-cosmos-loader@^4.8.2**

**Comment by skidding** [comment]
Hi @betoharres, `CosmosNativeLoader` is part of the Cosmos Classic API, that's why it doesn't work. `react-cosmos-loader` shouldn't even exist in your node_modules if you install `react-cosmos@next`.

There's no documentation for using Cosmos Next with RN, but I'm happy you opened this thread to discuss it.

Try this instead (keep the lines that haven't changed):

```js
import { FixtureLoader, createWebSocketsConnect } from 'react-cosmos-fixture';
import { fixtures } from './cosmos.userdeps.js';

class Cosmos extends Component {
  render() {
    return <FixtureLoader
      rendererId="anything-unique"
      rendererConnect={createWebSocketsConnect(getSocketUrl(5000))}
      fixtures={fixtures}
      systemDecorators={[]}
      userDecorators={[]}
      onFixtureChange={() => {}}
    />;
  }
}

function getSocketUrl(port: number) {
  const host = parse(NativeModules.SourceCode.scriptURL).hostname;
  return `ws://${host}:${port}`;
}
```

This is rudimentary. Let me know if it works and we can refine it into an official example.

**Comment by betoharres** [comment]
Hi @skidding, thanks a lot for taking the time to explain it. I'm going to take a look and update this issue. 
Great library you guys are doing, I loved it ❤️

**Comment by betoharres** [comment]
I got an error saying `createWebSocketsConnect` is not a function.  You can get a look into the `index.js` right here:
https://github.com/betoharres/cosmos-test/blob/master/index.js
package.json:
https://github.com/betoharres/cosmos-test/blob/master/package.json
I don't know if I missed something, I'm very new on cosmos :(

Thanks!

**Comment by skidding** [comment]
@betoharres Try installing `react-cosmos-fixture@next`

**Comment by betoharres** [comment]
@skidding thanks for the update, I'm going to take a look and get back here for the results

**Comment by skidding** [comment]
Updated the React Native integration in Cosmos Next: https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md#react-native

Please reopen if you still have issues.

**Comment by betoharres** [comment]
Thanks a lot, sorry for never taking on this again. I'll take a look on the project state ASAP. I had to continue with storybook but I hope one day I can migrate to cosmos. Great project btw!

**Comment by skidding** [comment]
Thanks! FYI the docs moved here: https://github.com/react-cosmos/react-cosmos/tree/81373eb67174ef320d63a7bf05f3e7a38f56d577#react-native
