### ISSUE TITLE
Can't find the way to use fixturesDir or fileMatch in Next

### ISSUE THREAD

**Issue by nhieunguyen1510** [react-cosmos/react-cosmos#969]
### What's wrong?

Can't find the way to use fixturesDir or fileMatch in Next

### Steps to reproduce

1. Create file `cosmos.config.js`
2. Use the below config to only build fixture inside *Pages* folder
```
module.exports = {
  next: true,
  globalImports: [
    'react-app-polyfill/ie11',
    'react-app-polyfill/stable',
    'styles/global.css',
    'typeface-open-sans',
  ],
  containerQuerySelector: '#root',
  webpackConfigPath: 'react-scripts/config/webpack.config.js',
  publicPath: 'public',
  fileMatch: ['**/__fixture?(s)__/Pages/**/*.{js,jsx,ts,tsx}'],
}
```
3. Run Cosmos using `cross-env NODE_PATH=src cosmos`
4. Cosmos still build all fixture inside *__fixtures__* folder

### User info

- Browser: Chrome
- Version: 4.8.1
- Next: true

**Comment by skidding** [comment]
Hi,

If you're using Cosmos Next I advise installing `react-cosmos@next` (which is currently `5.0.0-alpha.8`)

In the Cosmos Next docs you'll see the config is now a JSON.  Try this:

```json
{
  "globalImports": [
    "react-app-polyfill/ie11",
    "react-app-polyfill/stable",
    "styles/global.css",
    "typeface-open-sans"
  ],
  "staticPath": "public",
  "dom": {
    "containerQuerySelector": "#root"
  },
  "webpack": {
    "configPath": "react-scripts/config/webpack.config.js"
  }
}
```


Also `fileMatch` is no longer an option (but `fixturesDir` and `fixtureFileSuffix` is). But this config should already match the fixtures matched by your previous. Let me know if it works.

**Comment by nhieunguyen1510** [comment]
@skidding Thanks for your response
My use case when using `fileMatch` is I only want my local environment render a few Components that I'm working on. Because our team spend most of the team on Cosmos and its building process quite slow (take about 20s each time). I'm using the default webpack config from create-react-app.
Can you suggest any ways that i can boost up the speed ?

**Comment by skidding** [comment]
Two questions before I suggest anything:
- Does the dev build take less/same/more time than the Cosmos build?
- Are you more worried about the initial build time or the time it takes for the build to update on save?

**Comment by skidding** [comment]
Let me know if you still care about this and I'll reopen.
