### ISSUE TITLE
Support for Tailwind?

### ISSUE THREAD

**Issue by srhise** [react-cosmos/react-cosmos#981]
### What's up?

I am using Next.js + Tailwind CSS for a project, and wondering how I could implement support for Cosmos. Tailwind setup is using `postcss.config.js` to configure itself. 

### Mkay, tell me more...

I guess if there was an example that was using a postcss config file it might work?

**Comment by skidding** [comment]
Where exactly does `postcss.config.js` go?

Cosmos uses your existing webpack config so it's just a matter getting the webpack config available for Cosmos to read. If you have a Next.js + Cosmos project available I can help you add Tailwind to the mix. Don't see why it shouldn't work.

**Comment by srhise** [comment]
Here is the repo: https://github.com/srhise/nextjs-tailwindcss

Here is the setup article I used to get Next.js and Tailwind working together : https://medium.com/@notrab/get-up-and-running-with-tailwind-css-and-next-js-ba1b78cb9498

If you can get cosmos running and the tailwind classnames actually apply to the `<Button/>` component fixture.... well then that my friend would be a winner.

**Comment by srhise** [comment]
@skidding I tried myself and I was unable to get this working. But maybe you had more luck. Thanks for offering to assist, but also if you have no plans to support something like this feel free to close this issue as well.

**Comment by skidding** [comment]
Hi @srhise,

First of all the Cosmos config file was missing an _s_ in its name `comos.config.js`. But this wasn't the only change required unfortunately.

I haven't used Tailwind before so it took me some time to figure it out as well. In the end it boils down to adding PostCSS to Cosmos. The solution is a bit hacky, but it works, and I'm considering making it work out of the box in the future.

- Here are the required changes to make it work with the Cosmos version your were using https://github.com/srhise/nextjs-tailwindcss/compare/master...skidding:cosmos
- Here are the required changes to make it work with Cosmos Next (might as well use this if you're just getting started): https://github.com/srhise/nextjs-tailwindcss/compare/master...skidding:cosmos-next

This is how the latter looks on my machine:
![image](https://user-images.githubusercontent.com/250750/60052827-f3480400-96de-11e9-9d92-9e51385a4ee8.png)

**Comment by skidding** [comment]
Hi @srhise,

I'm made a patch to Cosmos (`react-cosmos@5.0.0-alpha.15`) that makes it work with PostCSS by default. [Here's what the diff to your updated repo looks like](https://github.com/srhise/nextjs-tailwindcss/compare/master...skidding:cosmos-next).

Closing this but let me know if it works for you.

**Comment by zning** [comment]
> Hi @srhise,
> 
> I'm made a patch to Cosmos (`react-cosmos@5.0.0-alpha.15`) that makes it work with PostCSS by default. [Here's what the diff to your updated repo looks like](https://github.com/srhise/nextjs-tailwindcss/compare/master...skidding:cosmos-next).
> 
> Closing this but let me know if it works for you.

I wonder if there's a solution for create-react-app with tailwindcss. I also opened an issue here.
#1326
