### ISSUE TITLE
Don't use componentWillReceiveProps in react-cosmos-loader

### ISSUE THREAD

**Issue by rouvenherzog** [react-cosmos/react-cosmos#984]
### What's up?

Technically, the issue arises in the react-cosmos-classic repo - let me know if this is not the right place to post this.
Link to the component: https://github.com/react-cosmos/react-cosmos-classic/blob/master/packages/react-cosmos-loader/src/components/Loader/index.js

When running tests with react 16.9.0-alpha.0, there are a lot of warnings about `Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.`. `componentWillReceiveProps` is being used in the react-cosmos-loader package, to update the list of proxies if changed during the tests. Let's get rid of it.

### Mkay, tell me more...

There are two options I see here:

1. Don't use the derived state in the react-cosmos-loader package. We could remove the componentWillReceiveProps method if we simply create the list of proxies on the fly. Performance wise it should not make a significant difference when creating a list of 10 to 100 proxies. I don't see an app using more proxies than that (correct me if I'm wrong). 
2. We move the list of proxies into state and use `static getDerivedStateFromProps` to update the list on props change.

I'm in favor of the first option, since it simplifies the component and removes complexity when creating the derived state.

What do you think?

**Comment by skidding** [comment]
Hi @rouvenherzog,

Thanks for bringing this up. I think option 1 is good enough, you're right.

Would you be interested in making a contribution?

Note that this is now part of React Cosmos Classic, and if you don't mind could you please move the issue to https://github.com/react-cosmos/react-cosmos-classic? I'm mostly focused on Cosmos Next (currently v5 alpha) but I can review and deploy a patch for 4.x with this.

**Comment by rouvenherzog** [comment]
Perfect! I'm happy to create a pull request on react-cosmos-classic :)
