### ISSUE TITLE
Can't group components under the same name and using a single file

### ISSUE THREAD

**Issue by pmfgomes** [react-cosmos/react-cosmos#985]
### What's up?
I'm trying to group multiple fixtures under the same name using an array of fixtures from a single file. 
When I use a `WrapperComponent` using the same `displayName = 'AutoSelect'` instead of grouping those fixtures under the same name, I get this:

![image](https://user-images.githubusercontent.com/25708216/60717262-4446cc00-9f19-11e9-83d3-02a1ff58a2f3.png)

What I want is something like this:
```
┌─ AutoSelect
├─── without on submit1
├─── without on submit2
├─ Component
├─── ...
....
```
My code:
```javascript
const WrapperComponent = (props) => {
    return (
        <AutoCompleteSelect {...props} />
    )
}
WrapperComponent.displayName = 'AutoSelect'

const ComponentWrapper = (props) => {
    return (
        <AutoCompleteSelect {...props} />
    )
}
ComponentWrapper.displayName = 'AutoSelect'

export default [
    {
        component: WrapperComponent,
        name: 'without on submit1',
    },
    {
        component: ComponentWrapper,
        name: 'without on submit2',
    },
    {
        component: (props) => (
            <AutoCompleteSelect {...props} />
        ),
        name: 'without on submit',
    },
    {
        component: (props) => (
            <Test {...props} />
        ),
        name: 'TEST',
    },
    {
        component: (props) => (
            <CreatableAutoCompleteSelect {...props} />
        ),
        name: 'with on submit',
        props: {
            options: options,
        }
    },
]

```

**Comment by skidding** [comment]
Hi @pmfgomes,

Do you have a lot of Cosmos fixtures created? I recommend trying [Cosmos Next](https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md), which handles this better.

**Comment by pmfgomes** [comment]
I have a bunch, but this project could have more in the future. I will upgrade to Cosmos Next as your recommendation and If I have any issue I will let you know.

Thanks for your help @skidding

**Comment by skidding** [comment]
Great, thanks @pmfgomes! Let me know if you have other issues.
