### ISSUE TITLE
Links to examples in the README are broken.

### ISSUE THREAD

**Issue by DanArthurGallagher** [react-cosmos/react-cosmos#993]
### What's wrong?

The README describes examples of fixtures and has links to further examples, but at least some of those are broken.

### Steps to reproduce

1.  Go to the README.
2.  Click on the `Check out the Fetch example to see the proxy in action.` under the XHR section, or on the `Check out the Axios example to see the proxy in action.`.section "XHR", 
3.  See a 404.

### User info

- This is on the `master` version of this repository at 09:35 CEST 14th July 2019.

### Additional context

I might be able to PR in a fix for this but I'm working right now, so I'm reporting it in the meantime.

**Comment by skidding** [comment]
Hi @DanArthurGallagher, the examples should point to the react-cosmos-classic repo. Eg.
- https://github.com/react-cosmos/react-cosmos-classic/tree/master/examples/axios
- https://github.com/react-cosmos/react-cosmos-classic/tree/master/examples/fetch

> Cosmos v5 is in the making and the repo is updated but the README still points to the stable version which was moved to a separate repo.

Sorry for the confusion. Contributions appreciated!
