### ISSUE TITLE
Cosmos@next requires install of html-webpack-plugin — docs

### ISSUE THREAD

**Issue by haf** [react-cosmos/react-cosmos#995]
### What's wrong?

<img width="1049" alt="Screenshot 2019-07-16 at 17 49 33" src="https://user-images.githubusercontent.com/193115/61309229-18b5c280-a7f2-11e9-8505-af0426397e9c.png">

```bash
$ yarn cosmos
yarn run v1.17.3
$ cosmos
[Cosmos] See you at http://localhost:5000
[Cosmos] Using default webpack config
[Cosmos] Building webpack...
webpack built ec17f13414ddd71e25bb in 1143ms
```

### Steps to reproduce

1.  `yarn add --dev react-cosmos@next && yarn cosmos & && start http://localhost:5000`

### User info

- Cosmos version: "react-cosmos": "^5.0.0-alpha.17",
- Cosmos config: none
- If applicable: webpack version: 4.32.2
- webpack config: there's one in `next.config.js`, unavailable to the app developer

### Extra

Could be solved by warning the user to install it as a peer dependency.

**Comment by skidding** [comment]
@haf Can you please share information from your terminal log?

**Comment by haf** [comment]
I did, there's nothing there.

**Comment by skidding** [comment]
My apologies, I rushed my answer.

Try this `yarn add --dev html-webpack-plugin` before running Cosmos. Let me know if it changes anything.

**Comment by haf** [comment]
Yes, that's the solution. Leaving open, because this affects all nextjs apps that don't use that plugin.

**Comment by skidding** [comment]
Added this information to docs: https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md#using-nextjs
