### ISSUE TITLE
next.js' webpack inaccessible — usability

### ISSUE THREAD

**Issue by haf** [react-cosmos/react-cosmos#999]
### What's wrong?

When getting started, you have to duplicate nextjs' web.config file; https://github.com/zeit/next.js/issues/6344

This makes the initial activation energy much higher than reasonable.

Unfortunately this doesn't work, and as you can see in the above linked issue, exposing web.config is a feature request.

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const nextConfig = require('./next.config')
module.exports = {
  webpack: (config, options) => {
    return {
      ...nextConfig(config, options),
      plugins: config.plugins.filter(
        p => !p.constructor || p.constructor.name !== 'OfflinePlugin'
      )
    };
  }
};
```

**Comment by skidding** [comment]
@haf I added this section on troubleshooting Cosmos with Next.js: https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md#using-nextjs.

Does it close this issue as well?

**Comment by haf** [comment]
Yes. Thank you for your help!
